/*
  GhibliKitchen – Woche 44 (Start: 2026-10-26)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Herbstlich-nährende chinesische Küche (秋冬滋補) – Abschluss der China-Serie mit wärmenden Schmorgerichten.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 44",
  startDate: "2026-10-26",
  id: "woche-44-2026-10-26",
  lang: "de",
  sidebar: "Woche 44 (2026-10-26)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-10-26)",
  di: "Dienstag (2026-10-27)",
  mi: "Mittwoch (2026-10-28)",
  do: "Donnerstag (2026-10-29)",
  fr: "Freitag (2026-10-30)",
  sa: "Samstag (2026-10-31)",
  so: "Sonntag (2026-11-01)",
};

const UI_TITLES = {
  main: "Rezepte Woche 44",
  list: "Einkaufsliste Woche 44",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Kürbis-Congee mit Erdnuss (南瓜花生粥)",
    desc: "Sämiger Reisbrei mit Kürbis und gerösteten Erdnüssen zum herbstlichen Wochenstart.",
    story: "Kürbis-Congee gilt in vielen Regionen Chinas als wärmendes, nährstoffreiches Herbstfrühstück.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Kürbis 150 g", "Erdnüsse geröstet 25 g", "Wasser 700 ml"],
    steps: ["Reis mit Kürbis und Wasser 30 Min. weich köcheln.", "Erdnüsse grob hacken.", "Unterheben.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "mo-m",
    title: "Yam-Hähnchen-Topf (山藥雞煲)",
    desc: "Chinesische Yamswurzel mit Hähnchen in milder Brühe geschmort, klassisches Nähr-Gericht.",
    story: "Shanyao gilt in der chinesischen Alltagsküche als besonders bekömmlich für die kühlere Jahreszeit.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Chinesische Yamswurzel 200 g", "Hähnchenschenkel ohne Haut 260 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen anbraten.", "Yamswurzel und Karotte zugeben, mit Wasser 25 Min. schmoren, bis vollständig durch.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-a",
    title: "Lotoswurzel-Rippchen-Suppe (蓮藕排骨湯)",
    desc: "Knackige Lotoswurzel mit mageren Rippchen, lange geschmort für tiefen Geschmack.",
    story: "Ein Wochenstart-Klassiker aus Woche 40, hier zum Abschluss der China-Serie wiederholt.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Magere Rippchen 250 g", "Lotoswurzel 200 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rippchen in Wasser 35 Min. köcheln, bis vollständig durch.", "Lotoswurzel und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Rippchen ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Warme Sojamilch mit Klebreiskuchen",
    desc: "Sojamilch mit kleinen gedämpften Klebreiskuchen, sanftes Herbstfrühstück.",
    story: "Klebreis-Snacks sind in ganz China als wärmendes, sättigendes Frühstück beliebt.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Ungesüßte Sojamilch 500 ml", "Klebreis (roh) 100 g", "Sesam geröstet 1 TL"],
    steps: ["Klebreis gar dämpfen, zu kleinen Kuchen formen.", "Mit Sesam bestreuen.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓",
    swaps: "Klebreis ↔ Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Klebreis", water: "1:1" },
  },
  {
    id: "di-m",
    title: "Rotgeschmortes Hähnchen mit Kürbis (南瓜紅燒雞)",
    desc: "Hähnchen und Kürbis in dunkler Sojasauce-Sauce geschmort, herbstliche Hongshao-Variante.",
    story: "Kürbis nimmt die dunkle Sauce besonders gut auf und bringt herbstliche Süße ins Gericht.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenschenkel ohne Haut 260 g", "Kürbis 150 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen anbraten.", "Kürbis zugeben, mit Sojasauce, Ingwer und Wasser 20 Min. schmoren, bis vollständig durch.", "Sauce leicht einkochen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-a",
    title: "Mais-Rippchen-Suppe (玉米排骨湯)",
    desc: "Süßlicher Mais und magere Rippchen in klarer, lang geköchelter Brühe.",
    story: "Ein bewährter Suppenklassiker aus Woche 40, der auch als Wochenausklang überzeugt.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Magere Rippchen 250 g", "Mais 2 Kolben", "Karotte 100 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rippchen in Wasser 35 Min. köcheln, bis vollständig durch.", "Mais und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Rippchen ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Reisbrei mit Ei und eingelegtem Gemüse",
    desc: "Klassischer Congee mit Ei und milden eingelegten Gemüsestreifen.",
    story: "Ein vertrautes, unaufgeregtes Frühstück für einen ruhigen Wochenmittelpunkt.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Gurke eingelegt mild 50 g", "Wasser 700 ml"],
    steps: ["Reis mit Wasser 30 Min. weich köcheln.", "Verquirltes Ei einrühren, stocken lassen.", "Eingelegtes Gemüse fein schneiden.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈66 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "mi-m",
    title: "Süßkartoffel-Rindfleisch-Topf (蕃薯牛肉煲)",
    desc: "Weich geschmorte Süßkartoffel mit magerem Rindfleisch in milder Sojasauce.",
    story: "Ein sättigendes, ballaststoffreiches Herbstgericht für den Wochenmittelpunkt.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch mager 240 g", "Süßkartoffel 200 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rind anbraten.", "Süßkartoffel zugeben, mit Sojasauce, Ingwer und Wasser 20 Min. schmoren, bis vollständig durch.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenschenkel",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-a",
    title: "Gedämpfter Kabeljau mit Kürbis (鱈魚南瓜煲)",
    desc: "Milder Eintopf mit Kabeljau und Kürbis in leichter Brühe.",
    story: "Ein bekömmliches Fischgericht, das schon in Woche 36 den Herbstauftakt begleitet hat.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljau 260 g", "Kürbis 150 g", "Reis (roh) 150 g", "Ingwer 10 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Kürbis in der Brühe 15 Min. köcheln.", "Kabeljau mit Ingwer zugeben, 8 Min. gar ziehen lassen bis durch.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Kabeljau durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Congee mit Pilzen und Ei (菌菇蛋粥)",
    desc: "Sanfter Reisbrei mit Champignons und Ei.",
    story: "Ein beruhigendes Frühstück für einen vollen Herbsttag, wie schon in Woche 36 bewährt.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Champignons 80 g", "Eier 2 Stück", "Wasser 700 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Wasser 30 Min. weich köcheln.", "Pilze in den letzten 10 Min. zugeben.", "Verquirltes Ei einrühren, stocken lassen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈66 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Champignons ↔ Shiitake",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "do-m",
    title: "Hühnersuppe mit Winterschwamm-Pilzen (冬菇雞湯)",
    desc: "Lang geköchelte Hühnerbrühe mit getrockneten Shiitake.",
    story: "Ein nährendes Mittagsgericht, das die wärmende Suppentradition der China-Serie fortführt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenschenkel ohne Haut 280 g", "Shiitake getrocknet 30 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Shiitake einweichen.", "Hähnchen in Wasser 25 Min. köcheln, bis vollständig durch.", "Pilze und Karotte zugeben, 10 Min. mitköcheln.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-a",
    title: "Geschmortes Rindfleisch mit Daikon (蘿蔔燉牛肉)",
    desc: "Zartes Rindfleisch mit Rettich in dunkler Sojasauce lange geschmort.",
    story: "Ein Familiengericht, das an kühlen Herbstabenden stundenlang leise vor sich hin köchelt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch mager 250 g", "Daikon 200 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rind anbraten.", "Mit Sojasauce, Ingwer und Wasser 40 Min. schmoren, bis zart und vollständig durch.", "Daikon zugeben, 15 Min. mitköcheln.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Frühlingszwiebel-Eierpfannkuchen (蔥花蛋餅)",
    desc: "Dünner, herzhafter Eierpfannkuchen mit viel Frühlingszwiebel.",
    story: "Ein bewährtes schnelles Frühstück, wie schon in Woche 37 beliebt.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Eier 4 Stück", "Mehl 60 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 1 EL", "Wasser 80 ml"],
    steps: ["Mehl mit Wasser und Eiern glatt verrühren.", "Frühlingszwiebel untermischen.", "In wenig Öl von beiden Seiten goldbraun backen, bis vollständig gestockt.", "Mit Sojasauce beträufelt servieren."],
    checks: "Diabetes ✓ – ≈58 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Claypot-Rettich-Hähnchen-Reis (煲仔蘿蔔雞飯)",
    desc: "Aromatischer Schmortopfreis mit Daikon und Hähnchen.",
    story: "Ein wärmendes One-Pot-Gericht, das die China-Serie mit vertrauten Aromen fortführt.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 220 g", "Daikon 100 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Daikon nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
  {
    id: "fr-a",
    title: "Miso-Lachs-Eintopf mit Daikon (味噌鮭魚煮)",
    desc: "Lachs und Daikon in milder Sojabohnenpaste-Brühe geschmort.",
    story: "Ein wärmendes Fischgericht für die kühleren Abende zum Wochenausklang.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Lachsfilet 260 g", "Daikon 120 g", "Sojabohnenpaste mild 2 EL", "Reis (roh) 150 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Daikon in der Brühe 15 Min. köcheln.", "Lachs zugeben, 8 Min. gar ziehen lassen bis durch.", "Sojabohnenpaste einrühren, nicht mehr kochen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Lachs durchgegart, quecksilberarm",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Warmer Kastanien-Milchreis (栗子粥)",
    desc: "Cremiger Milchreis mit Walnüssen als Kastanien-Alternative.",
    story: "Ein nussig-süßes Wochenendfrühstück, das an herbstliche Röstkastanien erinnert.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Walnüsse 30 g", "Zimt 1 Prise"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Walnüsse grob hacken, unterheben.", "Mit Zimt abschmecken.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Milch pasteurisiert",
    swaps: "Walnüsse ↔ Mandeln",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Gebratener Reis mit Char-Siu-Hähnchen (叉燒雞炒飯)",
    desc: "Gebratener Reis mit Resten des milden Char-Siu-Hähnchens, ideal für die Wochenendküche.",
    story: "Ein Beispiel für die chinesische Resteküchen-Tradition – nichts geht verloren.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 280 g", "Hähnchenbrust 200 g", "Eier 2 Stück", "Sojasauce natriumarm 2 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren, durchbraten, in Stücke schneiden.", "Ei in wenig Öl stocken lassen.", "Reis zugeben, kräftig anbraten, Hähnchen und Ei untermischen.", "Mit Frühlingszwiebel abschmecken."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Hähnchen und Ei durchgegart",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Herbstlicher Rindfleisch-Kürbis-Topf (南瓜牛肉煲)",
    desc: "Zartes Rindfleisch mit Kürbis in milder Sojasauce geschmort.",
    story: "Ein wärmendes Samstagabend-Schmorgericht, das schon in Woche 36 überzeugt hat.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch mager 250 g", "Kürbis 150 g", "Reis (roh) 150 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g"],
    steps: ["Rind anbraten.", "Kürbis zugeben, mit Sojasauce und Wasser 15 Min. köcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Warmer Congee zum Serienausklang mit Ei und Frühlingszwiebel",
    desc: "Klassischer, sanfter Reisbrei mit Ei und Frühlingszwiebel.",
    story: "Ein ruhiger, vertrauter Abschluss der achtwöchigen China-Serie.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Hühnerbrühe natriumarm 700 ml", "Frühlingszwiebel 2 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Verquirltes Ei einrühren, stocken lassen.", "Mild abschmecken.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈66 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Ei ↔ Tofuwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Große Jiaozi-Runde zum Serienabschluss (家庭餃子宴)",
    desc: "Gemischte Teigtaschen mit Hähnchen- und Gemüsefüllung, gemeinsam serviert.",
    story: "Ein Jiaozi-Sonntagslunch als würdiger Abschied von acht Wochen chinesischer Küche.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Jiaozi-Teighüllen 24 Stück", "Hähnchenhack 200 g", "Chinakohl 200 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Kohl fein hacken, mit Hack, Sojasauce und Ingwer vermengen.", "Teighüllen füllen, verschließen.", "12 Min. dämpfen oder in Wasser gar kochen, bis Füllung vollständig durch ist.", "Gemeinsam servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Hähnchen-Congee zum Serienausklang (雞肉粥收尾)",
    desc: "Wärmender Reisbrei mit Hähnchen als ruhiger Abschluss der China-Serie.",
    story: "Ein bewusst einfaches, vertrautes Gericht, um acht Wochen authentischer chinesischer Küche abzurunden.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Reis (roh) 120 g", "Hähnchenbrust 220 g", "Hühnerbrühe natriumarm 600 ml", "Ingwer 10 g", "Frühlingszwiebel 2 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Hähnchen zugeben, gar ziehen lassen bis vollständig durch.", "Mit Ingwer würzen.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
];

export default function Woche44DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="秋冬滋補 🍂 · Nährende Schmorgerichte · Balanced"
      heroChips={["Woche 44", "Serienabschluss", "6× 🍚 Reiskocher"]}
    />
  );
}
