/*
  GhibliKitchen – Woche 38 (Start: 2026-09-14)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Sichuan-Küche, mild angepasst – die berühmten Aromen ohne die Schärfe.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 38",
  startDate: "2026-09-14",
  id: "woche-38-2026-09-14",
  lang: "de",
  sidebar: "Woche 38 (2026-09-14)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-09-14)",
  di: "Dienstag (2026-09-15)",
  mi: "Mittwoch (2026-09-16)",
  do: "Donnerstag (2026-09-17)",
  fr: "Freitag (2026-09-18)",
  sa: "Samstag (2026-09-19)",
  so: "Sonntag (2026-09-20)",
};

const UI_TITLES = {
  main: "Rezepte Woche 38",
  list: "Einkaufsliste Woche 38",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Reisbrei mit Erdnüssen und Rosinen (花生粥)",
    desc: "Milder Congee mit gerösteten Erdnüssen, im Südwesten Chinas ein beliebtes Frühstück.",
    story: "In Sichuan wird der Frühstücks-Congee gern mit Nüssen und eingelegtem Gemüse serviert.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Erdnüsse geröstet 30 g", "Wasser 800 ml", "Rosinen 20 g"],
    steps: ["Reis mit Wasser 30 Min. weich köcheln.", "Erdnüsse grob hacken.", "Rosinen und Erdnüsse unterheben.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓",
    swaps: "Erdnüsse ↔ Cashewkerne",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "mo-m",
    title: "Mapo-Tofu mild (麻婆豆腐)",
    desc: "Weicher Tofu mit magerem Hackfleisch in würziger, deutlich entschärfter Sauce.",
    story: "Das Original aus Chengdu ist feurig scharf und betäubend pfeffrig – wir behalten Umami und Röstaroma, ohne die Schärfe.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Tofu weich 350 g", "Hähnchenhack 150 g", "Sojasauce natriumarm 2 EL", "Frühlingszwiebel 2 Stück", "Reis (roh) 150 g"],
    steps: ["Hack krümelig anbraten, bis vollständig durch.", "Mit Sojasauce und wenig Wasser aufgießen.", "Tofuwürfel vorsichtig zugeben, 5 Min. ziehen lassen.", "Mit Frühlingszwiebel bestreut auf Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-a",
    title: "Fischduftende Auberginen mild (鱼香茄子)",
    desc: "Samtige Auberginen in würzig-süßsaurer Sauce – der Name kommt von der Würzung, nicht vom Fisch.",
    story: "Yuxiang-Aromen (Knoblauch, Ingwer, Essig, wenig Zucker) sind eine der berühmtesten Würzkombinationen Sichuans.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Auberginen 350 g", "Hähnchenhack 150 g", "Reisessig mild 2 EL", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Auberginen in Stiften anbraten, bis weich.", "Hack zugeben, krümelig durchbraten.", "Mit Essig, Sojasauce und wenig Wasser ablöschen, kurz einköcheln.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Auberginen ↔ Zucchini",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Dampfbrötchen mit Sesampaste (芝麻馒头)",
    desc: "Klassisches weißes Dampfbrötchen, mit milder Sesampaste bestrichen.",
    story: "Mantou ist das Grundnahrungsmittel Nordchinas – schlicht, sättigend, vielseitig.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈12 g p. P.",
    ingredients: ["Mantou (fertig oder Hefeteig) 200 g", "Sesampaste 2 EL", "Warme Sojamilch 300 ml"],
    steps: ["Mantou 10 Min. dämpfen oder aufwärmen.", "Mit Sesampaste bestreichen.", "Sojamilch warm servieren.", "Zusammen genießen."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓",
    swaps: "Sesampaste ↔ Erdnussmus",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Gong Bao Garnelen mild (宫保虾仁)",
    desc: "Garnelen mit Erdnüssen und Gemüse, die Meeresfrüchte-Variante des Kung-Pao-Klassikers.",
    story: "Gongbao-Gerichte gibt es mit Hähnchen, Garnelen oder Tofu – das Würzprinzip bleibt gleich.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Garnelen (gegart) 240 g", "Erdnüsse geröstet 30 g", "Paprika 100 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Paprika kurz anbraten.", "Garnelen zugeben, 3 Min. durcherhitzen.", "Mit Sojasauce abschmecken.", "Mit Erdnüssen und Reis servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓ Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-a",
    title: "Gedämpfter Fisch nach Sichuan-Art mild (川式蒸鱼)",
    desc: "Gedämpftes Fischfilet mit Ingwer, Frühlingszwiebel und warmem Sojasauce-Guss.",
    story: "Selbst in der schärfeliebenden Sichuan-Küche bleibt gedämpfter Fisch traditionell zart und aromatisch statt feurig.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Seelachsfilet 280 g", "Ingwer 15 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Fisch mit Ingwer 10 Min. dämpfen, bis durchgegart.", "Frühlingszwiebel darüberstreuen.", "Sojasauce erhitzen, über den Fisch gießen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Fisch durchgegart, quecksilberarm",
    swaps: "Seelachs ↔ Kabeljau",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Kalte Sojasprossen mit Sesam (凉拌豆芽)",
    desc: "Blanchierte Sojasprossen mit Sesamöl, als leichtes Frühstück mit Ei ergänzt.",
    story: "Liangban-Gerichte (kalt angemacht) sind in Sichuan auch morgens beliebt – frisch und knackig.",
    target: "≈56 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Sojabohnensprossen 200 g", "Eier 2 Stück", "Sesamöl 1 TL", "Sojasauce natriumarm 1 EL", "Vollkornbrötchen 1 Stück"],
    steps: ["Sprossen 2 Min. blanchieren, abschrecken.", "Ei separat vollständig durchbraten.", "Sprossen mit Sesamöl und Sojasauce anmachen.", "Mit Ei und Brötchen servieren."],
    checks: "Diabetes ✓ – ≈56 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Sojasprossen ↔ Mungbohnensprossen",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Dan Dan Nudeln mild (担担面)",
    desc: "Weizennudeln mit Hackfleisch-Sesam-Sauce, das berühmte Sichuan-Streetfood ohne Chiliöl.",
    story: "Dandanmian wurde einst von Straßenhändlern an Bambusstangen (dan dan) getragen und verkauft.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Weizennudeln 200 g", "Hähnchenhack 180 g", "Sesampaste 2 EL", "Sojasauce natriumarm 2 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hack krümelig anbraten, bis vollständig durch.", "Sesampaste mit Sojasauce und etwas Nudelwasser glattrühren.", "Nudeln kochen, mit der Sauce vermengen.", "Hack und Frühlingszwiebel darüber verteilen."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Trocken gebratene grüne Bohnen (干煸四季豆)",
    desc: "Grüne Bohnen scharf angebraten, bis sie leicht runzelig sind, mit magerem Hackfleisch.",
    story: "Ganbian Sijidou ist eine Technik, keine Zutat: die Bohnen werden trocken gebraten statt gekocht, für konzentriertes Aroma.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Grüne Bohnen 300 g", "Hähnchenhack 180 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Bohnen in wenig Öl scharf braten, bis leicht runzelig.", "Hack zugeben, krümelig durchbraten.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Congee mit Kürbis und Erdnuss (南瓜花生粥)",
    desc: "Sämiger Reisbrei mit Kürbis und gerösteten Erdnüssen.",
    story: "Ein wärmendes Frühstück für den Übergang in den Herbst, mit Südwest-China-Note.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Kürbis 150 g", "Erdnüsse geröstet 25 g", "Wasser 700 ml"],
    steps: ["Reis mit Kürbis und Wasser 30 Min. weich köcheln.", "Erdnüsse grob hacken.", "Unterheben.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "do-m",
    title: "Zwiebel-Rindfleisch-Pfanne mild (洋葱牛肉)",
    desc: "Dünne Rindfleischstreifen mit Zwiebeln, sanft und aromatisch statt scharf gewürzt.",
    story: "Eine unaufgeregte Alltagsvariante der herzhaften Sichuan-Wok-Küche.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch mager 240 g", "Zwiebel 150 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Rind in dünne Streifen schneiden, scharf anbraten bis durch.", "Zwiebel zugeben, glasig braten.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-a",
    title: "Gedämpftes Ei mit Garnelen (虾仁蒸蛋)",
    desc: "Samtiger Eierstich mit eingebetteten Garnelen, proteinreicher Sichuan-Alltagsklassiker.",
    story: "Eine Variante des klassischen Zhengdangeng, hier mit Garnelen für ein vollwertiges Abendessen.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Eier 4 Stück", "Garnelen (gegart) 150 g", "Gemüsebrühe natriumarm 300 ml", "Sojasauce natriumarm 1 EL", "Reis (roh) 150 g"],
    steps: ["Eier mit Brühe glattrühren, durch ein Sieb gießen.", "Garnelen einbetten.", "12–15 Min. dämpfen, bis fest gestockt.", "Mit Sojasauce beträufelt mit Reis servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Ei und Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Tofuwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Sesam-Frühlingszwiebel-Fladenbrot (葱油饼)",
    desc: "Knuspriges, geschichtetes Fladenbrot mit Frühlingszwiebel, ganz ohne Frittieren aus der Pfanne.",
    story: "Congyoubing ist eines der bekanntesten chinesischen Frühstücksgebäcke – hier mit wenig Öl gebraten.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈12 g p. P.",
    ingredients: ["Mehl 150 g", "Frühlingszwiebel 3 Stück", "Sesamöl 1 EL", "Wasser 90 ml", "Salz 1 Prise"],
    steps: ["Teig aus Mehl, Wasser und Salz kneten, 20 Min. ruhen lassen.", "Dünn ausrollen, mit Öl und Frühlingszwiebel bestreichen, aufrollen und flach drücken.", "In der Pfanne mit wenig Öl goldbraun backen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Sliced Pork in würziger Sauce mild (蒜泥白肉)",
    desc: "Dünn geschnittenes, durchgegartes Schweinefleisch mit Knoblauch-Sojasauce, kalt serviert.",
    story: "Suanni Bairou ist ein Sichuan-Klassiker für heiße Sommertage – wir servieren ihn ganzjährig mild gewürzt.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Schweinefilet mager 250 g", "Knoblauch 2 Zehen", "Sojasauce natriumarm 2 EL", "Reisessig mild 1 EL", "Reis (roh) 150 g"],
    steps: ["Filet 20 Min. in Wasser gar ziehen lassen, bis vollständig durch.", "Auskühlen lassen, hauchdünn schneiden.", "Knoblauch, Sojasauce und Essig zur Sauce verrühren.", "Über das Fleisch geben, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-a",
    title: "Hähnchen-Cashew-Pfanne mild (腰果鸡丁)",
    desc: "Hähnchenwürfel mit Cashewkernen und Gemüse in leichter Sojasauce.",
    story: "Eine Cashew-Variante des Gongbao-Prinzips – süßer und milder als das Original mit Erdnüssen.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 260 g", "Cashewkerne 40 g", "Paprika 100 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Hähnchen würfeln, anbraten bis durch.", "Paprika zugeben, mitbraten.", "Mit Sojasauce abschmecken.", "Cashewkerne untermischen, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Klebreis-Frühstücksrolle mild (糯米卷)",
    desc: "Klebreis mit Ei und Frühlingszwiebel gefüllt, zur Rolle geformt.",
    story: "Eine Wochenend-Frühstücksvariante, angelehnt an die klebreisbasierten Snacks Südwestchinas.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Klebreis (roh) 120 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 1 EL"],
    steps: ["Klebreis gar dämpfen.", "Ei vollständig durchbraten, in Streifen schneiden.", "Reis flach drücken, Ei und Frühlingszwiebel einrollen.", "In Scheiben servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Klebreis ↔ Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Klebreis", water: "1:1" },
  },
  {
    id: "sa-m",
    title: "Doppelt gebratenes Schweinefleisch mild (回锅肉風)",
    desc: "In Anlehnung an das Sichuan-Original: gekochtes, dann gebratenes Schweinefleisch mit Lauch und Paprika, ohne Chilibohnenpaste.",
    story: "Huiguorou zählt zu den zehn berühmtesten Sichuan-Gerichten – unsere Version ersetzt die scharfe Doubanjiang durch milde Sojasauce.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Schweinefilet mager 250 g", "Lauch 100 g", "Paprika 100 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Filet 15 Min. gar ziehen lassen, dünn schneiden.", "In wenig Öl kurz scharf anbraten.", "Lauch und Paprika zugeben, mitbraten.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-a",
    title: "Kabeljau-Tofu-Topf sichuanisch mild (鱼豆腐煲)",
    desc: "Zarter Kabeljau und Tofu in leicht würziger Brühe, wärmendes Wochenendgericht.",
    story: "Ein Schmortopf, der die aromatische Tiefe der Sichuan-Küche zeigt – ganz ohne Feuer.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljau 220 g", "Tofu fest 200 g", "Ingwer 10 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Ingwer in der Brühe kurz anziehen lassen.", "Tofu zugeben, 5 Min. köcheln.", "Kabeljau zugeben, 8 Min. gar ziehen lassen.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Kabeljau durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Kalter Sesam-Nudelsalat (麻酱凉面)",
    desc: "Kühle Weizennudeln mit Sesampaste-Sauce, ein sommerlich-frisches Sichuan-Frühstück.",
    story: "Liangmian wird traditionell als Erfrischung an heißen Tagen gegessen – funktioniert aber ganzjährig als leichte Mahlzeit.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Sesampaste 2 EL", "Sojasauce natriumarm 2 EL", "Gurke 80 g", "Karotte 60 g"],
    steps: ["Nudeln kochen, kalt abschrecken.", "Sesampaste mit Sojasauce und etwas Wasser glattrühren.", "Gurke und Karotte in feine Streifen schneiden.", "Alles vermengen und servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓",
    swaps: "Weizennudeln ↔ Vollkornnudeln",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Hähnchen-Erdnuss-Reisschale (棒棒鸡飯)",
    desc: "Zartes, gerissenes Hähnchen mit Sesam-Erdnuss-Sauce auf Reis – die Reisschalen-Version des Bangbangji.",
    story: "Bangbangji verdankt seinen Namen den Stäbchen, mit denen das Fleisch traditionell geklopft wird, um es zart zu machen.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenbrust 260 g", "Sesampaste 2 EL", "Sojasauce natriumarm 2 EL", "Gurke 100 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen 15 Min. gar ziehen lassen, bis durch, dann zerrupfen.", "Sesampaste mit Sojasauce glattrühren.", "Gurke in Streifen dazu servieren.", "Über Reis anrichten."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-a",
    title: "Claypot-Rindfleisch-Reis sichuanisch (牛肉煲仔饭)",
    desc: "Schmortopfreis mit magerem Rindfleisch und Pilzen zum Wochenausklang.",
    story: "Ein wärmender Abschluss der Sichuan-Woche, aromatisch statt scharf.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Rindfleisch mager 220 g", "Champignons 60 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Rind mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Rind und Pilze nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
];

export default function Woche38DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="川菜 mild · Mapo & Gong Bao · Balanced"
      heroChips={["Woche 38", "Sichuan mild", "4× 🍚 Reiskocher"]}
    />
  );
}
