/*
  GhibliKitchen – Woche 29 (Start: 2026-07-13)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Japanische Sommerküche, kalte Sōmen, Donburi und milde Misosuppen.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 29",
  startDate: "2026-07-13",
  id: "woche-29-2026-07-13",
  lang: "de",
  sidebar: "Woche 29 (2026-07-13)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-07-13)",
  di: "Dienstag (2026-07-14)",
  mi: "Mittwoch (2026-07-15)",
  do: "Donnerstag (2026-07-16)",
  fr: "Freitag (2026-07-17)",
  sa: "Samstag (2026-07-18)",
  so: "Sonntag (2026-07-19)",
};

const UI_TITLES = {
  main: "Rezepte Woche 29",
  list: "Einkaufsliste Woche 29",
};

export const DATA = [
{
    id: "mo-f",
    title: "Zarte Tamago-Reisschale (卵かけご飯風)",
    desc: "Warmer Reis mit vollständig gestocktem Rührei und Sojasauce.",
    story: "Eine sichere, durchgegarte Variante des japanischen Frühstücksklassikers Tamago Kake Gohan.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (roh) 150 g", "Eier 3 Stück", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück", "Nori 1 Blatt"],
    steps: ["Reis im Reiskocher zubereiten.", "Eier verquirlen, in der Pfanne vollständig stocken lassen.", "Über den warmen Reis geben.", "Mit Sojasauce, Nori-Streifen und Frühlingszwiebel garnieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei komplett durchgegart) · Diabetes ✓",
    swaps: "Nori ↔ Sesam",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-m",
    title: "Kalte Sōmen mit Ei-Streifen (冷やし素麺)",
    desc: "Feine, gekühlte Weizennudeln mit Ei-Streifen und milder Dashi-Dip-Sauce.",
    story: "Sōmen sind der Inbegriff der japanischen Sommerküche – hier extra mild.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizennudeln (dünn) 180 g", "Eier 2 Stück", "Gemüsebrühe 250 ml", "Sojasauce 2 EL", "Mirin 1 EL"],
    steps: ["Nudeln kochen, eiskalt abschrecken.", "Ei zu dünnem Omelett braten, in Streifen schneiden.", "Brühe mit Sojasauce und Mirin verrühren, kalt stellen.", "Alles anrichten, Sauce separat reichen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Weizennudeln ↔ Soba",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Unadon-Style Aal-Ersatz mit Lachs (蒲焼き風サーモン丼)",
    desc: "In süßer Sojaglasur gebratenes Lachsfilet auf Reis, inspiriert vom Unadon.",
    story: "Da roher Aal für Schwangere ungeeignet ist, wird hier durchgegarter Lachs verwendet.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Lachsfilet 300 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Mirin 2 EL", "Zucker 1 TL"],
    steps: ["Reis im Reiskocher zubereiten.", "Sojasauce, Mirin und Zucker zu einer Glasur einkochen.", "Lachs in der Pfanne durchbraten, mit Glasur bestreichen.", "Auf Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Miso-Suppe mit Tofu und Wakame (味噌汁)",
    desc: "Klassische, milde Misosuppe mit Tofuwürfeln und wenig Wakame.",
    story: "Ein japanisches Frühstücksfundament – die Jodmenge wird bewusst gering gehalten.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Miso-Paste 2 EL", "Tofu 150 g", "Gemüsebrühe 500 ml", "Frühlingszwiebel 1 Stück", "Reis (roh) 100 g"],
    steps: ["Brühe erhitzen, nicht kochen.", "Miso-Paste einrühren.", "Tofuwürfel zugeben, kurz ziehen lassen.", "Mit Reis und Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Jod sparsam dosiert) · Diabetes ✓",
    swaps: "Tofu ↔ Ei",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Yakiudon mit Hähnchen (鶏肉焼きうどん)",
    desc: "Angebratene Udon-Nudeln mit Hähnchen und Kohlgemüse.",
    story: "Ein schnelles Pfannengericht für die Mittagspause.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Udon 200 g", "Hähnchenbrust 180 g", "Weißkohl 150 g", "Karotte 80 g", "Sojasauce 3 EL"],
    steps: ["Hähnchen in Streifen anbraten.", "Kohl und Karotte zugeben, mitbraten.", "Udon dazugeben, gut vermengen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Buta-Jiru Schweine-Misosuppe mild (豚汁)",
    desc: "Herzhafte Misosuppe mit magerem Schwein und Wurzelgemüse.",
    story: "Ein wärmendes Eintopfgericht, das trotz Sommer an kühleren Abenden gut passt.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Schweineschnitzel 200 g", "Daikon 100 g", "Karotte 80 g", "Miso-Paste 2 EL", "Reis (roh) 130 g"],
    steps: ["Schwein in dünnen Streifen anbraten.", "Daikon und Karotte zugeben, mit Wasser bedecken, 15 Min. köcheln.", "Miso einrühren, nicht mehr kochen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Schwein durchgegart) · Diabetes ✓",
    swaps: "Schwein ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Milder Natto-Ersatz-Reis mit Edamame",
    desc: "Warmer Reis mit Edamame und einer milden Sojasauce-Sesam-Note.",
    story: "Da Natto geschmacklich sehr speziell ist, setzen wir hier auf Edamame als milde Alternative.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (roh) 140 g", "Edamame 120 g", "Sojasauce 1 EL", "Sesamöl 1 TL", "Nori 1 Blatt"],
    steps: ["Reis im Reiskocher zubereiten.", "Edamame kurz erwärmen.", "Mit Sojasauce und Sesamöl vermengen.", "Mit Nori-Streifen bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Edamame)",
    swaps: "Edamame ↔ Erbsen",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Karaage-Style Hähnchen im Airfryer (からあげ風)",
    desc: "Knuspriges, mariniertes Hähnchen aus dem Airfryer, wenig Öl.",
    story: "Das japanische Frittierhähnchen wird hier ölarm im Airfryer nachgebaut.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Maisstärke 3 EL", "Sojasauce 2 EL", "Ingwer 10 g", "Reis (roh) 100 g"],
    steps: ["Hähnchen mit Sojasauce und Ingwer 20 Min. marinieren.", "In Maisstärke wenden.", "Im Airfryer 12 Min. bei 190°C knusprig backen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Maisstärke ↔ Panko",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Sukiyaki-Style Rind mild (すき焼き風)",
    desc: "Dünn geschnittenes Rindfleisch mit Kohl und Tofu in süßer Sojasauce.",
    story: "Eine entschärfte Sukiyaki-Version ohne rohes Ei zum Dippen.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Rindfleisch (mager) 220 g", "Weißkohl 150 g", "Tofu 150 g", "Sojasauce 3 EL", "Zucker 1 TL", "Reis (roh) 140 g"],
    steps: ["Rind kurz scharf anbraten.", "Kohl und Tofu zugeben.", "Mit Sojasauce und Zucker ablöschen, 8 Min. köcheln.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Rind vollständig durchgebraten) · Diabetes ✓",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Weicher Reis-Ei-Brei mit Nori (卵雑炊)",
    desc: "Sanfter Reisbrei mit Ei und Nori-Streifen, in Dashi gegart.",
    story: "Zōsui – ein beruhigendes Frühstück, oft aus übrig gebliebenem Reis gemacht.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (gekocht) 200 g", "Eier 2 Stück", "Gemüsebrühe 400 ml", "Nori 1 Blatt", "Sojasauce 1 EL"],
    steps: ["Brühe erhitzen, Reis zugeben, 8 Min. köcheln.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Sojasauce abschmecken.", "Mit Nori-Streifen bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Nori ↔ Frühlingszwiebel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Zucchini-Ricotta-Gnocchi-Pfanne",
    desc: "Sanfte Gnocchi mit Zucchini und cremigem Ricotta.",
    story: "Der italienische Programmpunkt der Woche, sehr mild und cremig.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Gnocchi 300 g", "Zucchini 150 g", "Ricotta 100 g", "Olivenöl 1 EL", "Basilikum 1 Bund"],
    steps: ["Gnocchi kochen.", "Zucchini in wenig Öl weich dünsten.", "Ricotta unterrühren, cremig verrühren.", "Mit Basilikum bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ricotta pasteurisiert) · Diabetes ✓",
    swaps: "Ricotta ↔ Quark",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Teriyaki-Hähnchen-Reisschale (照り焼きチキン丼)",
    desc: "Zartes Hähnchen in süßer Teriyaki-Glasur auf Reis mit Pak Choi.",
    story: "Ein Wochen-Dauerbrenner – einfach, verlässlich und mild gewürzt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Mirin 2 EL", "Pak Choi 120 g"],
    steps: ["Reis im Reiskocher zubereiten.", "Hähnchen anbraten, mit Sojasauce und Mirin glasieren.", "Pak Choi kurz mitdünsten.", "Auf Reis anrichten."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Lachs",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Onigiri mit Lachs (鮭おにぎり)",
    desc: "Reisbällchen gefüllt mit durchgegartem, zerpflücktem Lachs.",
    story: "Das japanische Reisbällchen für unterwegs, hier mit sicherem, gegartem Fisch.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Lachsfilet 100 g", "Nori 2 Blatt", "Sojasauce 1 EL", "Sesamöl 1 TL"],
    steps: ["Lachs vollständig durchgaren, zerpflücken.", "Reis kochen, leicht abkühlen lassen.", "Reis um den Lachs formen, mit Nori umwickeln.", "Mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs vollständig durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Katsudon light aus dem Airfryer (カツ丼風)",
    desc: "Knusprig gebackenes Hähnchenschnitzel mit Ei auf Reis.",
    story: "Die Airfryer-Variante des japanischen Frittier-Klassikers, deutlich ölärmer.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Panko 60 g", "Eier 2 Stück", "Reis (roh) 150 g", "Sojasauce 2 EL"],
    steps: ["Hähnchen panieren, im Airfryer 12 Min. backen.", "In Streifen schneiden.", "Mit verquirltem Ei in der Pfanne kurz stocken lassen.", "Auf Reis anrichten."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen und Ei durchgegart) · Diabetes ✓",
    swaps: "Panko ↔ Maisstärke",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-a",
    title: "Gedämpfter Kabeljau im Kombu-Sud (昆布蒸し鱈)",
    desc: "Milder, jodsparsam gewürzter Kabeljau, gedämpft mit wenig Kombu.",
    story: "Ein besonders schwangerschaftsfreundliches Fischgericht mit dezentem Umami.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljau 300 g", "Reis (roh) 140 g", "Sojasauce 2 EL", "Frühlingszwiebel 2 Stück", "Ingwer 10 g"],
    steps: ["Reis im Reiskocher zubereiten.", "Kabeljau mit Ingwer 10 Min. dämpfen.", "Mit wenig Sojasauce beträufeln.", "Mit Frühlingszwiebel garnieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Kabeljau durchgegart, Jod sehr sparsam) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Warme Soja-Reis-Frühstücksschale mit Beeren",
    desc: "Warmer Reis mit Milch, Blaubeeren und etwas Honig.",
    story: "Ein süßeres Wochenendfrühstück zur Abwechslung.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Blaubeeren 80 g", "Agavendicksaft 1 EL", "Walnüsse 15 g"],
    steps: ["Reis mit Milch weich köcheln.", "Mit Agavendicksaft süßen.", "Blaubeeren unterheben.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Blaubeeren ↔ Himbeeren",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Yasai Itame Gemüsepfanne (野菜炒め)",
    desc: "Buntes Wokgemüse mit Tofu, mild in Sojasauce gebraten.",
    story: "Ein einfaches, gemüsereiches Alltagsgericht der japanischen Hausmannskost.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Tofu 200 g", "Weißkohl 150 g", "Karotte 80 g", "Sojasprossen 100 g", "Sojasauce 2 EL"],
    steps: ["Tofu anbraten, beiseitestellen.", "Gemüse nacheinander anbraten.", "Tofu zurückgeben.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Nabeyaki-Udon mild (鍋焼きうどん)",
    desc: "Wärmender Udon-Eintopf mit Hähnchen, Ei und Pilzen in milder Dashi-Brühe.",
    story: "Eine Hotpot-Nudelsuppe im Einzeltopf – wärmend und beruhigend.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Udon 200 g", "Hähnchenbrust 150 g", "Eier 2 Stück", "Shiitake 30 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Brühe mit Sojasauce erhitzen.", "Hähnchen und Shiitake darin gar ziehen lassen.", "Udon zugeben.", "Ei hineingleiten lassen, vollständig stocken lassen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen und Ei durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-f",
    title: "Milder Miso-Lachs-Toast",
    desc: "Vollkorntoast mit einer dünnen Schicht Miso-Butter und Lachsflocken.",
    story: "Eine ungewöhnliche, aber sehr milde Fusion-Frühstücksidee.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Vollkorn-Toast 4 Scheiben", "Lachsfilet 100 g", "Miso-Paste 1 EL", "Butter 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Lachs vollständig durchgaren, zerpflücken.", "Miso mit weicher Butter verrühren.", "Toast damit bestreichen.", "Mit Lachs belegen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Kalte Udon-Salatschale mit Ei",
    desc: "Gekühlte Udon-Nudeln mit knackigem Gemüse und Ei-Streifen.",
    story: "Ein leichter Sonntagslunch, ideal zum Vorbereiten.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Udon 200 g", "Eier 2 Stück", "Gurke 100 g", "Karotte 80 g", "Sojasauce 2 EL"],
    steps: ["Udon kochen, kalt abschrecken.", "Ei zu Omelett braten, in Streifen schneiden.", "Gemüse in Streifen schneiden.", "Alles vermengen, mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Udon ↔ Soba",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Oden-Rettich-Reisschale mild (おでん風大根丼)",
    desc: "Sanft gegarter Daikon in milder Dashi-Sojasauce, mit Reis.",
    story: "Oden ganz ohne die traditionell stärkeren Fischkuchen – hier rein pflanzlich-mild.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Daikon 250 g", "Reis (roh) 150 g", "Sojasauce 2 EL", "Mirin 1 EL", "Eier 2 Stück"],
    steps: ["Daikon in Scheiben 20 Min. in Brühe köcheln.", "Ei hart kochen, halbieren.", "Mit Sojasauce und Mirin würzen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgekocht) · Diabetes ✓",
    swaps: "Daikon ↔ Karotte",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  }
];

export default function Woche29DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Sōmen & Donburi 🎐 · Japanisch mild · Balanced"
      heroChips={["Woche 29", "Japanische Sommerküche", "8× 🍚 Reiskocher"]}
    />
  );
}
