/*
  GhibliKitchen – Woche 33 (Start: 2026-08-10)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Airfryer-Leichtküche, knusprige Ergebnisse mit deutlich weniger Öl.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 33",
  startDate: "2026-08-10",
  id: "woche-33-2026-08-10",
  lang: "de",
  sidebar: "Woche 33 (2026-08-10)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-08-10)",
  di: "Dienstag (2026-08-11)",
  mi: "Mittwoch (2026-08-12)",
  do: "Donnerstag (2026-08-13)",
  fr: "Freitag (2026-08-14)",
  sa: "Samstag (2026-08-15)",
  so: "Sonntag (2026-08-16)",
};

const UI_TITLES = {
  main: "Rezepte Woche 33",
  list: "Einkaufsliste Woche 33",
};

export const DATA = [
{
    id: "mo-f",
    title: "Airfryer-Ei-Toast-Cups (烤蛋吐司杯)",
    desc: "In Toastbrot gebackene Ei-Cups mit Frühlingszwiebel.",
    story: "Der Airfryer macht aus Toast und Ei ein handliches Frühstück ganz ohne Pfanne.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Toastbrot 4 Scheiben", "Eier 4 Stück", "Frühlingszwiebel 1 Stück", "Käse 30 g", "Milch 2 EL"],
    steps: ["Toast in Muffinform drücken.", "Ei hineinschlagen, mit Käse bestreuen.", "Im Airfryer 10 Min. bei 180°C backen, bis fest.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt, Käse pasteurisiert) · Diabetes ✓",
    swaps: "Käse ↔ Feta",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Airfryer-Gemüse-Frühlingsrollen (烤蔬菜春卷)",
    desc: "Knusprige, im Airfryer statt frittierte Gemüsefrühlingsrollen.",
    story: "Alle Röstaromen der frittierten Frühlingsrolle, aber mit deutlich weniger Öl.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reispapier 10 Blatt", "Karotte 100 g", "Weißkohl 100 g", "Sojasprossen 80 g", "Sojasauce 2 EL"],
    steps: ["Gemüse in feine Streifen schneiden, kurz andünsten.", "In Reispapier straff einrollen.", "Mit wenig Öl bepinseln, im Airfryer 10 Min. bei 190°C knusprig backen.", "Mit Sojasauce-Dip servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Gemüse durchgegart) · Diabetes ✓",
    swaps: "Weißkohl ↔ Pak Choi",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Airfryer-Teriyaki-Lachs (エアフライヤー照り焼きサーモン)",
    desc: "Lachsfilet in Teriyaki-Glasur, knusprig aus dem Airfryer.",
    story: "Der Airfryer sorgt für eine leicht karamellisierte Kruste ohne zusätzliches Öl.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Lachsfilet 300 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Mirin 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Lachs in Sojasauce und Mirin 15 Min. marinieren.", "Reis im Reiskocher zubereiten.", "Lachs im Airfryer 10 Min. bei 190°C garen.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Airfryer-Süßkartoffel-Ecken mit Ei",
    desc: "Knusprige Süßkartoffelecken aus dem Airfryer mit einem weich gekochten Ei.",
    story: "Ballaststoffreiches Frühstück statt klassischer Pommes.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Süßkartoffel 250 g", "Eier 2 Stück", "Olivenöl 1 TL", "Frühlingszwiebel 1 Stück", "Sojasauce 1 EL"],
    steps: ["Süßkartoffel in Ecken schneiden, mit Öl beträufeln.", "Im Airfryer 15 Min. bei 200°C knusprig backen.", "Ei hart kochen.", "Zusammen mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgekocht) · Diabetes ✓ (ballaststoffreiche Süßkartoffel)",
    swaps: "Süßkartoffel ↔ Kartoffel",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Airfryer-Hähnchen-Spieße mit Gemüse (烤雞肉串)",
    desc: "Mariniertes Hähnchen und Gemüse am Spieß, im Airfryer gegart.",
    story: "Yakitori-Style Spieße, ganz ohne offene Flamme.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Hähnchenbrust 220 g", "Paprika 100 g", "Frühlingszwiebel 2 Stück", "Sojasauce 2 EL", "Mirin 1 EL"],
    steps: ["Hähnchen und Gemüse in Stücke schneiden, mit Sojasauce und Mirin marinieren.", "Auf Spieße stecken.", "Im Airfryer 12 Min. bei 190°C garen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Garnelen",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Airfryer-Karaage mit Reis (エアフライヤーからあげ)",
    desc: "Knuspriges, mariniertes Hähnchen aus dem Airfryer mit Reis.",
    story: "Der zweite Karaage-Auftritt der Saison – diesmal mit anderer Marinade.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Maisstärke 3 EL", "Sojasauce 2 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen mit Sojasauce und Ingwer marinieren.", "In Maisstärke wenden.", "Im Airfryer 12 Min. bei 190°C knusprig backen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Maisstärke ↔ Panko",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Airfryer-Ei-Muffins mit Lachs",
    desc: "Kleine Ei-Muffins mit durchgegartem Lachs, im Airfryer gebacken.",
    story: "Ein proteinreiches, handliches Frühstück für unterwegs.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Eier 5 Stück", "Lachsfilet 80 g", "Frühlingszwiebel 1 Stück", "Toastbrot 2 Scheiben", "Milch 2 EL"],
    steps: ["Lachs vollständig durchgaren, zerpflücken.", "Ei verquirlen, mit Lachs mischen.", "In Muffinförmchen im Airfryer 12 Min. bei 180°C backen.", "Mit Toast servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei und Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Airfryer-Tofu-Nuggets mit Gemüsereis",
    desc: "Knusprige Tofu-Nuggets aus dem Airfryer mit gebratenem Gemüsereis.",
    story: "Eine kinderfreundliche, vegetarische Mittagsoption.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Tofu 250 g", "Panko 60 g", "Reis (gekocht) 250 g", "Erbsen 60 g", "Sojasauce 2 EL"],
    steps: ["Tofu würfeln, panieren.", "Im Airfryer 12 Min. bei 190°C knusprig backen.", "Reis mit Erbsen kurz anbraten.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Reis durchgegart) · Diabetes ✓",
    swaps: "Panko ↔ Maisstärke",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Airfryer-Schweinefilet mit Ofengemüse (エアフライヤー豚ヒレ)",
    desc: "Zartes Schweinefilet mit Karotten und Zucchini, gemeinsam im Airfryer gegart.",
    story: "Ein unkompliziertes Ofengericht ganz ohne vorheriges Anbraten.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Schweineschnitzel 250 g", "Karotte 120 g", "Zucchini 100 g", "Reis (roh) 140 g", "Sojasauce 2 EL"],
    steps: ["Schwein und Gemüse mit Sojasauce marinieren.", "Im Airfryer 15 Min. bei 190°C garen.", "Reis im Reiskocher zubereiten.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Schwein vollständig durchgegart) · Diabetes ✓",
    swaps: "Schwein ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Airfryer-Bananen-Haferflocken-Röstis",
    desc: "Kleine, gebackene Haferflocken-Röstis mit Banane.",
    story: "Ein süßes, ballaststoffreiches Frühstück ohne zusätzliches Öl.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Haferflocken 100 g", "Banane 1 Stück", "Eier 1 Stück", "Zimt 1 Prise", "Milch 50 ml"],
    steps: ["Banane zerdrücken, mit Ei und Haferflocken vermengen.", "Kleine Röstis formen.", "Im Airfryer 10 Min. bei 180°C backen.", "Mit Zimt bestäuben."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓ (ballaststoffreicher Hafer)",
    swaps: "Banane ↔ Apfel",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Airfryer-Zucchini-Parmesan-Sticks mit Nudeln",
    desc: "Knusprige Zucchinisticks mit Parmesan, dazu milde Vollkorn-Penne.",
    story: "Der italienische Programmpunkt der Woche, luftig statt frittiert.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Zucchini 200 g", "Panko 50 g", "Parmesan 30 g", "Vollkorn-Penne 150 g", "Passierte Tomaten 150 ml"],
    steps: ["Zucchini in Sticks schneiden, panieren.", "Im Airfryer 10 Min. bei 190°C knusprig backen.", "Penne kochen, mit sanft eingekochten Tomaten vermengen.", "Zusammen servieren."],
    checks: "Balanced ✓ (Tomate mild eingekocht) · Schwangerschaft ✓ (Parmesan pasteurisiert) · Diabetes ✓",
    swaps: "Vollkorn-Penne ↔ Gnocchi",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Airfryer-Garnelen mit Knoblauch-Reis (エアフライヤーエビ)",
    desc: "Knusprig gegarte Garnelen mit mildem Knoblauchreis.",
    story: "Ein schnelles, proteinreiches Abendessen mit minimalem Aufwand.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Garnelen 250 g", "Reis (roh) 150 g", "Knoblauch 1 Zehe", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Garnelen mit etwas Öl und gehacktem Knoblauch marinieren.", "Im Airfryer 8 Min. bei 190°C garen bis durchgegart.", "Reis im Reiskocher zubereiten.", "Mit Sojasauce und Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart, Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Airfryer-Frühstücks-Baozi mild (烤包子)",
    desc: "Gefüllte Teigtaschen, statt gedämpft im Airfryer knusprig gebacken.",
    story: "Eine ofenfrische Variante des klassischen Dampfbrötchens.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Vollkorn-Tortillas 4 Stück", "Hähnchenbrust 120 g", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück", "Ingwer 5 g"],
    steps: ["Hähnchen klein würfeln, mit Sojasauce kurz schmoren.", "In Tortillas füllen, einrollen.", "Im Airfryer 8 Min. bei 190°C knusprig backen.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Airfryer-Gemüse-Tempura mild (野菜天ぷら風)",
    desc: "Leicht panierte Gemüsestücke, luftig aus dem Airfryer statt frittiert.",
    story: "Die Tempura-Idee ganz ohne Frittieröl.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Zucchini 100 g", "Karotte 80 g", "Champignons 80 g", "Mehl 60 g", "Sojasauce 2 EL"],
    steps: ["Gemüse in Scheiben schneiden.", "Dünnen Teig aus Mehl und Wasser anrühren, Gemüse eintunken.", "Im Airfryer 10 Min. bei 200°C knusprig backen.", "Mit Sojasauce-Dip servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Airfryer-Hähnchen-Curry-Reis mild",
    desc: "Knusprig gebackenes Hähnchen mit mildem Currysoße auf Reis.",
    story: "Ein Wochenabschluss mit sanfter Curry-Note.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Reis (roh) 150 g", "Kurkuma 1 TL", "Karotte 100 g", "Mehl 1 EL"],
    steps: ["Hähnchen im Airfryer 12 Min. bei 190°C garen.", "Karotte mit Kurkuma und Mehl zu milder Sauce köcheln.", "Reis im Reiskocher zubereiten.", "Alles zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Airfryer-French-Toast mild",
    desc: "In Ei-Milch getränkter Toast, knusprig im Airfryer gebacken.",
    story: "Ein süßes Wochenendfrühstück, deutlich ölärmer als in der Pfanne.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Vollkorn-Toast 4 Scheiben", "Eier 2 Stück", "Milch 4 EL", "Zimt 1 Prise", "Agavendicksaft 1 TL"],
    steps: ["Ei mit Milch und Zimt verquirlen.", "Toast darin tränken.", "Im Airfryer 8 Min. bei 180°C backen, bis fest.", "Mit Agavendicksaft beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig durchgegart) · Diabetes ✓",
    swaps: "Toast ↔ Vollkorn-Bagel",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Airfryer-Kabeljau-Sticks mit Gemüsereis",
    desc: "Knusprige Fischsticks aus Kabeljau, mit buntem Gemüsereis.",
    story: "Eine bekömmliche, kinderfreundliche Variante der klassischen Fischstäbchen.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Kabeljau 250 g", "Panko 50 g", "Reis (gekocht) 250 g", "Erbsen 60 g", "Karotte 50 g"],
    steps: ["Kabeljau in Sticks schneiden, panieren.", "Im Airfryer 10 Min. bei 190°C knusprig backen bis durchgegart.", "Reis mit Erbsen und Karotte anbraten.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Kabeljau durchgegart) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Airfryer-Rinderspieße mit Reis (エアフライヤー牛肉串)",
    desc: "Mariniertes, mageres Rindfleisch am Spieß, luftig gegart.",
    story: "Ein einfaches Grillgefühl ganz ohne Grillrost.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch (mager) 250 g", "Frühlingszwiebel 2 Stück", "Sojasauce 3 EL", "Reis (roh) 150 g", "Ingwer 10 g"],
    steps: ["Rind in Sojasauce und Ingwer 20 Min. marinieren.", "Auf Spieße stecken.", "Im Airfryer 10 Min. bei 200°C garen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Rind vollständig durchgegart) · Diabetes ✓",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Airfryer-Kartoffel-Ei-Röstis",
    desc: "Knusprige Kartoffelröstis mit weich gekochtem Ei.",
    story: "Ein herzhafter Sonntagmorgen-Klassiker, ölarm zubereitet.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Kartoffel 250 g", "Eier 2 Stück", "Frühlingszwiebel 1 Stück", "Mehl 1 EL", "Olivenöl 1 TL"],
    steps: ["Kartoffel grob raspeln, mit Mehl vermengen.", "Kleine Röstis formen.", "Im Airfryer 15 Min. bei 200°C knusprig backen.", "Mit weich gekochtem Ei servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgekocht) · Diabetes ✓",
    swaps: "Kartoffel ↔ Süßkartoffel",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Airfryer-Gemüse-Quiche-Ecken",
    desc: "Kleine, herzhafte Ei-Gemüse-Ecken aus dem Airfryer.",
    story: "Eine leichte Quiche-Variante ohne klassischen Mürbeteig.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Eier 4 Stück", "Zucchini 100 g", "Feta 50 g", "Toastbrot (zerkrümelt) 2 Scheiben", "Olivenöl 1 TL"],
    steps: ["Ei mit Gemüse und Feta vermengen.", "Zerkrümelten Toast als Boden in Förmchen geben.", "Ei-Mischung darübergeben, im Airfryer 12 Min. bei 180°C backen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart, Feta pasteurisiert) · Diabetes ✓",
    swaps: "Feta ↔ Ricotta",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Airfryer-Miso-Hähnchen mit Reis (エアフライヤー味噌チキン)",
    desc: "Hähnchen in milder Miso-Marinade, knusprig aus dem Airfryer.",
    story: "Ein aromatischer Wochenabschluss mit wenig Aufwand.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Miso-Paste 2 EL", "Mirin 1 EL", "Reis (roh) 150 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Hähnchen mit Miso und Mirin 20 Min. marinieren.", "Im Airfryer 12 Min. bei 190°C garen.", "Reis im Reiskocher zubereiten.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Lachs",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  }
];

export default function Woche33DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Knusprig, wenig Öl 🍗 · Airfryer-Woche · Balanced"
      heroChips={["Woche 33", "Airfryer-Leichtküche", "Täglich 1× 🍚 Reiskocher"]}
    />
  );
}
