/*
  GhibliKitchen – Woche 41 (Start: 2026-10-05)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Nordchinesische Nudel- und Teigwarenküche (麵食) – Nudeln, Jiaozi, Baozi.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 41",
  startDate: "2026-10-05",
  id: "woche-41-2026-10-05",
  lang: "de",
  sidebar: "Woche 41 (2026-10-05)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-10-05)",
  di: "Dienstag (2026-10-06)",
  mi: "Mittwoch (2026-10-07)",
  do: "Donnerstag (2026-10-08)",
  fr: "Freitag (2026-10-09)",
  sa: "Samstag (2026-10-10)",
  so: "Sonntag (2026-10-11)",
};

const UI_TITLES = {
  main: "Rezepte Woche 41",
  list: "Einkaufsliste Woche 41",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Sesam-Frühlingszwiebel-Fladenbrot mit Sojamilch (燒餅豆漿)",
    desc: "Knuspriges Fladenbrot mit warmer Sojamilch, klassisches nordchinesisches Frühstücksduo.",
    story: "Shaobing ist im Norden Chinas so alltäglich wie das Brötchen bei uns.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Mehl 150 g", "Sesam 1 EL", "Ungesüßte Sojamilch 400 ml", "Wasser 90 ml", "Salz 1 Prise"],
    steps: ["Teig aus Mehl, Wasser und Salz kneten, 20 Min. ruhen lassen.", "Ausrollen, mit Sesam bestreuen, in der Pfanne goldbraun backen.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Gedämpfte Jiaozi mit Hähnchen-Kohl-Füllung (雞肉白菜蒸餃)",
    desc: "Klassische Teigtaschen mit Hähnchen-Kohl-Füllung, gedämpft statt frittiert.",
    story: "Jiaozi sind eines der bekanntesten Symbole chinesischer Küche – jede Familie hat ihr eigenes Füllungsrezept.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Jiaozi-Teighüllen 20 Stück", "Hähnchenhack 220 g", "Chinakohl 200 g", "Ingwer 8 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Kohl fein hacken, kurz salzen, Wasser ausdrücken.", "Mit Hack, Ingwer und Sojasauce vermengen.", "Teighüllen füllen, verschließen.", "12 Min. dämpfen, bis Füllung vollständig durchgegart ist."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Geriebene Sauce-Nudeln mild (炸醬麵風)",
    desc: "Weizennudeln mit Hackfleisch-Sojabohnenpaste-Sauce, Pekinger Klassiker ohne Schärfe.",
    story: "Zhajiangmian ist ein Aushängeschild der Pekinger Küche – die Sauce köchelt traditionell lange für tiefen Geschmack.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Weizennudeln 200 g", "Hähnchenhack 200 g", "Gelbe Bohnenpaste mild 2 EL", "Gurke 80 g", "Frühlingszwiebel 2 Stück"],
    steps: ["Hack krümelig anbraten, bis vollständig durch.", "Bohnenpaste und etwas Wasser zugeben, 10 Min. köcheln.", "Nudeln kochen.", "Sauce über die Nudeln geben, mit Gurkenstreifen servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-f",
    title: "Sesamölnudeln zum Frühstück (麻油麵線)",
    desc: "Feine Weizenfadennudeln mit Sesamöl und Ei, schnelles nordchinesisches Frühstück.",
    story: "Mianxian sind hauchdünn und garen in Sekunden – ideal für einen zügigen Start.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizenfadennudeln 120 g", "Eier 2 Stück", "Sesamöl 1 TL", "Sojasauce natriumarm 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Nudeln 2 Min. kochen.", "Ei separat vollständig durchbraten, in Streifen schneiden.", "Nudeln mit Sesamöl und Sojasauce mischen.", "Mit Ei und Frühlingszwiebel servieren."],
    checks: "Diabetes ✓ – ≈74 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Handgezogene Nudeln mit Rind und Tomate (番茄牛肉拉麵)",
    desc: "Breite Weizennudeln mit magerem Rindfleisch in milder Tomatensauce.",
    story: "Lamian-Techniken stammen ursprünglich aus dem Nordwesten Chinas – bei uns geht's mit gekauften breiten Nudeln genauso gut.",
    target: "≈94 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Breite Weizennudeln 200 g", "Rindfleisch mager 220 g", "Tomaten 200 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Rind anbraten, bis durch.", "Tomaten zugeben, 10 Min. mild köcheln.", "Mit Sojasauce und Ingwer abschmecken.", "Über gekochte Nudeln geben."],
    checks: "Diabetes ✓ – ≈94 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Gebratene Jiaozi mit Ei-Lauch-Füllung (韭菜蛋煎餃)",
    desc: "Knusprig gebratene Teigtaschen mit Ei-Lauch-Füllung, unten kross, oben zart.",
    story: "Jianjiao (gebratene Jiaozi) entstanden ursprünglich aus übrig gebliebenen gekochten Teigtaschen vom Vortag.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Jiaozi-Teighüllen 20 Stück", "Eier 3 Stück", "Lauch 150 g", "Sesamöl 1 TL", "Sojasauce natriumarm 1 EL"],
    steps: ["Ei vollständig durchbraten, klein hacken.", "Mit Lauch, Sesamöl und Sojasauce vermengen, Teig füllen.", "In wenig Öl anbraten, dann mit Deckel und etwas Wasser gar dämpfen.", "Bis Boden knusprig und Füllung heiß durch ist servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart",
    swaps: "Lauch ↔ Schnittlauch",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-f",
    title: "Reisbrei mit Frühlingszwiebel-Ei-Pfannkuchen",
    desc: "Milder Congee mit dünnem Eierpfannkuchen als Beilage.",
    story: "Eine ruhige Frühstückskombination aus Süd- und Nordtechnik.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Wasser 700 ml", "Frühlingszwiebel 2 Stück"],
    steps: ["Reis mit Wasser 30 Min. weich köcheln.", "Ei mit Frühlingszwiebel verquirlen, dünn ausbacken bis vollständig gestockt.", "In Streifen schneiden.", "Über den Congee geben."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "mi-m",
    title: "Beef-Noodle-Soup mild (紅燒牛肉麵)",
    desc: "Breite Nudeln in milder Rindfleischbrühe, ohne die übliche Chiliöl-Schärfe.",
    story: "Hongshao Niurou Mian gilt vielen als Taiwans Nationalgericht – unsere Version bleibt mild und familienfreundlich.",
    target: "≈96 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Breite Weizennudeln 200 g", "Rindfleisch mager 250 g", "Karotte 100 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g"],
    steps: ["Rind in Wasser 40 Min. köcheln, bis zart und vollständig durch.", "Karotte zugeben, 10 Min. mitköcheln.", "Mit Sojasauce und Ingwer würzen.", "Über gekochte Nudeln geben."],
    checks: "Diabetes ✓ – ≈96 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenschenkel",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Sesamsauce-Auberginen-Nudeln (麻醬茄子拌麵)",
    desc: "Weizennudeln mit weich gebratenen Auberginen und Sesamsauce.",
    story: "Ein vegetarischer Nudelabend, der die reiche Sesampasten-Tradition Nordchinas zeigt.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Auberginen 250 g", "Sesampaste 2 EL", "Sojasauce natriumarm 2 EL", "Knoblauch 1 Zehe"],
    steps: ["Auberginen in Stiften weich braten.", "Sesampaste mit Sojasauce und Knoblauch glattrühren.", "Nudeln kochen.", "Alles vermengen und servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓",
    swaps: "Auberginen ↔ Zucchini",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-f",
    title: "Gedämpfte Frühlingszwiebel-Baozi (葱花包子)",
    desc: "Weiche Hefeteigtaschen mit gebratenem Ei-Frühlingszwiebel-Füllung.",
    story: "Baozi sind der große Bruder der Jiaozi – luftiger Hefeteig statt dünner Nudelteig.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Hefeteig (fertig) 300 g", "Eier 2 Stück", "Frühlingszwiebel 3 Stück", "Sesamöl 1 TL"],
    steps: ["Ei vollständig durchbraten, hacken.", "Mit Frühlingszwiebel und Sesamöl mischen.", "Teig füllen, formen, 15 Min. dämpfen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓ Ei vollständig durchgegart",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Kalte Sesam-Nudeln mit Hähnchen (麻醬雞絲涼麵)",
    desc: "Kühle Weizennudeln mit zerrupftem Hähnchen und Sesamsauce.",
    story: "Eine sättigende, erfrischende Mittagspause – auch an kühleren Herbsttagen beliebt.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Hähnchenbrust 200 g", "Sesampaste 2 EL", "Sojasauce natriumarm 2 EL", "Gurke 80 g"],
    steps: ["Hähnchen 15 Min. gar ziehen lassen, bis vollständig durch, zerrupfen.", "Nudeln kochen, kalt abschrecken.", "Sesampaste mit Sojasauce glattrühren.", "Alles mit Gurkenstreifen vermengen."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Lauwarme Jiaozi-Suppe (餃子湯)",
    desc: "Gedämpfte Teigtaschen in klarer Brühe serviert, wärmendes Abendgericht.",
    story: "Statt sie zu dämpfen, wandern die Jiaozi hier direkt in die heiße Brühe – eine beliebte Variante für kühle Abende.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Jiaozi-Teighüllen 20 Stück", "Hähnchenhack 220 g", "Chinakohl 150 g", "Gemüsebrühe natriumarm 600 ml", "Frühlingszwiebel 2 Stück"],
    steps: ["Kohl fein hacken, mit Hack vermengen.", "Teighüllen füllen, verschließen.", "In der kochenden Brühe 8 Min. garen, bis Füllung vollständig durch ist.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-f",
    title: "Klebreisrolle mit Ei (糯米飯捲蛋)",
    desc: "Klebreis mit durchgebratenem Ei und Frühlingszwiebel gefüllt und gerollt.",
    story: "Ein herzhaftes, tragbares Frühstück – in China oft direkt beim Straßenhändler gekauft.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Klebreis (roh) 120 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 1 EL"],
    steps: ["Klebreis gar dämpfen.", "Ei vollständig durchbraten, in Streifen schneiden.", "Reis flach drücken, Ei einrollen.", "In Scheiben servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Klebreis ↔ Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Klebreis", water: "1:1" },
  },
  {
    id: "fr-m",
    title: "Gebratene Udon nordchinesisch angelehnt (北方炒麵)",
    desc: "Kräftig gebratene Nudeln mit Hähnchen und Kohl, im Wok scharf angebraten.",
    story: "Chaomian-Varianten gibt es in jeder Region – diese hält sich an die einfache nordchinesische Grundform.",
    target: "≈94 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Udon 200 g", "Hähnchenbrust 200 g", "Weißkohl 150 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen in Streifen anbraten bis durch.", "Kohl zugeben, mitbraten.", "Nudeln zugeben, bei hoher Hitze durchschwenken.", "Mit Sojasauce abschmecken."],
    checks: "Diabetes ✓ – ≈94 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Gedämpfte Fleischtaschen mit Rind (牛肉蒸包)",
    desc: "Hefeteigtaschen mit magerem Rinderhack gefüllt, herzhafter Wochenausklang.",
    story: "Niurou Baozi sind besonders im Nordwesten Chinas beliebt, wo Rind statt Schwein die Küche prägt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hefeteig (fertig) 300 g", "Rinderhack mager 220 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Hack mit Frühlingszwiebel, Sojasauce und Ingwer vermengen.", "Teig füllen, formen.", "18 Min. dämpfen, bis Füllung vollständig durchgegart ist.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-f",
    title: "Sesam-Kringel mit Sojamilch (芝麻燒餅豆漿)",
    desc: "Rundes Sesamgebäck mit warmer Sojamilch, Wochenend-Frühstücksklassiker.",
    story: "Shaobing-Varianten mit viel Sesam sind besonders in Nordchina an jeder Straßenecke zu finden.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Mehl 150 g", "Sesam 2 EL", "Ungesüßte Sojamilch 400 ml", "Wasser 90 ml"],
    steps: ["Teig kneten, 20 Min. ruhen lassen.", "Zu Kringeln formen, in Sesam wälzen.", "In der Pfanne goldbraun backen.", "Mit warmer Sojamilch servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Handgeschnittene Nudeln mit Tomate und Ei (西紅柿炒蛋刀削麵)",
    desc: "Breite Nudeln mit der klassischen Tomate-Ei-Pfanne, deftiges Wochenendgericht.",
    story: "Daoxiaomian ('gehobelte Nudeln') stammen aus Shanxi – bei uns geht's mit gekauften breiten Nudeln genauso aromatisch.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Breite Weizennudeln 200 g", "Tomaten 250 g", "Eier 3 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 1 EL"],
    steps: ["Ei in wenig Öl stocken lassen bis vollständig durch, herausnehmen.", "Tomaten anbraten, bis sie zerfallen.", "Ei zurückgeben, mit Sojasauce abschmecken.", "Über gekochte Nudeln geben."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "-",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Geschmorte Rinder-Nudeln im Topf (紅燒牛肉煲麵)",
    desc: "Breite Nudeln mit langsam geschmortem Rindfleisch und Karotten in kräftiger Sauce.",
    story: "Ein wärmendes Samstagabendgericht, das die Nudelwoche stimmungsvoll abrundet.",
    target: "≈96 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Breite Weizennudeln 200 g", "Rindfleisch mager 250 g", "Karotte 100 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g"],
    steps: ["Rind anbraten, bis durch.", "Mit Sojasauce, Ingwer und Wasser 30 Min. schmoren.", "Karotte zugeben, 10 Min. mitköcheln.", "Über gekochte Nudeln geben."],
    checks: "Diabetes ✓ – ≈96 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-f",
    title: "Jiaozi zum Sonntagsfrühstück mit Fisch-Füllung (魚肉蒸餃)",
    desc: "Zarte Teigtaschen mit fein gehacktem Kabeljau, sonntäglich besonderes Frühstück.",
    story: "Fischfüllungen sind an Chinas Küste ebenso beliebt wie Fleischfüllungen im Landesinneren.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Jiaozi-Teighüllen 20 Stück", "Kabeljaufilet 220 g", "Frühlingszwiebel 2 Stück", "Ingwer 8 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Kabeljau fein hacken, mit Frühlingszwiebel, Ingwer und Sojasauce vermengen.", "Teighüllen füllen, verschließen.", "12 Min. dämpfen, bis Füllung vollständig durchgegart ist.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Sauer-scharfe Nudelsuppe mild (酸辣麵)",
    desc: "Weizennudeln in würziger, mit Essig statt Chili balancierter Brühe.",
    story: "Eine mildere Verwandte der Suanlatang – als Nudelsuppe statt Suppe mit Einlage serviert.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Tofu fest 150 g", "Eier 2 Stück", "Reisessig mild 2 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Tofu in der Brühe 5 Min. köcheln.", "Mit Essig abschmecken.", "Verquirltes Ei einrühren.", "Über gekochte Nudeln geben, mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Tofu ↔ Hähnchenwürfel",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Große Jiaozi-Runde zum Wochenausklang (家庭餃子宴)",
    desc: "Gemischte Teigtaschen mit Hähnchen- und Gemüsefüllung, gemeinsam serviert – der klassische chinesische Familienabend.",
    story: "Ein Jiaozi-Abend ist in vielen chinesischen Familien Tradition, besonders am Wochenende gemeinsam gefaltet.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Jiaozi-Teighüllen 24 Stück", "Hähnchenhack 200 g", "Chinakohl 200 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Kohl fein hacken, mit Hack, Sojasauce und Ingwer vermengen.", "Teighüllen füllen, verschließen.", "12 Min. dämpfen oder in Wasser gar kochen, bis Füllung vollständig durch ist.", "Gemeinsam servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
];

export default function Woche41DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="麵食 🥟 · Nudeln, Jiaozi & Baozi · Balanced"
      heroChips={["Woche 41", "Nordchinesische Teigwaren", "1× 🍚 Reiskocher"]}
    />
  );
}
