/*
  GhibliKitchen – Woche 37 (Start: 2026-09-07)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Echte chinesische Hausmannskost (家常菜) – die Klassiker, die in jeder Familienküche stehen.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 37",
  startDate: "2026-09-07",
  id: "woche-37-2026-09-07",
  lang: "de",
  sidebar: "Woche 37 (2026-09-07)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-09-07)",
  di: "Dienstag (2026-09-08)",
  mi: "Mittwoch (2026-09-09)",
  do: "Donnerstag (2026-09-10)",
  fr: "Freitag (2026-09-11)",
  sa: "Samstag (2026-09-12)",
  so: "Sonntag (2026-09-13)",
};

const UI_TITLES = {
  main: "Rezepte Woche 37",
  list: "Einkaufsliste Woche 37",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Weizenbrei mit Ei und Frühlingszwiebel (蛋花小米粥)",
    desc: "Sanfter Hirsebrei mit eingerührtem Ei, ein klassisches chinesisches Frühstück.",
    story: "Xiaomizhou steht in Nordchina fast täglich auf dem Frühstückstisch.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Hirse (roh) 90 g", "Wasser 700 ml", "Eier 2 Stück", "Frühlingszwiebel 1 Stück", "Salz 1 Prise"],
    steps: ["Hirse mit Wasser 25 Min. weich köcheln.", "Verquirltes Ei langsam einrühren, stocken lassen.", "Mit Salz abschmecken.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Hirse ↔ Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Kung Pao Hähnchen mild (宫保鸡丁)",
    desc: "Hähnchenwürfel mit Erdnüssen und Gemüse, deutlich entschärft statt scharf-pikant.",
    story: "Das Original aus Sichuan lebt von Chili – unsere milde Version behält Röstaroma und Erdnuss-Crunch.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 260 g", "Erdnüsse geröstet 40 g", "Paprika 100 g", "Reis (roh) 150 g", "Sojasauce natriumarm 2 EL", "Ingwer 10 g"],
    steps: ["Hähnchen würfeln, kurz anbraten.", "Paprika und Ingwer zugeben, mitbraten.", "Mit Sojasauce ablöschen, 3 Min. köcheln.", "Erdnüsse untermischen, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-a",
    title: "Tomaten-Ei-Suppe (西红柿鸡蛋汤)",
    desc: "Die wohl bekannteste Suppe Chinas – Tomate, Ei und Frühlingszwiebel in klarer Brühe.",
    story: "In fast jedem chinesischen Haushalt steht diese Suppe mindestens einmal die Woche auf dem Tisch.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Tomaten 300 g", "Eier 2 Stück", "Reis (roh) 130 g", "Gemüsebrühe natriumarm 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Tomaten häuten, würfeln, in der Brühe 8 Min. köcheln.", "Verquirltes Ei langsam einrühren.", "Mit Frühlingszwiebel bestreuen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈58 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Reis ↔ Vollkornreis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Gedämpfte Eierstich-Schale (蒸蛋羹)",
    desc: "Samtig gedämpftes Ei in milder Brühe, chinesisches Pendant zum japanischen Chawanmushi.",
    story: "Zhengdangeng ist eines der ersten Gerichte, das chinesische Kinder selbst kochen lernen.",
    target: "≈54 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Eier 4 Stück", "Gemüsebrühe natriumarm 300 ml", "Reis (roh) 130 g", "Sojasauce natriumarm 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Eier mit Brühe glatt verquirlen, durch ein Sieb gießen.", "In Schälchen 12–15 Min. dämpfen, bis fest gestockt.", "Mit Sojasauce beträufeln.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈54 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Hackfleisch-Tofu-Pfanne (肉沫豆腐)",
    desc: "Fein gehacktes Hähnchenhack mit Tofuwürfeln in milder Sojasauce.",
    story: "Roumo Doufu ist der Inbegriff schneller chinesischer Alltagsküche – 15 Minuten von Pfanne bis Teller.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenhack 200 g", "Tofu fest 300 g", "Reis (roh) 150 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Hack krümelig anbraten, bis vollständig durch.", "Tofuwürfel vorsichtig untermischen.", "Mit Sojasauce und Ingwer würzen, 5 Min. ziehen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Hack vollständig durchgebraten",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-a",
    title: "Geschmortes Hähnchen mit Frühlingszwiebelöl (葱油焖鸡)",
    desc: "Hähnchenteile sanft in Frühlingszwiebelöl und Sojasauce geschmort.",
    story: "Congyou-Aromen (Frühlingszwiebel in heißem Öl gezogen) sind eine Grundtechnik der chinesischen Küche.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenschenkel ohne Haut 300 g", "Frühlingszwiebel 4 Stück", "Reis (roh) 150 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g"],
    steps: ["Frühlingszwiebel in wenig Öl bei milder Hitze aromatisieren.", "Hähnchen zugeben, rundum anbraten.", "Mit Sojasauce und Wasser 18 Min. schmoren, bis durch.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Warme Sojamilch mit Vollkornbrötchen",
    desc: "Ungesüßte warme Sojamilch, das klassische Duo zu chinesischem Streetfood-Frühstück.",
    story: "Doujiang gehört morgens auf jede Straßenecke Chinas – bei uns hausgemacht und mild.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Ungesüßte Sojamilch 500 ml", "Vollkornbrötchen 2 Stück", "Sesam geröstet 1 TL", "Frühlingszwiebel 1 Stück"],
    steps: ["Sojamilch warm erhitzen, nicht kochen.", "Brötchen leicht anrösten.", "Mit Sesam bestreuen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈62 g KH · Schwangerschaft ✓ pasteurisierte Sojamilch",
    swaps: "Sojamilch ↔ Hafermilch",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Sauer-scharfe Kartoffelstreifen mild (酸辣土豆丝)",
    desc: "Fein geschnittene Kartoffelstreifen, kurz gebraten, mit Essig statt Chili abgeschmeckt.",
    story: "Suanla Tudousi ist DAS Gericht, an dem in China jede Hobbyköchin ihre Messerarbeit übt.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Kartoffeln 350 g", "Karotte 60 g", "Reisessig mild 2 EL", "Sojasauce natriumarm 1 EL", "Hähnchenbrust 150 g"],
    steps: ["Kartoffeln in feine Streifen schneiden, kurz wässern.", "Mit Karotte und Hähnchen 5 Min. scharf anbraten.", "Mit Essig und Sojasauce ablöschen.", "Sofort servieren, solange die Kartoffeln noch Biss haben."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Weißkohl mit Glasnudeln (包菜粉丝)",
    desc: "Zart gebratener Weißkohl mit Glasnudeln und magerem Schweinefleisch, mild gewürzt.",
    story: "Baocai Fensi ist ein Resteküchen-Klassiker – schnell, günstig, in jeder Provinz mit eigener Note.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Glasnudeln (roh) 80 g", "Weißkohl 250 g", "Schweinefilet mager 180 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Glasnudeln in warmem Wasser einweichen.", "Fleisch anbraten, bis durch.", "Kohl zugeben, mitbraten.", "Nudeln untermischen, mit Sojasauce abschmecken."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-f",
    title: "Reisbrei mit eingelegtem Gemüse mild (小菜白粥)",
    desc: "Klassischer weißer Congee mit milden eingelegten Gemüsestreifen.",
    story: "Baizhou ist die Basis, auf der sich unzählige chinesische Frühstücksbeilagen aufbauen.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈10 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Wasser 800 ml", "Gurke eingelegt mild 60 g", "Karotte eingelegt mild 40 g"],
    steps: ["Reis mit Wasser 35 Min. weich köcheln, bis cremig.", "Eingelegtes Gemüse fein schneiden.", "Congee in Schalen füllen.", "Mit dem Gemüse servieren."],
    checks: "Diabetes ✓ – ≈66 g KH · Schwangerschaft ✓",
    swaps: "Reis ↔ Brauner Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "do-m",
    title: "Knoblauch-Brokkoli (蒜蓉西兰花)",
    desc: "Kurz blanchierter Brokkoli mit Knoblauch, klassische chinesische Gemüsebeilage als Hauptgericht ausgebaut.",
    story: "Suanrong Xilanhua zeigt, wie viel Aroma zwei Zutaten – Brokkoli und Knoblauch – tragen können.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Brokkoli 300 g", "Knoblauch 2 Zehen", "Hähnchenbrust 200 g", "Reis (roh) 150 g", "Sojasauce natriumarm 1 EL"],
    steps: ["Brokkoli 2 Min. blanchieren.", "Hähnchen anbraten, bis durch.", "Knoblauch und Brokkoli zugeben, kurz mitbraten.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-a",
    title: "Gebratene Mungbohnensprossen mit Rind (爆炒绿豆芽牛肉)",
    desc: "Knackige Mungbohnensprossen, scharf angebraten, mit magerem Rindfleisch.",
    story: "Baochao Lüdouya lebt von der Hitze der Pfanne – Sprossen dürfen nur Sekunden mitgaren, damit sie knackig bleiben.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch mager 220 g", "Mungbohnensprossen 250 g", "Reis (roh) 150 g", "Sojasauce natriumarm 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Rind in dünne Streifen schneiden, scharf anbraten bis durch.", "Sprossen zugeben, nur 1–2 Min. mitbraten.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Frühlingszwiebel-Eierpfannkuchen (葱花鸡蛋饼)",
    desc: "Dünner, herzhafter Eierpfannkuchen mit viel Frühlingszwiebel.",
    story: "Conghua Jidanbing ist die Heimversion des Streetfood-Klassikers Jianbing – ganz ohne Frittieren.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Eier 4 Stück", "Mehl 60 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 1 EL", "Wasser 80 ml"],
    steps: ["Mehl mit Wasser und Eiern glatt verrühren.", "Frühlingszwiebel untermischen.", "In wenig Öl von beiden Seiten goldbraun backen, bis vollständig gestockt.", "Mit Sojasauce beträufelt servieren."],
    checks: "Diabetes ✓ – ≈58 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Zucchini-Pfanne mit Ei (西葫芦炒蛋)",
    desc: "Zarte Zucchinistreifen mit Ei, ein schnelles Alltagsgericht aus dem Norden Chinas.",
    story: "Xihulu Chaodan steht für die schlichte, gemüsebetonte Seite der chinesischen Hausmannskost.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Zucchini 300 g", "Eier 3 Stück", "Reis (roh) 150 g", "Sojasauce natriumarm 1 EL", "Knoblauch 1 Zehe"],
    steps: ["Zucchini in Halbmonde schneiden.", "Ei in wenig Öl stocken lassen, herausnehmen.", "Zucchini und Knoblauch anbraten, Ei zurück in die Pfanne.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "Zucchini ↔ Gurke",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-a",
    title: "Kabeljau in Sojasauce gedämpft (豉油蒸鳕鱼)",
    desc: "Sanft gedämpfter Kabeljau mit warmer Sojasauce-Ingwer-Übergießung, kantonesische Technik.",
    story: "Das Dämpfen mit heißem Öl-Sojasauce-Guss ist eine der schonendsten Garmethoden der kantonesischen Küche.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljaufilet 280 g", "Ingwer 15 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Fisch mit Ingwerscheiben 8–10 Min. dämpfen, bis durchgegart.", "Frühlingszwiebel darüberstreuen.", "Sojasauce kurz erhitzen und darüber gießen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Kabeljau durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Gedämpfte Teigtaschen mit Lauch-Ei-Füllung (韭菜鸡蛋包子)",
    desc: "Hefeteigtaschen mit Schnittlauch-Ei-Füllung, vollständig durchgegart.",
    story: "Jiucai-Jidan-Baozi sind eines der beliebtesten vegetarischen Baozi Nordchinas.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Hefeteig (fertig) 300 g", "Eier 3 Stück", "Schnittlauch 100 g", "Sesamöl 1 TL", "Sojasauce natriumarm 1 EL"],
    steps: ["Ei vollständig durchbraten, klein hacken.", "Mit Schnittlauch, Sesamöl und Sojasauce mischen.", "Teig füllen, formen, 15 Min. dämpfen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈72 g KH · Schwangerschaft ✓ Ei vollständig durchgegart",
    swaps: "Schnittlauch ↔ Lauch",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Sauer-scharfe Suppe mild (家常酸辣汤)",
    desc: "Klare, sämige Suppe mit Tofu, Ei und Pilzen, mit Essig statt Chili balanciert.",
    story: "Suanlatang ist normalerweise feurig scharf – unsere Version setzt ganz auf die milde Säure des Essigs.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Tofu fest 200 g", "Champignons 100 g", "Eier 2 Stück", "Reisessig mild 2 EL", "Reis (roh) 130 g"],
    steps: ["Pilze und Tofu in Streifen in Brühe 8 Min. köcheln.", "Mit Essig abschmecken.", "Verquirltes Ei langsam einrühren.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Champignons ↔ Shiitake",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-a",
    title: "Geschmortes Schweinefilet süß-sauer (糖醋里脊)",
    desc: "Mageres, paniertes Schweinefilet in milder süß-saurer Sauce – ohne Frittieren, aus der Pfanne.",
    story: "Tangcu Liji ist einer der bekanntesten Exportschlager der chinesischen Küche, hier bewusst leichter gemacht.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Schweinefilet mager 260 g", "Maisstärke 2 EL", "Ananas 100 g", "Reisessig mild 2 EL", "Reis (roh) 150 g"],
    steps: ["Filetstreifen in Stärke wenden, in wenig Öl knusprig braten bis durch.", "Ananas kurz mitbraten.", "Mit Essig und wenig Zucker ablöschen, binden.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Reisbrei mit Ei und Fleischspieß-Streifen (肉丝蛋粥)",
    desc: "Herzhafter Congee mit dünnen Fleischstreifen und Ei, sonntagstauglich üppiger.",
    story: "Am Wochenende darf der Congee ruhig etwas reichhaltiger ausfallen als unter der Woche.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Hähnchenbrust 150 g", "Eier 2 Stück", "Hühnerbrühe natriumarm 700 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis in Brühe 30 Min. weich köcheln.", "Hähnchen in feinen Streifen zugeben, gar ziehen lassen.", "Verquirltes Ei einrühren.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Hähnchen und Ei durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Ameisen im Baum mild (蚂蚁上树)",
    desc: "Glasnudeln mit fein gehacktem Hackfleisch – der Name kommt von den Hackstückchen, die wie Ameisen an den Nudeln 'kleben'.",
    story: "Mayi Shangshu ist ein Sichuan-Klassiker, hier ganz ohne Chili, mit dem typischen süß-salzigen Grundaroma.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Glasnudeln (roh) 100 g", "Hähnchenhack 220 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Glasnudeln einweichen.", "Hack krümelig anbraten, bis vollständig durch.", "Nudeln, Sojasauce und etwas Wasser zugeben, 5 Min. ziehen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Claypot-Hähnchen-Pilz-Reis (香菇鸡肉煲仔饭)",
    desc: "Aromatischer Schmortopfreis mit Hähnchen und Shiitake, kantonesische Wochenausklang-Klassik.",
    story: "Bao Zai Fan wird traditionell direkt im heißen Tontopf serviert – bei uns aus dem Reiskocher, genauso aromatisch.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 220 g", "Shiitake 60 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Pilze nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
];

export default function Woche37DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="家常菜 · Chinesische Hausmannskost · Balanced"
      heroChips={["Woche 37", "Echte Hausmannskost", "5× 🍚 Reiskocher"]}
    />
  );
}
