/*
  GhibliKitchen – Woche 31 (Start: 2026-07-27)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: China-Woche – fast ausschließlich chinesische Klassiker & virale Food-Trends
  (IG/YouTube), bewusst wenig Zucker, nur 2× Reiskocher-Gericht statt jeden Tag.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 31",
  startDate: "2026-07-27",
  id: "woche-31-2026-07-27",
  lang: "de",
  sidebar: "Woche 31 (2026-07-27)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-07-27)",
  di: "Dienstag (2026-07-28)",
  mi: "Mittwoch (2026-07-29)",
  do: "Donnerstag (2026-07-30)",
  fr: "Freitag (2026-07-31)",
  sa: "Samstag (2026-08-01)",
  so: "Sonntag (2026-08-02)",
};

const UI_TITLES = {
  main: "Rezepte Woche 31",
  list: "Einkaufsliste Woche 31",
};

export const DATA = [
  // MONTAG
  {
    id: "mo-f",
    title: "Reiskocher-Congee mit Ei & Frühlingszwiebel (電鍋蛋花粥)",
    desc: "Klassischer Reisbrei, über Nacht oder morgens einfach im Reiskocher gegart.",
    story: "Der 'Set it and forget it'-Reiskocher-Congee ist auf Instagram/YouTube ein Dauerbrenner — Zutaten rein, Programm starten, fertig frühstücken.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Hühnerbrühe natriumarm 600 ml", "Frühlingszwiebel 1 Stück", "Sojasauce natriumarm 1 EL"],
    steps: ["Reis mit Brühe im Reiskocher auf Congee-Programm ansetzen.", "5 Min. vor Ende Ei einrühren, bis es vollständig stockt.", "Mit Sojasauce mild abschmecken.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓ · Low Sugar ✓ (ungesüßt)",
    swaps: "Ei ↔ Tofuwürfel",
    side: "Ungesüßter Tee.",
    remind: true,
    isViral: true,
    riceCooker: { enabled: true, program: "Congee", water: "1:6" },
  },
  {
    id: "mo-m",
    title: "Mapo-Aubergine mild ohne Chili (麻婆茄子微辣版)",
    desc: "Sichuan-inspirierte geschmorte Aubergine mit Hackfleisch, ganz ohne Chili/Chiliöl.",
    story: "Das Mapo-Aroma kommt hier aus milder Bohnenpaste und Ingwer statt aus Schärfe — genauso herzhaft, aber magenfreundlich.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Aubergine 300 g", "Schweinehack (mager) 150 g", "Reis (roh) 130 g", "Sojasauce natriumarm 2 EL", "Ingwer 10 g", "Maisstärke 1 TL"],
    steps: ["Aubergine in Stücke schneiden, in wenig Öl anschwitzen.", "Hack mit Ingwer krümelig anbraten.", "Mit Sojasauce und wenig Wasser ablöschen, 8 Min. sanft schmoren.", "Mit Maisstärke leicht binden, zu separat gekochtem Reis servieren."],
    checks: "Gastritis ✓ (ohne Chili) · Schwangerschaft ✓ (Hack durchgebraten) · Diabetes ✓ · Low Sugar ✓",
    swaps: "Schweinehack ↔ Hähnchenhack oder Tofu",
    side: "-",
    remind: false,
  },
  {
    id: "mo-a",
    title: "Kantonesisch gedämpfter Kabeljau mit Ingwer (清蒸鱈魚)",
    desc: "Klassiker der kantonesischen Küche: sanft gedämpfter Fisch mit Ingwer-Frühlingszwiebel-Öl.",
    story: "So schlicht wie berühmt — in Kantons Familienküchen der Inbegriff eines guten Abendessens.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Kabeljau 300 g", "Reis (roh) 130 g", "Ingwer 15 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Sesamöl 1 TL"],
    steps: ["Kabeljau mit Ingwerstreifen 10 Min. dämpfen.", "Reis separat kochen.", "Sojasauce und heißes Sesamöl über den Fisch geben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Fisch vollständig durchgegart) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs/Wolfsbarsch",
    side: "Warmer Gerstentee.",
    remind: true,
  },
  // DIENSTAG
  {
    id: "di-f",
    title: "Ungesüßte Sojamilch mit Vollkorn-Toast-Streifen (無糖豆漿配全麥吐司)",
    desc: "Warme, ungesüßte Sojamilch mit knusprigen Vollkorntoast-Streifen zum Dippen.",
    story: "Die leichte China-Frühstücksvariante des Youtiao-Klassikers — ganz ohne Frittieren und Zucker.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Sojamilch ungesüßt 500 ml", "Vollkorn-Toast 4 Scheiben", "Sesam geröstet 1 TL", "Frühlingszwiebel 1 Stück", "Sojasauce natriumarm 1 TL"],
    steps: ["Sojamilch sanft erwärmen (nicht kochen).", "Mit einem Spritzer Sojasauce leicht herzhaft würzen.", "Toast rösten und in Streifen schneiden.", "Mit Sesam bestreut und Toaststreifen zum Dippen servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ · Diabetes ✓ · Low Sugar ✓ (ungesüßte Sojamilch)",
    swaps: "Sojamilch ↔ Hafermilch ungesüßt",
    side: "-",
    remind: true,
  },
  {
    id: "di-m",
    title: "Wok-Ei-Bratreis im Wok-Hei-Stil (鑊氣蛋炒飯)",
    desc: "Eierbratreis mit dem rauchigen 'Wok Hei'-Aroma — durch sehr heißes, kurzes Anbraten statt Öl oder Schärfe.",
    story: "Das YouTube-berühmte 'Wok Hei'-Eierbratreis-Video hat Millionen Aufrufe — hier die milde, magenfreundliche Version davon.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 300 g", "Eier 3 Stück", "Erbsen 80 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL"],
    steps: ["Eier verquirlen, in sehr heißem Wok kurz stocken lassen, herausnehmen.", "Kalten Reis im selben Wok kurz und heiß anbraten, damit er 'hüpft'.", "Ei, Erbsen und Sojasauce zurück in den Wok geben, kurz durchschwenken.", "Mit Frühlingszwiebel bestreut sofort servieren."],
    checks: "Gastritis ✓ (wenig Öl) · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Erbsen ↔ Mais",
    side: "-",
    remind: false,
    isViral: true,
  },
  {
    id: "di-a",
    title: "Rotgeschmortes Schweinefilet, wenig Zucker (少糖紅燒里脊)",
    desc: "Mageres Schweinefilet in dunkler Sojasauce geschmort — bewusst mit deutlich weniger Zucker als klassisches Hong Shao Rou.",
    story: "Der Klassiker Hongshaorou ist normalerweise sehr süß — diese Version setzt auf Gewürze statt Zucker für die Tiefe.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Schweinefilet 300 g", "Reis (roh) 130 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Sternanis 1 Stück", "Zucker 1 TL (statt üblich 2–3 EL)"],
    steps: ["Filet in Würfel schneiden, kurz scharf anbraten.", "Mit Sojasauce, Ingwer, Sternanis und wenig Wasser ablöschen.", "20 Min. bei niedriger Hitze sanft schmoren, bis zart.", "Mit separat gekochtem Reis servieren."],
    checks: "Gastritis ✓ (wenig Öl, mild) · Schwangerschaft ✓ (vollständig durchgegart) · Diabetes ✓ · Low Sugar ✓ (Zucker stark reduziert)",
    swaps: "Schweinefilet ↔ Hähnchenschenkel ohne Haut",
    side: "Warmer Gerstentee.",
    remind: true,
  },
  // MITTWOCH
  {
    id: "mi-f",
    title: "Seidener Dampfei mit Krabbenfleisch (蟹肉蒸蛋)",
    desc: "Butterzartes gedämpftes Ei mit Krabbenfleisch — ein Instagram-Dauerbrenner für seine perfekte Wackel-Konsistenz.",
    story: "Der Trick fürs seidige Ergebnis: Ei und lauwarmes Wasser im Verhältnis 1:1,5, ganz sanft gedämpft.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Eier 4 Stück", "Krabbenfleisch (gegart) 100 g", "Hühnerbrühe natriumarm 200 ml", "Reis (roh) 120 g", "Sojasauce natriumarm 1 EL"],
    steps: ["Ei mit lauwarmer Brühe glatt verquirlen, durch ein Sieb streichen.", "In eine Schale gießen, Krabbenfleisch einlegen.", "Mit Frischhaltefolie abgedeckt 12 Min. sanft dämpfen, bis fest.", "Mit Sojasauce beträufelt zu Reis servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Ei & Krabbenfleisch vollständig durchgegart) · Diabetes ✓",
    swaps: "Krabbenfleisch ↔ Garnelen, klein geschnitten",
    side: "-",
    remind: true,
  },
  {
    id: "mi-m",
    title: "Hühnchen-Chop-Suey mit buntem Gemüse (雞肉雜燴)",
    desc: "Schnell gegartes Hähnchen mit viel Gemüse in leichter Sauce.",
    story: "Ein kantonesischer Wok-Klassiker, der in jede Restwoche passt.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Hähnchenbrust 220 g", "Karotte 80 g", "Sojasprossen 100 g", "Champignons 80 g", "Reis (roh) 130 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Hähnchen in Streifen schneiden, kurz anbraten.", "Gemüse nacheinander nach Garzeit zugeben.", "Mit Sojasauce und wenig Wasser kurz köcheln.", "Zu separat gekochtem Reis servieren."],
    checks: "Gastritis ✓ (wenig Öl) · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
  },
  {
    id: "mi-a",
    title: "Klare Hühnerbrühe mit Glasnudeln & Pak Choi (雞湯冬粉)",
    desc: "Leichte, klare Suppe mit Glasnudeln, Hähnchen und Pak Choi.",
    story: "Ein sanfter, wärmender Abschluss für einen ruhigen Mittwochabend.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Hähnchenbrust 200 g", "Glasnudeln 80 g", "Pak Choi 150 g", "Hühnerbrühe natriumarm 700 ml", "Ingwer 8 g"],
    steps: ["Brühe mit Ingwer aufkochen, Hähnchen darin gar ziehen lassen.", "Glasnudeln nach Packungsangabe einweichen, zugeben.", "Pak Choi in den letzten 2 Min. dazugeben.", "Mild abschmecken und servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Glasnudeln ↔ Reisnudeln",
    side: "-",
    remind: true,
  },
  // DONNERSTAG
  {
    id: "do-f",
    title: "Sesam-Süßkartoffel-Congee, wenig Zucker (芝麻紅薯粥)",
    desc: "Cremiger Reisbrei mit Süßkartoffel und schwarzem Sesam — die natürliche Süße kommt vom Gemüse, nicht vom Zucker.",
    story: "Ein warmes, sättigendes Frühstück ganz ohne zugesetzten Zucker.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 80 g", "Süßkartoffel 200 g", "Wasser 700 ml", "Schwarze Sesampaste 1 EL", "Walnüsse 15 g"],
    steps: ["Reis und gewürfelte Süßkartoffel mit Wasser 30 Min. sanft köcheln.", "Mit dem Kochlöffel etwas zerdrücken für Cremigkeit.", "Mit Sesampaste verrühren.", "Mit Walnüssen bestreut servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreich) · Low Sugar ✓ (ohne zugesetzten Zucker)",
    swaps: "Süßkartoffel ↔ Kürbis",
    side: "Ungesüßter Tee.",
    remind: true,
  },
  {
    id: "do-m",
    title: "Entrollte Frühlingsrollen-Bowl ohne Frittieren (免炸春捲碗)",
    desc: "Alle Frühlingsrollen-Zutaten als Bowl, ohne Teigmantel und ohne Frittieren.",
    story: "Der virale 'deconstructed spring roll'-Trend aus Kurzvideos — gleicher Geschmack, kein Frittierfett.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Hähnchenhack 180 g", "Weißkohl 150 g", "Karotte 80 g", "Glasnudeln 60 g", "Reisessig mild 1 TL", "Sojasauce natriumarm 2 EL"],
    steps: ["Hackfleisch krümelig anbraten.", "Kohl und Karotte fein raspeln, kurz mitdünsten.", "Glasnudeln separat einweichen, untermengen.", "Mit Sojasauce und wenig Reisessig abschmecken, als Bowl servieren."],
    checks: "Gastritis ✓ (Essig sehr sparsam) · Schwangerschaft ✓ (Hack durchgebraten) · Diabetes ✓",
    swaps: "Hähnchenhack ↔ Tofu-Crumble",
    side: "-",
    remind: false,
  },
  {
    id: "do-a",
    title: "Frühlingszwiebelöl-Nudeln mit Hähnchen (蔥油拌麵配雞肉)",
    desc: "Shanghaier Street-Food-Klassiker: Nudeln in warmem Frühlingszwiebelöl, hier mit gegartem Hähnchen ergänzt.",
    story: "Cong You Ban Mian ist einer der meistgekochten viralen China-Streetfood-Trends auf Social Media — hier magenfreundlich mit wenig Öl.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Weizennudeln 200 g", "Hähnchenbrust 200 g", "Frühlingszwiebel 4 Stück", "Sojasauce natriumarm 2 EL", "Sesamöl 1 TL"],
    steps: ["Hähnchen gar ziehen lassen, zerzupfen.", "Frühlingszwiebel in wenig Öl bei niedriger Hitze langsam bräunen, bis aromatisch.", "Nudeln kochen, abtropfen.", "Mit Zwiebelöl, Sojasauce und Hähnchen vermengen."],
    checks: "Gastritis ✓ (wenig Öl) · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Weizennudeln ↔ Vollkornnudeln",
    side: "Warmer Gerstentee.",
    remind: true,
  },
  // FREITAG
  {
    id: "fr-f",
    title: "Vollkorn-Mantou mit Rührei (全麥饅頭配炒蛋)",
    desc: "Gedämpfte Vollkorn-Mantou-Brötchen mit mildem Rührei.",
    story: "Mantou sind in Nordchina der Frühstücks-Grundpfeiler — hier in der Vollkornvariante.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Vollkorn-Mantou (fertig/tiefgekühlt) 4 Stück", "Eier 3 Stück", "Frühlingszwiebel 1 Stück", "Milch 1 EL", "Sojasauce natriumarm 1 TL"],
    steps: ["Mantou nach Packungsangabe dämpfen.", "Eier mit Milch verquirlen, sanft stocken lassen.", "Mit Sojasauce und Frühlingszwiebel würzen.", "Zusammen servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Mantou ↔ Vollkorn-Toast",
    side: "Kaffee oder Tee.",
    remind: true,
  },
  {
    id: "fr-m",
    title: "Gebratene Nudeln mit Garnelen (蝦仁炒麵)",
    desc: "Klassische chinesische Bratnudeln mit Garnelen und Gemüse.",
    story: "Ein zuverlässiger Wok-Favorit für einen entspannten Freitagmittag.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Reisnudeln 180 g", "Garnelen 200 g", "Sojasprossen 100 g", "Karotte 60 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Nudeln nach Packungsangabe vorbereiten.", "Garnelen kurz anbraten, herausnehmen.", "Gemüse im Wok kurz anbraten, Nudeln zugeben.", "Garnelen zurückgeben, mit Sojasauce vermengen."],
    checks: "Gastritis ✓ (wenig Öl) · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenhack",
    side: "-",
    remind: false,
  },
  {
    id: "fr-a",
    title: "Reiskocher-Claypot-Hähnchenreis, viraler One-Pot-Hack (電鍋煲仔雞飯)",
    desc: "Der kantonesische Claypot-Reis-Klassiker, komplett im Reiskocher statt im Tontopf.",
    story: "Der 'Claypot rice in a rice cooker'-Hack ist auf Instagram/YouTube ein Dauerbrenner, weil er den knusprigen Boden ganz ohne Tontopf hinbekommt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenschenkel ohne Haut 220 g", "Shiitake 30 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück", "Ingwer 8 g"],
    steps: ["Hähnchen mit Sojasauce und Ingwer kurz marinieren.", "Reis wie gewohnt in den Reiskocher geben.", "Hähnchen und Shiitake nach halber Garzeit obenauf legen, Deckel schließen.", "Vor dem Servieren vom Boden her vorsichtig umrühren, mit Frühlingszwiebel bestreuen."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    isViral: true,
    riceCooker: { enabled: true, program: "Claypot/Weißreis", water: "1:1,3", notes: "Hähnchen erst nach halber Garzeit zugeben, sonst wird's trocken." },
  },
  // SAMSTAG
  {
    id: "sa-f",
    title: "Herzhafter Fisch-Congee mit Sesam (魚片芝麻粥)",
    desc: "Milder Reisbrei mit zartem Fisch und geröstetem Sesam.",
    story: "Ein entspanntes Wochenendfrühstück ohne Eile.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 80 g", "Kabeljau 150 g", "Wasser 700 ml", "Ingwer 8 g", "Sesam geröstet 1 TL"],
    steps: ["Reis mit Wasser 30 Min. sanft köcheln.", "Fisch in dünnen Scheiben in den letzten 5 Min. mitgaren.", "Mit Ingwer würzen.", "Mit Sesam bestreut servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Fisch durchgegart) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Ungesüßter Tee.",
    remind: true,
  },
  {
    id: "sa-m",
    title: "Knoblauch-Aubergine gedünstet, wenig Öl (蒜蓉蒸茄子)",
    desc: "Gedünstete Aubergine mit mildem Knoblauch-Sojasauce-Dressing.",
    story: "Ein einfaches vegetarisches Gericht, das die Aubergine ganz ohne viel Öl cremig werden lässt.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Aubergine 350 g", "Reis (roh) 130 g", "Knoblauch 1 Zehe", "Sojasauce natriumarm 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Aubergine längs halbieren, 12 Min. dämpfen bis weich.", "Knoblauch in wenig Öl ganz sanft anschwitzen.", "Mit Sojasauce verrühren, über die Aubergine geben.", "Mit Frühlingszwiebel bestreut zu Reis servieren."],
    checks: "Gastritis ✓ (Knoblauch gut gegart, wenig Öl) · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Aubergine ↔ Zucchini",
    side: "-",
    remind: false,
  },
  {
    id: "sa-a",
    title: "Rindfleisch mit Brokkoli, kantonesisch (芥蘭牛肉)",
    desc: "Zartes Rindfleisch mit Brokkoli in leichter Sojasauce.",
    story: "Einer der bekanntesten kantonesischen Restaurant-Klassiker, hier mit magerem Rind und wenig Öl.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Rindfleisch (mager) 250 g", "Brokkoli 200 g", "Reis (roh) 130 g", "Sojasauce natriumarm 2 EL", "Maisstärke 1 TL", "Ingwer 8 g"],
    steps: ["Rind dünn schneiden, mit Maisstärke kurz marinieren.", "Rind scharf und kurz anbraten, herausnehmen.", "Brokkoli mit Ingwer kurz dünsten.", "Rind zurückgeben, mit Sojasauce vermengen, zu Reis servieren."],
    checks: "Gastritis ✓ (wenig Öl) · Schwangerschaft ✓ (Rind vollständig durchgegart) · Diabetes ✓",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
  },
  // SONNTAG
  {
    id: "so-f",
    title: "Milder Kürbis-Sesam-Congee, wenig Zucker (南瓜芝麻粥)",
    desc: "Sanfter Kürbis-Reisbrei, natürlich süß durch den Kürbis, ganz ohne zugesetzten Zucker.",
    story: "Ein ruhiges Sonntagsfrühstück, das lange satt hält.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 80 g", "Kürbis 200 g", "Wasser 700 ml", "Schwarze Sesampaste 1 TL", "Walnüsse 15 g"],
    steps: ["Reis und Kürbis mit Wasser 30 Min. sanft köcheln.", "Etwas zerdrücken für Cremigkeit.", "Mit Sesampaste verrühren.", "Mit Walnüssen bestreut servieren."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ · Diabetes ✓ · Low Sugar ✓ (ohne zugesetzten Zucker)",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "Ungesüßter Tee.",
    remind: true,
  },
  {
    id: "so-m",
    title: "Knoblauch-Bok-Choy mit Tofu (蒜蓉豆腐油菜)",
    desc: "Sanft gedünsteter Bok Choy mit Tofu in mildem Knoblauch-Sojasauce-Sud.",
    story: "Ein leichtes, schnelles vegetarisches Mittagessen für einen ruhigen Sonntag.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Bok Choy (Pak Choi) 250 g", "Tofu 200 g", "Reis (roh) 130 g", "Knoblauch 1 Zehe", "Sojasauce natriumarm 2 EL"],
    steps: ["Tofu in Würfel schneiden, sanft anbraten.", "Knoblauch kurz mitanschwitzen.", "Bok Choy zugeben, 3–4 Min. dünsten.", "Mit Sojasauce abschmecken, zu Reis servieren."],
    checks: "Gastritis ✓ (Knoblauch gut gegart) · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "-",
    remind: false,
  },
  {
    id: "so-a",
    title: "Gedämpfte Jiaozi mit Hühnchen-Gemüse-Füllung (蒸餃)",
    desc: "Gedämpfte Teigtaschen mit Hähnchen-Kohl-Füllung.",
    story: "Jiaozi-Falt-Videos gehören zu den meistgeklickten Kochvideos auf Social Media — ein schöner, gemeinsamer Wochenabschluss.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Jiaozi-Teigblätter 20 Stück", "Hähnchenhack 200 g", "Weißkohl 150 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Kohl fein hacken, kurz salzen und Flüssigkeit ausdrücken.", "Mit Hack, Ingwer und Sojasauce zu einer Füllung vermengen.", "Teigblätter füllen, sorgfältig verschließen.", "12 Min. im Dampfeinsatz vollständig dämpfen."],
    checks: "Gastritis ✓ · Schwangerschaft ✓ (Füllung vollständig durchgegart) · Diabetes ✓",
    swaps: "Hähnchenhack ↔ Schweinehack (mager)",
    side: "Warmer Gerstentee.",
    remind: true,
    isViral: true,
  },
];

export default function Woche31DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="China-Woche 🇨🇳 · Virale Trends · Low Sugar · Schwangerschaftsgeeignet"
      heroChips={["Woche 31", "China-Woche", "Wenig Zucker", "2× 🍚 Reiskocher (nicht jeden Tag)"]}
    />
  );
}
