/*
  GhibliKitchen – Woche 43 (Start: 2026-10-19)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Chinesische Frühstückskultur (中式早點) – jeden Tag anders, wie am Straßenstand.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 43",
  startDate: "2026-10-19",
  id: "woche-43-2026-10-19",
  lang: "de",
  sidebar: "Woche 43 (2026-10-19)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-10-19)",
  di: "Dienstag (2026-10-20)",
  mi: "Mittwoch (2026-10-21)",
  do: "Donnerstag (2026-10-22)",
  fr: "Freitag (2026-10-23)",
  sa: "Samstag (2026-10-24)",
  so: "Sonntag (2026-10-25)",
};

const UI_TITLES = {
  main: "Rezepte Woche 43",
  list: "Einkaufsliste Woche 43",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Sojamilch mit Sesamkringel (豆漿芝麻燒餅)",
    desc: "Warme, ungesüßte Sojamilch mit knusprigem Sesamgebäck – der Klassiker unter Chinas Frühstücksständen.",
    story: "Doujiang und Shaobing gehören seit Generationen zusammen, egal in welcher Stadt.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Ungesüßte Sojamilch 500 ml", "Mehl 150 g", "Sesam 2 EL", "Wasser 90 ml"],
    steps: ["Teig kneten, 20 Min. ruhen lassen.", "Ausrollen, mit Sesam bestreuen, in der Pfanne goldbraun backen.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Reisbrei mit Fleischstreifen (瘦肉粥)",
    desc: "Herzhafter Congee mit magerem Schweinefleisch – auch mittags ein beliebter Klassiker.",
    story: "In vielen Congee-Häusern läuft dieses Gericht den ganzen Tag über die Theke, nicht nur morgens.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Schweinefilet mager 150 g", "Ingwer 10 g", "Wasser 800 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Wasser 40 Min. weich köcheln.", "Fleisch fein geschnitten zugeben, gar ziehen lassen bis vollständig durch.", "Mit Ingwer würzen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "mo-a",
    title: "Gedämpfte Baozi-Runde mit Gemüsefüllung (素菜包子)",
    desc: "Hefeteigtaschen mit Pilz-Kohl-Füllung, herzhaft-vegetarisches Abendessen.",
    story: "Sucai Baozi zeigen, dass Baozi längst nicht nur mit Fleisch gefüllt werden.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Hefeteig (fertig) 320 g", "Champignons 150 g", "Chinakohl 150 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Pilze und Kohl fein hacken, kurz anbraten.", "Mit Sojasauce und Ingwer würzen, auskühlen lassen.", "Teig füllen, formen, 15 Min. dämpfen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓",
    swaps: "Champignons ↔ Shiitake",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-f",
    title: "Ei-Frühlingszwiebel-Jianbing (雞蛋煎餅)",
    desc: "Dünner, knuspriger Getreidepfannkuchen mit Ei – die Heimversion des berühmten Streetfood-Klassikers.",
    story: "Original-Jianbing wird auf einer großen Gussplatte gegart – zuhause funktioniert die Pfanne genauso gut.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Mehl 80 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 1 EL", "Wasser 100 ml"],
    steps: ["Teig aus Mehl und Wasser glattrühren.", "Dünn in der Pfanne ausbacken, Ei darauf verteilen.", "Wenden, bis Ei vollständig gestockt ist.", "Mit Sojasauce und Frühlingszwiebel servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Congee mit Pilzen und Hähnchen (菌菇雞肉粥)",
    desc: "Wärmender Reisbrei mit Champignons und zartem Hähnchen.",
    story: "Auch mittags ist Congee in China eine völlig normale, sättigende Wahl.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Hähnchenbrust 180 g", "Champignons 80 g", "Wasser 800 ml", "Ingwer 8 g"],
    steps: ["Reis mit Wasser 35 Min. weich köcheln.", "Hähnchen und Pilze zugeben, gar ziehen lassen bis vollständig durch.", "Mit Ingwer würzen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Champignons ↔ Shiitake",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "di-a",
    title: "Gedämpfter Kabeljau mit Sojasauce (豉油蒸鱈魚)",
    desc: "Sanft gedämpfter Kabeljau mit warmem Sojasauce-Ingwer-Guss, kantonesische Technik.",
    story: "Ein ruhiger Abendabschluss, der die schonende Dampfgartechnik zeigt.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljaufilet 280 g", "Ingwer 15 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Fisch mit Ingwer 10 Min. dämpfen, bis vollständig durchgegart.", "Frühlingszwiebel darüberstreuen.", "Sojasauce erhitzen, über den Fisch gießen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Kabeljau durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Klebreisrolle mit Ei und Frühlingszwiebel (糯米飯團)",
    desc: "Klebreis mit durchgebratenem Ei gefüllt, herzhaftes tragbares Frühstück.",
    story: "Fantuan sind in Shanghai und Umgebung eines der beliebtesten Frühstücke zum Mitnehmen.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Klebreis (roh) 120 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 1 EL"],
    steps: ["Klebreis gar dämpfen.", "Ei vollständig durchbraten, in Streifen schneiden.", "Reis flach drücken, Ei einrollen.", "In Scheiben servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Klebreis ↔ Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Klebreis", water: "1:1" },
  },
  {
    id: "mi-m",
    title: "Gebratener Reis mit Garnelen (蝦仁炒飯)",
    desc: "Lockerer gebratener Reis mit Garnelen, Ei und Erbsen.",
    story: "Xiaren Chaofan ist eine der beliebtesten Fried-Rice-Varianten in ganz China.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 280 g", "Garnelen (gegart) 180 g", "Eier 2 Stück", "Erbsen (TK) 100 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Ei in wenig Öl stocken lassen, grob zerteilen.", "Reis zugeben, kräftig anbraten.", "Garnelen und Erbsen untermischen, durcherhitzen.", "Mit Sojasauce abschmecken."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Ei und Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Kochschinken",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Geschmortes Hähnchen mit Kastanien-Alternative (栗子雞風)",
    desc: "Hähnchen mit Süßkartoffelwürfeln in dunkler Sojasauce geschmort, als Kastanien-Alternative.",
    story: "Liziji ist ein herbstliches Festtagsgericht – Süßkartoffel bringt hier die passende erdig-süße Note.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenschenkel ohne Haut 280 g", "Süßkartoffel 150 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen anbraten.", "Süßkartoffel zugeben, mit Sojasauce, Ingwer und Wasser 20 Min. schmoren, bis alles durch ist.", "Sauce leicht einkochen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Süßkartoffel ↔ Kürbis",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Reisnudelsuppe zum Frühstück (米粉湯)",
    desc: "Dünne Reisnudeln in klarer Brühe mit Ei, leichtes und schnelles Frühstück.",
    story: "Mifentang zeigt die Reisnudel-Tradition Südchinas, wo Reis statt Weizen die Küche prägt.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reisnudeln 120 g", "Eier 2 Stück", "Gemüsebrühe natriumarm 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Nudeln in der Brühe 3 Min. garen.", "Verquirltes Ei einrühren.", "Mit Frühlingszwiebel bestreuen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈72 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Reisnudeln ↔ Glasnudeln",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Sauer-scharfe Kartoffelstreifen mit Hähnchen (酸辣土豆絲雞肉)",
    desc: "Feine Kartoffelstreifen mit Hähnchen, mild mit Essig statt Chili abgeschmeckt.",
    story: "Eine proteinreichere Version des Sichuan-Klassikers aus Woche 37.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Kartoffeln 300 g", "Hähnchenbrust 200 g", "Reisessig mild 2 EL", "Sojasauce natriumarm 1 EL", "Karotte 60 g"],
    steps: ["Kartoffeln in feine Streifen schneiden, kurz wässern.", "Mit Hähnchen und Karotte 6 Min. anbraten bis durch.", "Mit Essig und Sojasauce ablöschen.", "Sofort servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Rindfleisch-Kohl-Eintopf (白菜牛肉煲)",
    desc: "Mageres Rinderhack mit Weißkohl in milder Sojasauce geschmort.",
    story: "Ein herzhafter, wärmender Herbsteintopf, der zu jeder Jahreszeit passt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Rinderhack mager 220 g", "Weißkohl 200 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Hack krümelig anbraten, bis vollständig durch.", "Kohl zugeben, mit Sojasauce und Wasser 15 Min. köcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Gedämpfte Reisnudelrolle mit Garnelen (蝦腸粉)",
    desc: "Zarte Reisnudelrolle mit Garnelenfüllung, kantonesischer Dim-Sum-Frühstücksklassiker.",
    story: "Xia Changfen zählt zu den beliebtesten Frühstücks-Dim-Sum überhaupt.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reismehl 80 g", "Wasser 200 ml", "Garnelen (gegart, klein geschnitten) 100 g", "Sojasauce natriumarm 1 EL"],
    steps: ["Reismehl mit Wasser glattrühren.", "Dünn auf ein geöltes Blech gießen, Garnelen verteilen.", "8 Min. dämpfen bis vollständig durch, aufrollen.", "Mit Sojasauce beträufelt servieren."],
    checks: "Diabetes ✓ – ≈74 g KH · Schwangerschaft ✓ Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Ei",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Zhajiangmian mit Gemüse (炸醬素麵)",
    desc: "Weizennudeln mit Gemüse-Bohnenpaste-Sauce, vegetarische Pekinger Nudeln.",
    story: "Eine gemüsebetonte Variante des klassischen Zhajiangmian aus Woche 41.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizennudeln 200 g", "Champignons 150 g", "Gelbe Bohnenpaste mild 2 EL", "Gurke 80 g", "Karotte 60 g"],
    steps: ["Pilze fein hacken, anbraten.", "Bohnenpaste und etwas Wasser zugeben, 8 Min. köcheln.", "Nudeln kochen.", "Sauce über die Nudeln geben, mit Gurke und Karotte servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓",
    swaps: "Champignons ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Weißes geschnittenes Hähnchen mit Ingweröl (蔥薑白切雞)",
    desc: "Sanft pochiertes Hähnchen mit Ingwer-Frühlingszwiebel-Öl, kalt in Scheiben serviert.",
    story: "Der kantonesische Klassiker aus Woche 39, hier als ruhiger Wochenausklang wiederholt.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenbrust 300 g", "Ingwer 20 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Hähnchen in Wasser 20 Min. sanft pochieren, bis Kerntemperatur ≥75 °C erreicht ist.", "Ingwer und Frühlingszwiebel fein hacken, in warmem Öl übergießen.", "Hähnchen in Scheiben schneiden.", "Mit dem Öl beträufelt und Reis servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenbrust ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "You Tiao-Alternative mit Sojamilch (健康版油條豆漿)",
    desc: "Im Ofen gebackene Teigstangen statt frittiert, mit warmer Sojamilch.",
    story: "Klassisches Youtiao wird frittiert – unsere Ofenvariante behält die Form, spart aber das Frittieröl.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Mehl 150 g", "Backpulver 1 TL", "Ungesüßte Sojamilch 500 ml", "Wasser 60 ml"],
    steps: ["Teig aus Mehl, Backpulver und Wasser kneten.", "Zu Stangen formen, im Ofen bei 200 °C 15 Min. backen.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Kalte Sesamnudeln mit Ei (麻醬雞蛋涼麵)",
    desc: "Kühle Weizennudeln mit Sesamsauce und Ei-Streifen.",
    story: "Ein erfrischendes Wochenendgericht, das auch an kühleren Tagen überzeugt.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Eier 2 Stück", "Sesampaste 2 EL", "Sojasauce natriumarm 2 EL", "Gurke 80 g"],
    steps: ["Ei separat vollständig durchbraten, in Streifen schneiden.", "Nudeln kochen, kalt abschrecken.", "Sesampaste mit Sojasauce glattrühren.", "Alles mit Gurkenstreifen vermengen."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "-",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Claypot-Pilz-Hähnchen-Reis (香菇雞煲仔飯)",
    desc: "Aromatischer Schmortopfreis mit Hähnchen und Shiitake.",
    story: "Ein bewährter Wochenend-Klassiker, der schon in Woche 37 überzeugt hat.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 220 g", "Shiitake 60 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Pilze nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
  {
    id: "so-f",
    title: "Sonntags-Dim-Sum-Auswahl (蒸點心拼盤)",
    desc: "Gedämpfte Hackbällchen und Gemüse-Baozi gemeinsam serviert, kleines Dim-Sum-Frühstück.",
    story: "Ein entspannter Sonntagmorgen, wie er in vielen kantonesischen Familien mit Dim Sum beginnt.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Hefeteig (fertig) 200 g", "Champignons 100 g", "Hähnchenhack 120 g", "Sojasauce natriumarm 2 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Pilze fein hacken, mit Hack und Sojasauce vermengen.", "Kleine Baozi formen.", "12 Min. dämpfen, bis Füllung vollständig durchgegart ist.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓ Füllung vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Gebratener Reis mit Rind und Ei (牛肉蛋炒飯)",
    desc: "Kräftig gebratener Reis mit magerem Rindfleisch und Ei.",
    story: "Ein herzhafter Sonntagslunch, der die Frühstückswoche mit vertrautem Wok-Aroma verbindet.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 280 g", "Rinderhack mager 180 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL"],
    steps: ["Hack krümelig anbraten, bis vollständig durch.", "Ei zugeben, stocken lassen.", "Reis zugeben, kräftig anbraten.", "Mit Sojasauce und Frühlingszwiebel abschmecken."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Hack und Ei durchgegart",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Wochenausklang-Congee mit Hähnchen und Pilzen (收尾雞肉菌菇粥)",
    desc: "Wärmender Reisbrei mit Hähnchen und Champignons als ruhiger Abschluss der Frühstückswoche.",
    story: "Ein bewusst einfaches Gericht zum Ausklang – Congee schließt den Kreis zu Montagmorgen.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Hähnchenbrust 180 g", "Champignons 80 g", "Hühnerbrühe natriumarm 700 ml", "Frühlingszwiebel 2 Stück"],
    steps: ["Reis in Brühe 35 Min. weich köcheln.", "Hähnchen und Pilze zugeben, gar ziehen lassen bis vollständig durch.", "Mild abschmecken.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Champignons ↔ Shiitake",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: false },
  },
];

export default function Woche43DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="中式早點 🥣 · Frühstück den ganzen Tag · Balanced"
      heroChips={["Woche 43", "Frühstückskultur", "5× 🍚 Reiskocher"]}
    />
  );
}
