/*
  GhibliKitchen – Woche 36 (Start: 2026-08-31)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Herbstauftakt: wärmende Eintöpfe, Congee und die ersten kühleren Abende.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 36",
  startDate: "2026-08-31",
  id: "woche-36-2026-08-31",
  lang: "de",
  sidebar: "Woche 36 (2026-08-31)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-08-31)",
  di: "Dienstag (2026-09-01)",
  mi: "Mittwoch (2026-09-02)",
  do: "Donnerstag (2026-09-03)",
  fr: "Freitag (2026-09-04)",
  sa: "Samstag (2026-09-05)",
  so: "Sonntag (2026-09-06)",
};

const UI_TITLES = {
  main: "Rezepte Woche 36",
  list: "Einkaufsliste Woche 36",
};

export const DATA = [
{
    id: "mo-f",
    title: "Herbst-Congee mit Kürbis und Hähnchen (南瓜雞肉粥)",
    desc: "Wärmender Reisbrei mit Kürbis und zartem Hähnchen zum Herbstauftakt.",
    story: "Der erste kühle Morgen der Saison ruft nach einem wärmenden Congee.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Kürbis 120 g", "Hähnchenbrust 120 g", "Hühnerbrühe 500 ml", "Ingwer 10 g"],
    steps: ["Reis mit Brühe und Kürbis 30 Min. weich köcheln.", "Hähnchen fein geschnitten in den letzten 10 Min. mitgaren.", "Mit Ingwer würzen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Warmer Rettich-Nudel-Eintopf (蘿蔔麵湯)",
    desc: "Milde Brühe mit Daikon-Rettich und dünnen Nudeln.",
    story: "Ein sanfter Mittagseintopf, der den Übergang in den Herbst einläutet.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Weizennudeln 150 g", "Daikon 150 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Daikon in Scheiben 15 Min. in der Brühe köcheln.", "Nudeln zugeben, gar ziehen lassen.", "Mit Sojasauce abschmecken.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Daikon ↔ Karotte",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Geschmortes Hähnchen mit Wurzelgemüse (根菜煮込みチキン)",
    desc: "Sanft geschmortes Hähnchen mit Karotten und Daikon in milder Sojasauce.",
    story: "Ein wärmendes Schmorgericht, das den Herbst willkommen heißt.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Karotte 100 g", "Daikon 100 g", "Reis (roh) 150 g", "Sojasauce 3 EL"],
    steps: ["Hähnchen anbraten.", "Wurzelgemüse zugeben, mit Sojasauce und Wasser 20 Min. schmoren.", "Reis im Reiskocher zubereiten.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Congee mit Pilzen und Ei (菌菇蛋粥)",
    desc: "Sanfter Reisbrei mit Champignons und Ei.",
    story: "Ein beruhigendes Frühstück für die ersten kühleren Tage.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Champignons 80 g", "Eier 2 Stück", "Gemüsebrühe 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Pilze in den letzten 10 Min. zugeben.", "Verquirltes Ei einrühren, stocken lassen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Champignons ↔ Shiitake",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Süßkartoffel-Tofu-Eintopf (蕃薯豆腐煲)",
    desc: "Weich geschmorte Süßkartoffel mit Tofu in milder Brühe.",
    story: "Ein sättigendes, ballaststoffreiches Mittagsgericht.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Süßkartoffel 200 g", "Tofu 200 g", "Gemüsebrühe 400 ml", "Sojasauce 2 EL", "Ingwer 10 g"],
    steps: ["Süßkartoffel in Würfeln 15 Min. köcheln.", "Tofu zugeben, kurz mitziehen lassen.", "Mit Sojasauce und Ingwer würzen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Süßkartoffel)",
    swaps: "Süßkartoffel ↔ Kürbis",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Miso-Lachs-Eintopf herbstlich (味噌鮭魚煮込み)",
    desc: "Lachs und Daikon in milder Miso-Brühe geschmort.",
    story: "Ein wärmendes Fischgericht für die ersten kühlen Abende.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Lachsfilet 260 g", "Daikon 120 g", "Miso-Paste 2 EL", "Reis (roh) 150 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Daikon in der Brühe 15 Min. köcheln.", "Lachs zugeben, 8 Min. gar ziehen lassen.", "Miso einrühren, nicht mehr kochen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Warmer Kastanien-Milchreis (栗子粥)",
    desc: "Cremiger Milchreis mit Walnüssen als Kastanien-Alternative.",
    story: "Ein nussig-süßes Frühstück, das an herbstliche Röstkastanien erinnert.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Walnüsse 30 g", "Zimt 1 Prise", "Agavendicksaft 1 TL"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Walnüsse grob hacken, unterheben.", "Mit Zimt und Agavendicksaft abschmecken.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Walnüsse ↔ Mandeln",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Minestrone mit Kürbis herbstlich",
    desc: "Milde Gemüsesuppe mit Kürbis, weißen Bohnen und kurzen Nudeln.",
    story: "Der italienische Programmpunkt der Woche, herbstlich mit Kürbis verfeinert.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Kurze Nudeln 100 g", "Kürbis 150 g", "Weiße Bohnen 120 g", "Passierte Tomaten 150 ml", "Olivenöl 1 EL"],
    steps: ["Kürbis in wenig Öl anschwitzen.", "Tomaten und Wasser zugeben, 15 Min. mild köcheln.", "Bohnen und Nudeln zugeben, gar ziehen lassen.", "Mit Olivenöl abrunden."],
    checks: "Balanced ✓ (Tomate mild eingekocht) · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Bohnen)",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Rinderhack-Kohl-Eintopf mild (白菜牛肉煲)",
    desc: "Mageres Rinderhack mit Weißkohl in milder Sojasauce geschmort.",
    story: "Ein herzhafter, wärmender Herbsteintopf.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Rinderhack (mager) 220 g", "Weißkohl 200 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Ingwer 10 g"],
    steps: ["Hack krümelig anbraten.", "Kohl zugeben, mit Sojasauce und Wasser 15 Min. köcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hack vollständig durchgebraten) · Diabetes ✓",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Ei-Tofu-Congee (蛋豆腐粥)",
    desc: "Sanfter Reisbrei mit Ei und Tofu, extra proteinreich.",
    story: "Ein nahrhaftes Frühstück für einen vollen Herbsttag.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Tofu 100 g", "Hühnerbrühe 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Tofu zugeben.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Tofu ↔ Champignons",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Gebratener Kohl mit Hähnchen (白菜炒雞肉)",
    desc: "Weißkohl mit zartem Hähnchen, mild in Sojasauce gebraten.",
    story: "Ein einfaches, schnelles Alltagsgericht mit herbstlichem Kohl.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Hähnchenbrust 200 g", "Weißkohl 180 g", "Karotte 60 g", "Sojasauce 2 EL", "Reis (roh) 100 g"],
    steps: ["Hähnchen in Streifen anbraten.", "Kohl und Karotte zugeben, mitbraten.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Kabeljau-Kürbis-Eintopf (鱈魚南瓜煲)",
    desc: "Milder Eintopf mit Kabeljau und Kürbis in leichter Brühe.",
    story: "Ein besonders bekömmliches Fischgericht für kühlere Abende.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljau 260 g", "Kürbis 150 g", "Reis (roh) 150 g", "Ingwer 10 g", "Sojasauce 2 EL"],
    steps: ["Kürbis in der Brühe 15 Min. köcheln.", "Kabeljau mit Ingwer zugeben, 8 Min. gar ziehen lassen.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Kabeljau durchgegart) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Warme Sojamilch mit Frühlingszwiebel-Reisbällchen",
    desc: "Warme Milch mit gefüllten Reisbällchen als herzhaftes Duo.",
    story: "Ein taiwanesisches Frühstücksduo zum Wochenausklang.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 120 g", "Eier 2 Stück", "Milch 300 ml", "Frühlingszwiebel 1 Stück", "Sojasauce 1 EL"],
    steps: ["Reis kochen, zu Bällchen formen, mit hartgekochtem Ei füllen.", "Milch warm erhitzen.", "Reisbällchen mit Sojasauce beträufeln.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgekocht, Milch pasteurisiert) · Diabetes ✓",
    swaps: "Milch ↔ ungesüßte Sojamilch",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Pilz-Hähnchen-Udon herbstlich (菌菇鶏うどん)",
    desc: "Udon-Nudeln mit Hähnchen und Pilzen in milder Brühe.",
    story: "Ein wärmendes Nudelgericht für den Übergang in die kühlere Jahreszeit.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Udon 200 g", "Hähnchenbrust 180 g", "Shiitake 30 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Hähnchen in der Brühe gar ziehen lassen.", "Pilze zugeben.", "Udon zugeben, gar ziehen lassen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Claypot-Rettich-Hähnchen-Reis (煲仔蘿蔔雞飯)",
    desc: "Aromatischer Schmortopfreis mit Daikon und Hähnchen.",
    story: "Ein wärmendes One-Pot-Gericht zum Ausklang der Woche.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 220 g", "Daikon 100 g", "Sojasauce 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Daikon nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
  {
    id: "sa-f",
    title: "Kürbis-Ei-Toast herbstlich",
    desc: "Vollkorntoast mit Kürbispüree und einem weich gestockten Ei.",
    story: "Ein herbstliches Wochenendfrühstück mit warmem Kürbisaroma.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Vollkorn-Toast 4 Scheiben", "Kürbis 150 g", "Eier 2 Stück", "Butter 1 TL", "Frühlingszwiebel 1 Stück"],
    steps: ["Kürbis weich kochen, pürieren.", "Auf Toast verteilen.", "Ei in Butter vollständig durchbraten.", "Auf den Toast legen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Sojasprossen-Hähnchen-Reisschale herbstlich (豆芽雞肉丼)",
    desc: "Reisschale mit Sojasprossen und Hähnchen, mild sojagewürzt.",
    story: "Ein einfaches, sättigendes Wochenendgericht.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Reis (roh) 150 g", "Hähnchenbrust 180 g", "Sojasprossen 150 g", "Sojasauce 2 EL", "Sesamöl 1 TL"],
    steps: ["Reis im Reiskocher zubereiten.", "Hähnchen anbraten.", "Sojasprossen kurz mitbraten.", "Mit Sojasauce und Sesamöl abschmecken, auf Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-a",
    title: "Herbstlicher Rindfleisch-Kürbis-Topf (南瓜牛肉煲)",
    desc: "Zartes Rindfleisch mit Kürbis in milder Sojasauce geschmort.",
    story: "Ein wärmendes Samstagabend-Schmorgericht.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rindfleisch (mager) 250 g", "Kürbis 150 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Ingwer 10 g"],
    steps: ["Rind anbraten.", "Kürbis zugeben, mit Sojasauce und Wasser 15 Min. köcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Rind vollständig durchgegart) · Diabetes ✓",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Warmer Congee zum Wochenausklang mit Ei und Frühlingszwiebel",
    desc: "Klassischer, sanfter Reisbrei mit Ei und Frühlingszwiebel.",
    story: "Ein ruhiger, vertrauter Abschluss der zehnwöchigen Plan-Serie.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Hühnerbrühe 500 ml", "Frühlingszwiebel 2 Stück", "Sojasauce 1 EL"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Sojasauce würzen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Ei ↔ Tofuwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Vollkorn-Nudelsalat mit Herbstgemüse warm",
    desc: "Warmer Nudelsalat mit Kürbis, Karotte und mildem Sesamdressing.",
    story: "Ein bunter, wärmender Sonntagslunch.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Vollkorn-Penne 180 g", "Kürbis 100 g", "Karotte 80 g", "Sojasauce 2 EL", "Sesamöl 1 TL"],
    steps: ["Nudeln kochen.", "Kürbis und Karotte weich dünsten.", "Alles vermengen.", "Mit Sojasauce und Sesamöl abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Vollkorn-Penne ↔ Gnocchi",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Hähnchen-Congee zum Wochen- und Serienausklang (雞肉粥收尾)",
    desc: "Wärmender Reisbrei mit Hähnchen als ruhiger Abschluss der Plan-Serie.",
    story: "Ein bewusst einfaches, vertrautes Gericht, um die zehn neuen Wochen abzurunden.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Reis (roh) 120 g", "Hähnchenbrust 220 g", "Hühnerbrühe 600 ml", "Ingwer 10 g", "Frühlingszwiebel 2 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Hähnchen zugeben, gar ziehen lassen.", "Mit Ingwer würzen.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  }
];

export default function Woche36DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Wärmende Eintöpfe & Congee 🍂 · Herbstauftakt · Balanced"
      heroChips={["Woche 36", "Herbstauftakt", "7× 🍚 Reiskocher"]}
    />
  );
}
