/*
  GhibliKitchen – Woche 27 (Start: 2026-06-29)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Hochsommer-Kühlküche, kalte Nudeln & sanfte Congees, viel Dampfgaren.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 27",
  startDate: "2026-06-29",
  id: "woche-27-2026-06-29",
  lang: "de",
  sidebar: "Woche 27 (2026-06-29)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-06-29)",
  di: "Dienstag (2026-06-30)",
  mi: "Mittwoch (2026-07-01)",
  do: "Donnerstag (2026-07-02)",
  fr: "Freitag (2026-07-03)",
  sa: "Samstag (2026-07-04)",
  so: "Sonntag (2026-07-05)",
};

const UI_TITLES = {
  main: "Rezepte Woche 27",
  list: "Einkaufsliste Woche 27",
};

export const DATA = [
{
    id: "mo-f",
    title: "Sommer-Reisbrei mit Pfirsich (桃粥)",
    desc: "Cremiger Reisbrei, sanft gesüßt mit reifem Pfirsich und einem Hauch Zimt.",
    story: "Ein leichtes Frühstück für heiße Morgen – der Reis wird extra weich gekocht, damit er kühl serviert werden kann.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Pfirsich 2 Stück", "Zimt 1 TL", "Agavendicksaft 1 TL", "Mandeln 20 g"],
    steps: ["Reis mit Milch und wenig Wasser 25 Min. weich köcheln, öfter rühren.", "Pfirsich in kleine Würfel schneiden, die Hälfte unterrühren.", "Mit Zimt und Agavendicksaft abschmecken.", "Mit restlichem Pfirsich und gehackten Mandeln servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert, durchgekocht) · Diabetes ✓ (langsam gegarter Reis, ballaststoffreich durch Mandeln)",
    swaps: "Pfirsich ↔ Aprikose",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Kalte Soba mit Ei-Streifen (冷やしそば)",
    desc: "Gekühlte Buchweizennudeln mit dünnen Omelettstreifen und milder Dip-Sauce.",
    story: "Ein Klassiker aus Tokio für die Sommerhitze – die Nudeln werden nach dem Kochen eiskalt abgeschreckt.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Soba-Nudeln 180 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce 3 EL", "Mirin 1 EL", "Gemüsebrühe 200 ml"],
    steps: ["Soba nach Packung kochen, kalt abschrecken.", "Eier zu einem dünnen Omelett braten, komplett stocken lassen, in Streifen schneiden.", "Sojasauce, Mirin und Brühe verrühren, kalt stellen.", "Nudeln mit Ei-Streifen und Frühlingszwiebel anrichten, Sauce separat reichen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Soba ↔ Udon",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Gedämpfter Kabeljau mit Ingwer (清蒸鱈魚)",
    desc: "Schonend gedämpftes Kabeljaufilet mit Ingwer-Frühlingszwiebel-Öl und Reis.",
    story: "Ein kantonesischer Klassiker – das milde Dämpfen erhält die zarte Textur des Fisches.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Kabeljau 300 g", "Reis (roh) 140 g", "Ingwer 20 g", "Frühlingszwiebel 3 Stück", "Sojasauce 2 EL", "Pak Choi 150 g"],
    steps: ["Reis im Reiskocher zubereiten.", "Kabeljau mit Ingwerscheiben 10 Min. dämpfen, bis er sich leicht blättert.", "Pak Choi kurz mitdämpfen.", "Frühlingszwiebel und heißes Öl über den Fisch geben, mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Fisch >80°C durchgegart, quecksilberarm) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2", notes: "Reis parallel zum Dämpfen ansetzen." },
  },
  {
    id: "di-f",
    title: "Gedämpftes Ei mit Garnelen (蝦仁蒸蛋)",
    desc: "Samtiges Dampf-Ei mit kleinen Garnelenstücken und Frühlingszwiebel.",
    story: "Chawanmushi-artiges Frühstück, das Kindern wie Erwachsenen gleichermaßen schmeckt.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Eier 4 Stück", "Garnelen 100 g", "Hühnerbrühe 200 ml", "Frühlingszwiebel 1 Stück", "Sojasauce 1 EL", "Toastbrot 4 Scheiben"],
    steps: ["Eier mit lauwarmer Brühe verquirlen, durch ein Sieb streichen.", "Garnelen unterheben, in Schälchen füllen.", "12 Min. sanft dämpfen, bis fest gestockt.", "Mit Sojasauce und Frühlingszwiebel garnieren, Toast dazu reichen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei und Garnelen vollständig durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Krabbenfleisch (gekocht)",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Japchae mit Hähnchen (닭고기 잡채)",
    desc: "Glasnudeln mit buntem Gemüse und zartem Hähnchen, mild sojagewürzt.",
    story: "Koreanisches Fest-Gericht ohne Schärfe – jede Zutat wird einzeln angebraten für feine Aromen.",
    target: "≈75 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Glasnudeln 150 g", "Hähnchenbrust 200 g", "Karotte 100 g", "Spinat 100 g", "Champignons 100 g", "Sojasauce 3 EL"],
    steps: ["Glasnudeln nach Packung garen, abtropfen.", "Hähnchen in Streifen anbraten, beiseitestellen.", "Karotte, Spinat und Champignons nacheinander kurz anbraten.", "Alles mit Sojasauce und den Nudeln vermengen, warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓ (Glasnudeln moderat portioniert)",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Miso-Auberginen-Reisschale (茄子味噌丼)",
    desc: "Weich gedünstete Auberginen in süßlicher Miso-Glasur auf Reis.",
    story: "Nasu Dengaku als Bowl-Variante – die Aubergine wird gedünstet statt frittiert.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Aubergine (als Zucchini-Ersatz möglich) 2 Stück", "Reis (roh) 150 g", "Miso-Paste 2 EL", "Mirin 1 EL", "Sesamöl 1 TL", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis im Reiskocher zubereiten.", "Aubergine in Scheiben schneiden, in wenig Öl weich dünsten.", "Miso mit Mirin verrühren, über die Aubergine geben und kurz köcheln.", "Auf Reis anrichten, mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiches Gemüse)",
    swaps: "Aubergine ↔ Zucchini",
    side: "Warmer Mugicha (Gerstentee).",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Warmer Soja-Pudding (豆花)",
    desc: "Sanfter, warmer Sojapudding mit leichtem Ingwersirup.",
    story: "Douhua zum Frühstück – beruhigend für den Magen und leicht bekömmlich.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Seidentofu 400 g", "Milch 100 ml", "Agavendicksaft 2 EL", "Ingwer 10 g", "Mandeln 15 g"],
    steps: ["Seidentofu vorsichtig erwärmen, nicht kochen.", "Ingwer mit wenig Wasser und Agavendicksaft kurz aufkochen, absieben.", "Tofu in Schalen geben, mit dem Sirup übergießen.", "Mit gehackten Mandeln bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (pasteurisierte Milch) · Diabetes ✓",
    swaps: "Ingwersirup ↔ etwas Zimt",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Yaki Udon mit Tofu (豆腐焼きうどん)",
    desc: "Kräftig angebratene Udon-Nudeln mit Tofu und Kohlgemüse.",
    story: "Ein schnelles Pfannengericht, das sich gut für heiße Tage eignet, da es in einem Schritt fertig wird.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Udon 200 g", "Tofu 200 g", "Weißkohl 150 g", "Karotte 80 g", "Sojasauce 3 EL", "Sesamöl 1 EL"],
    steps: ["Udon kurz vorkochen.", "Tofu in Würfeln knusprig anbraten, herausnehmen.", "Kohl und Karotte anbraten, Udon dazugeben.", "Tofu zurückgeben, mit Sojasauce und Sesamöl abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Sanftes Bulgogi mit Reis (순한 불고기)",
    desc: "Mariniertes Rindfleisch, mild in Birnen-Soja-Marinade gegart, mit Reis.",
    story: "Bulgogi ganz ohne Schärfe – die Marinade setzt auf Süße statt Chili.",
    target: "≈85 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Rindfleisch (mager) 250 g", "Reis (roh) 150 g", "Birne (oder Apfel) 50 g", "Sojasauce 3 EL", "Knoblauch 1 Zehe", "Frühlingszwiebel 2 Stück"],
    steps: ["Rindfleisch dünn schneiden, mit püriertem Birnenstück, Sojasauce und Knoblauch 30 Min. marinieren.", "Reis im Reiskocher zubereiten.", "Fleisch in der Pfanne durchbraten.", "Mit Frühlingszwiebel bestreut auf Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Fleisch vollständig durchgebraten) · Diabetes ✓",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Milde Congee mit Hähnchen (雞肉粥)",
    desc: "Sämiger Reisbrei mit zart gegartem Hähnchen und Ingwer.",
    story: "Der klassische kantonesische Frühstücksbrei, ideal für einen ruhigen Magen.",
    target: "≈65 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Hähnchenbrust 120 g", "Hühnerbrühe 500 ml", "Ingwer 10 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Hähnchen fein geschnitten die letzten 10 Min. mitgaren.", "Mit Ingwer würzen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓ (langsam gegarter Reis)",
    swaps: "Hähnchen ↔ Tofuwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Sommer-Orzo mit gegartem Tomatensugo",
    desc: "Vollkorn-Orzo in einem lang eingekochten, milden Tomatensugo mit Basilikum.",
    story: "Der wöchentliche italienische Ausflug – die Tomaten köcheln extra lange, damit die Säure mild bleibt.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Kurze Nudeln 180 g", "Passierte Tomaten 300 ml", "Karotte 50 g", "Olivenöl 1 EL", "Basilikum 1 Bund", "Parmesan 20 g"],
    steps: ["Tomaten mit fein geriebener Karotte 20 Min. sanft köcheln, das mildert die Säure.", "Nudeln separat kochen.", "Sauce mit Olivenöl abrunden.", "Mit Basilikum und wenig Parmesan servieren."],
    checks: "Balanced ✓ (Tomate lang gegart, mild) · Schwangerschaft ✓ (Parmesan aus pasteurisierter Milch) · Diabetes ✓",
    swaps: "Orzo ↔ Vollkorn-Penne",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Gedünstetes Hähnchen-Curry mild (鶏肉のカレー)",
    desc: "Sanftes japanisches Curry mit Hähnchen, Karotten und Kartoffeln, wenig scharf.",
    story: "Japanisches Curry ist von Natur aus mild und süßlich – perfekt für einen ruhigen Magen.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Reis (roh) 150 g", "Karotte 120 g", "Zwiebel 80 g", "Mehl 1 EL", "Kurkuma 1 TL"],
    steps: ["Zwiebel und Karotte in wenig Öl weich dünsten.", "Hähnchen zugeben und gar ziehen lassen.", "Mit Mehl und Kurkuma bestäuben, mit Wasser ablöschen, 15 Min. köcheln.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Tamagoyaki-Sandwich (卵焼きサンド)",
    desc: "Leicht gesüßtes japanisches Omelett zwischen weichem Vollkorntoast.",
    story: "Der Tamago Sando aus Tokioter Konbinis, hausgemacht und milder gewürzt.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Eier 4 Stück", "Vollkorn-Toast 4 Scheiben", "Milch 2 EL", "Mayonnaise 1 EL", "Zucker 1 TL"],
    steps: ["Eier mit Milch und Zucker verquirlen, in mehreren Schichten zum Omelett rollen.", "Vollständig durchgaren.", "Toast mit wenig Mayonnaise bestreichen.", "Omelett hineinlegen und in Scheiben schneiden."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei komplett durchgegart) · Diabetes ✓",
    swaps: "Toast ↔ Vollkorn-Bagel",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Bibimbap mild ohne Chili (순한 비빔밥)",
    desc: "Bunte Reisschale mit Gemüse, Ei und Hähnchen, gewürzt mit Sesam statt Chili.",
    story: "Klassisches Bibimbap, bei dem Gochujang durch eine milde Sesam-Soja-Sauce ersetzt wird.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Reis (roh) 150 g", "Hähnchenbrust 150 g", "Spinat 100 g", "Karotte 80 g", "Sojasprossen 100 g", "Eier 2 Stück"],
    steps: ["Reis im Reiskocher zubereiten.", "Gemüse einzeln kurz blanchieren/anbraten.", "Hähnchen anbraten, Ei als Spiegelei vollständig durchbraten.", "Alles auf Reis anrichten, mit Sesamöl und Sojasauce beträufeln."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Ei und Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-a",
    title: "Gedämpfte Garnelen-Dumplings (蝦餃)",
    desc: "Zarte, gedämpfte Teigtaschen mit Garnelenfüllung.",
    story: "Har Gow im Miniformat – gut vorzubereiten und schonend gegart.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Garnelen 250 g", "Reispapier (als Teig-Ersatz) 12 Blatt", "Frühlingszwiebel 2 Stück", "Ingwer 10 g", "Sojasauce 2 EL", "Pak Choi 100 g"],
    steps: ["Garnelen fein hacken, mit Ingwer und Frühlingszwiebel vermengen.", "In Reispapier einwickeln, gut verschließen.", "12 Min. dämpfen, bis Garnelenfüllung durchgegart ist.", "Mit Pak Choi und Sojasauce-Dip servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen vollständig durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenhack",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-f",
    title: "Kürbis-Congee (南瓜粥)",
    desc: "Sanfter Reisbrei mit weich gegartem Kürbis und einer Prise Zimt.",
    story: "Ein leicht süßlicher Wochenend-Brei, der besonders bekömmlich ist.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Kürbis 200 g", "Gemüsebrühe 400 ml", "Zimt 1 Prise", "Walnüsse 20 g"],
    steps: ["Kürbis in Würfel schneiden.", "Mit Reis und Brühe 30 Min. weich köcheln, bis cremig.", "Mit Zimt abschmecken.", "Mit gehackten Walnüssen bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiches Gemüse)",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Zucchini-Nudel-Pfanne mit Garnelen",
    desc: "Leichte Zoodles mit Garnelen und mildem Knoblauch-Sojasauce.",
    story: "Ein besonders leichtes Wochenendgericht mit viel Gemüseanteil.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Zucchini 300 g", "Garnelen 200 g", "Weizennudeln 100 g", "Knoblauch 1 Zehe", "Sojasauce 2 EL", "Sesamöl 1 TL"],
    steps: ["Zucchini in feine Streifen hobeln.", "Nudeln separat kochen, mit Zucchini vermengen.", "Garnelen mit Knoblauch anbraten, bis durchgegart.", "Alles vermengen, mit Sojasauce und Sesamöl abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart, Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Oyakodon mild (親子丼)",
    desc: "Hähnchen und Ei in süßlicher Dashi-Sauce auf Reis, ein japanischer Familienklassiker.",
    story: "Der Name bedeutet 'Eltern und Kind' – Hähnchen und Ei vereint in einer Schale.",
    target: "≈85 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 200 g", "Eier 3 Stück", "Reis (roh) 150 g", "Zwiebel 80 g", "Sojasauce 2 EL", "Mirin 1 EL"],
    steps: ["Reis im Reiskocher zubereiten.", "Zwiebel in Brühe mit Sojasauce und Mirin weich köcheln.", "Hähnchen zugeben und gar ziehen lassen.", "Verquirltes Ei darübergeben, stocken lassen, auf Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei und Hähnchen vollständig durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Milder Soja-Reisball-Brunch (豆漿飯糰)",
    desc: "Warmer Sojamilch mit gefüllten Reisbällchen und Ei.",
    story: "Ein taiwanesisches Frühstücksduo, ruhig und nahrhaft für den Sonntagmorgen.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (roh) 120 g", "Eier 2 Stück", "Milch (als Sojamilch-Ersatz) 300 ml", "Frühlingszwiebel 1 Stück", "Sojasauce 1 EL"],
    steps: ["Reis kochen, zu Bällchen formen, mit hartgekochtem Ei füllen.", "Milch warm erhitzen.", "Reisbällchen mit Sojasauce beträufeln.", "Mit Frühlingszwiebel bestreuen und warme Milch dazu servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei komplett durchgekocht) · Diabetes ✓",
    swaps: "Milch ↔ ungesüßte Sojamilch",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Kalte Reisnudelsalat-Schale (涼拌米粉)",
    desc: "Gekühlte Reisnudeln mit knackigem Gemüse und mildem Sesam-Dressing.",
    story: "Ein erfrischender Sonntagslunch, der komplett vorgekocht sein kann.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reisnudeln 180 g", "Gurke 100 g", "Karotte 80 g", "Edamame 80 g", "Sojasauce 2 EL", "Sesamöl 1 EL"],
    steps: ["Reisnudeln kochen, kalt abschrecken.", "Gemüse in feine Streifen schneiden.", "Alles mit Sojasauce und Sesamöl vermengen.", "Kühl servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Reisnudeln ↔ Soba",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Sanftes Sundubu ohne Chili (순한 순두부찌개)",
    desc: "Seidentofu-Eintopf in milder Dashi-Brühe mit Ei und Pilzen, ganz ohne Schärfe.",
    story: "Die beruhigende Variante des koreanischen Sundubu-Jjigae – wärmend statt feurig.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Seidentofu 300 g", "Champignons 100 g", "Ei 2 Stück", "Gemüsebrühe 400 ml", "Sojasauce 2 EL", "Reis (roh) 100 g"],
    steps: ["Brühe mit Champignons 10 Min. köcheln.", "Seidentofu grob in den Topf geben.", "Ei hineingleiten lassen, vollständig stocken lassen.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Seidentofu ↔ fester Tofu",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  }
];

export default function Woche27DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Kalte Soba & Congee 🌊 · Sanftes Dämpfen · Balanced"
      heroChips={["Woche 27", "Hochsommer-Kühlküche", "6× 🍚 Reiskocher"]}
    />
  );
}
