/*
  GhibliKitchen – Woche 28 (Start: 2026-07-06)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Kantonesisches Dim Sum & Dampfgaren, sanfte Cheung Fun und Congees.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 28",
  startDate: "2026-07-06",
  id: "woche-28-2026-07-06",
  lang: "de",
  sidebar: "Woche 28 (2026-07-06)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-07-06)",
  di: "Dienstag (2026-07-07)",
  mi: "Mittwoch (2026-07-08)",
  do: "Donnerstag (2026-07-09)",
  fr: "Freitag (2026-07-10)",
  sa: "Samstag (2026-07-11)",
  so: "Sonntag (2026-07-12)",
};

const UI_TITLES = {
  main: "Rezepte Woche 28",
  list: "Einkaufsliste Woche 28",
};

export const DATA = [
{
    id: "mo-f",
    title: "Gedämpfte Char-Siu-Bao mild (叉燒包)",
    desc: "Weiche Dampfbrötchen mit mild geschmortem Hähnchenfüllung.",
    story: "Cantonese Dim-Sum-Klassiker, hier mit magerem Hähnchen statt fettigem Schweinebauch.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Vollkorn-Tortillas (als Teig-Ersatz) 4 Stück", "Hähnchenbrust 150 g", "Sojasauce 2 EL", "Hoisin-Sauce 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Hähnchen klein würfeln, mit Sojasauce und Hoisin-Sauce 15 Min. schmoren.", "In Tortillas füllen, straff einrollen.", "10 Min. dämpfen.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Cheung Fun mit Garnelen (蝦腸粉)",
    desc: "Seidige Reisnudelrollen mit Garnelenfüllung in süßer Sojasauce.",
    story: "Ein zarter Dim-Sum-Klassiker, der überraschend einfach zuhause gelingt.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reisnudeln (breit) 200 g", "Garnelen 150 g", "Sojasauce 3 EL", "Frühlingszwiebel 1 Stück", "Sesamöl 1 TL"],
    steps: ["Garnelen kurz dämpfen bis durchgegart, grob hacken.", "Reisnudelblätter mit Garnelen füllen, aufrollen.", "5 Min. dämpfen.", "Mit süßer Sojasauce und Sesamöl beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Gedämpfter Lachs mit Sojasauce (豉油蒸三文魚)",
    desc: "Kantonesisch gedämpfter Lachs in würziger Sojasauce mit Ingwer und Reis.",
    story: "Ein Feiertagsgericht, das durch das schonende Dämpfen jede Woche gelingt.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Lachsfilet 300 g", "Reis (roh) 150 g", "Ingwer 15 g", "Frühlingszwiebel 3 Stück", "Sojasauce 2 EL", "Pak Choi 150 g"],
    steps: ["Reis im Reiskocher zubereiten.", "Lachs mit Ingwerstreifen 10 Min. dämpfen.", "Pak Choi kurz mitdämpfen.", "Mit heißem Öl und Sojasauce übergießen, mit Frühlingszwiebel garnieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs >80°C durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Congee mit Ei und Frühlingszwiebel (蔥花蛋粥)",
    desc: "Sanfter Reisbrei mit weichem Ei und frischer Frühlingszwiebel.",
    story: "Ein Frühstück, das in Hongkonger Garküchen jeden Morgen serviert wird.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Hühnerbrühe 500 ml", "Frühlingszwiebel 2 Stück", "Sojasauce 1 EL"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Verquirltes Ei einrühren, vollständig stocken lassen.", "Mit Sojasauce abschmecken.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Ei ↔ Tofuwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Wok-Gemüse mit Tofu und Cashew (腰果豆腐)",
    desc: "Buntes Wokgemüse mit knusprig gebratenem Tofu und Cashewkernen.",
    story: "Ein Allzeit-Klassiker aus der kantonesischen Wok-Küche, mild gewürzt.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Tofu 250 g", "Paprika 100 g", "Karotte 80 g", "Champignons 100 g", "Sojasauce 2 EL", "Walnüsse (als Cashew-Ersatz) 30 g"],
    steps: ["Tofu in Würfeln knusprig anbraten, beiseitestellen.", "Gemüse nacheinander im Wok anbraten.", "Tofu zurückgeben, mit Sojasauce ablöschen.", "Mit Nüssen bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Weißkohl-Schweinehack-Reisschale (白菜豬肉丼)",
    desc: "Zart geschmortes, mageres Schweinehack mit Weißkohl auf Reis.",
    story: "Ein wärmendes Alltagsgericht, das in vielen kantonesischen Haushaltsküchen steht.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Schweinehack (mager) 200 g", "Weißkohl 250 g", "Reis (roh) 150 g", "Ingwer 10 g", "Sojasauce 2 EL"],
    steps: ["Reis im Reiskocher zubereiten.", "Hack mit Ingwer krümelig anbraten.", "Weißkohl zugeben, 10 Min. mitschmoren.", "Mit Sojasauce abschmecken, auf Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hack vollständig durchgebraten) · Diabetes ✓",
    swaps: "Schweinehack ↔ Hähnchenhack",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Milchreis-Frühstücksschale mit Walnuss",
    desc: "Cremiger Milchreis mit gerösteten Walnüssen und wenig Honig.",
    story: "Ein ruhiges Frühstück für einen vollen Dim-Sum-Tag.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reis (roh) 80 g", "Milch 350 ml", "Walnüsse 25 g", "Agavendicksaft 1 EL", "Zimt 1 Prise"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Mit Agavendicksaft und Zimt süßen.", "Mit gerösteten Walnüssen bestreuen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Walnüsse ↔ Mandeln",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Wonton-Suppe mild (雲吞湯)",
    desc: "Zarte Garnelen-Wontons in klarer, milder Hühnerbrühe.",
    story: "Eine beruhigende Suppe, die in Hongkong rund um die Uhr serviert wird.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Garnelen 150 g", "Reispapier (als Teig-Ersatz) 16 Blatt", "Hühnerbrühe 600 ml", "Frühlingszwiebel 2 Stück", "Sojasauce 1 EL"],
    steps: ["Garnelen fein hacken, in Reispapier einwickeln.", "Brühe erhitzen.", "Wontons darin 6 Min. gar ziehen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Gedünstetes Huhn mit Shiitake (冬菇蒸雞)",
    desc: "Zartes Hähnchen mit aromatischen Shiitake-Pilzen, sanft gedämpft.",
    story: "Ein Gericht, das traditionell für Familienfeiern zubereitet wird.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Shiitake 40 g", "Reis (roh) 150 g", "Ingwer 10 g", "Sojasauce 2 EL", "Mirin 1 EL"],
    steps: ["Shiitake in warmem Wasser einweichen.", "Hähnchen mit Pilzen, Ingwer, Sojasauce und Mirin 20 Min. dämpfen.", "Reis im Reiskocher zubereiten.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Dampf-Ei mit Pilzen (香菇蒸蛋)",
    desc: "Samtiges Dampfei mit fein geschnittenen Champignons.",
    story: "Ein zartes, leicht verdauliches Frühstück im kantonesischen Stil.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Eier 4 Stück", "Champignons 60 g", "Hühnerbrühe 200 ml", "Sojasauce 1 EL", "Toastbrot 4 Scheiben"],
    steps: ["Eier mit Brühe verquirlen, durch ein Sieb geben.", "Champignons klein schneiden, untermengen.", "12 Min. dämpfen bis fest.", "Mit Sojasauce beträufeln, Toast dazu."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Champignons ↔ Shiitake",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Gnocchi mit mildem Pesto und Erbsen",
    desc: "Vollkorn-Gnocchi mit grünem Pesto und zarten Erbsen.",
    story: "Der wöchentliche italienische Programmpunkt – bewusst ölarm gehalten.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Gnocchi 300 g", "Pesto 2 EL", "Erbsen 100 g", "Parmesan 20 g", "Olivenöl 1 TL"],
    steps: ["Gnocchi in kochendem Wasser garen.", "Erbsen kurz mitkochen.", "Mit Pesto und Olivenöl vermengen.", "Mit Parmesan bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Parmesan pasteurisiert) · Diabetes ✓",
    swaps: "Gnocchi ↔ Vollkorn-Penne",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Rotes Braten-Huhn mild (清燉紅燒雞)",
    desc: "Sanft geschmortes Hähnchen in leichter Soja-Sternanis-Sauce.",
    story: "Eine mildere Version des klassischen Hong Shao – ohne scharfe Gewürze.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Zucker 1 TL", "Ingwer 10 g", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen in Sojasauce, Zucker und Ingwer 25 Min. schmoren.", "Reis im Reiskocher zubereiten.", "Sauce leicht einkochen lassen.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Reis-Frühstücksrolle mit Ei (蛋餅)",
    desc: "Dünner Reismehl-Pfannkuchen, gefüllt mit Rührei.",
    story: "Danbing, ein taiwanesischer Frühstücksstraßenklassiker, mild nachgekocht.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Mehl 100 g", "Eier 3 Stück", "Milch 50 ml", "Frühlingszwiebel 1 Stück", "Sojasauce 1 EL"],
    steps: ["Teig aus Mehl, Milch und Wasser dünn anrühren.", "In der Pfanne zu einem dünnen Fladen backen.", "Ei darüber verteilen, vollständig stocken lassen.", "Aufrollen, mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei komplett durchgegart) · Diabetes ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Gebratener Reis mit Ei (蛋炒飯)",
    desc: "Klassischer Eierbratreis, wenig Öl, viel Frühlingszwiebel.",
    story: "Ein Resteessen-Held, der aus kalt gewordenem Reis am besten gelingt.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 300 g", "Eier 2 Stück", "Erbsen 60 g", "Karotte 50 g", "Sojasauce 2 EL"],
    steps: ["Ei in wenig Öl stocken lassen, grob zerteilen.", "Reis zugeben, gut auflockern.", "Erbsen und Karotte untermengen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart, Reis vom Vortag durchgegart) · Diabetes ✓",
    swaps: "Ei ↔ Tofuwürfel",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Gedämpfte Auberginen-Knoblauch-Schale (蒜蓉蒸茄子)",
    desc: "Weich gedämpfte Aubergine mit mildem Knoblauch-Sojadressing.",
    story: "Ein einfaches Gemüsegericht, das in Südchina häufig als Hauptgang dient.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Aubergine 2 Stück", "Reis (roh) 150 g", "Knoblauch 1 Zehe", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Aubergine in Streifen 10 Min. dämpfen.", "Knoblauch in wenig Öl sanft anschwitzen, mit Sojasauce ablöschen.", "Reis im Reiskocher zubereiten.", "Aubergine mit der Sauce übergießen, mit Frühlingszwiebel garnieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Aubergine ↔ Zucchini",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Soja-Reisbällchen-Frühstück (飯糰)",
    desc: "Gefüllte Reisbällchen mit Ei und Frühlingszwiebel.",
    story: "Ein handliches Wochenendfrühstück, das sich gut vorbereiten lässt.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 150 g", "Eier 2 Stück", "Frühlingszwiebel 1 Stück", "Sojasauce 1 EL", "Nori 1 Blatt"],
    steps: ["Reis kochen, leicht abkühlen lassen.", "Ei hart kochen, klein würfeln.", "Reis mit Ei und Frühlingszwiebel vermengen, zu Bällchen formen.", "Mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgekocht) · Diabetes ✓",
    swaps: "Ei ↔ Tofuwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Sanftes Kung Pao Huhn ohne Chili (無辣宮保雞丁)",
    desc: "Klassisches Kung-Pao-Gericht, gewürzt mit Paprika statt getrockneter Chili.",
    story: "Alle Aromen des Originals – nur ohne die Schärfe.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Paprika 100 g", "Erdnüsse (als Walnuss-Ersatz) 30 g", "Sojasauce 2 EL", "Reisessig 1 TL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen in Würfeln anbraten.", "Paprika kurz mitbraten.", "Mit Sojasauce und wenig Reisessig ablöschen.", "Mit Nüssen und Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Erdnüsse ↔ Walnüsse",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Claypot-Reis mit Hähnchen (煲仔飯)",
    desc: "Aromatischer Schmortopfreis mit Hähnchen und Shiitake, im Reiskocher nachgebaut.",
    story: "Das kantonesische Wintergericht wird hier als sommertaugliche Reiskocher-Variante serviert.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 200 g", "Shiitake 30 g", "Sojasauce 3 EL", "Frühlingszwiebel 2 Stück", "Ingwer 10 g"],
    steps: ["Hähnchen mit Sojasauce und Ingwer kurz marinieren.", "Reis im Reiskocher ansetzen, Hähnchen und Pilze nach der Hälfte der Garzeit obenauf legen.", "Bis zum Ende garen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3", notes: "Hähnchen nach Ankochen des Reises zugeben." },
  },
  {
    id: "so-f",
    title: "Warmer Soja-Milchreis mit Beeren",
    desc: "Cremiger Milchreis, verfeinert mit Blaubeeren.",
    story: "Ein süßer, ruhiger Start in den Sonntag.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 80 g", "Milch 350 ml", "Blaubeeren 80 g", "Agavendicksaft 1 EL", "Walnüsse 15 g"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Mit Agavendicksaft süßen.", "Blaubeeren unterheben.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Blaubeeren ↔ Himbeeren",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Kalte Gurken-Sesam-Nudeln (涼拌黃瓜麵)",
    desc: "Gekühlte Weizennudeln mit Gurkenstreifen und Sesam-Dressing.",
    story: "Ein erfrischender Sonntagslunch nach einem Dim-Sum-reichen Wochenende.",
    target: "≈75 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Gurke 150 g", "Sojasauce 2 EL", "Schwarze Sesampaste 1 EL", "Reisessig 1 TL"],
    steps: ["Nudeln kochen, kalt abschrecken.", "Gurke in feine Streifen schneiden.", "Sojasauce, Sesampaste und wenig Reisessig verrühren.", "Alles vermengen, kühl servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Weizennudeln ↔ Soba",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Gedämpfter Tofu mit Frühlingszwiebel-Öl (蔥油豆腐)",
    desc: "Seidiger Tofu, übergossen mit heißem Frühlingszwiebel-Ingwer-Öl.",
    story: "Ein leichter Sonntagabschluss nach einer Woche voller Dim Sum.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Seidentofu 350 g", "Reis (roh) 130 g", "Frühlingszwiebel 3 Stück", "Ingwer 10 g", "Sojasauce 2 EL"],
    steps: ["Tofu 8 Min. dämpfen.", "Reis im Reiskocher zubereiten.", "Frühlingszwiebel und Ingwer in heißem Öl kurz anschwitzen.", "Über den Tofu geben, mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Seidentofu ↔ fester Tofu",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  }
];

export default function Woche28DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Dim Sum & Dampfgaren 🥟 · Kantonesisch mild · Balanced"
      heroChips={["Woche 28", "Kantonesisches Dim Sum", "Täglich 1× 🍚 Reiskocher"]}
    />
  );
}
