/*
  GhibliKitchen – Woche 30 (Start: 2026-07-20)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Koreanische Banchan-Woche, alle Klassiker bewusst ohne Chili/Gochujang.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 30",
  startDate: "2026-07-20",
  id: "woche-30-2026-07-20",
  lang: "de",
  sidebar: "Woche 30 (2026-07-20)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-07-20)",
  di: "Dienstag (2026-07-21)",
  mi: "Mittwoch (2026-07-22)",
  do: "Donnerstag (2026-07-23)",
  fr: "Freitag (2026-07-24)",
  sa: "Samstag (2026-07-25)",
  so: "Sonntag (2026-07-26)",
};

const UI_TITLES = {
  main: "Rezepte Woche 30",
  list: "Einkaufsliste Woche 30",
};

export const DATA = [
{
    id: "mo-f",
    title: "Gyeran-Jjim Dampfei mild (계란찜)",
    desc: "Fluffiges koreanisches Dampfei, sanft mit Sesamöl verfeinert.",
    story: "Ein Trostfrühstück, das in fast jedem koreanischen Haushalt zubereitet wird.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Eier 4 Stück", "Gemüsebrühe 250 ml", "Frühlingszwiebel 1 Stück", "Sesamöl 1 TL", "Reis (roh) 100 g"],
    steps: ["Eier mit Brühe verquirlen.", "In feuerfeste Schale füllen, 12 Min. dämpfen bis fluffig gestockt.", "Mit Sesamöl beträufeln.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Sesamöl ↔ etwas Butter",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Bibim-Guksu mild ohne Chili (순한 비빔국수)",
    desc: "Kalte Weizennudeln mit süß-mildem Sesam-Soja-Dressing statt Gochugaru.",
    story: "Die scharfe Sommernudel wird hier komplett ohne Chili zubereitet.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Gurke 100 g", "Karotte 60 g", "Sojasauce 2 EL", "Schwarze Sesampaste 1 EL"],
    steps: ["Nudeln kochen, kalt abschrecken.", "Gemüse in feine Streifen schneiden.", "Sojasauce und Sesampaste verrühren.", "Alles vermengen, kühl servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Weizennudeln ↔ Reisnudeln",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Galbijjim mild geschmort (순한 갈비찜)",
    desc: "Sanft geschmortes, mageres Rindfleisch mit Karotten in süßer Sojasauce.",
    story: "Das koreanische Fest-Schmorgericht, mit Rinderhack statt fettiger Rippen leichter gemacht.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rinderhack (mager) 250 g", "Karotte 120 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Birne 40 g", "Knoblauch 1 Zehe"],
    steps: ["Rind mit Sojasauce und püriertem Birnenstück marinieren.", "In der Pfanne durchbraten.", "Karotte zugeben, 10 Min. mitschmoren.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Rind vollständig durchgebraten, Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Miyeok-Guk Algensuppe (미역국)",
    desc: "Sanfte Seetangsuppe mit etwas Rindfleisch, Jod bewusst sparsam dosiert.",
    story: "Traditionell zum Geburtstag gegessen – hier als nahrhaftes, jodarmes Frühstück.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Rindfleisch (mager) 100 g", "Wakame (getrocknet, wenig) 5 g", "Sojasauce 1 EL", "Reis (roh) 100 g", "Knoblauch 1 Zehe"],
    steps: ["Rind klein schneiden, kurz anbraten.", "Wakame nach Packung einweichen, zugeben.", "Mit Wasser aufgießen, 15 Min. köcheln.", "Mit Sojasauce würzen, mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Rind durchgegart, Jod sehr sparsam) · Diabetes ✓",
    swaps: "Rind ↔ Tofu",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Japchae mit Garnelen (새우 잡채)",
    desc: "Glasnudeln mit buntem Gemüse und Garnelen, mild sojagewürzt.",
    story: "Eine Variante des Fest-Klassikers mit Meeresfrüchten statt Fleisch.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Glasnudeln 150 g", "Garnelen 180 g", "Spinat 100 g", "Karotte 80 g", "Sojasauce 3 EL"],
    steps: ["Glasnudeln garen, abtropfen.", "Garnelen anbraten bis durchgegart.", "Gemüse einzeln kurz anbraten.", "Alles mit Sojasauce vermengen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Doenjang-Jjigae mild (순한 된장찌개)",
    desc: "Sanfter Sojabohnenpasten-Eintopf mit Tofu und Zucchini.",
    story: "Die milde Version des koreanischen Alltagseintopfs, ganz ohne Schärfe.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Miso-Paste (als Doenjang-Ersatz) 2 EL", "Tofu 200 g", "Zucchini 120 g", "Reis (roh) 150 g", "Knoblauch 1 Zehe"],
    steps: ["Wasser mit Knoblauch aufkochen.", "Zucchini zugeben, 8 Min. köcheln.", "Miso-Paste einrühren.", "Tofu zugeben, kurz ziehen lassen, mit Reis servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Zucchini ↔ Weißkohl",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Warme Soja-Reisbrei-Schale (콩죽)",
    desc: "Cremiger Reisbrei mit pürierten Sojabohnen, mild und nahrhaft.",
    story: "Kongjuk gilt in Korea als besonders bekömmliches Frühstück.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Weiße Bohnen 100 g", "Milch 200 ml", "Agavendicksaft 1 TL", "Walnüsse 15 g"],
    steps: ["Bohnen mit Milch pürieren.", "Mit Reis und wenig Wasser 25 Min. weich köcheln.", "Mit Agavendicksaft abschmecken.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓ (ballaststoffreiche Bohnen)",
    swaps: "Weiße Bohnen ↔ Edamame",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Gedämpfte Ei-Frühlingsrollen mit Gemüse",
    desc: "Reispapierrollen mit Ei-Streifen und knackigem Gemüse.",
    story: "Ein frischer Mittagslunch, komplett gegart statt roh gerollt.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reispapier 10 Blatt", "Eier 3 Stück", "Karotte 80 g", "Gurke 80 g", "Sojasauce 2 EL"],
    steps: ["Ei zu dünnem Omelett braten, in Streifen schneiden.", "Gemüse in feine Streifen schneiden.", "Reispapier kurz anfeuchten, Füllung einrollen.", "Mit Sojasauce-Dip servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Ei ↔ Tofustreifen",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Dak-Bokkeum-Tang mild (순한 닭볶음탕)",
    desc: "Geschmortes Hähnchen mit Kartoffeln und Karotten in milder Sojasauce.",
    story: "Ein Familientopf, hier ganz ohne Gochugaru zubereitet.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Karotte 120 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Zwiebel 60 g"],
    steps: ["Hähnchen anbraten.", "Zwiebel und Karotte zugeben.", "Mit Sojasauce und wenig Wasser 20 Min. schmoren.", "Mit Reis servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Juk Reisbrei mit Hähnchen (닭죽)",
    desc: "Koreanischer Reisbrei mit zartem Hähnchen und Sesamöl.",
    story: "Juk gilt in Korea als Genesungsessen – mild und gut bekömmlich.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Hähnchenbrust 120 g", "Hühnerbrühe 500 ml", "Sesamöl 1 TL", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Hähnchen fein geschnitten mitgaren.", "Mit Sesamöl beträufeln.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Mildes Vollkorn-Risotto mit Erbsen",
    desc: "Cremiges Risotto mit Erbsen und wenig Parmesan.",
    story: "Der wöchentliche italienische Ausflug, hier extra sanft und cremig.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Risottoreis 160 g", "Erbsen 100 g", "Gemüsebrühe 500 ml", "Parmesan 20 g", "Olivenöl 1 EL"],
    steps: ["Reis in Olivenöl kurz anschwitzen.", "Nach und nach heiße Brühe angießen, rühren.", "Erbsen in den letzten 5 Min. zugeben.", "Mit Parmesan verfeinern."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Parmesan pasteurisiert) · Diabetes ✓",
    swaps: "Risottoreis ↔ Quinoa",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Sanftes Samgyetang (순한 삼계탕)",
    desc: "Klare Hähnchen-Ginseng-Suppe mit Reis, leicht und nahrhaft.",
    story: "Die koreanische Kraftsuppe, hier in einfacherer Alltagsversion.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenbrust 280 g", "Reis (roh) 100 g", "Knoblauch 1 Zehe", "Ingwer 10 g", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Knoblauch und Ingwer in Wasser 30 Min. köcheln.", "Reis separat kochen oder in der Brühe mitgaren.", "Hähnchen zerpflücken.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart, Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-f",
    title: "Gebackene Ei-Muffins mit Gemüse",
    desc: "Kleine Ei-Muffins mit Karotten und Frühlingszwiebel, im Airfryer gebacken.",
    story: "Ein handliches Frühstück für einen vollen Tag.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Eier 5 Stück", "Karotte 60 g", "Frühlingszwiebel 1 Stück", "Käse 40 g", "Toastbrot 2 Scheiben"],
    steps: ["Ei mit fein geriebener Karotte und Frühlingszwiebel verquirlen.", "In Muffinförmchen füllen.", "Im Airfryer 12 Min. bei 180°C backen, bis fest.", "Mit Toast servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt, Käse pasteurisiert) · Diabetes ✓",
    swaps: "Käse ↔ Feta",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Kalte Naengmyeon-Style Reisnudeln (냉면풍)",
    desc: "Gekühlte Reisnudeln in milder Sojabrühe mit Ei und Gurke.",
    story: "Angelehnt an das koreanische Kaltnudelgericht, hier ganz ohne Essig-Schärfe.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reisnudeln 180 g", "Gemüsebrühe 300 ml", "Eier 2 Stück", "Gurke 100 g", "Sojasauce 2 EL"],
    steps: ["Nudeln kochen, kalt abschrecken.", "Brühe mit Sojasauce verrühren, kalt stellen.", "Ei hart kochen, halbieren.", "Alles anrichten, Brühe angießen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgekocht) · Diabetes ✓",
    swaps: "Reisnudeln ↔ Soba",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Sanftes Jeyuk-Bokkeum ohne Chili (순한 제육볶음)",
    desc: "Mageres Schwein, mild in Sojasauce und Birne mariniert und angebraten.",
    story: "Das normalerweise feurige Pfannengericht, hier komplett ohne Gochujang.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Schweineschnitzel 220 g", "Zwiebel 80 g", "Reis (roh) 150 g", "Sojasauce 3 EL", "Birne 40 g"],
    steps: ["Schwein in Streifen mit Birne und Sojasauce marinieren.", "In der Pfanne durchbraten.", "Zwiebel zugeben, mitbraten.", "Mit Reis servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Schwein durchgegart) · Diabetes ✓",
    swaps: "Schwein ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Milchreis-Frühstück mit Kastanien",
    desc: "Cremiger Reisbrei mit weichen Kastanien und Zimt.",
    story: "Ein nussig-süßes Wochenendfrühstück.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Walnüsse (als Kastanien-Ersatz) 30 g", "Zimt 1 Prise", "Agavendicksaft 1 TL"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Walnüsse grob hacken, unterheben.", "Mit Zimt und Agavendicksaft abschmecken.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Walnüsse ↔ Mandeln",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Kongnamul-Bap Sojasprossen-Reis (콩나물밥)",
    desc: "Reis, gemeinsam mit Sojasprossen gegart, mit milder Sojasauce serviert.",
    story: "Ein einfacher koreanischer One-Pot-Klassiker.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Sojasprossen 200 g", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück", "Sesamöl 1 TL"],
    steps: ["Reis und Sojasprossen zusammen im Reiskocher garen.", "Sojasauce mit Sesamöl verrühren.", "Reis vorsichtig auflockern.", "Mit Sauce und Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Sprossen)",
    swaps: "Sojasprossen ↔ Erbsen",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-a",
    title: "Gedämpfte Lachs-Banchan-Schale (연어 반찬)",
    desc: "Gedämpfter Lachs mit drei kleinen milden Gemüse-Beilagen (Banchan).",
    story: "Ein Banchan-Teller im Miniformat – Vielfalt statt einem großen Hauptgang.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Lachsfilet 250 g", "Spinat 100 g", "Karotte 80 g", "Sojasprossen 100 g", "Reis (roh) 150 g", "Sesamöl 1 EL"],
    steps: ["Reis im Reiskocher zubereiten.", "Lachs 10 Min. dämpfen.", "Gemüse einzeln kurz blanchieren, mit Sesamöl und Sojasauce würzen.", "Alles zusammen anrichten."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Warme Soja-Ei-Suppe zum Frühstück (계란국)",
    desc: "Sanfte Ei-Tropfen-Suppe mit Frühlingszwiebel.",
    story: "Gyeranguk – eine der einfachsten und mildesten koreanischen Suppen.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Eier 3 Stück", "Gemüsebrühe 500 ml", "Sojasauce 1 EL", "Frühlingszwiebel 1 Stück", "Reis (roh) 100 g"],
    steps: ["Brühe erhitzen.", "Verquirltes Ei langsam einrühren, vollständig stocken lassen.", "Mit Sojasauce würzen.", "Mit Reis und Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Ei ↔ Tofu",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Yachae-Bokkeumbap Gemüse-Bratreis (야채볶음밥)",
    desc: "Bratreis mit buntem Gemüse und Ei, mild sojagewürzt.",
    story: "Der koreanische Vetter des Eierbratreis, mit extra viel Gemüse.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 300 g", "Eier 2 Stück", "Karotte 60 g", "Erbsen 60 g", "Sojasauce 2 EL"],
    steps: ["Ei stocken lassen, grob zerteilen.", "Gemüse kurz anbraten.", "Reis zugeben, gut vermengen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart, Reis durchgegart) · Diabetes ✓",
    swaps: "Ei ↔ Tofuwürfel",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Sanftes Budae-Jjigae ohne Chili (순한 부대찌개)",
    desc: "Milder Eintopf mit magerem Schweinehack, Tofu und Kohl.",
    story: "Die entschärfte Version des koreanischen Army-Stew – ohne Instant-Nudeln und Schärfe.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Schweinehack (mager) 200 g", "Tofu 150 g", "Weißkohl 150 g", "Reis (roh) 150 g", "Sojasauce 2 EL"],
    steps: ["Hack anbraten.", "Kohl zugeben, mit Wasser aufgießen, 12 Min. köcheln.", "Tofu zugeben, kurz mitziehen lassen.", "Mit Sojasauce würzen, mit Reis servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Hack vollständig durchgebraten) · Diabetes ✓",
    swaps: "Schweinehack ↔ Hähnchenhack",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  }
];

export default function Woche30DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Banchan & Jjigae 🥢 · Koreanisch ohne Chili · Balanced"
      heroChips={["Woche 30", "Koreanische Banchan-Woche", "7× 🍚 Reiskocher"]}
    />
  );
}
