/*
  GhibliKitchen – Woche 32 (Start: 2026-08-03)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Sommergemüse & Tofu im Fokus, viel Zucchini, Paprika und Sojasprossen.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 32",
  startDate: "2026-08-03",
  id: "woche-32-2026-08-03",
  lang: "de",
  sidebar: "Woche 32 (2026-08-03)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-08-03)",
  di: "Dienstag (2026-08-04)",
  mi: "Mittwoch (2026-08-05)",
  do: "Donnerstag (2026-08-06)",
  fr: "Freitag (2026-08-07)",
  sa: "Samstag (2026-08-08)",
  so: "Sonntag (2026-08-09)",
};

const UI_TITLES = {
  main: "Rezepte Woche 32",
  list: "Einkaufsliste Woche 32",
};

export const DATA = [
{
    id: "mo-f",
    title: "Zucchini-Tofu-Frittata (節瓜豆腐蛋餅)",
    desc: "Luftige Frittata mit Zucchini und zerbröckeltem Tofu, im Airfryer gebacken.",
    story: "Ein proteinreicher, gemüsestarker Start in die Gemüsewoche.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Eier 4 Stück", "Tofu 100 g", "Zucchini 120 g", "Milch 2 EL", "Toastbrot 2 Scheiben"],
    steps: ["Ei mit Milch verquirlen.", "Zucchini und Tofu untermengen.", "Im Airfryer 12 Min. bei 170°C backen, bis fest.", "Mit Toast servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Zucchini ↔ Champignons",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Sommergemüse-Tofu-Wok (夏野菜豆腐炒め)",
    desc: "Buntes Sommergemüse mit knusprigem Tofu, mild sojagewürzt.",
    story: "Ein Wok voller Farbe – Paprika, Zucchini und Erbsen treffen auf Tofu.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Tofu 250 g", "Zucchini 120 g", "Paprika 100 g", "Erbsen 60 g", "Sojasauce 2 EL"],
    steps: ["Tofu anbraten, beiseitestellen.", "Gemüse nacheinander im Wok anbraten.", "Tofu zurückgeben.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Gedämpfte Zucchini-Röllchen mit Hähnchen (雞肉節瓜卷)",
    desc: "Dünne Zucchinistreifen, gefüllt mit Hähnchenhack, gedämpft serviert.",
    story: "Ein leichtes, gemüsereiches Abendgericht für heiße Tage.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Zucchini 250 g", "Hähnchenhack 200 g", "Reis (roh) 140 g", "Ingwer 10 g", "Sojasauce 2 EL"],
    steps: ["Zucchini in dünnen Längsstreifen hobeln.", "Hack mit Ingwer würzen, auf die Streifen geben, aufrollen.", "12 Min. dämpfen bis durchgegart.", "Mit Reis und Sojasauce servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchenhack vollständig durchgegart) · Diabetes ✓",
    swaps: "Hähnchenhack ↔ Tofu",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Spinat-Ei-Congee (菠菜蛋粥)",
    desc: "Sanfter Reisbrei mit frischem Spinat und Ei.",
    story: "Ein grünes, eisenreiches Frühstück für die Sommerhitze.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Spinat 100 g", "Eier 2 Stück", "Gemüsebrühe 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Spinat in den letzten 5 Min. zugeben.", "Verquirltes Ei einrühren, stocken lassen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart, Spinat durchgegart) · Diabetes ✓",
    swaps: "Spinat ↔ Pak Choi",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Gurken-Sesam-Salat mit Garnelen (小黃瓜蝦仁沙拉)",
    desc: "Knackige Gurke mit gegarten Garnelen und mildem Sesamdressing.",
    story: "Ein erfrischender, proteinreicher Sommersalat.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Gurke 200 g", "Garnelen 200 g", "Sojasauce 2 EL", "Sesamöl 1 EL", "Reis (roh) 100 g"],
    steps: ["Garnelen dämpfen bis durchgegart.", "Gurke in Scheiben schneiden.", "Mit Sojasauce und Sesamöl vermengen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Auberginen-Tofu-Topf mild (茄子豆腐煲)",
    desc: "Weich geschmorte Aubergine und Tofu in milder Sojasauce, mit Reis.",
    story: "Ein wärmendes vegetarisches Gericht, das auch im Sommer bekommt.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Aubergine 200 g", "Tofu 200 g", "Reis (roh) 150 g", "Sojasauce 2 EL", "Ingwer 10 g"],
    steps: ["Aubergine und Tofu getrennt kurz anbraten.", "Mit Ingwer und Sojasauce ablöschen, 10 Min. köcheln.", "Zusammen servieren.", "Mit Reis anrichten."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Aubergine ↔ Zucchini",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Karotten-Ingwer-Suppe zum Frühstück (紅蘿蔔薑湯)",
    desc: "Sanfte, leicht süßliche Karottensuppe mit Ingwer.",
    story: "Eine ungewöhnliche, aber sehr milde Frühstückssuppe.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Karotte 250 g", "Gemüsebrühe 400 ml", "Ingwer 10 g", "Reis (roh) 90 g", "Milch 50 ml"],
    steps: ["Karotte mit Brühe und Ingwer 20 Min. weich köcheln.", "Fein pürieren, mit wenig Milch verfeinern.", "Reis separat kochen.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Karotte ↔ Kürbis",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Champignon-Tofu-Nudeln (香菇豆腐麵)",
    desc: "Weizennudeln mit Champignons und Tofu in milder Sojasauce.",
    story: "Ein einfaches, schnelles Mittagsgericht mit viel Umami durch die Pilze.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Champignons 150 g", "Tofu 150 g", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Nudeln kochen.", "Champignons und Tofu anbraten.", "Mit Sojasauce ablöschen, Nudeln untermengen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Weizennudeln ↔ Udon",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Paprika-Hähnchen-Pfanne (彩椒雞肉)",
    desc: "Buntes Paprikagemüse mit Hähnchenbrust, mild angebraten.",
    story: "Ein farbenfrohes Sommergericht mit viel Vitamin C.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Paprika 200 g", "Reis (roh) 150 g", "Sojasauce 2 EL", "Knoblauch 1 Zehe"],
    steps: ["Hähnchen in Streifen anbraten.", "Paprika und Knoblauch zugeben, mitbraten.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart, Knoblauch gut gegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Warmer Edamame-Reisbrei (毛豆粥)",
    desc: "Cremiger Reisbrei mit pürierten Edamame, mild gewürzt.",
    story: "Ein proteinreiches, grünes Frühstück.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Edamame 100 g", "Gemüsebrühe 450 ml", "Sesamöl 1 TL", "Nori 1 Blatt"],
    steps: ["Reis mit Brühe 25 Min. weich köcheln.", "Edamame pürieren, unterrühren.", "Mit Sesamöl verfeinern.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Edamame)",
    swaps: "Edamame ↔ Erbsen",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Zoodles mit Garnelen-Scampi mild",
    desc: "Zucchininudeln mit Garnelen in mildem Knoblauch-Olivenöl.",
    story: "Der italienische Programmpunkt der Woche, ganz ohne Zitrone für den Magen.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Zucchini 300 g", "Garnelen 200 g", "Olivenöl 1 EL", "Knoblauch 1 Zehe", "Parmesan 15 g"],
    steps: ["Zucchini zu Nudeln hobeln.", "Garnelen mit Knoblauch in Olivenöl anbraten bis durchgegart.", "Zoodles kurz mit anbraten.", "Mit Parmesan bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart, Knoblauch gut gegart, Parmesan pasteurisiert) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Kürbis-Kabeljau-Topf (南瓜鱈魚煲)",
    desc: "Milder Eintopf mit Kürbis und Kabeljau in leichter Brühe.",
    story: "Ein sanftes Sommer-Herbst-Crossover-Gericht.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kürbis 200 g", "Kabeljau 250 g", "Reis (roh) 150 g", "Ingwer 10 g", "Sojasauce 2 EL"],
    steps: ["Kürbis in Würfeln 15 Min. köcheln.", "Kabeljau mit Ingwer zugeben, 8 Min. gar ziehen lassen.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Kabeljau durchgegart) · Diabetes ✓",
    swaps: "Kabeljau ↔ Seelachs",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Tofu-Rührei mit Gemüse (豆腐炒蛋)",
    desc: "Rührei mit zerbröckeltem Tofu und feinem Gemüse.",
    story: "Ein proteinreiches, sättigendes Frühstück ohne viel Aufwand.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Eier 3 Stück", "Tofu 100 g", "Karotte 50 g", "Frühlingszwiebel 1 Stück", "Toastbrot 2 Scheiben"],
    steps: ["Tofu zerbröckeln, mit Ei verquirlen.", "Karotte fein reiben, untermengen.", "In der Pfanne vollständig stocken lassen.", "Mit Toast servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Tofu ↔ Champignons",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Sommergemüse-Reisnudelsuppe mild (夏野菜米粉湯)",
    desc: "Leichte Brühe mit Reisnudeln und buntem Sommergemüse.",
    story: "Eine warme Suppe, die trotz Sommerhitze angenehm leicht bleibt.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reisnudeln 150 g", "Zucchini 100 g", "Karotte 80 g", "Gemüsebrühe 500 ml", "Sojasauce 1 EL"],
    steps: ["Brühe erhitzen.", "Gemüse darin 8 Min. köcheln.", "Reisnudeln zugeben, gar ziehen lassen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Reisnudeln ↔ Udon",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Gebratener Tofu mit Sojasprossen (豆芽豆腐)",
    desc: "Knusprig gebratener Tofu mit knackigen Sojasprossen, mild gewürzt.",
    story: "Ein einfaches, proteinreiches vegetarisches Abendessen.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Tofu 300 g", "Sojasprossen 150 g", "Reis (roh) 140 g", "Sojasauce 2 EL", "Sesamöl 1 TL"],
    steps: ["Tofu in Scheiben knusprig anbraten.", "Sojasprossen kurz mitbraten.", "Mit Sojasauce und Sesamöl abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Warmer Zucchini-Milchreis herzhaft",
    desc: "Herzhafte Variante des Milchreises mit fein geriebener Zucchini.",
    story: "Ein ungewöhnliches, aber mildes Wochenendfrühstück.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Zucchini 80 g", "Käse 20 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Fein geriebene Zucchini unterrühren.", "Mit Käse verfeinern.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch und Käse pasteurisiert) · Diabetes ✓",
    swaps: "Zucchini ↔ Karotte",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Bunter Sommergemüse-Reis (夏野菜炒飯)",
    desc: "Bratreis mit Zucchini, Paprika und Erbsen, mild gewürzt.",
    story: "Ein Resteessen-Held für übriggebliebenes Sommergemüse.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 300 g", "Zucchini 100 g", "Paprika 80 g", "Erbsen 60 g", "Sojasauce 2 EL"],
    steps: ["Gemüse in wenig Öl anbraten.", "Reis zugeben, gut auflockern.", "Mit Sojasauce abschmecken.", "Heiß servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Reis durchgegart) · Diabetes ✓",
    swaps: "Erbsen ↔ Edamame",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Gedämpfter Lachs auf Sommergemüse (鮭魚夏野菜)",
    desc: "Zart gedämpfter Lachs auf einem Bett aus Zucchini und Karotten.",
    story: "Ein besonders leichtes, gemüsereiches Abendgericht.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Lachsfilet 280 g", "Zucchini 150 g", "Karotte 100 g", "Reis (roh) 140 g", "Sojasauce 2 EL"],
    steps: ["Reis im Reiskocher zubereiten.", "Gemüse und Lachs zusammen 10 Min. dämpfen.", "Mit Sojasauce beträufeln.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Sommer-Gemüseomelett (夏野菜オムレツ)",
    desc: "Fluffiges Omelett mit Zucchini, Paprika und Frühlingszwiebel.",
    story: "Ein farbenfroher Sonntagsstart mit viel Gemüse.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Eier 4 Stück", "Zucchini 80 g", "Paprika 60 g", "Toastbrot 2 Scheiben", "Milch 2 EL"],
    steps: ["Ei mit Milch verquirlen.", "Gemüse fein würfeln, untermengen.", "In der Pfanne beidseitig vollständig durchgaren.", "Mit Toast servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Paprika ↔ Karotte",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Kalte Tofu-Gemüse-Nudelschale",
    desc: "Gekühlte Weizennudeln mit Tofu und Sommergemüse.",
    story: "Ein leichter Sonntagslunch, ideal zum Vorbereiten.",
    target: "≈75 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Tofu 150 g", "Gurke 100 g", "Karotte 60 g", "Sojasauce 2 EL"],
    steps: ["Nudeln kochen, kalt abschrecken.", "Tofu kurz anbraten, abkühlen lassen.", "Gemüse in Streifen schneiden.", "Alles vermengen, mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Weizennudeln ↔ Reisnudeln",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Gebratenes Hähnchen mit Sommergemüse-Medley (夏野菜チキン)",
    desc: "Hähnchenbrust mit buntem Sommergemüse, mild in Sojasauce gebraten.",
    story: "Ein bunter Wochenabschluss, der die Gemüsewoche zusammenfasst.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Zucchini 100 g", "Paprika 80 g", "Reis (roh) 150 g", "Sojasauce 2 EL"],
    steps: ["Hähnchen in Streifen anbraten.", "Gemüse zugeben, mitbraten.", "Mit Sojasauce abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  }
];

export default function Woche32DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Viel Gemüse, viel Tofu 🥒 · Leichte Sommerküche · Balanced"
      heroChips={["Woche 32", "Sommergemüse & Tofu", "Täglich 1× 🍚 Reiskocher"]}
    />
  );
}
