/*
  GhibliKitchen – Woche 40 (Start: 2026-09-28)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Chinesische Suppenküche (家常湯) – klare Brühen und nahrhafte Eintöpfe.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 40",
  startDate: "2026-09-28",
  id: "woche-40-2026-09-28",
  lang: "de",
  sidebar: "Woche 40 (2026-09-28)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-09-28)",
  di: "Dienstag (2026-09-29)",
  mi: "Mittwoch (2026-09-30)",
  do: "Donnerstag (2026-10-01)",
  fr: "Freitag (2026-10-02)",
  sa: "Samstag (2026-10-03)",
  so: "Sonntag (2026-10-04)",
};

const UI_TITLES = {
  main: "Rezepte Woche 40",
  list: "Einkaufsliste Woche 40",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Tomaten-Ei-Suppe zum Frühstück (西紅柿蛋湯)",
    desc: "Die Klassiker-Suppe, hier als wärmender Start in den Tag.",
    story: "In vielen chinesischen Haushalten ist diese Suppe jederzeit passend – auch morgens.",
    target: "≈56 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Tomaten 250 g", "Eier 2 Stück", "Vollkornbrötchen 1 Stück", "Gemüsebrühe natriumarm 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Tomaten würfeln, in Brühe 8 Min. köcheln.", "Verquirltes Ei langsam einrühren.", "Mit Frühlingszwiebel bestreuen.", "Mit Brötchen servieren."],
    checks: "Diabetes ✓ – ≈56 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Mais-Rippchen-Suppe (玉米排骨湯)",
    desc: "Süßlicher Mais und magere Rippchen in klarer, lang geköchelter Brühe.",
    story: "Yumi Paigutang ist eine der beliebtesten Familiensuppen Chinas – süß, herzhaft, unkompliziert.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Magere Rippchen 250 g", "Mais 2 Kolben", "Karotte 100 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rippchen in Wasser 35 Min. köcheln, bis vollständig durch.", "Mais und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Rippchen ↔ Hähnchenschenkel",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-a",
    title: "Drei-Delikatessen-Pilzsuppe (三鮮菌菇湯)",
    desc: "Klare Brühe mit drei Pilzsorten und magerem Hähnchen.",
    story: "Sanxian-Suppen ('drei Frische') kombinieren traditionell Fleisch, Meeresfrüchte und Gemüse – wir setzen auf drei Pilzarten für Umami-Tiefe.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Champignons 80 g", "Shiitake 60 g", "Austernpilze 60 g", "Hähnchenbrust 180 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen in der Brühe 10 Min. gar ziehen lassen.", "Pilze zugeben, 8 Min. köcheln.", "Mild abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈76 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Pilz-Ei-Suppe (口蘑蛋湯)",
    desc: "Sanfte Champignon-Suppe mit eingerührtem Ei, schnelles Frühstück.",
    story: "Kouмо-Tang ist eine der schnellsten Suppen der chinesischen Küche – 10 Minuten von Topf zu Tisch.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Champignons 150 g", "Eier 2 Stück", "Gemüsebrühe natriumarm 500 ml", "Vollkornbrötchen 1 Stück", "Frühlingszwiebel 1 Stück"],
    steps: ["Champignons in Scheiben 6 Min. köcheln.", "Verquirltes Ei einrühren.", "Mit Frühlingszwiebel bestreuen.", "Mit Brötchen servieren."],
    checks: "Diabetes ✓ – ≈58 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Champignons ↔ Austernpilze",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Chaoshan-Rindfleischsuppe mild (潮汕牛肉湯)",
    desc: "Zarte Rindfleischscheiben in klarer, aromatischer Brühe mit Rettich, aus der Küstenstadt Chaoshan.",
    story: "Chaoshan Niurou Tang ist berühmt für die Präzision, mit der das Fleisch hauchdünn geschnitten wird.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Rindfleisch mager 220 g", "Daikon 150 g", "Ingwer 10 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Rind hauchdünn schneiden.", "Brühe mit Daikon 15 Min. köcheln.", "Rind zugeben, 3 Min. gar ziehen lassen bis vollständig durch.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-a",
    title: "Yam-Magerfleisch-Suppe (山藥瘦肉湯)",
    desc: "Chinesische Yamswurzel mit magerem Schweinefleisch in milder Brühe geschmort.",
    story: "Shanyao gilt in der chinesischen Alltagsküche als besonders bekömmlich und wird gern in Suppen verwendet.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Chinesische Yamswurzel 250 g", "Schweinefilet mager 200 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Fleisch in Wasser 20 Min. köcheln, bis vollständig durch.", "Yamswurzel und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Century-Egg-Alternative-Suppe mit Hackfleisch (肉末蛋花湯)",
    desc: "Milde Suppe mit fein gehacktem Fleisch und Ei, statt Preserved Egg mit extra Ei verfeinert.",
    story: "Eine kindgerecht-milde Variante der traditionellen Piedan-Suppe, ganz ohne das intensive Preserved Egg.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Hähnchenhack 120 g", "Eier 2 Stück", "Gemüsebrühe natriumarm 500 ml", "Reis (roh) 130 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Hack krümelig in der Brühe garen, bis vollständig durch.", "Verquirltes Ei einrühren.", "Mit Frühlingszwiebel bestreuen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈60 g KH · Schwangerschaft ✓ Hack und Ei durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-m",
    title: "Brühe mit Broccoli (上湯西蘭花)",
    desc: "Broccoliröschen in kräftiger Hühnerbrühe, als sättigende Hauptmahlzeit mit Hähnchen ausgebaut.",
    story: "Shangtang-Gemüsegerichte zeigen, wie viel Aroma eine gute Grundbrühe einem einfachen Gemüse gibt.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Brokkoli 250 g", "Hähnchenbrust 200 g", "Hühnerbrühe natriumarm 500 ml", "Knoblauch 1 Zehe", "Reis (roh) 150 g"],
    steps: ["Hähnchen in der Brühe 10 Min. gar ziehen lassen, herausnehmen und schneiden.", "Brokkoli 4 Min. in der Brühe garen.", "Hähnchen zurückgeben, mit Knoblauch würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈74 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-a",
    title: "Lauchsuppe mit Venusmuscheln (絲瓜炒花蛤湯)",
    desc: "Zarter Schwammkürbis (Luffa) mit Venusmuscheln in leichter Brühe.",
    story: "Sigua-Gerichte sind ein Sommerklassiker, der auch im Herbst mit seiner milden Süße überzeugt.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Luffa (Schwammkürbis) 250 g", "Venusmuscheln 200 g", "Ingwer 10 g", "Sojasauce natriumarm 1 EL", "Reis (roh) 150 g"],
    steps: ["Luffa schälen, in Stücke schneiden, 6 Min. köcheln.", "Muscheln zugeben, garen bis alle sich vollständig geöffnet haben (geschlossene entsorgen).", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Muscheln vollständig gegart",
    swaps: "Venusmuscheln ↔ Garnelen",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Reine vegetarische Suppe (純素湯)",
    desc: "Leichte Gemüsesuppe mit Tofu, Karotte und Pilzen zum sanften Start.",
    story: "Chun Su Tang zeigt die vegetarische Seite der Suppenküche – klar, sauber, nährstoffreich.",
    target: "≈58 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Tofu fest 200 g", "Karotte 80 g", "Champignons 80 g", "Gemüsebrühe natriumarm 500 ml", "Vollkornbrötchen 1 Stück"],
    steps: ["Karotte und Pilze 10 Min. in der Brühe köcheln.", "Tofuwürfel zugeben, 3 Min. ziehen lassen.", "Mild abschmecken.", "Mit Brötchen servieren."],
    checks: "Diabetes ✓ – ≈58 g KH · Schwangerschaft ✓",
    swaps: "Tofu ↔ Hähnchenwürfel",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Garnelenpaste-Pilzsuppe (蝦滑菌菇湯)",
    desc: "Zarte Garnelenklößchen mit gemischten Pilzen in klarer Brühe.",
    story: "Ein proteinreiches Mittagsgericht, das leicht bleibt und trotzdem sättigt.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Garnelen (gegart, püriert) 220 g", "Shiitake 80 g", "Champignons 60 g", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Garnelenpaste zu kleinen Klößchen formen.", "Pilze in der Brühe 8 Min. köcheln.", "Klößchen zugeben, 4 Min. gar ziehen lassen bis vollständig durch.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈72 g KH · Schwangerschaft ✓ Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-a",
    title: "Lungenbefeuchtende Rettich-Suppe (潤肺蘿蔔湯)",
    desc: "Milde Rettich-Suppe mit magerem Fleisch, traditionell für die kühlere Jahreszeit gedacht.",
    story: "In der chinesischen Alltagsküche gelten bestimmte Suppen als besonders wohltuend für den Übergang in den Herbst.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Daikon 250 g", "Schweinefilet mager 200 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Fleisch in Wasser 20 Min. köcheln, bis vollständig durch.", "Daikon und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Warme Sojamilch mit Frühlingszwiebel-Pfannkuchen",
    desc: "Sojamilch mit dünnem, herzhaftem Pfannkuchen als Frühstücksduo.",
    story: "Ein bewährtes, unkompliziertes Frühstück, wie es überall in China zu finden ist.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Ungesüßte Sojamilch 500 ml", "Mehl 60 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück"],
    steps: ["Teig aus Mehl, Ei und wenig Wasser verrühren.", "In wenig Öl dünn ausbacken, bis vollständig gestockt.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Winterspinat-Tofu-Suppe (菠菜豆腐湯)",
    desc: "Klare Suppe mit Spinat und weichem Tofu, schnelles Alltagsgericht.",
    story: "Bocai Doufu Tang ist eine der einfachsten und beliebtesten Alltagssuppen Chinas.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Spinat 200 g", "Tofu weich 250 g", "Gemüsebrühe natriumarm 500 ml", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Tofu in der Brühe 5 Min. köcheln.", "Spinat zugeben, 2 Min. ziehen lassen.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓",
    swaps: "Spinat ↔ Pak Choi",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-a",
    title: "Hühnersuppe mit Winterschwamm-Pilzen (冬菇雞湯)",
    desc: "Lang geköchelte Hühnerbrühe mit getrockneten Shiitake, wärmendes Wochenendgericht.",
    story: "Dogu-Ji-Tang gehört zu den Suppen, die man in China für einen besonders sättigenden Abend kocht.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenschenkel ohne Haut 280 g", "Shiitake getrocknet 30 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Shiitake einweichen.", "Hähnchen in Wasser 25 Min. köcheln, bis vollständig durch.", "Pilze und Karotte zugeben, 10 Min. mitköcheln.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Mungbohnen-Reissuppe süß-mild (綠豆粥)",
    desc: "Sanfter Congee mit Mungbohnen, traditionell kühlend, hier warm zum Frühstück.",
    story: "Lüdouzhou wird in China meist im Sommer gegessen – als herzhaftes Frühstück funktioniert er das ganze Jahr.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 70 g", "Mungbohnen (roh) 50 g", "Wasser 800 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Mungbohnen 2 Std. einweichen.", "Mit Reis und Wasser 35 Min. weich köcheln.", "Mild abschmecken.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈72 g KH · Schwangerschaft ✓",
    swaps: "Mungbohnen ↔ rote Linsen",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "sa-m",
    title: "Hackbällchen-Glasnudel-Suppe (肉丸粉絲湯)",
    desc: "Zarte Hähnchen-Hackbällchen mit Glasnudeln in klarer Brühe.",
    story: "Ein sättigendes Wochenendgericht, das in vielen Regionen Chinas seine eigene Würzvariante hat.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Hähnchenhack 220 g", "Glasnudeln (roh) 80 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Hack zu kleinen Bällchen formen.", "In der Brühe 8 Min. gar ziehen lassen, bis vollständig durch.", "Glasnudeln zugeben, gar ziehen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Lotoswurzel-Rippchen-Suppe (蓮藕排骨湯)",
    desc: "Knackige Lotoswurzel mit mageren Rippchen, lange geschmort für tiefen Geschmack.",
    story: "Ou Paigutang ist ein Wochenend-Klassiker – am besten, wenn genug Zeit zum langsamen Köcheln bleibt.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Magere Rippchen 250 g", "Lotoswurzel 200 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rippchen in Wasser 35 Min. köcheln, bis vollständig durch.", "Lotoswurzel und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Rippchen ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Ei-Tomaten-Nudelsuppe (西紅柿蛋麵)",
    desc: "Die Tomaten-Ei-Kombination als Nudelsuppe, sonntäglich üppiger.",
    story: "Ein Frühstück, das die Woche mit vertrautem Aroma abrundet.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Weizennudeln 150 g", "Tomaten 200 g", "Eier 2 Stück", "Gemüsebrühe natriumarm 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Tomaten in der Brühe 8 Min. köcheln.", "Verquirltes Ei einrühren.", "Nudeln separat kochen, in die Suppe geben.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Weizennudeln ↔ Vollkornnudeln",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Winterschwamm-Hähnchen-Reisschale (冬菇雞肉飯)",
    desc: "Hähnchen und Shiitake in leichter Sojasauce auf Reis.",
    story: "Ein einfaches Reisschalen-Gericht als ruhiger Sonntagslunch.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 240 g", "Shiitake 80 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen anbraten, bis durch.", "Pilze zugeben, mitbraten.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-a",
    title: "Claypot-Suppen-Reis zum Wochenausklang (老火湯煲仔飯)",
    desc: "Reis im Schmortopf mit den Suppenaromen der Woche vereint, wärmender Abschluss.",
    story: "Ein bewusst ruhiges Gericht, das die Suppenwoche mit vertrauten Aromen ausklingen lässt.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenschenkel ohne Haut 220 g", "Karotte 80 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Karotte nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
];

export default function Woche40DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="家常湯 🥣 · Klare Brühen & Eintöpfe · Balanced"
      heroChips={["Woche 40", "Suppenwoche", "6× 🍚 Reiskocher"]}
    />
  );
}
