/*
  GhibliKitchen – Woche 39 (Start: 2026-09-21)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Kantonesische Küche – Dampfgaren, klare Brühen, zarte Texturen.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 39",
  startDate: "2026-09-21",
  id: "woche-39-2026-09-21",
  lang: "de",
  sidebar: "Woche 39 (2026-09-21)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-09-21)",
  di: "Dienstag (2026-09-22)",
  mi: "Mittwoch (2026-09-23)",
  do: "Donnerstag (2026-09-24)",
  fr: "Freitag (2026-09-25)",
  sa: "Samstag (2026-09-26)",
  so: "Sonntag (2026-09-27)",
};

const UI_TITLES = {
  main: "Rezepte Woche 39",
  list: "Einkaufsliste Woche 39",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Cantonese Congee mit Ei (廣東白粥)",
    desc: "Sehr lang gekochter, seidig-cremiger Reisbrei, kantonesische Grundtechnik.",
    story: "In Kantons Congee-Häusern köchelt der Reis oft über zwei Stunden, bis er komplett zerfällt.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Wasser 900 ml", "Eier 2 Stück", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit reichlich Wasser 45 Min. köcheln, bis cremig.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Frühlingszwiebel bestreuen.", "Warm servieren."],
    checks: "Diabetes ✓ – ≈64 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Reis ↔ Brauner Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:10" },
  },
  {
    id: "mo-m",
    title: "Brühe mit Baby-Pak-Choi (上湯娃娃菜)",
    desc: "Zarter Baby-Pak-Choi in klarer, kräftiger Hühnerbrühe, kantonesische Gemüse-Technik.",
    story: "Shangtang ('obere Brühe') ist die Basis unzähliger kantonesischer Gemüsegerichte.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Baby-Pak-Choi 250 g", "Hähnchenbrust 180 g", "Hühnerbrühe natriumarm 500 ml", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen in der Brühe 10 Min. gar ziehen lassen, dann herausnehmen und in Streifen schneiden.", "Pak Choi 3 Min. in der Brühe garen.", "Hähnchen zurückgeben.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈72 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Pak Choi ↔ Spinat",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-a",
    title: "Weißes geschnittenes Hähnchen (白切雞)",
    desc: "Sanft pochiertes Hähnchen, kalt in Scheiben serviert, mit Ingwer-Frühlingszwiebel-Öl.",
    story: "Baiqieji gilt als Prüfstein kantonesischer Kochkunst – Einfachheit, die volle Konzentration verlangt.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenbrust 300 g", "Ingwer 20 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Hähnchen in Wasser 20 Min. sanft pochieren, bis Kerntemperatur ≥75 °C erreicht ist.", "Ingwer und Frühlingszwiebel fein hacken, in warmem Öl übergießen.", "Hähnchen in Scheiben schneiden.", "Mit dem Öl beträufelt und Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenbrust ↔ Hähnchenschenkel ohne Haut",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Congee mit Fisch und Ingwer (魚片粥)",
    desc: "Milder Congee mit hauchdünnen Fischscheiben, klassisches kantonesisches Frühstück.",
    story: "Der Fisch gart nur durch die Resthitze des heißen Congees – daher müssen die Scheiben hauchdünn sein.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Seelachsfilet 150 g", "Ingwer 10 g", "Wasser 800 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Wasser 40 Min. weich köcheln.", "Fisch hauchdünn schneiden, in den kochend heißen Congee geben und 3 Min. ziehen lassen, bis durchgegart.", "Mit Ingwer würzen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓ Fisch durchgegart, quecksilberarm",
    swaps: "Seelachs ↔ Kabeljau",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:9" },
  },
  {
    id: "di-m",
    title: "Gedämpfte Hackfleischtorte mit Salzei (梅菜蒸肉餅)",
    desc: "Flach gedämpfter Hackfleischkuchen, kantonesisches Alltagsgericht mit Tiefe.",
    story: "Zhengroubing wird im Dampf direkt über dem Reiskocher zubereitet – zwei Gerichte, ein Topf.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Hähnchenhack 220 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Maisstärke 1 EL", "Reis (roh) 150 g"],
    steps: ["Hack mit Sojasauce, Stärke und Frühlingszwiebel verkneten.", "Flach in eine Schale drücken.", "12–15 Min. dämpfen, bis vollständig durchgegart.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-a",
    title: "Rettich-Suppe mit Rinderbrust mild (牛腩蘿蔔湯)",
    desc: "Lang geschmorte, magere Rinderbrust mit Rettich in klarer Brühe.",
    story: "Niunan Luobo Tang ist ein kantonesisches Familiengericht, das am Herd stundenlang leise köchelt.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Rinderbrust mager 250 g", "Daikon 200 g", "Ingwer 15 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Rind in Wasser 45 Min. köcheln, bis zart und vollständig durch.", "Daikon zugeben, 15 Min. mitköcheln.", "Mit Sojasauce und Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rinderbrust ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Gedämpfte Reisnudelrolle (腸粉)",
    desc: "Zarte, gedämpfte Reisnudelrolle mit Ei gefüllt, kantonesischer Dim-Sum-Frühstücksklassiker.",
    story: "Changfen wird traditionell in speziellen Dampfschubladen gegart – bei uns funktioniert es auch im normalen Dämpfer.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reismehl 80 g", "Wasser 200 ml", "Eier 2 Stück", "Sojasauce natriumarm 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Reismehl mit Wasser glattrühren.", "Dünn auf ein geöltes Blech gießen, Ei darauf verteilen.", "8 Min. dämpfen, bis vollständig gestockt, aufrollen.", "Mit Sojasauce beträufelt servieren."],
    checks: "Diabetes ✓ – ≈72 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Garnelen mit Zuckerschoten (蝦仁炒荷蘭豆)",
    desc: "Knackige Zuckerschoten mit Garnelen, leicht und schnell gebraten.",
    story: "Ein Beispiel für die kantonesische Vorliebe, Gemüse nur kurz zu braten und den Biss zu erhalten.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Garnelen (gegart) 220 g", "Zuckerschoten 200 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Zuckerschoten kurz anbraten.", "Garnelen zugeben, 3 Min. durcherhitzen.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈74 g KH · Schwangerschaft ✓ Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-a",
    title: "Char-Siu-Hähnchen mild (蜜汁叉燒雞)",
    desc: "Hähnchenbrust in milder Char-Siu-Marinade gegart – die Honig-Sojasauce-Süße des Original-Schweinegerichts, hier mit Geflügel.",
    story: "Original-Char-Siu ist Schweinenacken, oft rot gefärbt und süß-rauchig – unsere Version bleibt hell und mild.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenbrust 280 g", "Sojasauce natriumarm 2 EL", "Honig 1 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen mit Sojasauce, Honig und Ingwer 20 Min. marinieren.", "Im Ofen oder in der Pfanne rundum durchbraten, bis Kerntemperatur ≥75 °C.", "In Scheiben schneiden.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenbrust ↔ Putenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Congee mit Hundert-Jahre-Ei-Alternative und Magerfleisch (瘦肉粥)",
    desc: "Herzhafter Congee mit magerem Schweinefleisch, klassische kantonesische Frühstückskombination.",
    story: "Shourou Zhou ist eine der beliebtesten Congee-Varianten in Kantons Frühstückslokalen.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Schweinefilet mager 150 g", "Ingwer 10 g", "Wasser 800 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Wasser 40 Min. weich köcheln.", "Fleisch fein geschnitten zugeben, gar ziehen lassen bis vollständig durch.", "Mit Ingwer würzen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "do-m",
    title: "Gebratener Reis kantonesisch (廣式炒飯)",
    desc: "Lockerer gebratener Reis mit Ei, Erbsen und magerem Schinken.",
    story: "Guangshi Chaofan ist die Basis, aus der Yangzhou-Fried-Rice und viele andere Varianten hervorgingen.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 300 g", "Eier 2 Stück", "Erbsen (TK) 100 g", "Kochschinken mager 80 g", "Sojasauce natriumarm 2 EL"],
    steps: ["Ei in wenig Öl stocken lassen, grob zerteilen.", "Kalten Reis zugeben, kräftig anbraten.", "Erbsen und Schinken untermischen.", "Mit Sojasauce abschmecken."],
    checks: "Diabetes ✓ – ≈90 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Kochschinken ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Gedämpfter Wolfsbarsch mit Ingwer (清蒸鱸魚)",
    desc: "Ganzer Wolfsbarsch (oder Filet), sanft gedämpft, mit heißem Öl-Sojasauce-Guss übergossen.",
    story: "Qingzheng Yu ist das Paradebeispiel kantonesischer Kochphilosophie: möglichst wenig tun, damit die Frische spricht.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Wolfsbarschfilet 280 g", "Ingwer 15 g", "Frühlingszwiebel 3 Stück", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Fisch mit Ingwer 10 Min. dämpfen, bis vollständig durchgegart.", "Frühlingszwiebel darüberstreuen.", "Sojasauce erhitzen, über den Fisch gießen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Fisch durchgegart, quecksilberarm",
    swaps: "Wolfsbarsch ↔ Seelachs",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Sojamilch mit Reisnudel-Snack",
    desc: "Warme Sojamilch mit kleinen gebratenen Reisnudelstreifen.",
    story: "Ein einfaches, sättigendes Frühstücksduo aus dem kantonesischen Alltag.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Ungesüßte Sojamilch 500 ml", "Reisnudeln 100 g", "Sojasauce natriumarm 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Reisnudeln kochen, kurz in wenig Öl anbraten.", "Mit Sojasauce abschmecken.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓",
    swaps: "Reisnudeln ↔ Glasnudeln",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Auberginen-Fisch-Topf mild (茄子魚煲)",
    desc: "Weiche Auberginen mit Kabeljau in leichter Sojasauce-Brühe.",
    story: "Ein einfacher Mittagstopf, der Gemüse und Fisch in einem Schritt vereint.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Auberginen 250 g", "Kabeljau 220 g", "Ingwer 10 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Auberginen in Stiften 8 Min. anbraten.", "Kabeljau zugeben, 8 Min. gar ziehen lassen bis durch.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Kabeljau durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-a",
    title: "Zuckerrohr-Rettich-Suppe mit Rind (甘蔗蘿蔔牛肉湯)",
    desc: "Klare, leicht süßliche Suppe mit Rettich und magerem Rindfleisch.",
    story: "Kantonesische Suppen gelten als 'flüssige Medizin' – täglich frisch angesetzt, nie aufgewärmt.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Rindfleisch mager 220 g", "Daikon 200 g", "Karotte 80 g", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rind in Wasser 30 Min. köcheln, bis vollständig durch.", "Daikon und Karotte zugeben, 15 Min. mitköcheln.", "Mit Ingwer würzen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Gedämpfte Schweinefleischbällchen (蒸肉丸)",
    desc: "Weiche, gedämpfte Fleischbällchen aus magerem Schweinehack, Dim-Sum-Klassiker als Frühstück.",
    story: "Zheng Rouwan wird traditionell im Bambuskörbchen serviert – zart durch die Dampfgarung, nie trocken.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Schweinehack mager 200 g", "Frühlingszwiebel 2 Stück", "Maisstärke 1 EL", "Sojasauce natriumarm 1 EL", "Vollkornbrötchen 1 Stück"],
    steps: ["Hack mit Frühlingszwiebel, Stärke und Sojasauce verkneten.", "Zu Bällchen formen.", "10 Min. dämpfen, bis vollständig durchgegart.", "Mit Brötchen servieren."],
    checks: "Diabetes ✓ – ≈62 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Schweinehack ↔ Hähnchenhack",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Rindfleisch-Beefsteak-Tomaten-Nudeln (茄汁牛肉麵)",
    desc: "Weizennudeln in milder Tomatensauce mit magerem Rindfleisch, kantonesisch-westliche Fusion.",
    story: "Ein Erbe der 'Soy-Sauce-Western'-Küche Hongkongs, die westliche Zutaten kantonesisch interpretiert.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Rinderhack mager 220 g", "Passierte Tomaten 200 ml", "Zwiebel 80 g", "Sojasauce natriumarm 1 EL"],
    steps: ["Zwiebel anschwitzen, Hack krümelig anbraten bis durch.", "Tomaten zugeben, 10 Min. mild köcheln.", "Mit Sojasauce abschmecken.", "Über gekochte Nudeln geben."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Honig-Sojasauce-Spareribs mild (蜜汁排骨)",
    desc: "Magere Rippchen in milder Honig-Sojasauce geschmort, bis das Fleisch zart vom Knochen löst.",
    story: "Mizhi Paigu zeigt die kantonesische Vorliebe für die Balance aus süß und salzig.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Magere Rippchen 300 g", "Sojasauce natriumarm 3 EL", "Honig 1 EL", "Ingwer 10 g", "Reis (roh) 150 g"],
    steps: ["Rippchen anbraten.", "Mit Sojasauce, Honig, Ingwer und Wasser 35 Min. schmoren, bis zart und vollständig durch.", "Sauce leicht einkochen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Rippchen ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Congee zum Wochenausklang mit Hähnchen und Pilzen (雞肉菌菇粥)",
    desc: "Herzhafter Sonntags-Congee mit Hähnchen und Champignons.",
    story: "Ein ruhiger, vertrauter Frühstücksabschluss der kantonesischen Woche.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Hähnchenbrust 150 g", "Champignons 80 g", "Wasser 800 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Wasser 35 Min. weich köcheln.", "Hähnchen und Pilze zugeben, gar ziehen lassen bis durch.", "Mild abschmecken.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Champignons ↔ Shiitake",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "so-m",
    title: "Gebratene Reisnudeln kantonesisch (廣炒河粉)",
    desc: "Breite Reisnudeln mit Hähnchen, Sojasprossen und Sojasauce, im heißen Wok gebraten.",
    story: "Guangchao Hefen verlangt maximale Pfannenhitze – der rauchige Wok-Geschmack (Wok Hei) macht das Gericht besonders.",
    target: "≈94 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Breite Reisnudeln 200 g", "Hähnchenbrust 200 g", "Sojabohnensprossen 150 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen in Streifen anbraten bis durch.", "Nudeln zugeben, bei hoher Hitze mitbraten.", "Sprossen und Sojasauce untermischen.", "Mit Frühlingszwiebel servieren."],
    checks: "Diabetes ✓ – ≈94 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Claypot-Reis mit Kochwurst und Hähnchen (臘腸雞煲仔飯)",
    desc: "Kantonesischer Schmortopfreis mit magerer Kochwurst und Hähnchen zum Wochenausklang.",
    story: "Baozaifan mit Lapcheong (chinesische Wurst) gehört zu den beliebtesten Herbst- und Winter-Comfortfoods Kantons.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 200 g", "Magere Kochwurst 60 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Wurst nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Kochwurst ↔ Kochschinken",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
];

export default function Woche39DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="粵菜 · Dampfgaren & klare Brühen · Balanced"
      heroChips={["Woche 39", "Kantonesisch", "5× 🍚 Reiskocher"]}
    />
  );
}
