/*
  GhibliKitchen – Woche 34 (Start: 2026-08-17)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Nudelsuppen-Klassiker, milde Ramen, Udon und Reisnudelbrühen.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 34",
  startDate: "2026-08-17",
  id: "woche-34-2026-08-17",
  lang: "de",
  sidebar: "Woche 34 (2026-08-17)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-08-17)",
  di: "Dienstag (2026-08-18)",
  mi: "Mittwoch (2026-08-19)",
  do: "Donnerstag (2026-08-20)",
  fr: "Freitag (2026-08-21)",
  sa: "Samstag (2026-08-22)",
  so: "Sonntag (2026-08-23)",
};

const UI_TITLES = {
  main: "Rezepte Woche 34",
  list: "Einkaufsliste Woche 34",
};

export const DATA = [
{
    id: "mo-f",
    title: "Warme Miso-Nudelbrühe zum Frühstück (味噌うどんスープ)",
    desc: "Milde Miso-Brühe mit dünnen Udon-Fäden und Frühlingszwiebel.",
    story: "Ein wärmender, sanfter Start in eine Woche voller Nudelsuppen.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Udon 120 g", "Miso-Paste 2 EL", "Gemüsebrühe 500 ml", "Frühlingszwiebel 1 Stück", "Tofu 100 g"],
    steps: ["Brühe erhitzen, Miso einrühren.", "Udon und Tofu zugeben, gar ziehen lassen.", "Nicht mehr kochen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Udon ↔ Soba",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Milde Ramen mit Hähnchen (鶏白湯風ラーメン)",
    desc: "Cremige, milde Hühnerbrühe mit Nudeln und zartem Hähnchen.",
    story: "Eine entschärfte Tori-Paitan-Ramen ohne intensive Würzpaste.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Hähnchenbrust 200 g", "Hühnerbrühe 600 ml", "Milch 50 ml", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen in der Brühe gar ziehen lassen, herausnehmen und in Scheiben schneiden.", "Brühe mit wenig Milch cremig verfeinern.", "Nudeln separat kochen.", "Alles anrichten, mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart, Milch pasteurisiert) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Shoyu-Ramen mit Ei (醤油ラーメン)",
    desc: "Klare Sojasauce-Brühe mit Nudeln und einem vollständig durchgegarten Ei.",
    story: "Die klassische Tokioter Ramen-Variante, hier ganz ohne rohes Ei.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Eier 2 Stück", "Sojasauce 3 EL", "Hühnerbrühe 600 ml", "Frühlingszwiebel 2 Stück"],
    steps: ["Ei hart kochen, halbieren.", "Brühe mit Sojasauce würzen.", "Nudeln kochen, in die Brühe geben.", "Mit Ei und Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig durchgekocht) · Diabetes ✓",
    swaps: "Weizennudeln ↔ Udon",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-f",
    title: "Sanfte Reisnudelsuppe mit Ei (蛋花米粉湯)",
    desc: "Milde Brühe mit Reisnudeln und Ei-Tropfen.",
    story: "Eine besonders bekömmliche Nudelsuppe für den Morgen.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reisnudeln 120 g", "Eier 2 Stück", "Gemüsebrühe 500 ml", "Sojasauce 1 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Brühe erhitzen.", "Reisnudeln zugeben, gar ziehen lassen.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Sojasauce und Frühlingszwiebel abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Reisnudeln ↔ Sōmen",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Zha Jiang Mian mild (温和炸醬麵)",
    desc: "Weizennudeln mit mildem Sojabohnenpasten-Hackfleisch-Topping.",
    story: "Der Pekinger Nudel-Klassiker, entschärft und milder gewürzt.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Schweinehack (mager) 180 g", "Miso-Paste 2 EL", "Zucchini 80 g", "Sojasauce 1 EL"],
    steps: ["Hack krümelig anbraten.", "Miso und Zucchini zugeben, 8 Min. köcheln.", "Nudeln kochen.", "Mit Sauce servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hack vollständig durchgebraten) · Diabetes ✓",
    swaps: "Schweinehack ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Tantan-Style Sesam-Nudeln mild (胡麻担々麺風)",
    desc: "Sesamige Nudelsuppe mit Hähnchenhack, ganz ohne Chiliöl.",
    story: "Tantanmen ohne Schärfe, dafür mit viel nussigem Sesamgeschmack.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Hähnchenhack 200 g", "Schwarze Sesampaste 2 EL", "Hühnerbrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Hack anbraten.", "Brühe mit Sesampaste und Sojasauce verrühren, erhitzen.", "Nudeln kochen, in die Brühe geben.", "Mit Hack servieren."],
    checks: "Balanced ✓ (ohne Chili) · Schwangerschaft ✓ (Hack vollständig durchgebraten) · Diabetes ✓",
    swaps: "Hähnchenhack ↔ Tofu",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-f",
    title: "Warme Sojamilch-Nudelsuppe (豆漿麵線)",
    desc: "Feine Nudeln in milder, leicht cremiger Sojamilch-Brühe.",
    story: "Ein außergewöhnliches, sehr sanftes Frühstück aus Taiwan.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Reisnudeln (dünn) 120 g", "Milch (als Sojamilch-Ersatz) 400 ml", "Sojasauce 1 EL", "Frühlingszwiebel 1 Stück", "Sesamöl 1 TL"],
    steps: ["Milch sanft erwärmen.", "Nudeln separat kochen, abtropfen.", "Nudeln in die warme Milch geben.", "Mit Sojasauce und Frühlingszwiebel abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Milch ↔ ungesüßte Sojamilch",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Vollkorn-Minestrone mild",
    desc: "Milde Gemüsesuppe mit kurzen Vollkornnudeln und weißen Bohnen.",
    story: "Der italienische Programmpunkt der Woche, als wärmende Nudelsuppe.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Kurze Nudeln 100 g", "Weiße Bohnen 150 g", "Karotte 80 g", "Passierte Tomaten 200 ml", "Olivenöl 1 EL"],
    steps: ["Karotte in wenig Öl anschwitzen.", "Tomaten und Wasser zugeben, mit Karotte 15 Min. mild köcheln.", "Bohnen und Nudeln zugeben, gar ziehen lassen.", "Mit Olivenöl abrunden."],
    checks: "Balanced ✓ (Tomate mild eingekocht) · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Bohnen)",
    swaps: "Kurze Nudeln ↔ Quinoa",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Udon-Hotpot mit Garnelen (海老うどん鍋)",
    desc: "Wärmender Udon-Eintopf mit Garnelen und Pilzen in milder Dashi.",
    story: "Ein Shabu-Shabu-artiger Eintopf im Einzeltopf.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Udon 200 g", "Garnelen 200 g", "Shiitake 30 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Brühe mit Sojasauce erhitzen.", "Garnelen und Pilze darin gar ziehen lassen.", "Udon zugeben.", "Heiß servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-f",
    title: "Milde Hühnernudelsuppe (清燉雞肉麵)",
    desc: "Klare Hühnerbrühe mit dünnen Nudeln und Karotten.",
    story: "Eine beruhigende Suppe, die als sanftes Frühstück dient.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Weizennudeln (dünn) 120 g", "Hähnchenbrust 120 g", "Hühnerbrühe 500 ml", "Karotte 60 g", "Frühlingszwiebel 1 Stück"],
    steps: ["Hähnchen in der Brühe gar ziehen lassen, zerpflücken.", "Karotte fein geschnitten mitköcheln.", "Nudeln zugeben, gar ziehen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Zha Cai Nudel-Suppe mild (榨菜肉絲湯麵)",
    desc: "Milde Brühe mit dünnen Fleischstreifen und Nudeln.",
    story: "Eine Alltagssuppe aus Sichuan, hier bewusst ohne Schärfe.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Schweineschnitzel 150 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Schwein in dünnen Streifen anbraten.", "Brühe mit Sojasauce erhitzen, Fleisch zugeben.", "Nudeln kochen, in die Brühe geben.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Schwein durchgegart) · Diabetes ✓",
    swaps: "Schwein ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Kimchi-freie Nudelsuppe koreanisch mild (순한 잔치국수)",
    desc: "Janchi-Guksu-Style Nudelsuppe in milder Anchovis-Ersatz-Brühe.",
    story: "Die koreanische Fest-Nudelsuppe, hier mit Gemüsebrühe statt intensiver Fischbrühe.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizennudeln (dünn) 180 g", "Eier 2 Stück", "Zucchini 80 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Ei zu dünnem Omelett braten, in Streifen schneiden.", "Zucchini kurz andünsten.", "Brühe mit Sojasauce erhitzen, Nudeln darin gar ziehen lassen.", "Mit Ei und Zucchini anrichten."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Weizennudeln ↔ Soba",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-f",
    title: "Warme Miso-Ei-Nudelschale zum Frühstück",
    desc: "Milde Misobrühe mit Ei und dünnen Nudeln.",
    story: "Ein herzhaftes, wärmendes Frühstück zum Wochenausklang.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Weizennudeln (dünn) 120 g", "Eier 2 Stück", "Miso-Paste 2 EL", "Gemüsebrühe 450 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Brühe erhitzen, Miso einrühren.", "Nudeln zugeben, gar ziehen lassen.", "Verquirltes Ei einrühren, stocken lassen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Miso-Paste ↔ Sojasauce",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Yaki Udon mit Garnelen (海老焼きうどん)",
    desc: "Angebratene Udon-Nudeln mit Garnelen und Kohlgemüse.",
    story: "Eine Pfannen-Nudel-Pause inmitten der Suppenwoche.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Udon 200 g", "Garnelen 180 g", "Weißkohl 120 g", "Karotte 60 g", "Sojasauce 3 EL"],
    steps: ["Garnelen anbraten bis durchgegart.", "Kohl und Karotte zugeben.", "Udon zugeben, gut vermengen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Wan Tan Mian mild (雲吞麵)",
    desc: "Nudeln mit Garnelen-Wontons in klarer, milder Brühe.",
    story: "Die Nudelversion der klassischen Wonton-Suppe.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Weizennudeln 150 g", "Garnelen 150 g", "Reispapier 12 Blatt", "Hühnerbrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Garnelen fein hacken, in Reispapier einwickeln.", "Brühe mit Sojasauce erhitzen, Wontons darin 6 Min. gar ziehen lassen.", "Nudeln separat kochen.", "Zusammen servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenhack",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-f",
    title: "Warmer Milchreis mit Zimt zum Wochenende",
    desc: "Cremiger Milchreis mit Zimt und Walnüssen als Pause von den Nudeln.",
    story: "Eine kleine süße Verschnaufpause innerhalb der Suppenwoche.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Zimt 1 Prise", "Walnüsse 20 g", "Agavendicksaft 1 TL"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Mit Zimt und Agavendicksaft süßen.", "Mit Walnüssen bestreuen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Walnüsse ↔ Mandeln",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Champignon-Udon-Suppe (椎茸うどん)",
    desc: "Milde Dashi-Brühe mit Udon und aromatischen Champignons.",
    story: "Eine einfache, beruhigende Wochenend-Nudelsuppe.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Udon 200 g", "Champignons 150 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Champignons in Scheiben in der Brühe köcheln.", "Mit Sojasauce würzen.", "Udon zugeben, gar ziehen lassen.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Champignons ↔ Shiitake",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Rindfleisch-Pho-Style Suppe mild (清燉牛肉河粉風)",
    desc: "Milde Rinderbrühe mit Reisnudeln und dünnen Rindfleischscheiben.",
    story: "Angelehnt an vietnamesisches Pho, mit chinesisch-milder Würzung statt Sternanis-Fülle.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Reisnudeln 180 g", "Rindfleisch (mager) 200 g", "Gemüsebrühe 600 ml", "Sojasauce 2 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Brühe mit Sojasauce erhitzen.", "Rind hauchdünn schneiden, in der heißen Brühe gar ziehen lassen bis durchgegart.", "Nudeln separat kochen, in die Suppe geben.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Rind vollständig durchgegart) · Diabetes ✓",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-f",
    title: "Sanfte Ei-Tofu-Suppe zum Frühstück (豆腐蛋湯)",
    desc: "Milde Brühe mit Tofu und Ei-Tropfen.",
    story: "Ein ruhiger Sonntagmorgen-Abschluss der Nudelsuppenwoche.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Tofu 150 g", "Eier 2 Stück", "Gemüsebrühe 500 ml", "Sojasauce 1 EL", "Reis (roh) 100 g"],
    steps: ["Brühe erhitzen.", "Tofu zugeben.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenhack",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Kalte Sesam-Soba-Schale zum Ausklang",
    desc: "Gekühlte Soba-Nudeln mit mildem Sesamdressing.",
    story: "Ein erfrischender Abschluss nach vielen warmen Suppen.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Soba-Nudeln 180 g", "Sojasauce 2 EL", "Schwarze Sesampaste 1 EL", "Gurke 80 g", "Karotte 60 g"],
    steps: ["Soba kochen, kalt abschrecken.", "Gurke in Streifen schneiden.", "Sojasauce und Sesampaste verrühren.", "Alles vermengen, kühl servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Soba ↔ Reisnudeln",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Nabe-Eintopf mit Hähnchen und Nudeln (寄せ鍋風うどん)",
    desc: "Wärmender Hotpot-Eintopf mit Hähnchen, Gemüse und Udon.",
    story: "Ein gemütlicher Wochenabschluss im Eintopf-Stil.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Udon 200 g", "Hähnchenbrust 200 g", "Pak Choi 100 g", "Shiitake 30 g", "Gemüsebrühe 600 ml"],
    steps: ["Brühe erhitzen.", "Hähnchen und Pilze darin gar ziehen lassen.", "Pak Choi und Udon zugeben.", "Heiß servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: false },
  }
];

export default function Woche34DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Ramen, Udon & Co. 🍜 · Milde Brühen · Balanced"
      heroChips={["Woche 34", "Nudelsuppen-Klassiker"]}
    />
  );
}
