/*
  GhibliKitchen – Woche 42 (Start: 2026-10-12)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Wok-Klassiker der chinesischen Hausküche (家常炒菜) – rot geschmort, sauer-süß, kross gebraten.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 42",
  startDate: "2026-10-12",
  id: "woche-42-2026-10-12",
  lang: "de",
  sidebar: "Woche 42 (2026-10-12)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-10-12)",
  di: "Dienstag (2026-10-13)",
  mi: "Mittwoch (2026-10-14)",
  do: "Donnerstag (2026-10-15)",
  fr: "Freitag (2026-10-16)",
  sa: "Samstag (2026-10-17)",
  so: "Sonntag (2026-10-18)",
};

const UI_TITLES = {
  main: "Rezepte Woche 42",
  list: "Einkaufsliste Woche 42",
};

export const DATA = [
  {
    id: "mo-f",
    title: "Congee mit eingelegtem Gemüse und Erdnuss (小菜花生粥)",
    desc: "Klassischer Reisbrei mit milden eingelegten Gemüsestreifen und Erdnüssen.",
    story: "Ein einfacher, vertrauter Start in eine Woche voller Wok-Klassiker.",
    target: "≈66 g KH gesamt (2 P.) · Protein ≈12 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Gurke eingelegt mild 50 g", "Erdnüsse geröstet 25 g", "Wasser 700 ml"],
    steps: ["Reis mit Wasser 30 Min. weich köcheln.", "Eingelegtes Gemüse fein schneiden.", "Erdnüsse grob hacken.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈66 g KH · Schwangerschaft ✓",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "mo-m",
    title: "Rot geschmortes Hähnchen (紅燒雞塊)",
    desc: "Hähnchenteile in dunkler Sojasauce-Zucker-Sauce sanft geschmort.",
    story: "Hongshao ('rot geschmort') ist eine der prägendsten Techniken der chinesischen Küche – Karamell und Sojasauce ergeben die charakteristische Farbe.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Hähnchenschenkel ohne Haut 280 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Frühlingszwiebel 2 Stück", "Reis (roh) 150 g"],
    steps: ["Hähnchen rundum anbraten.", "Mit Sojasauce, Ingwer und wenig Wasser 20 Min. schmoren, bis vollständig durch.", "Sauce leicht einkochen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mo-a",
    title: "Fischduftendes Schweinefleisch mild (魚香肉絲)",
    desc: "Dünne Schweinefleischstreifen mit Gemüse in der klassischen Yuxiang-Würzung.",
    story: "Yuxiang Rousi ist neben den Auberginen die bekannteste Anwendung dieser süß-sauren Würzkombination.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Schweinefilet mager 220 g", "Karotte 80 g", "Holzohrpilze 40 g", "Reisessig mild 2 EL", "Reis (roh) 150 g"],
    steps: ["Fleisch in dünne Streifen schneiden, anbraten bis durch.", "Gemüse zugeben, mitbraten.", "Mit Essig, Sojasauce und wenig Zucker ablöschen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Gebratener Reis mit Ei (蛋炒飯)",
    desc: "Der einfachste und beliebteste gebratene Reis Chinas – nur Reis, Ei und Frühlingszwiebel.",
    story: "Danchaofan ist oft das erste Wok-Gericht, das man in China selbst kochen lernt.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 280 g", "Eier 3 Stück", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL"],
    steps: ["Ei in wenig Öl stocken lassen bis vollständig durch, grob zerteilen.", "Kalten Reis zugeben, kräftig anbraten.", "Ei untermischen.", "Mit Sojasauce und Frühlingszwiebel abschmecken."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Süß-saures Hähnchen (糖醋雞塊)",
    desc: "Hähnchenwürfel in milder süß-saurer Sauce mit Ananas und Paprika – ohne Frittieren.",
    story: "Tangcu-Gerichte sind im Westen oft die bekanntesten chinesischen Exportgerichte überhaupt.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 260 g", "Ananas 100 g", "Paprika 100 g", "Reisessig mild 2 EL", "Reis (roh) 150 g"],
    steps: ["Hähnchen würfeln, anbraten bis durch.", "Paprika und Ananas zugeben, mitbraten.", "Mit Essig und wenig Zucker ablöschen, leicht binden.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-a",
    title: "Essig-geschmorter Chinakohl (醋溜白菜)",
    desc: "Kurz gebratener Chinakohl mit mildem Essig-Glanz, klassische nordchinesische Beilage als Hauptgericht.",
    story: "Culiu Baicai zeigt, wie ein einfaches Gemüse mit der richtigen Säure-Balance zum Star wird.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Chinakohl 300 g", "Hähnchenbrust 180 g", "Reisessig mild 2 EL", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Hähnchen anbraten bis durch.", "Kohl zugeben, kräftig anbraten.", "Mit Essig und Ingwer ablöschen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Hähnchen durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Warme Sojamilch mit Sesamkringel",
    desc: "Ungesüßte Sojamilch mit knusprigem Sesamgebäck.",
    story: "Ein bewährtes Duo, das in dieser Woche schon öfter für einen zügigen Start gesorgt hat.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Ungesüßte Sojamilch 500 ml", "Vollkornbrötchen 2 Stück", "Sesam geröstet 1 TL"],
    steps: ["Sojamilch warm erhitzen.", "Brötchen anrösten.", "Mit Sesam bestreuen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Rotgeschmorter Fisch mild (紅燒魚)",
    desc: "Kabeljau in dunkler Sojasauce-Ingwer-Sauce geschmort.",
    story: "Hongshao Yu ist ein Festtagsgericht, das an chinesischen Neujahrstischen für Wohlstand steht.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kabeljaufilet 260 g", "Sojasauce natriumarm 3 EL", "Ingwer 15 g", "Frühlingszwiebel 2 Stück", "Reis (roh) 150 g"],
    steps: ["Fisch von beiden Seiten kurz anbraten.", "Mit Sojasauce, Ingwer und wenig Wasser 10 Min. schmoren, bis vollständig durch.", "Sauce leicht einkochen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈84 g KH · Schwangerschaft ✓ Kabeljau durchgegart, quecksilberarm",
    swaps: "Kabeljau ↔ Seelachs",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-a",
    title: "Doppelt gebratenes Gemüse mit Hähnchen (回鍋雞風)",
    desc: "Angelehnt an das Huiguorou-Prinzip: gegartes, dann gebratenes Hähnchen mit Paprika und Lauch.",
    story: "Die 'doppelte' Garmethode – erst kochen, dann braten – bringt eine besondere Textur, ganz ohne Chilibohnenpaste.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 260 g", "Paprika 100 g", "Lauch 100 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Hähnchen 12 Min. gar ziehen lassen, bis durch, dann in Scheiben schneiden.", "In wenig Öl kurz scharf anbraten.", "Paprika und Lauch zugeben, mitbraten.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchen ↔ Tofu",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-f",
    title: "Congee mit Frühlingszwiebel-Ei-Pfannkuchenstreifen",
    desc: "Milder Reisbrei mit knusprigen Eierpfannkuchenstreifen.",
    story: "Eine schnelle, sättigende Frühstückskombination für einen vollen Tag.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Eier 2 Stück", "Frühlingszwiebel 2 Stück", "Wasser 700 ml"],
    steps: ["Reis mit Wasser 30 Min. weich köcheln.", "Ei mit Frühlingszwiebel verquirlen, dünn ausbacken bis vollständig durch.", "In Streifen schneiden.", "Über den Congee geben."],
    checks: "Diabetes ✓ – ≈68 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "-",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "do-m",
    title: "Gebratene Garnelen mit Cashewkernen (腰果蝦仁)",
    desc: "Knackige Garnelen mit Cashewkernen und Gemüse, milde Sojasauce-Würzung.",
    story: "Cashew-Varianten der klassischen Gongbao-Technik gehören zu den beliebtesten Restaurant-Gerichten.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Garnelen (gegart) 220 g", "Cashewkerne 40 g", "Zucchini 100 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Zucchini kurz anbraten.", "Garnelen zugeben, 3 Min. durcherhitzen.", "Mit Sojasauce abschmecken.", "Mit Cashewkernen und Reis servieren."],
    checks: "Diabetes ✓ – ≈78 g KH · Schwangerschaft ✓ Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "do-a",
    title: "Geschmorte Auberginen mit Hackfleisch (肉末茄子)",
    desc: "Weiche Auberginenstücke mit magerem Hackfleisch in dunkler Sojasauce.",
    story: "Ein alltägliches Schmorgericht, das in den meisten chinesischen Haushalten fest zum Repertoire gehört.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈26 g p. P.",
    ingredients: ["Auberginen 300 g", "Hähnchenhack 180 g", "Sojasauce natriumarm 2 EL", "Ingwer 8 g", "Reis (roh) 150 g"],
    steps: ["Auberginen in Stücken weich anbraten.", "Hack zugeben, krümelig durchbraten.", "Mit Sojasauce und Ingwer abschmecken, kurz köcheln.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Hähnchenhack ↔ Putenhack",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Frühlingszwiebel-Eierpfannkuchen mit Sojamilch",
    desc: "Dünner Eierpfannkuchen mit warmer Sojamilch, bewährtes Wochenfrühstück.",
    story: "Ein einfaches Duo, das sich diese Woche schon mehrfach bewährt hat.",
    target: "≈62 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Eier 3 Stück", "Mehl 40 g", "Frühlingszwiebel 2 Stück", "Ungesüßte Sojamilch 400 ml"],
    steps: ["Teig aus Ei, Mehl und wenig Wasser verrühren.", "Mit Frühlingszwiebel in wenig Öl ausbacken, bis vollständig gestockt.", "Sojamilch warm erhitzen.", "Zusammen servieren."],
    checks: "Diabetes ✓ – ≈62 g KH · Schwangerschaft ✓ Ei vollständig gestockt",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Ameisen im Baum mit Rind (螞蟻上樹牛肉)",
    desc: "Glasnudeln mit fein gehacktem Rinderhack, würzig-mild statt scharf.",
    story: "Eine Rindfleisch-Variante des Sichuan-Klassikers aus Woche 37 – diesmal mit kräftigerem Rindfleischaroma.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Glasnudeln (roh) 100 g", "Rinderhack mager 220 g", "Frühlingszwiebel 2 Stück", "Sojasauce natriumarm 2 EL", "Ingwer 8 g"],
    steps: ["Glasnudeln einweichen.", "Hack krümelig anbraten, bis vollständig durch.", "Nudeln, Sojasauce und etwas Wasser zugeben, 5 Min. ziehen lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Hack vollständig durchgegart",
    swaps: "Rinderhack ↔ Hähnchenhack",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Rotgeschmortes mageres Schweinefleisch (紅燒瘦肉)",
    desc: "Magere Schweinefleischwürfel in dunkler Sojasauce-Sauce sanft geschmort.",
    story: "Eine leichtere Version des berühmten Hongshaorou, mit magerem statt durchwachsenem Fleisch.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Schweinefilet mager 260 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Frühlingszwiebel 2 Stück", "Reis (roh) 150 g"],
    steps: ["Fleisch würfeln, rundum anbraten.", "Mit Sojasauce, Ingwer und wenig Wasser 20 Min. schmoren, bis vollständig durch.", "Sauce leicht einkochen lassen.", "Mit Reis servieren."],
    checks: "Diabetes ✓ – ≈88 g KH · Schwangerschaft ✓ Fleisch vollständig durchgegart",
    swaps: "Schweinefilet ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Klebreis-Frühstücksschale mit Erdnuss und Ei",
    desc: "Warmer Klebreis mit gehackten Erdnüssen und durchgebratenem Ei.",
    story: "Ein sättigendes Wochenendfrühstück, das lange satt hält.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Klebreis (roh) 120 g", "Erdnüsse geröstet 25 g", "Eier 2 Stück", "Frühlingszwiebel 1 Stück"],
    steps: ["Klebreis gar dämpfen.", "Ei separat vollständig durchbraten.", "Erdnüsse grob hacken.", "Alles zusammen anrichten."],
    checks: "Diabetes ✓ – ≈82 g KH · Schwangerschaft ✓ Ei durchgegart",
    swaps: "Klebreis ↔ Reis",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Klebreis", water: "1:1" },
  },
  {
    id: "sa-m",
    title: "Gebratene Garnelen mit Lychee (荔枝蝦球)",
    desc: "Garnelen mit Lychee und Gemüse, mild-fruchtige Wok-Kombination.",
    story: "Süß-herzhafte Frucht-Fleisch-Kombinationen sind in der südchinesischen Küche fest verankert.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Garnelen (gegart) 240 g", "Lychee (aus der Dose, ungesüßt) 100 g", "Paprika 80 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Paprika kurz anbraten.", "Garnelen zugeben, 3 Min. durcherhitzen.", "Lychee zugeben, kurz mitschwenken.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈80 g KH · Schwangerschaft ✓ Garnelen vollständig gegart",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-a",
    title: "Trockenbrat-Topf mit Hähnchenflügeln und Garnelen mild (干鍋雞翅蝦)",
    desc: "Hähnchen und Garnelen mit Gemüse trocken angebraten, aromatisch statt feurig.",
    story: "Ganguo-Gerichte werden ohne viel Flüssigkeit im heißen Wok zubereitet – konzentriertes Röstaroma pur.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈34 g p. P.",
    ingredients: ["Hähnchenflügel ohne Haut 250 g", "Garnelen (gegart) 150 g", "Paprika 100 g", "Sojasauce natriumarm 2 EL", "Reis (roh) 150 g"],
    steps: ["Hähnchen rundum anbraten, bis vollständig durch.", "Paprika zugeben, mitbraten.", "Garnelen in den letzten 3 Min. zugeben.", "Mit Sojasauce abschmecken, mit Reis servieren."],
    checks: "Diabetes ✓ – ≈86 g KH · Schwangerschaft ✓ Hähnchen und Garnelen vollständig gegart",
    swaps: "Hähnchenflügel ↔ Hähnchenschenkel",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "so-f",
    title: "Sonntags-Congee mit Rind und Ei (牛肉蛋粥)",
    desc: "Herzhafter Reisbrei mit magerem Rindfleisch und Ei.",
    story: "Ein etwas reichhaltigerer Congee, wie er am Wochenende gern serviert wird.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈24 g p. P.",
    ingredients: ["Reis (roh) 100 g", "Rindfleisch mager 150 g", "Eier 2 Stück", "Wasser 800 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Wasser 35 Min. weich köcheln.", "Rind fein geschnitten zugeben, gar ziehen lassen bis vollständig durch.", "Verquirltes Ei einrühren.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Diabetes ✓ – ≈70 g KH · Schwangerschaft ✓ Rind und Ei durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "-",
    remind: true,
    riceCooker: { enabled: true, program: "Porridge/Congee", water: "1:8" },
  },
  {
    id: "so-m",
    title: "Gebratene Reisnudeln mit Rind (乾炒牛河)",
    desc: "Breite Reisnudeln mit magerem Rindfleisch und Sojasprossen, kräftig im Wok gebraten.",
    story: "Ganchao Niuhe ist ein kantonesischer Wok-Klassiker, der Präzision bei hoher Hitze verlangt.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Breite Reisnudeln 200 g", "Rindfleisch mager 220 g", "Sojabohnensprossen 150 g", "Sojasauce natriumarm 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Rind in Streifen anbraten bis durch.", "Nudeln zugeben, bei hoher Hitze mitbraten.", "Sprossen und Sojasauce untermischen.", "Mit Frühlingszwiebel servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Rind vollständig durchgegart",
    swaps: "Rind ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Claypot-Hongshao-Hähnchen-Reis zum Wochenausklang (紅燒雞煲仔飯)",
    desc: "Schmortopfreis mit rotgeschmortem Hähnchen, wärmender Abschluss der Wok-Woche.",
    story: "Ein Gericht, das die Woche der Wok-Techniken mit vertrauten Hongshao-Aromen ausklingen lässt.",
    target: "≈92 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenschenkel ohne Haut 220 g", "Sojasauce natriumarm 3 EL", "Ingwer 10 g", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce und Ingwer marinieren.", "Reis in den Reiskocher geben.", "Hähnchen nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreut servieren."],
    checks: "Diabetes ✓ – ≈92 g KH · Schwangerschaft ✓ Hähnchen vollständig durchgegart",
    swaps: "Hähnchenschenkel ↔ Hähnchenbrust",
    side: "Warmer Chrysanthementee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
];

export default function Woche42DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="家常炒菜 · Hongshao & süß-sauer · Balanced"
      heroChips={["Woche 42", "Wok-Klassiker", "6× 🍚 Reiskocher"]}
    />
  );
}
