/*
  GhibliKitchen – Woche 35 (Start: 2026-08-24)
  Status: KOMPLETT & FUNKTIONSFÄHIG (Alle 21 Rezepte)
  Fokus: Spätsommer-Ernte: Kürbis, Mais und die ersten Pilze der Saison.
*/

import React from "react";
import PlanTemplate from "../PlanTemplate";

export const meta = {
  title: "Woche 35",
  startDate: "2026-08-24",
  id: "woche-35-2026-08-24",
  lang: "de",
  sidebar: "Woche 35 (2026-08-24)",
};

const DAY_NAME_DE = {
  mo: "Montag (2026-08-24)",
  di: "Dienstag (2026-08-25)",
  mi: "Mittwoch (2026-08-26)",
  do: "Donnerstag (2026-08-27)",
  fr: "Freitag (2026-08-28)",
  sa: "Samstag (2026-08-29)",
  so: "Sonntag (2026-08-30)",
};

const UI_TITLES = {
  main: "Rezepte Woche 35",
  list: "Einkaufsliste Woche 35",
};

export const DATA = [
{
    id: "mo-f",
    title: "Mais-Ei-Congee (玉米蛋粥)",
    desc: "Sanfter Reisbrei mit süßem Mais und Ei.",
    story: "Der erste Mais der Spätsommerernte findet seinen Weg ins Frühstück.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Mais 100 g", "Eier 2 Stück", "Hühnerbrühe 500 ml", "Frühlingszwiebel 1 Stück"],
    steps: ["Reis mit Brühe 30 Min. weich köcheln.", "Mais in den letzten 10 Min. zugeben.", "Verquirltes Ei einrühren, stocken lassen.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Mais ↔ Erbsen",
    side: "-",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-m",
    title: "Pilz-Nudel-Pfanne herbstlich (菌菇炒麵)",
    desc: "Weizennudeln mit einer Mischung aus Champignons und Shiitake.",
    story: "Die Pilzsaison beginnt – ein umami-reiches, mildes Nudelgericht.",
    target: "≈76 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Weizennudeln 180 g", "Champignons 120 g", "Shiitake 40 g", "Sojasauce 2 EL", "Frühlingszwiebel 1 Stück"],
    steps: ["Nudeln kochen.", "Pilze in wenig Öl anbraten.", "Nudeln zugeben, mit Sojasauce abschmecken.", "Mit Frühlingszwiebel servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Shiitake ↔ Champignons",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mo-a",
    title: "Kürbis-Hähnchen-Reisschale (南瓜雞肉丼)",
    desc: "Weich gegarter Kürbis mit zartem Hähnchen auf Reis.",
    story: "Der Kürbis der Spätsommerernte trifft auf mildes Hähnchen.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Kürbis 200 g", "Hähnchenbrust 220 g", "Reis (roh) 150 g", "Sojasauce 2 EL", "Ingwer 10 g"],
    steps: ["Kürbis in Würfeln 15 Min. köcheln.", "Hähnchen zugeben, gar ziehen lassen.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "di-f",
    title: "Süßkartoffel-Milchreis (蕃薯粥)",
    desc: "Cremiger Milchreis mit weicher Süßkartoffel.",
    story: "Ein herbstlich-süßes Frühstück mit viel Ballaststoffen.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 80 g", "Süßkartoffel 150 g", "Milch 300 ml", "Zimt 1 Prise", "Walnüsse 15 g"],
    steps: ["Süßkartoffel in Würfeln mit Reis und Milch 25 Min. weich köcheln.", "Mit Zimt abschmecken.", "Bei Bedarf leicht pürieren.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓ (ballaststoffreiche Süßkartoffel)",
    swaps: "Süßkartoffel ↔ Kürbis",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "di-m",
    title: "Pilz-Tofu-Suppe herzhaft (菌菇豆腐湯)",
    desc: "Milde Gemüsebrühe mit Champignons, Shiitake und Tofu.",
    story: "Eine wärmende, leichte Mittagssuppe für kühlere Spätsommertage.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Champignons 100 g", "Shiitake 30 g", "Tofu 200 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL", "Reis (roh) 100 g"],
    steps: ["Pilze in der Brühe 10 Min. köcheln.", "Tofu zugeben.", "Mit Sojasauce würzen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Tofu ↔ Hähnchenbrust",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "di-a",
    title: "Mais-Rippchen-Suppe mager (玉米排骨湯)",
    desc: "Klare, milde Suppe mit Mais und magerem Schweinefilet.",
    story: "Eine kantonesische Herbstsuppe, mit magerem Filet statt fettiger Rippen.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Schweineschnitzel 200 g", "Mais 150 g", "Karotte 80 g", "Reis (roh) 150 g", "Ingwer 10 g"],
    steps: ["Schwein anbraten, mit Wasser aufgießen.", "Mais, Karotte und Ingwer zugeben, 20 Min. köcheln.", "Leicht salzen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Schwein durchgegart) · Diabetes ✓",
    swaps: "Schwein ↔ Hähnchenbrust",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "mi-f",
    title: "Warmer Kürbis-Hafer-Porridge",
    desc: "Cremiges Haferporridge mit Kürbispüree und Zimt.",
    story: "Eine Ost-West-Kombination für kühlere Spätsommermorgen.",
    target: "≈68 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Haferflocken 100 g", "Kürbis 100 g", "Milch 300 ml", "Zimt 1 Prise", "Agavendicksaft 1 TL"],
    steps: ["Kürbis weich dünsten, pürieren.", "Mit Haferflocken und Milch 10 Min. köcheln.", "Mit Zimt und Agavendicksaft abschmecken.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓ (ballaststoffreicher Hafer)",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-m",
    title: "Gnocchi mit Pilz-Sahnesauce mild",
    desc: "Vollkorn-Gnocchi mit einer milden, cremigen Pilzsauce.",
    story: "Der italienische Programmpunkt der Woche, herbstlich mit Pilzen.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Gnocchi 300 g", "Champignons 150 g", "Milch 100 ml", "Parmesan 20 g", "Olivenöl 1 EL"],
    steps: ["Pilze in Öl anbraten.", "Mit Milch ablöschen, kurz einköcheln.", "Gnocchi kochen, zur Sauce geben.", "Mit Parmesan bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch und Parmesan pasteurisiert) · Diabetes ✓",
    swaps: "Gnocchi ↔ Vollkorn-Penne",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "mi-a",
    title: "Gebratener Kürbis-Garnelen-Reis (南瓜蝦仁炒飯)",
    desc: "Bratreis mit Kürbis und Garnelen, mild sojagewürzt.",
    story: "Ein farbenfroher Herbstreis, der Süße und Umami vereint.",
    target: "≈88 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Reis (gekocht, kalt) 300 g", "Kürbis 120 g", "Garnelen 180 g", "Eier 1 Stück", "Sojasauce 2 EL"],
    steps: ["Kürbis in kleinen Würfeln weich braten.", "Garnelen zugeben, durchgaren.", "Ei und Reis zugeben, gut vermengen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Garnelen und Ei durchgegart) · Diabetes ✓",
    swaps: "Garnelen ↔ Hähnchenbrust",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-f",
    title: "Pilz-Ei-Dampfschale (菌菇蒸蛋)",
    desc: "Samtiges Dampfei mit fein geschnittenen Shiitake-Pilzen.",
    story: "Ein herbstlich-umamireiches Frühstück.",
    target: "≈60 g KH gesamt (2 P.) · Protein ≈20 g p. P.",
    ingredients: ["Eier 4 Stück", "Shiitake 40 g", "Hühnerbrühe 200 ml", "Sojasauce 1 EL", "Toastbrot 2 Scheiben"],
    steps: ["Ei mit Brühe verquirlen, durch ein Sieb geben.", "Shiitake klein schneiden, untermengen.", "12 Min. dämpfen bis fest.", "Mit Toast servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei vollständig gestockt) · Diabetes ✓",
    swaps: "Shiitake ↔ Champignons",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "do-m",
    title: "Mais-Hähnchen-Salat warm (玉米雞肉沙拉)",
    desc: "Warmer Salat mit Mais, Hähnchen und mildem Sesamdressing.",
    story: "Ein sättigender, proteinreicher Mittagssalat.",
    target: "≈72 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Hähnchenbrust 200 g", "Mais 120 g", "Gurke 100 g", "Sojasauce 2 EL", "Sesamöl 1 EL"],
    steps: ["Hähnchen anbraten, in Streifen schneiden.", "Mais und Gurke vorbereiten.", "Alles mit Sojasauce und Sesamöl vermengen.", "Lauwarm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Garnelen",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "do-a",
    title: "Herbstlicher Kürbis-Tofu-Eintopf (南瓜豆腐煲)",
    desc: "Weich geschmorter Kürbis mit Tofu in milder Sojasauce.",
    story: "Ein wärmendes, vegetarisches Herbstgericht.",
    target: "≈82 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Kürbis 220 g", "Tofu 200 g", "Reis (roh) 150 g", "Sojasauce 2 EL", "Ingwer 10 g"],
    steps: ["Kürbis in Würfeln 15 Min. köcheln.", "Tofu zugeben, kurz mitziehen lassen.", "Mit Sojasauce und Ingwer abschmecken.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Kürbis ↔ Süßkartoffel",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "fr-f",
    title: "Mais-Frühlingszwiebel-Pfannkuchen (玉米蔥油餅)",
    desc: "Herzhafte Pfannkuchen mit Mais und Frühlingszwiebel.",
    story: "Eine Variante des klassischen Congyoubing mit süßem Mais.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Mehl 120 g", "Mais 100 g", "Frühlingszwiebel 2 Stück", "Eier 1 Stück", "Sojasauce 1 EL"],
    steps: ["Teig aus Mehl, Ei und Wasser anrühren.", "Mais und Frühlingszwiebel untermengen.", "In der Pfanne beidseitig knusprig backen.", "Mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Mehl ↔ Vollkornmehl",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-m",
    title: "Herbst-Gemüse-Udon (秋野菜うどん)",
    desc: "Udon-Nudeln mit Kürbis, Pilzen und Karotten in milder Brühe.",
    story: "Ein wärmendes Nudelgericht zum Wochenausklang.",
    target: "≈78 g KH gesamt (2 P.) · Protein ≈16 g p. P.",
    ingredients: ["Udon 200 g", "Kürbis 100 g", "Champignons 80 g", "Gemüsebrühe 500 ml", "Sojasauce 2 EL"],
    steps: ["Kürbis in der Brühe 10 Min. köcheln.", "Pilze zugeben.", "Udon zugeben, gar ziehen lassen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓",
    swaps: "Udon ↔ Soba",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "fr-a",
    title: "Lachs mit Kürbispüree (鮭魚南瓜泥)",
    desc: "Gedämpfter Lachs auf cremigem Kürbispüree.",
    story: "Ein besonders elegantes, herbstliches Freitagsabendessen.",
    target: "≈84 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Lachsfilet 280 g", "Kürbis 250 g", "Milch 50 ml", "Reis (roh) 100 g", "Sojasauce 1 EL"],
    steps: ["Kürbis weich kochen, mit wenig Milch pürieren.", "Lachs 10 Min. dämpfen.", "Reis im Reiskocher zubereiten.", "Alles anrichten, mit Sojasauce beträufeln."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Lachs durchgegart, Milch pasteurisiert) · Diabetes ✓",
    swaps: "Lachs ↔ Kabeljau",
    side: "Warmer Mugicha.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  },
  {
    id: "sa-f",
    title: "Pilz-Ei-Toast (菌菇蛋吐司)",
    desc: "Vollkorntoast mit Rührei und angebratenen Pilzen.",
    story: "Ein herzhaftes Wochenendfrühstück mit viel Umami.",
    target: "≈64 g KH gesamt (2 P.) · Protein ≈22 g p. P.",
    ingredients: ["Vollkorn-Toast 4 Scheiben", "Eier 3 Stück", "Champignons 80 g", "Butter 1 TL", "Frühlingszwiebel 1 Stück"],
    steps: ["Pilze in wenig Butter anbraten.", "Ei verquirlen, dazugeben, stocken lassen.", "Auf Toast anrichten.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Ei durchgegart) · Diabetes ✓",
    swaps: "Champignons ↔ Shiitake",
    side: "Kaffee oder Tee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-m",
    title: "Süßkartoffel-Hähnchen-Bowl (蕃薯雞肉碗)",
    desc: "Warme Bowl mit Süßkartoffel, Hähnchen und Spinat.",
    story: "Ein sättigendes, ballaststoffreiches Wochenendgericht.",
    target: "≈80 g KH gesamt (2 P.) · Protein ≈28 g p. P.",
    ingredients: ["Süßkartoffel 200 g", "Hähnchenbrust 200 g", "Spinat 100 g", "Sojasauce 2 EL", "Sesamöl 1 TL"],
    steps: ["Süßkartoffel in Würfeln weich dünsten.", "Hähnchen anbraten, in Streifen schneiden.", "Spinat kurz mitdünsten.", "Alles mit Sojasauce und Sesamöl vermengen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓ (ballaststoffreiche Süßkartoffel)",
    swaps: "Süßkartoffel ↔ Kürbis",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "sa-a",
    title: "Claypot-Kürbis-Hähnchen-Reis (煲仔南瓜雞飯)",
    desc: "Aromatischer Schmortopfreis mit Kürbis und Hähnchen.",
    story: "Eine herbstliche Variante des kantonesischen Claypot-Reis.",
    target: "≈90 g KH gesamt (2 P.) · Protein ≈32 g p. P.",
    ingredients: ["Reis (roh) 160 g", "Hähnchenbrust 220 g", "Kürbis 120 g", "Sojasauce 3 EL", "Frühlingszwiebel 2 Stück"],
    steps: ["Hähnchen mit Sojasauce marinieren.", "Reis in den Reiskocher geben.", "Hähnchen und Kürbis nach halber Garzeit zugeben.", "Mit Frühlingszwiebel bestreuen."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kochschinken",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Claypot/Mixed", water: "1:1,3" },
  },
  {
    id: "so-f",
    title: "Warmer Mais-Milchreis",
    desc: "Cremiger Milchreis mit süßem Mais.",
    story: "Ein ungewöhnliches, aber mildes Sonntagsfrühstück.",
    target: "≈70 g KH gesamt (2 P.) · Protein ≈14 g p. P.",
    ingredients: ["Reis (roh) 90 g", "Milch 300 ml", "Mais 80 g", "Agavendicksaft 1 TL", "Walnüsse 15 g"],
    steps: ["Reis mit Milch 25 Min. weich köcheln.", "Mais unterrühren.", "Mit Agavendicksaft süßen.", "Warm servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Milch pasteurisiert) · Diabetes ✓",
    swaps: "Mais ↔ Erbsen",
    side: "Kräutertee.",
    remind: true,
    riceCooker: { enabled: false },
  },
  {
    id: "so-m",
    title: "Pilz-Quinoa-Salat warm",
    desc: "Warmer Quinoa-Salat mit angebratenen Pilzen und Frühlingszwiebel.",
    story: "Ein leichter, proteinreicher Sonntagslunch.",
    target: "≈74 g KH gesamt (2 P.) · Protein ≈18 g p. P.",
    ingredients: ["Quinoa 150 g", "Champignons 120 g", "Frühlingszwiebel 1 Stück", "Sojasauce 2 EL", "Olivenöl 1 TL"],
    steps: ["Quinoa nach Packung kochen.", "Pilze in Öl anbraten.", "Alles vermengen.", "Mit Sojasauce abschmecken."],
    checks: "Balanced ✓ · Schwangerschaft ✓ · Diabetes ✓ (ballaststoffreiche Quinoa)",
    swaps: "Quinoa ↔ Reis",
    side: "-",
    remind: false,
    riceCooker: { enabled: false },
  },
  {
    id: "so-a",
    title: "Herbstlicher Hähnchen-Kürbis-Eintopf zum Wochenausklang",
    desc: "Wärmender Eintopf mit Hähnchen, Kürbis und Karotten.",
    story: "Ein rundum wärmender Abschluss der Erntewoche.",
    target: "≈86 g KH gesamt (2 P.) · Protein ≈30 g p. P.",
    ingredients: ["Hähnchenbrust 250 g", "Kürbis 150 g", "Karotte 80 g", "Reis (roh) 150 g", "Sojasauce 2 EL"],
    steps: ["Hähnchen anbraten.", "Kürbis und Karotte zugeben, mit Wasser aufgießen, 15 Min. köcheln.", "Mit Sojasauce würzen.", "Mit Reis servieren."],
    checks: "Balanced ✓ · Schwangerschaft ✓ (Hähnchen durchgegart) · Diabetes ✓",
    swaps: "Hähnchen ↔ Kabeljau",
    side: "Warmer Gerstentee.",
    remind: true,
    riceCooker: { enabled: true, program: "Weißreis", water: "1:1,2" },
  }
];

export default function Woche35DE() {
  return (
    <PlanTemplate
      meta={meta}
      data={DATA}
      dayNames={DAY_NAME_DE}
      uiTitles={UI_TITLES}
      subtitle="Kürbis, Mais & Pilze 🌽 · Erntefrisch mild · Balanced"
      heroChips={["Woche 35", "Spätsommer-Ernte", "6× 🍚 Reiskocher"]}
    />
  );
}
