// src/plans/canon.js
// Zusammengeführtes Zutaten-Wörterbuch für die Einkaufslisten-Aggregation (aggregateList in
// PlanTemplate.jsx). Vorher hatte jede Wochendatei ihre eigene Kopie dieser Liste — jetzt einmal
// zentral, Union aller bisher verwendeten Schlüssel über alle 36 Wochen.
export const CANON = {
  // Protein/Fisch/Tofu
  "Aburaage": { group: "Protein/Fisch/Tofu", label: "Aburaage (Fritt. Tofu)", unitDefault: "Stk" },
  "Brie": { group: "Protein/Fisch/Tofu", label: "Brie / Camembert (pasteurisiert)", unitDefault: "g" },
  "Cabanossi": { group: "Protein/Fisch/Tofu", label: "Cabanossi/Räucherwurst", unitDefault: "Stück" },
  "Camembert": { group: "Protein/Fisch/Tofu", label: "Camembert (pasteurisiert)", unitDefault: "Stk" },
  "Cevapcici": { group: "Protein/Fisch/Tofu", label: "Cevapcici (TK)", unitDefault: "Stück" },
  "Cheddar": { group: "Protein/Fisch/Tofu", label: "Cheddar/Gouda (pasteurisiert)", unitDefault: "g" },
  "Cottage Cheese": { group: "Protein/Fisch/Tofu", label: "Körniger Frischkäse", unitDefault: "g" },
  "Eier": { group: "Protein/Fisch/Tofu", label: "Eier", unitDefault: "Stück" },
  "Feta": { group: "Protein/Fisch/Tofu", label: "Feta (pasteurisiert)", unitDefault: "g" },
  "Feta-Käse": { group: "Protein/Fisch/Tofu", label: "Feta (pasteurisiert)", unitDefault: "g" },
  "Fischkuchen": { group: "Protein/Fisch/Tofu", label: "Surimi/Fischkuchen", unitDefault: "g" },
  "Fleischwurst": { group: "Protein/Fisch/Tofu", label: "Fleischwurst/Geflügelwurst", unitDefault: "g" },
  "Frischkäse": { group: "Protein/Fisch/Tofu", label: "Frischkäse", unitDefault: "EL" },
  "Garnelen": { group: "Protein/Fisch/Tofu", label: "Garnelen (geschält)", unitDefault: "g" },
  "Geflügelwurst": { group: "Protein/Fisch/Tofu", label: "Geflügelwurst/Cabanossi", unitDefault: "g" },
  "Goldbrassenfilet": { group: "Protein/Fisch/Tofu", label: "Goldbrassenfilet", unitDefault: "g" },
  "Gouda": { group: "Protein/Fisch/Tofu", label: "Käse/Gouda (pasteurisiert)", unitDefault: "g" },
  "Hähnchenbrust": { group: "Protein/Fisch/Tofu", label: "Hähnchenbrust", unitDefault: "g" },
  "Hähnchenfleisch": { group: "Protein/Fisch/Tofu", label: "Hähnchenfleisch", unitDefault: "g" },
  "Hähnchenflügel": { group: "Protein/Fisch/Tofu", label: "Hähnchenflügel", unitDefault: "g" },
  "Hähnchenhack": { group: "Protein/Fisch/Tofu", label: "Hähnchenhack", unitDefault: "g" },
  "Hähnchenkeule": { group: "Protein/Fisch/Tofu", label: "Hähnchenkeule (o. Knochen)", unitDefault: "g" },
  "Hähnchenkeulen-Fleisch": { group: "Protein/Fisch/Tofu", label: "Hähnchenkeulen-Fleisch", unitDefault: "g" },
  "Hähnchenschenkel": { group: "Protein/Fisch/Tofu", label: "Hähnchenschenkel (o. Knochen)", unitDefault: "g" },
  "Inari-Age": { group: "Protein/Fisch/Tofu", label: "Inari-Age (Tofutaschen)", unitDefault: "Stk" },
  "Jakobsmuscheln": { group: "Protein/Fisch/Tofu", label: "Jakobsmuscheln (TK)", unitDefault: "g" },
  "Kabeljau": { group: "Protein/Fisch/Tofu", label: "Weißfisch (Kabeljau)", unitDefault: "g" },
  "Kabeljaufilet": { group: "Protein/Fisch/Tofu", label: "Kabeljau", unitDefault: "g" },
  "Kochschinken": { group: "Protein/Fisch/Tofu", label: "Kochschinken", unitDefault: "g" },
  "Käse": { group: "Protein/Fisch/Tofu", label: "Käse (Gouda/Cheddar)", unitDefault: "g" },
  "Lachs": { group: "Protein/Fisch/Tofu", label: "Lachs", unitDefault: "g" },
  "Lachsfilet": { group: "Protein/Fisch/Tofu", label: "Lachsfilet", unitDefault: "g" },
  "Lap Cheong": { group: "Protein/Fisch/Tofu", label: "Lap Cheong / Cabanossi", unitDefault: "Stück" },
  "Meeresfrüchte-Mix": { group: "Protein/Fisch/Tofu", label: "Meeresfrüchte-Mix (TK)", unitDefault: "g" },
  "Miesmuscheln": { group: "Protein/Fisch/Tofu", label: "Miesmuscheln", unitDefault: "g" },
  "Mozzarella": { group: "Protein/Fisch/Tofu", label: "Mozzarella (pasteurisiert)", unitDefault: "g" },
  "Pancetta": { group: "Protein/Fisch/Tofu", label: "Pancetta", unitDefault: "g" },
  "Putenbrustaufschnitt": { group: "Protein/Fisch/Tofu", label: "Putenbrustaufschnitt", unitDefault: "Scheiben" },
  "Quark": { group: "Protein/Fisch/Tofu", label: "Quark (Magerstufe)", unitDefault: "EL" },
  "Ricotta": { group: "Protein/Fisch/Tofu", label: "Ricotta (pasteurisiert)", unitDefault: "g" },
  "Rinderhack": { group: "Protein/Fisch/Tofu", label: "Rinderhack (mager)", unitDefault: "g" },
  "Rinderhack mager": { group: "Protein/Fisch/Tofu", label: "Rinderhack (mager)", unitDefault: "g" },
  "Rindersteak": { group: "Protein/Fisch/Tofu", label: "Rindersteak/Minutensteaks", unitDefault: "g" },
  "Rindfleisch": { group: "Protein/Fisch/Tofu", label: "Rindfleisch (Streifen/Scheiben)", unitDefault: "g" },
  "Räucherwurst": { group: "Protein/Fisch/Tofu", label: "Räucherwurst/Cabanossi", unitDefault: "g" },
  "Schinken": { group: "Protein/Fisch/Tofu", label: "Schinken", unitDefault: "Scheiben" },
  "Schinkenwürfel": { group: "Protein/Fisch/Tofu", label: "Schinkenwürfel (gekocht)", unitDefault: "g" },
  "Schweinebauch": { group: "Protein/Fisch/Tofu", label: "Schweinebauch", unitDefault: "g" },
  "Schweinefilet": { group: "Protein/Fisch/Tofu", label: "Schweinefilet", unitDefault: "g" },
  "Schweinefleisch": { group: "Protein/Fisch/Tofu", label: "Schweinefleisch (dünn)", unitDefault: "g" },
  "Schweinegeschnetzeltes": { group: "Protein/Fisch/Tofu", label: "Schweinegeschnetzeltes", unitDefault: "g" },
  "Schweinegulasch": { group: "Protein/Fisch/Tofu", label: "Schweinegulasch/Schulter", unitDefault: "g" },
  "Schweinehack": { group: "Protein/Fisch/Tofu", label: "Schweinehack (mager)", unitDefault: "g" },
  "Schweineschnitzel": { group: "Protein/Fisch/Tofu", label: "Schweineschnitzel (mager)", unitDefault: "g" },
  "Seidentofu": { group: "Protein/Fisch/Tofu", label: "Seidentofu", unitDefault: "g" },
  "Spam": { group: "Protein/Fisch/Tofu", label: "Spam/Kochschinken", unitDefault: "g" },
  "Speckwürfel": { group: "Protein/Fisch/Tofu", label: "Speckwürfel/Pancetta", unitDefault: "g" },
  "Sprotten": { group: "Protein/Fisch/Tofu", label: "Sprotten/Anchovis", unitDefault: "g" },
  "Surimi": { group: "Protein/Fisch/Tofu", label: "Surimi/Flusskrebse", unitDefault: "g" },
  "Tarako": { group: "Protein/Fisch/Tofu", label: "Kabeljaurogen / Fisch", unitDefault: "g" },
  "Thunfisch": { group: "Protein/Fisch/Tofu", label: "Thunfisch (Dose)", unitDefault: "g" },
  "Tofu": { group: "Protein/Fisch/Tofu", label: "Tofu (Natur/Seiden)", unitDefault: "g" },
  "Tofu fest": { group: "Protein/Fisch/Tofu", label: "Tofu (fest)", unitDefault: "g" },
  "Tofu seiden": { group: "Protein/Fisch/Tofu", label: "Tofu (seiden)", unitDefault: "g" },
  "Weißer Fisch": { group: "Protein/Fisch/Tofu", label: "Weißer Fisch (Filet)", unitDefault: "g" },
  "Würstchen": { group: "Protein/Fisch/Tofu", label: "Würstchen/Cabanossi", unitDefault: "g" },

  // Gemüse/Pilze
  "Adzuki": { group: "Gemüse/Pilze", label: "Adzuki (vorgegart)", unitDefault: "g" },
  "Adzukibohnen": { group: "Gemüse/Pilze", label: "Adzukibohnen (vorgekocht)", unitDefault: "g" },
  "Ananas": { group: "Gemüse/Pilze", label: "Ananas (Dose)", unitDefault: "g" },
  "Apfel": { group: "Gemüse/Pilze", label: "Apfel", unitDefault: "Stück" },
  "Aubergine": { group: "Gemüse/Pilze", label: "Aubergine", unitDefault: "g" },
  "Avocado": { group: "Gemüse/Pilze", label: "Avocado", unitDefault: "Stück" },
  "Backpflaumen": { group: "Gemüse/Pilze", label: "Backpflaumen", unitDefault: "Stück" },
  "Bambussprossen": { group: "Gemüse/Pilze", label: "Bambussprossen (Dose)", unitDefault: "g" },
  "Banane": { group: "Gemüse/Pilze", label: "Banane", unitDefault: "Stück" },
  "Basilikum": { group: "Gemüse/Pilze", label: "Basilikum (frisch)", unitDefault: "Bund" },
  "Beeren": { group: "Gemüse/Pilze", label: "Beeren (TK)", unitDefault: "g" },
  "Birne": { group: "Gemüse/Pilze", label: "Birne", unitDefault: "g" },
  "Blaubeeren": { group: "Gemüse/Pilze", label: "Blaubeeren (TK)", unitDefault: "g" },
  "Brokkoli": { group: "Gemüse/Pilze", label: "Brokkoli", unitDefault: "g" },
  "Champignons": { group: "Gemüse/Pilze", label: "Champignons", unitDefault: "g" },
  "Cherrytomaten": { group: "Gemüse/Pilze", label: "Cherrytomaten", unitDefault: "g" },
  "Chinakohl": { group: "Gemüse/Pilze", label: "Chinakohl", unitDefault: "g" },
  "Daikon": { group: "Gemüse/Pilze", label: "Daikon (Rettich)", unitDefault: "g" },
  "Edamame": { group: "Gemüse/Pilze", label: "Edamame (TK)", unitDefault: "g" },
  "Enoki": { group: "Gemüse/Pilze", label: "Enoki-Pilze", unitDefault: "g" },
  "Erbsen": { group: "Gemüse/Pilze", label: "Erbsen (TK)", unitDefault: "g" },
  "Frühlingszwiebel": { group: "Gemüse/Pilze", label: "Frühlingszwiebeln", unitDefault: "g" },
  "Gewürzgurken": { group: "Gemüse/Pilze", label: "Gewürzgurken", unitDefault: "g" },
  "Gurke": { group: "Gemüse/Pilze", label: "Gurke/Salatgurke", unitDefault: "g" },
  "Ingwer": { group: "Gemüse/Pilze", label: "Ingwer", unitDefault: "g" },
  "Karotte": { group: "Gemüse/Pilze", label: "Karotten", unitDefault: "g" },
  "Kartoffel": { group: "Gemüse/Pilze", label: "Kartoffel", unitDefault: "g" },
  "Kichererbsen": { group: "Gemüse/Pilze", label: "Kichererbsen (Dose)", unitDefault: "g" },
  "Kimchi": { group: "Gemüse/Pilze", label: "Kimchi", unitDefault: "g" },
  "Kirschtomaten": { group: "Gemüse/Pilze", label: "Kirschtomaten", unitDefault: "g" },
  "Knoblauch": { group: "Gemüse/Pilze", label: "Knoblauch", unitDefault: "Zehe" },
  "Kohl": { group: "Gemüse/Pilze", label: "Weißkohl/Chinakohl", unitDefault: "g" },
  "Kürbis": { group: "Gemüse/Pilze", label: "Kürbis (Hokkaido)", unitDefault: "g" },
  "Lauch": { group: "Gemüse/Pilze", label: "Lauch", unitDefault: "g" },
  "Mais": { group: "Gemüse/Pilze", label: "Mais & Erbsen (TK)", unitDefault: "g" },
  "Mango": { group: "Gemüse/Pilze", label: "Mango", unitDefault: "Stück" },
  "Miyeok": { group: "Gemüse/Pilze", label: "Miyeok (getrocknet)", unitDefault: "g" },
  "Mu-Err": { group: "Gemüse/Pilze", label: "Mu-Err Pilze (getrocknet)", unitDefault: "g" },
  "Pak Choi": { group: "Gemüse/Pilze", label: "Pak Choi", unitDefault: "g" },
  "Pao Jiang Dou": { group: "Gemüse/Pilze", label: "Pao Jiang Dou (Saure Bohnen)", unitDefault: "g" },
  "Paprika": { group: "Gemüse/Pilze", label: "Paprika", unitDefault: "g" },
  "Passierte Tomaten": { group: "Gemüse/Pilze", label: "Passierte Tomaten", unitDefault: "EL" },
  "Pfirsich": { group: "Gemüse/Pilze", label: "Pfirsich", unitDefault: "Stück" },
  "Pomelo": { group: "Gemüse/Pilze", label: "Pomelo/Grapefruit", unitDefault: "Stück" },
  "Rote Datteln": { group: "Gemüse/Pilze", label: "Rote Datteln (Jujube)", unitDefault: "Stück" },
  "Salat": { group: "Gemüse/Pilze", label: "Gemischter Salat", unitDefault: "g" },
  "Schwarze Bohnen": { group: "Gemüse/Pilze", label: "Schwarze Bohnen", unitDefault: "g" },
  "Sellerie": { group: "Gemüse/Pilze", label: "Staudensellerie", unitDefault: "g" },
  "Shiitake": { group: "Gemüse/Pilze", label: "Pilze (Shiitake/Champignons)", unitDefault: "g" },
  "Sojasprossen": { group: "Gemüse/Pilze", label: "Sojasprossen (frisch)", unitDefault: "g" },
  "Spargel": { group: "Gemüse/Pilze", label: "Spargel (TK/Glas)", unitDefault: "g" },
  "Spinat": { group: "Gemüse/Pilze", label: "Spinat (frisch)", unitDefault: "g" },
  "Süßkartoffel": { group: "Gemüse/Pilze", label: "Süßkartoffel-Püree", unitDefault: "g" },
  "Taro": { group: "Gemüse/Pilze", label: "Taro (Wasserbrotwurzel)", unitDefault: "g" },
  "Tomate": { group: "Gemüse/Pilze", label: "Tomaten (frisch/Kirsch)", unitDefault: "g" },
  "Tomaten": { group: "Gemüse/Pilze", label: "Tomaten (frisch/Kirsch)", unitDefault: "g" },
  "Tomaten passiert": { group: "Gemüse/Pilze", label: "Passierte Tomaten", unitDefault: "ml" },
  "Tomatenmark": { group: "Gemüse/Pilze", label: "Tomatenmark", unitDefault: "EL" },
  "Weißkohl": { group: "Gemüse/Pilze", label: "Weißkohl/Chinakohl", unitDefault: "g" },
  "Weißkohlblätter": { group: "Gemüse/Pilze", label: "Weißkohlblätter", unitDefault: "Stück" },
  "Zha Cai": { group: "Gemüse/Pilze", label: "Zha Cai (Senfknolle)", unitDefault: "g" },
  "Zucchini": { group: "Gemüse/Pilze", label: "Zucchini/Sellerie", unitDefault: "g" },
  "Zwiebel": { group: "Gemüse/Pilze", label: "Zwiebeln", unitDefault: "g" },

  // Reis/Nudeln/Sättigung
  "Bao Buns": { group: "Reis/Nudeln/Sättigung", label: "Bao Buns (TK)", unitDefault: "Stück" },
  "Blätterteig": { group: "Reis/Nudeln/Sättigung", label: "Blätterteig (Rolle)", unitDefault: "Stück" },
  "Brauner Reis": { group: "Reis/Nudeln/Sättigung", label: "Brauner Reis (roh)", unitDefault: "g" },
  "Chow Mein Nudeln": { group: "Reis/Nudeln/Sättigung", label: "Chow Mein / Mie", unitDefault: "g" },
  "Cornflakes": { group: "Reis/Nudeln/Sättigung", label: "Cornflakes (ungesüßt)", unitDefault: "g" },
  "Fleckerl": { group: "Reis/Nudeln/Sättigung", label: "Nudeln (Fleckerl)", unitDefault: "g" },
  "Glasnudeln": { group: "Reis/Nudeln/Sättigung", label: "Glasnudeln", unitDefault: "g" },
  "Gnocchi": { group: "Reis/Nudeln/Sättigung", label: "Gnocchi", unitDefault: "g" },
  "Goldhirse": { group: "Reis/Nudeln/Sättigung", label: "Goldhirse", unitDefault: "g" },
  "Haferflocken": { group: "Reis/Nudeln/Sättigung", label: "Haferflocken zart", unitDefault: "g" },
  "Hörnchennudeln": { group: "Reis/Nudeln/Sättigung", label: "Hörnchennudeln", unitDefault: "g" },
  "Kartoffeln": { group: "Reis/Nudeln/Sättigung", label: "Kartoffeln", unitDefault: "g" },
  "Kartoffelrösti": { group: "Reis/Nudeln/Sättigung", label: "Kartoffelrösti (TK)", unitDefault: "Stück" },
  "Kinako": { group: "Reis/Nudeln/Sättigung", label: "Kinako (Sojabohnenmehl)", unitDefault: "EL" },
  "Knäckebrot": { group: "Reis/Nudeln/Sättigung", label: "Knäckebrot", unitDefault: "Scheiben" },
  "Kurze Nudeln": { group: "Reis/Nudeln/Sättigung", label: "Kurze Nudeln (Penne/Makkaroni)", unitDefault: "g" },
  "Maisstärke": { group: "Reis/Nudeln/Sättigung", label: "Maisstärke/Katakuriko", unitDefault: "EL" },
  "Makkaroni": { group: "Reis/Nudeln/Sättigung", label: "Makkaroni (kurz)", unitDefault: "g" },
  "Mehl": { group: "Reis/Nudeln/Sättigung", label: "Mehl", unitDefault: "g" },
  "Nori-Blätter": { group: "Reis/Nudeln/Sättigung", label: "Nori-Blätter", unitDefault: "Stück" },
  "Nudeln": { group: "Reis/Nudeln/Sättigung", label: "Nudeln", unitDefault: "g" },
  "Paniermehl": { group: "Reis/Nudeln/Sättigung", label: "Paniermehl/Panko", unitDefault: "g" },
  "Panko": { group: "Reis/Nudeln/Sättigung", label: "Panko/Paniermehl", unitDefault: "g" },
  "Quinoa": { group: "Reis/Nudeln/Sättigung", label: "Quinoa", unitDefault: "g" },
  "Reis": { group: "Reis/Nudeln/Sättigung", label: "Reis (roh/gekocht)", unitDefault: "g" },
  "Reismehl": { group: "Reis/Nudeln/Sättigung", label: "Reismehl", unitDefault: "g" },
  "Reisnudeln": { group: "Reis/Nudeln/Sättigung", label: "Reisnudeln (breit)", unitDefault: "g" },
  "Reispapier": { group: "Reis/Nudeln/Sättigung", label: "Reispapier", unitDefault: "Blatt" },
  "Risottoreis": { group: "Reis/Nudeln/Sättigung", label: "Risottoreis", unitDefault: "g" },
  "Rote Linsen": { group: "Reis/Nudeln/Sättigung", label: "Rote Linsen", unitDefault: "g" },
  "Soba": { group: "Reis/Nudeln/Sättigung", label: "Soba-Nudeln", unitDefault: "g" },
  "Spaghetti": { group: "Reis/Nudeln/Sättigung", label: "Spaghetti", unitDefault: "g" },
  "Suppennudeln": { group: "Reis/Nudeln/Sättigung", label: "Suppennudeln", unitDefault: "g" },
  "Süßkartoffel-Glasnudeln": { group: "Reis/Nudeln/Sättigung", label: "Süßkartoffel-Glasnudeln (Dangmyeon)", unitDefault: "g" },
  "Süßkartoffel-Gnocchi": { group: "Reis/Nudeln/Sättigung", label: "Süßkartoffel-Gnocchi", unitDefault: "g" },
  "Toastbrot": { group: "Reis/Nudeln/Sättigung", label: "Toastbrot / Vollkorn", unitDefault: "Scheiben" },
  "Tteokbokki": { group: "Reis/Nudeln/Sättigung", label: "Reiskuchen (Tteok)", unitDefault: "g" },
  "Udon": { group: "Reis/Nudeln/Sättigung", label: "Udon-Nudeln", unitDefault: "g" },
  "Vollkorn-Bagel": { group: "Reis/Nudeln/Sättigung", label: "Vollkorn-Bagel", unitDefault: "Stück" },
  "Vollkorn-Nudeln": { group: "Reis/Nudeln/Sättigung", label: "Vollkorn-Nudeln", unitDefault: "g" },
  "Vollkorn-Penne": { group: "Reis/Nudeln/Sättigung", label: "Vollkorn-Penne", unitDefault: "g" },
  "Vollkorn-Risottoreis": { group: "Reis/Nudeln/Sättigung", label: "Risottoreis", unitDefault: "g" },
  "Vollkorn-Toast": { group: "Reis/Nudeln/Sättigung", label: "Vollkorn-Toast", unitDefault: "Scheiben" },
  "Vollkorn-Tortillas": { group: "Reis/Nudeln/Sättigung", label: "Tortilla-Wraps", unitDefault: "Stück" },
  "Vollkornbrot": { group: "Reis/Nudeln/Sättigung", label: "Vollkornbrot", unitDefault: "Scheiben" },
  "Vollkornmehl": { group: "Reis/Nudeln/Sättigung", label: "Vollkornmehl", unitDefault: "g" },
  "Vollkorn‑Risottoreis": { group: "Reis/Nudeln/Sättigung", label: "Vollkorn-Risottoreis", unitDefault: "g" },
  "Wan-Tan-Blätter": { group: "Reis/Nudeln/Sättigung", label: "Wan-Tan-Blätter", unitDefault: "Stück" },
  "Weichweizengrieß": { group: "Reis/Nudeln/Sättigung", label: "Grieß", unitDefault: "g" },
  "Weizennudeln": { group: "Reis/Nudeln/Sättigung", label: "Weizennudeln/Yakisoba", unitDefault: "g" },
  "Weiße Bohnen": { group: "Reis/Nudeln/Sättigung", label: "Weiße Bohnen (Dose)", unitDefault: "g" },

  // Algen/Brühen/Würze
  "Agavendicksaft": { group: "Algen/Brühen/Würze", label: "Agavendicksaft", unitDefault: "EL" },
  "Ajvar": { group: "Algen/Brühen/Würze", label: "Ajvar (mild)", unitDefault: "EL" },
  "Aonori": { group: "Algen/Brühen/Würze", label: "Aonori (Algenflocken)", unitDefault: "Prise" },
  "Austernsauce": { group: "Algen/Brühen/Würze", label: "Austernsauce", unitDefault: "EL" },
  "Backpulver": { group: "Algen/Brühen/Würze", label: "Backpulver", unitDefault: "TL" },
  "Balsamico-Essig": { group: "Algen/Brühen/Würze", label: "Balsamico-Essig", unitDefault: "EL" },
  "Brühwürfel": { group: "Algen/Brühen/Würze", label: "Brühwürfel", unitDefault: "Stück" },
  "Butter": { group: "Algen/Brühen/Würze", label: "Butter", unitDefault: "g" },
  "Char Siu Sauce": { group: "Algen/Brühen/Würze", label: "Char Siu/Hoisin", unitDefault: "EL" },
  "Chia-Samen": { group: "Algen/Brühen/Würze", label: "Chia-Samen", unitDefault: "EL" },
  "Chili-Öl": { group: "Algen/Brühen/Würze", label: "Crispy Chili Oil", unitDefault: "EL" },
  "Curry-Block": { group: "Algen/Brühen/Würze", label: "Curry-Block (Japanisch)", unitDefault: "Würfel" },
  "Curry-Roux": { group: "Algen/Brühen/Würze", label: "Curry-Roux", unitDefault: "Stk" },
  "Currypulver": { group: "Algen/Brühen/Würze", label: "Currypulver", unitDefault: "TL" },
  "Dashi": { group: "Algen/Brühen/Würze", label: "Dashi/Fischbrühe", unitDefault: "ml" },
  "Dill": { group: "Algen/Brühen/Würze", label: "Dill (frisch)", unitDefault: "EL" },
  "Doenjang": { group: "Algen/Brühen/Würze", label: "Doenjang", unitDefault: "g" },
  "Erdnussbutter": { group: "Algen/Brühen/Würze", label: "Erdnussbutter", unitDefault: "EL" },
  "Erdnüsse": { group: "Algen/Brühen/Würze", label: "Erdnüsse", unitDefault: "g" },
  "Furikake": { group: "Algen/Brühen/Würze", label: "Furikake", unitDefault: "g" },
  "Fünf-Gewürze-Pulver": { group: "Algen/Brühen/Würze", label: "Fünf-Gewürze-Pulver", unitDefault: "TL" },
  "Gemüsebrühe": { group: "Algen/Brühen/Würze", label: "Gemüsebrühe", unitDefault: "ml" },
  "Gochujang": { group: "Algen/Brühen/Würze", label: "Gochujang", unitDefault: "EL" },
  "Hefe": { group: "Algen/Brühen/Würze", label: "Trockenhefe", unitDefault: "g" },
  "Hoisin-Sauce": { group: "Algen/Brühen/Würze", label: "Hoisin-Sauce", unitDefault: "EL" },
  "Honig": { group: "Algen/Brühen/Würze", label: "Honig/Zucker", unitDefault: "TL" },
  "Hühnerbrühe": { group: "Algen/Brühen/Würze", label: "Hühnerbrühe", unitDefault: "ml" },
  "Italienische Kräuter": { group: "Algen/Brühen/Würze", label: "Italienische Kräuter", unitDefault: "TL" },
  "Joghurt": { group: "Algen/Brühen/Würze", label: "Joghurt (Griechisch)", unitDefault: "EL" },
  "Kakaonibs": { group: "Algen/Brühen/Würze", label: "Kakaonibs", unitDefault: "EL" },
  "Kardamom": { group: "Algen/Brühen/Würze", label: "Kardamom", unitDefault: "TL" },
  "Ketchup": { group: "Algen/Brühen/Würze", label: "Ketchup", unitDefault: "EL" },
  "Kochsahne": { group: "Algen/Brühen/Würze", label: "Kochsahne", unitDefault: "ml" },
  "Kokosmilch": { group: "Algen/Brühen/Würze", label: "Kokosmilch (fettarm)", unitDefault: "ml" },
  "Kurkuma": { group: "Algen/Brühen/Würze", label: "Kurkuma", unitDefault: "TL" },
  "Mandelmus": { group: "Algen/Brühen/Würze", label: "Mandelmus", unitDefault: "EL" },
  "Mandeln": { group: "Algen/Brühen/Würze", label: "Mandeln", unitDefault: "g" },
  "Matcha": { group: "Algen/Brühen/Würze", label: "Matcha-Pulver", unitDefault: "TL" },
  "Mayo": { group: "Algen/Brühen/Würze", label: "Mayo (Tube)", unitDefault: "EL" },
  "Mayonnaise": { group: "Algen/Brühen/Würze", label: "Mayo (Tube, pasteurisiert)", unitDefault: "EL" },
  "Milch": { group: "Algen/Brühen/Würze", label: "Milch", unitDefault: "ml" },
  "Mirin": { group: "Algen/Brühen/Würze", label: "Mirin", unitDefault: "EL" },
  "Miso hell": { group: "Algen/Brühen/Würze", label: "Miso hell", unitDefault: "g" },
  "Miso-Paste": { group: "Algen/Brühen/Würze", label: "Miso-Paste", unitDefault: "EL" },
  "Nori": { group: "Algen/Brühen/Würze", label: "Nori-Blätter/Brösel", unitDefault: "Stk" },
  "Okonomiyaki-Sauce": { group: "Algen/Brühen/Würze", label: "Okonomiyaki-Sauce", unitDefault: "EL" },
  "Olivenöl": { group: "Algen/Brühen/Würze", label: "Olivenöl", unitDefault: "EL" },
  "Paprikapulver": { group: "Algen/Brühen/Würze", label: "Paprikapulver", unitDefault: "TL" },
  "Parmesan": { group: "Algen/Brühen/Würze", label: "Parmesan (pasteur.)", unitDefault: "g" },
  "Pesto": { group: "Algen/Brühen/Würze", label: "Pesto (Glas)", unitDefault: "EL" },
  "Reisessig": { group: "Algen/Brühen/Würze", label: "Reisessig", unitDefault: "EL" },
  "Rinderbrühe": { group: "Algen/Brühen/Würze", label: "Rinderbrühe", unitDefault: "ml" },
  "Rosmarin": { group: "Algen/Brühen/Würze", label: "Rosmarin", unitDefault: "TL" },
  "Rotweinessig": { group: "Algen/Brühen/Würze", label: "Rotweinessig", unitDefault: "EL" },
  "Sahne": { group: "Algen/Brühen/Würze", label: "Sahne", unitDefault: "ml" },
  "Schwarze Bohnenpaste": { group: "Algen/Brühen/Würze", label: "Schwarze Bohnenpaste", unitDefault: "g" },
  "Schwarze Bohnensauce": { group: "Algen/Brühen/Würze", label: "Schwarze Bohnensauce", unitDefault: "EL" },
  "Schwarze Sesampaste": { group: "Algen/Brühen/Würze", label: "Schwarze Sesampaste", unitDefault: "EL" },
  "Sesam": { group: "Algen/Brühen/Würze", label: "Sesam", unitDefault: "TL" },
  "Sesamöl": { group: "Algen/Brühen/Würze", label: "Sesamöl", unitDefault: "TL" },
  "Sojamilch": { group: "Algen/Brühen/Würze", label: "Sojamilch (ungezuckert)", unitDefault: "ml" },
  "Sojasauce": { group: "Algen/Brühen/Würze", label: "Sojasauce", unitDefault: "EL" },
  "Sojasauce natriumarm": { group: "Algen/Brühen/Würze", label: "Sojasauce (natriumarm)", unitDefault: "ml" },
  "Speiseöl": { group: "Algen/Brühen/Würze", label: "Speiseöl", unitDefault: "EL" },
  "Sriracha": { group: "Algen/Brühen/Würze", label: "Sriracha (mild)/Mayo", unitDefault: "EL" },
  "Sriracha-Sauce": { group: "Algen/Brühen/Würze", label: "Sriracha (mild)", unitDefault: "TL" },
  "Sternanis": { group: "Algen/Brühen/Würze", label: "Sternanis", unitDefault: "Stück" },
  "Süße Bohnenpaste": { group: "Algen/Brühen/Würze", label: "Süße Bohnenpaste/Hoisin", unitDefault: "EL" },
  "Tahini": { group: "Algen/Brühen/Würze", label: "Tahini/Sesampaste", unitDefault: "EL" },
  "Teriyaki-Sauce": { group: "Algen/Brühen/Würze", label: "Teriyaki-Sauce", unitDefault: "EL" },
  "Tom Yum Paste": { group: "Algen/Brühen/Würze", label: "Tom Yum Paste", unitDefault: "EL" },
  "Tonkatsu-Sauce": { group: "Algen/Brühen/Würze", label: "Tonkatsu-Sauce", unitDefault: "EL" },
  "Walnüsse": { group: "Algen/Brühen/Würze", label: "Walnüsse", unitDefault: "g" },
  "Yuzu-Sirup": { group: "Algen/Brühen/Würze", label: "Yuzu-Sirup (Yuja-cha)", unitDefault: "EL" },
  "Zimt": { group: "Algen/Brühen/Würze", label: "Zimt", unitDefault: "TL" },
  "Zitrone": { group: "Algen/Brühen/Würze", label: "Zitrone", unitDefault: "TL" },
  "Zucker": { group: "Algen/Brühen/Würze", label: "Zucker", unitDefault: "TL" },

};
