// src/plans/coldDishes.ts
// "Kalte Gerichte" — eigener Bereich, kein Preppen: fertig-kalt servierte Salate/Beilagen aus
// China/Japan/Korea (涼拌/漬け物/banchan), meist frisch vorzubereiten statt einzufrieren.
// Gleiche Feld-Struktur wie PrepRecipe (Karten-UI teilt sich Komponente/CSS), aber ohne
// "category" — diese Datei ist nur ein einziger Bereich, keine Tab-Unterscheidung nötig.

export type ColdDish = {
  id: string;
  /** Kapitel-Gruppierung, z.B. "Salat/Kalte Gerichte", "Eingelegt/Tsukemono", "Banchan". */
  type: string;
  emoji: string;
  title: string;
  desc: string;
  batchSize: string;
  ingredients: string[];
  steps: string[];
  freezeMethod: string;
  freezerLife: string;
  reheat: string;
  tags: string[];
};

export const COLD_DISHES: ColdDish[] = [
  {
    id: "china-salat-gurken-smashed",
    type: "Salat/Kalte Gerichte",
    emoji: "🥒",
    title: "Smashed-Gurken-Salat, mild sauer-würzig (拍黃瓜)",
    desc: "Klassiker der chinesischen Küche — die Gurke wird plattgeklopft statt geschnitten, nimmt dadurch die Sauce viel besser auf. Für Meal-Prep: Gurke und Dressing getrennt vorbereiten, erst vor dem Servieren mischen.",
    batchSize: "Ergibt 4 Portionen (Dressing separat haltbar)",
    ingredients: [
      "Salatgurke 2 Stück",
      "Knoblauch 2 Zehen",
      "Reisessig mild 2 EL",
      "Sojasauce natriumarm 2 EL",
      "Sesamöl 1 TL",
      "Zucker 1 TL (statt der sonst üblichen 1–2 EL)",
    ],
    steps: [
      "Gurken mit der Breitseite eines Messers plattklopfen, grob zerteilen, kurz salzen, überschüssiges Wasser abgießen.",
      "Dressing aus Knoblauch, Essig, Sojasauce, Sesamöl und Zucker separat verrühren.",
      "Gurken und Dressing getrennt im Kühlschrank aufbewahren.",
      "Erst kurz vor dem Servieren vermengen, damit die Gurke knackig bleibt.",
    ],
    freezeMethod: "Kein Einfrieren — Gurke und Dressing getrennt im Kühlschrank vorbereiten, bis zu 3 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren — Gurke und Dressing erst kurz vor dem Essen vermengen, sonst wird der Salat wässrig.",
    tags: ["China", "Salat", "Low Sugar ✓ (Zucker reduziert)", "Vegetarisch"],
  },
  {
    id: "china-salat-holzohrpilz",
    type: "Salat/Kalte Gerichte",
    emoji: "🍄",
    title: "Kalter Holzohrpilz-Salat, sauer-würzig (涼拌木耳)",
    desc: "Knackige schwarze Pilze in einer sauer-würzigen Sauce — proteinarm, aber ballaststoffreich, guter Beilagensalat.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Getrocknete Holzohrpilze (Mu-Err) 30 g",
      "Knoblauch 2 Zehen",
      "Reisessig mild 2 EL",
      "Sojasauce natriumarm 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Pilze in warmem Wasser 20 Min. einweichen, bis weich, gründlich abspülen, klein reißen.",
      "2 Min. blanchieren (wichtig — Holzohrpilze sollten nicht roh gegessen werden), abschrecken.",
      "Dressing aus Knoblauch, Essig, Sojasauce und Sesamöl separat verrühren.",
      "Pilze und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — blanchierte Pilze und Dressing getrennt im Kühlschrank, bis zu 3 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch", "Holzohrpilze immer blanchiert servieren, nie roh"],
  },
  {
    id: "china-salat-rotkohl-apfel",
    type: "Salat/Kalte Gerichte",
    emoji: "🍎",
    title: "Rotkohl-Apfel-Salat, knackig (紫甘藍拌蘋果絲)",
    desc: "Fein geraspelter Rotkohl mit Apfel — süß-säuerlich, hoher Vitamin-C-Gehalt, hält sich roh mehrere Tage im Kühlschrank.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Rotkohl 300 g",
      "Apfel 1 Stück",
      "Reisessig mild 2 EL",
      "Zucker 1 TL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Rotkohl und Apfel sehr fein raspeln/hobeln (Apfel mit etwas Zitronensaft vor dem Braunwerden schützen).",
      "Dressing aus Essig, Zucker und Sesamöl separat verrühren.",
      "Kohl und Apfel können bereits Stunden vorher geraspelt werden.",
      "Dressing erst kurz vor dem Servieren untermischen.",
    ],
    freezeMethod: "Kein Einfrieren — geraspelte Zutaten und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren.",
    tags: ["China", "Salat", "Vegetarisch", "Low Sugar ✓"],
  },
  {
    id: "china-salat-haehnchenbrust-gerissen",
    type: "Salat/Kalte Gerichte",
    emoji: "🍗",
    title: "Handgezupfte Hähnchenbrust-Salat (手撕雞胸肉)",
    desc: "Pochierte, in Fasern gezupfte Hähnchenbrust mit einer würzigen Sauce — proteinreicher Meal-Prep-Salat, gut vorzukochen.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hähnchenbrust 400 g",
      "Frühlingszwiebel 2 Stück",
      "Ingwer 10 g",
      "Sojasauce natriumarm 2 EL",
      "Sesamöl 1 TL",
      "Reisessig mild 1 EL",
    ],
    steps: [
      "Hähnchenbrust mit Ingwer und Frühlingszwiebel in Wasser pochieren, bis vollständig durchgegart (kein Rosa mehr, Kerntemperatur prüfen).",
      "Abkühlen lassen, in feine Fasern zupfen.",
      "Dressing aus Sojasauce, Sesamöl und Essig separat verrühren.",
      "Gezupftes Hähnchen bis zu 3 Tage im Kühlschrank aufbewahren (auch portionsweise einfrierbar), Dressing erst vor dem Servieren untermischen.",
    ],
    freezeMethod: "Gegart und gezupft, portionsweise im Beutel — Dressing separat, nicht mit einfrieren.",
    freezerLife: "bis zu 2 Monate (gegartes Hähnchen)",
    reheat: "Im Kühlschrank auftauen, kalt mit frischem Dressing servieren (nicht erneut erhitzen — bleibt so am saftigsten).",
    tags: ["China", "Salat", "Diabetes: mageres Protein, proteinreich"],
  },
  {
    id: "china-salat-algen-streifen",
    type: "Salat/Kalte Gerichte",
    emoji: "🌊",
    title: "Kalter Algen-Streifen-Salat, mild (涼拌海帶絲)",
    desc: "Fein geschnittene Algen-/Kombu-Streifen in einer leichten Sauce — jodreich, daher in Maßen genießen, besonders in der Schwangerschaft.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Getrocknete Algenstreifen (Kombu/Wakame) 30 g",
      "Knoblauch 1 Zehe",
      "Reisessig mild 2 EL",
      "Sojasauce natriumarm 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Algen nach Packungsanweisung einweichen/blanchieren, bis weich, gründlich abspülen (reduziert Jod- und Salzgehalt).",
      "Dressing aus Knoblauch, Essig, Sojasauce und Sesamöl separat verrühren.",
      "Algen und Dressing getrennt im Kühlschrank aufbewahren.",
      "Erst kurz vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — eingeweichte Algen und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen vermengen.",
    tags: ["China", "Salat", "Jod: sparsam dosieren, in Schwangerschaft nur kleine Portion", "Vegetarisch"],
  },
  {
    id: "china-salat-austernpilz",
    type: "Salat/Kalte Gerichte",
    emoji: "🍄",
    title: "Kalter Austernpilz-Salat, würzig (涼拌杏鮑菇)",
    desc: "Kurz gekochte King-Oyster-Pilze in einer würzigen Sesam-Sojasauce — fleischige Textur, macht auch ohne Fleisch richtig satt.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "King-Oyster-Pilze (Austernpilze) 300 g",
      "Knoblauch 2 Zehen",
      "Sojasauce natriumarm 2 EL",
      "Reisessig mild 1 EL",
      "Sesamöl 1 TL",
      "Frühlingszwiebel 1 Stück",
    ],
    steps: [
      "Pilze in mundgerechte Streifen reißen (nicht schneiden — reißen ergibt bessere Textur).",
      "5–7 Min. in kochendem Wasser garen, bis weich, abtropfen lassen und auskühlen.",
      "Dressing aus Knoblauch, Sojasauce, Essig und Sesamöl separat verrühren.",
      "Pilze und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen, mit Frühlingszwiebel bestreuen.",
    ],
    freezeMethod: "Kein Einfrieren — gegarte Pilze und Dressing getrennt im Kühlschrank, bis zu 3 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch"],
  },
  {
    id: "china-salat-tofustreifen",
    type: "Salat/Kalte Gerichte",
    emoji: "🧊",
    title: "Kalter Tofu-Streifen-Salat (涼拌豆腐絲)",
    desc: "Feine Tofu-Streifen (getrockneter/gepresster Tofu, nicht Seidentofu) in einer Sesam-Sojasauce — proteinreich, klassischer Beilagensalat.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Getrocknete Tofu-Streifen (豆腐絲) 250 g",
      "Karotte, julienne 50 g",
      "Knoblauch 1 Zehe",
      "Sojasauce natriumarm 1 EL",
      "Sesamöl 1 TL",
      "Reisessig mild 1 EL",
    ],
    steps: [
      "Tofu-Streifen kurz blanchieren (1–2 Min.), abschrecken.",
      "Karotte fein julienne schneiden.",
      "Dressing aus Knoblauch, Sojasauce, Sesamöl und Essig separat verrühren.",
      "Tofu-Streifen, Karotte und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — blanchierte Tofu-Streifen und Dressing getrennt im Kühlschrank, bis zu 3 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen vermengen.",
    tags: ["China", "Salat", "Vegetarisch", "Diabetes: proteinreich, wenig Kohlenhydrate"],
  },
  {
    id: "china-salat-kartoffelstreifen-sauerscharf",
    type: "Salat/Kalte Gerichte",
    emoji: "🥔",
    title: "Sauer-scharfe Kartoffelstreifen, kurz blanchiert (炝拌土豆絲)",
    desc: "Kartoffeln werden in feine Streifen geschnitten statt gestampft — kurz blanchiert bleiben sie knackig statt matschig, klassischer nordchinesischer Beilagensalat.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Kartoffeln, festkochend 400 g",
      "Knoblauch 2 Zehen",
      "Reisessig mild 2 EL",
      "Sojasauce natriumarm 1 EL",
      "Sesamöl 1 TL",
      "Chiliflocken 1 Prise (optional)",
    ],
    steps: [
      "Kartoffeln schälen, in sehr feine Streifen schneiden, in kaltem Wasser die Stärke auswaschen (wichtig für die knackige Textur).",
      "Nur 60–90 Sek. in kochendem Wasser blanchieren, sofort in Eiswasser abschrecken.",
      "Dressing aus Knoblauch, Essig, Sojasauce, Sesamöl und optional Chiliflocken separat verrühren.",
      "Kartoffelstreifen und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — blanchierte Kartoffelstreifen und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen vermengen — je länger die Streifen im Dressing liegen, desto weicher werden sie.",
    tags: ["China", "Salat", "Vegetarisch", "Diabetes: Portion beachten (stärkehaltig)"],
  },
  {
    id: "china-salat-grosser-gemischter",
    type: "Salat/Kalte Gerichte",
    emoji: "🥗",
    title: "Großer gemischter Salat, nordchinesisch (大拌菜)",
    desc: "Bunte Mischung aus rohem und blanchiertem Gemüse mit einer einfachen Sojasauce-Sesam-Vinaigrette — der Salat, den es in nordchinesischen Restaurants als Beilage zu fast allem gibt.",
    batchSize: "Ergibt 4–6 Portionen",
    ingredients: [
      "Eisbergsalat oder Chinakohl 200 g",
      "Gurke 1 Stück",
      "Kirschtomaten 150 g",
      "Frühlingszwiebel 2 Stück",
      "Koriander 1 Handvoll (optional)",
      "Sojasauce natriumarm 2 EL",
      "Reisessig mild 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Alles Gemüse grob in mundgerechte Stücke schneiden/reißen.",
      "Dressing aus Sojasauce, Essig und Sesamöl separat verrühren.",
      "Geschnittenes Gemüse getrennt vom Dressing im Kühlschrank aufbewahren — Salat und Tomaten setzen sonst Wasser ab.",
      "Erst direkt vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — Gemüse und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst direkt vor dem Essen vermengen.",
    tags: ["China", "Salat", "Vegetarisch"],
  },
  {
    id: "china-salat-caixin-blanchiert",
    type: "Salat/Kalte Gerichte",
    emoji: "🥦",
    title: "Kalter Cai-Xin-Salat, mild (涼拌菜心)",
    desc: "Blanchierter chinesischer Blattkohl (Cai Xin/Choy Sum) mit einer leichten Knoblauch-Sojasauce — schnelle, gemüsereiche Beilage.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Cai Xin (Choy Sum) 400 g",
      "Knoblauch 2 Zehen",
      "Sojasauce natriumarm 1 EL",
      "Sesamöl 1 TL",
      "Röstsesam 1 TL",
    ],
    steps: [
      "Cai Xin waschen, in kochendem Wasser 1–2 Min. blanchieren, bis leuchtend grün.",
      "Sofort in Eiswasser abschrecken, abtropfen lassen.",
      "Dressing aus Knoblauch, Sojasauce und Sesamöl separat verrühren.",
      "Blanchiertes Gemüse und Dressing getrennt im Kühlschrank aufbewahren, mit Sesam bestreut servieren.",
    ],
    freezeMethod: "Kein Einfrieren — blanchiertes Gemüse und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen vermengen.",
    tags: ["China", "Salat", "Vegetarisch"],
  },
  {
    id: "china-salat-rind-koriander-ananas",
    type: "Salat/Kalte Gerichte",
    emoji: "🍍",
    title: "Rindfleisch-Salat mit Koriander und Ananas (香菜菠蘿拌牛肉)",
    desc: "Ungewöhnliche, aber beliebte Kombination: dünn geschnittenes gegartes Rind mit frischer Ananas und Koriander — süß-herzhaft, erfrischend.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Rindfleisch (mager, kurzgebraten) 300 g",
      "Frische Ananas 200 g",
      "Koriander 1 Handvoll",
      "Sojasauce natriumarm 1 EL",
      "Reisessig mild 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Rindfleisch scharf anbraten, auskühlen lassen, in dünne Scheiben schneiden.",
      "Ananas in kleine Stücke schneiden, Koriander grob hacken.",
      "Dressing aus Sojasauce, Essig und Sesamöl separat verrühren.",
      "Rind, Ananas, Koriander und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Gegartes Rind portionsweise einfrierbar — Ananas, Koriander und Dressing immer frisch, nicht mit einfrieren.",
    freezerLife: "Rind bis zu 2 Monate, restliche Zutaten nicht einfrieren",
    reheat: "Rind im Kühlschrank auftauen, kalt mit frischer Ananas, Koriander und Dressing servieren.",
    tags: ["China", "Salat", "Diabetes: mageres Protein, Frucht in Maßen"],
  },
  {
    id: "china-salat-spinat-enoki",
    type: "Salat/Kalte Gerichte",
    emoji: "🍃",
    title: "Spinat mit Enoki-Pilzen, Sesam-Sojasauce (菠菜拌金針菇)",
    desc: "Klassiker für die schnelle Kombi-Platte — beides nur kurz blanchiert, in 10 Minuten fertig, passt zu fast jedem anderen kalten Gericht dazu.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Blattspinat 250 g",
      "Enoki-Pilze (Nadelpilze) 150 g",
      "Knoblauch 1 Zehe",
      "Sojasauce natriumarm 1 EL",
      "Reisessig mild 1 TL",
      "Sesamöl 1 TL",
      "Geröstete Sesamsamen 1 TL",
    ],
    steps: [
      "Enoki-Wurzelenden abschneiden, Büschel auseinanderzupfen.",
      "Spinat und Enoki nacheinander je 1–2 Min. in kochendem Wasser blanchieren, abschrecken, gut ausdrücken.",
      "Dressing aus Knoblauch, Sojasauce, Essig und Sesamöl separat verrühren.",
      "Spinat, Enoki und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen und mit Sesam bestreuen.",
    ],
    freezeMethod: "Kein Einfrieren — blanchiertes Gemüse und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch", "Schwangerschaft: vollständig blanchiert"],
  },
  {
    id: "china-salat-weisskohl-essig",
    type: "Salat/Kalte Gerichte",
    emoji: "🥬",
    title: "Knackiger Weißkohl-Salat, süß-sauer (醋溜白菜絲)",
    desc: "Nur rohe Zutaten, kein Kochtopf nötig — Kohl wird kurz gesalzen statt gegart, bleibt dadurch besonders knackig. Fertig in 5 Minuten aktive Zeit.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Weißkohl (oder Spitzkohl) 400 g",
      "Karotte 1 Stück",
      "Salz 1/2 TL (zum Ziehenlassen)",
      "Reisessig mild 2 EL",
      "Sojasauce natriumarm 1 TL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Kohl und Karotte in feine Streifen schneiden, mit Salz vermengen, 15 Min. ziehen lassen.",
      "Austretendes Wasser gut abgießen und ausdrücken.",
      "Dressing aus Essig, Sojasauce und Sesamöl separat verrühren.",
      "Kohlmischung und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — hält roh mariniert bis zu 3 Tage im Kühlschrank.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch", "Low Sugar ✓"],
  },
  {
    id: "china-salat-fuzhu-sellerie",
    type: "Salat/Kalte Gerichte",
    emoji: "🥢",
    title: "Getrockneter Tofuhaut-Salat mit Sellerie (芹菜拌腐竹)",
    desc: "Proteinreiche Beilage, die sich gut mit anderen Salaten kombinieren lässt — Fuzhu (getrocknete Tofuhaut) einweichen, kurz blanchieren, fertig.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Getrocknete Tofuhaut (腐竹/Fuzhu) 80 g",
      "Staudensellerie 3 Stangen",
      "Knoblauch 1 Zehe",
      "Sojasauce natriumarm 1 EL",
      "Reisessig mild 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Fuzhu mind. 2 Std. (oder über Nacht) in kaltem Wasser einweichen, bis weich, dann in mundgerechte Stücke schneiden.",
      "Fuzhu und Sellerie je 1–2 Min. blanchieren, abschrecken, abtropfen lassen.",
      "Dressing aus Knoblauch, Sojasauce, Essig und Sesamöl separat verrühren.",
      "Fuzhu, Sellerie und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — eingeweichtes/blanchiertes Fuzhu und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch", "Diabetes: proteinreich"],
  },
  {
    id: "china-salat-brokkoli-knoblauch",
    type: "Salat/Kalte Gerichte",
    emoji: "🥦",
    title: "Brokkoli in Knoblauch-Sojasauce, kalt (蒜蓉西蘭花)",
    desc: "Einfachste aller Kombinationen: Brokkoli blanchieren, Sauce drüber — ballaststoffreiches Standbein für jede Kombi-Platte.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Brokkoli 400 g",
      "Knoblauch 2 Zehen",
      "Sojasauce natriumarm 1 EL",
      "Sesamöl 1 TL",
      "Geröstete Sesamsamen 1 TL",
    ],
    steps: [
      "Brokkoli in Röschen teilen, 2–3 Min. blanchieren, bis knackig-weich, abschrecken.",
      "Dressing aus Knoblauch, Sojasauce und Sesamöl separat verrühren.",
      "Brokkoli und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen und mit Sesam bestreuen.",
    ],
    freezeMethod: "Kein Einfrieren — blanchierter Brokkoli und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch", "Diabetes: ballaststoffreich"],
  },
  {
    id: "china-salat-glasnudeln-gurke",
    type: "Salat/Kalte Gerichte",
    emoji: "🍜",
    title: "Glasnudel-Gurken-Salat, leicht sauer-würzig (黃瓜拌粉絲)",
    desc: "Sättigende Basis für die Kombi-Platte — Glasnudeln nur kurz in heißem Wasser garziehen lassen, kein Kochen nötig.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Mungbohnen-Glasnudeln 100 g",
      "Salatgurke 1 Stück",
      "Karotte 1 Stück (klein)",
      "Knoblauch 1 Zehe",
      "Sojasauce natriumarm 1 EL",
      "Reisessig mild 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Glasnudeln 5 Min. in heißem Wasser einweichen, bis glasig-weich, abgießen, mit einer Schere kürzen.",
      "Gurke und Karotte in feine Streifen schneiden oder raspeln.",
      "Dressing aus Knoblauch, Sojasauce, Essig und Sesamöl separat verrühren.",
      "Glasnudeln, Gemüse und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — Glasnudeln werden beim Auftauen matschig; alle Zutaten getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen mit dem Dressing vermengen.",
    tags: ["China", "Salat", "Vegetarisch"],
  },
  {
    id: "china-salat-huehnerfuesse-poachili",
    type: "Salat/Kalte Gerichte",
    emoji: "🐔",
    title: "Hühnerfüße in Chili-Essig, sauer-scharf (泡椒鳳爪)",
    desc: "Klassiker der kantonesischen Dim-Sum- und Snack-Küche — lange gekocht bis butterweich, dann in einer sauer-scharfen Marinade eingelegt. Bindegewebsreich, kollagenreich statt proteinreich im klassischen Sinn.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hühnerfüße 500 g",
      "Frühlingszwiebel 2 Stück, Ingwer 3 Scheiben (zum Kochen)",
      "Eingelegte rote Chilis (泡椒) 4–6 Stück",
      "Knoblauch 3 Zehen",
      "Reisessig mild 3 EL",
      "Sojasauce natriumarm 1 EL",
      "Zucker 1 TL",
    ],
    steps: [
      "Hühnerfüße mit Frühlingszwiebel und Ingwer 25–30 Min. köcheln, bis butterweich, abgießen und auskühlen lassen.",
      "Krallenspitzen abschneiden, Füße nach Belieben halbieren.",
      "Marinade aus Chilis, Knoblauch, Essig, Sojasauce und Zucker verrühren.",
      "Hühnerfüße in der Marinade mind. 2 Std. (besser über Nacht) im Kühlschrank ziehen lassen.",
    ],
    freezeMethod: "Kein Einfrieren — mariniert hält sich bis zu 4 Tage im Kühlschrank, wird mit der Zeit noch würziger.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt aus dem Kühlschrank servieren.",
    tags: ["China", "Kalte Platte", "Vollständig durchgegart"],
  },
  {
    id: "china-salat-schweineohr-knoblauch",
    type: "Salat/Kalte Gerichte",
    emoji: "🐷",
    title: "Schweineohr in Knoblauch-Chiliöl, hauchdünn geschnitten (蒜泥豬耳)",
    desc: "Traditioneller kalter Aufschnitt für die Vorspeisenplatte — Ohr wird gekocht, gepresst und erst kurz vor dem Servieren hauchdünn aufgeschnitten, damit es die Bissfestigkeit behält.",
    batchSize: "Ergibt 4 Portionen als Vorspeise",
    ingredients: [
      "Schweineohren 2 Stück (küchenfertig)",
      "Frühlingszwiebel 2 Stück, Ingwer 3 Scheiben, Sternanis 1 Stück (zum Kochen)",
      "Knoblauch 3 Zehen",
      "Chiliöl 1–2 TL (nach Geschmack)",
      "Sojasauce natriumarm 2 EL",
      "Reisessig mild 1 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Ohren gründlich abflammen/reinigen, mit Frühlingszwiebel, Ingwer und Sternanis 45–60 Min. köcheln, bis gar.",
      "Noch warm zwischen zwei Tellern beschwert flachpressen, auskühlen lassen — ergibt gleichmäßige Scheiben.",
      "Dressing aus Knoblauch, Chiliöl, Sojasauce, Essig und Sesamöl verrühren.",
      "Ohr erst kurz vor dem Servieren hauchdünn aufschneiden und mit dem Dressing beträufeln.",
    ],
    freezeMethod: "Gekochtes, gepresstes Ohr ungeschnitten portionsweise einfrierbar — erst nach dem Auftauen aufschneiden.",
    freezerLife: "bis zu 2 Monate (ungeschnitten)",
    reheat: "Im Kühlschrank auftauen, kalt hauchdünn aufschneiden und mit frischem Dressing servieren.",
    tags: ["China", "Kalte Platte", "Vollständig durchgegart"],
  },
  {
    id: "japan-gomaae-spinat",
    type: "Tsukemono/Aemono",
    emoji: "🥬",
    title: "Goma-ae — Spinat in Sesam-Dressing (ごま和え)",
    desc: "Blanchierter Spinat in einer süß-salzigen Sesam-Sauce — einer der bekanntesten japanischen Beilagensalate, in wenigen Minuten fertig.",
    batchSize: "Ergibt 2 Portionen",
    ingredients: [
      "Blattspinat 200 g",
      "Geröstete, gemahlene Sesamsamen 10 g",
      "Sojasauce natriumarm 1 TL",
      "Mirin 1/2 TL",
      "Dashi (oder Wasser) 1 TL",
    ],
    steps: [
      "Spinat in kochendem Wasser 30–60 Sek. blanchieren, sofort in Eiswasser abschrecken.",
      "Gründlich ausdrücken, in 3–4 cm lange Stücke schneiden.",
      "Sesam-Dressing aus gemahlenem Sesam, Sojasauce, Mirin und Dashi verrühren.",
      "Spinat und Dressing getrennt im Kühlschrank aufbewahren — erst direkt vor dem Servieren vermengen, sonst zieht der Spinat Wasser.",
    ],
    freezeMethod: "Kein Einfrieren — blanchierter Spinat und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, unmittelbar vor dem Essen vermengen.",
    tags: ["Japan", "Vegetarisch", "Aemono"],
  },
  {
    id: "japan-sunomono-gurke-wakame",
    type: "Tsukemono/Aemono",
    emoji: "🥒",
    title: "Sunomono — Gurken-Wakame-Salat (酢の物)",
    desc: "Leicht gesalzene Gurke mit eingeweichter Wakame-Alge in einer milden Essig-Sauce (Sanbaizu) — klassische erfrischende Beilage.",
    batchSize: "Ergibt 2 Portionen",
    ingredients: [
      "Salatgurke 1 Stück",
      "Getrocknete Wakame 3 g",
      "Reisessig mild 2 EL",
      "Zucker 1 TL",
      "Sojasauce natriumarm 1 TL",
      "Salz 1 Prise",
    ],
    steps: [
      "Gurke in dünne Scheiben schneiden, mit einer Prise Salz vermengen, 5 Min. ziehen lassen, Wasser ausdrücken.",
      "Wakame 5 Min. in Wasser einweichen, gut ausdrücken.",
      "Sanbaizu-Dressing aus Essig, Zucker und Sojasauce verrühren.",
      "Gurke, Wakame und Dressing getrennt im Kühlschrank aufbewahren, erst vor dem Servieren vermengen.",
    ],
    freezeMethod: "Kein Einfrieren — vorbereitete Zutaten und Dressing getrennt im Kühlschrank, bis zu 2 Tage haltbar.",
    freezerLife: "nicht einfrieren",
    reheat: "Kalt servieren, erst kurz vor dem Essen vermengen.",
    tags: ["Japan", "Vegetarisch", "Jod: sparsam dosieren (Wakame)", "Low Sugar ✓"],
  },
  {
    id: "japan-shiomomi-gurke",
    type: "Tsukemono/Aemono",
    emoji: "🧂",
    title: "Shio-Momi — Salz-Massier-Gurke (塩もみきゅうり)",
    desc: "Die einfachste Tsukemono-Methode überhaupt: Gurke wird nur mit Salz massiert, kein Fermentieren, kein Essig — in 10 Minuten fertig, sehr knackig.",
    batchSize: "Ergibt 2 Portionen",
    ingredients: [
      "Salatgurke 1 Stück",
      "Salz 1/2 TL",
    ],
    steps: [
      "Gurke in dünne Scheiben schneiden.",
      "Mit Salz gründlich vermengen/massieren, bis leicht glasig.",
      "5–10 Min. ziehen lassen, austretende Flüssigkeit ausdrücken.",
      "Direkt servieren oder im Kühlschrank bis zu 2 Tage aufbewahren.",
    ],
    freezeMethod: "Kein Einfrieren — im Kühlschrank, luftdicht verschlossen.",
    freezerLife: "bis zu 2 Tage im Kühlschrank",
    reheat: "Kalt servieren als einfachste Beilage zu Reis.",
    tags: ["Japan", "Vegetarisch", "Salzgehalt: in Maßen genießen"],
  },
  {
    id: "japan-asazuke-gemischt",
    type: "Tsukemono/Aemono",
    emoji: "🥕",
    title: "Asazuke — Schnell-Mischgemüse (浅漬け)",
    desc: "Vielseitige Schnellpökel-Methode für gemischtes Gemüse — funktioniert mit fast allem im Kühlschrank, in 30 Minuten fertig.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Gemischtes Gemüse (Rettich, Karotte, Kohl) 400 g",
      "Salz 8 g (2% des Gemüsegewichts)",
      "Kombu-Streifen 5 g (optional)",
      "Yuzu- oder Zitronenschale 1 Prise (optional)",
    ],
    steps: [
      "Gemüse in dünne, mundgerechte Stücke schneiden.",
      "Mit Salz und optional Kombu vermengen, in einen Gefrierbeutel geben.",
      "Luft herausdrücken, mit einem Gewicht (z. B. Teller) beschwert 30–60 Min. bei Zimmertemperatur ziehen lassen.",
      "Austretende Flüssigkeit abgießen, im Kühlschrank aufbewahren.",
    ],
    freezeMethod: "Kein Einfrieren — im Kühlschrank, luftdicht verschlossen.",
    freezerLife: "bis zu 4 Tage im Kühlschrank",
    reheat: "Kalt servieren als Beilage zu Reis oder Congee.",
    tags: ["Japan", "Vegetarisch", "Salzgehalt: in Maßen genießen"],
  },
  {
    id: "japan-moyashi-namul",
    type: "Tsukemono/Aemono",
    emoji: "🌱",
    title: "Moyashi-Namul — Sojasprossen-Beilage, japanisch-koreanisch (もやしナムル)",
    desc: "Kurz blanchierte Sojasprossen mit Sesamöl und Knoblauch — schnelle, izakaya-typische Beilage, die auch als Basis für Bibimbap dient.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Sojasprossen 300 g",
      "Knoblauch 1 Zehe",
      "Sesamöl 1 TL",
      "Sojasauce natriumarm 1 TL",
      "Röstsesam 1 TL",
    ],
    steps: [
      "Sojasprossen in kochendem Wasser 2–3 Min. blanchieren, dabei den Deckel nicht anheben (vermeidet bitteren Geruch).",
      "Sofort in Eiswasser abschrecken, gut abtropfen lassen.",
      "Mit Knoblauch, Sesamöl, Sojasauce und Sesam vermengen.",
      "Im Kühlschrank aufbewahren, kalt oder leicht angewärmt servieren.",
    ],
    freezeMethod: "Kein Einfrieren — fertig angemacht im Kühlschrank, luftdicht verschlossen.",
    freezerLife: "bis zu 3 Tage im Kühlschrank",
    reheat: "Kalt servieren oder kurz bei Zimmertemperatur ziehen lassen.",
    tags: ["Japan/Korea", "Vegetarisch", "Diabetes: sehr kohlenhydratarm"],
  },
  {
    id: "korea-musaengchae-rettich",
    type: "Banchan",
    emoji: "🥕",
    title: "Musaengchae — Scharf-saurer Rettich-Salat (무생채)",
    desc: "Fein geraspelter Rettich in einer scharf-süß-sauren Marinade — einer der bekanntesten koreanischen Banchan, auch beliebt zu Bibimbap.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Rettich (koreanisch/Daikon) 400 g",
      "Gochugaru (koreanisches Chilipulver) 1–2 EL",
      "Knoblauch 1 Zehe",
      "Reisessig mild 1 EL",
      "Zucker 1 TL",
      "Salz 1/2 TL",
    ],
    steps: [
      "Rettich in sehr feine Streifen schneiden.",
      "Mit Salz kurz vermengen, 5 Min. ziehen lassen, überschüssige Flüssigkeit abgießen (nicht auswaschen).",
      "Gochugaru, Knoblauch, Essig und Zucker zugeben, gründlich vermengen.",
      "Im Kühlschrank aufbewahren — schmeckt nach ein paar Stunden Durchziehen noch besser.",
    ],
    freezeMethod: "Kein Einfrieren — im Kühlschrank, luftdicht verschlossen.",
    freezerLife: "bis zu 5 Tage im Kühlschrank",
    reheat: "Kalt servieren als Banchan-Beilage.",
    tags: ["Korea", "Banchan", "Vegetarisch", "Low Sugar ✓"],
  },
  {
    id: "korea-kongnamul-muchim",
    type: "Banchan",
    emoji: "🌱",
    title: "Kongnamul-Muchim — Sojasprossen-Banchan (콩나물무침)",
    desc: "Gedämpfte Sojasprossen mit Sesamöl, Knoblauch und Frühlingszwiebel — fester Bestandteil jedes koreanischen Banchan-Sets.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Sojasprossen 300 g",
      "Frühlingszwiebel 1 Stück",
      "Knoblauch 1 Zehe",
      "Sesamöl 1 TL",
      "Sojasauce natriumarm 1 TL",
      "Röstsesam 1 TL",
    ],
    steps: [
      "Sojasprossen mit etwas Wasser im geschlossenen Topf 3–4 Min. dämpfen/kochen — Deckel während des Garens nicht anheben, sonst wird der Geruch streng.",
      "Abtropfen lassen, auskühlen.",
      "Mit Frühlingszwiebel, Knoblauch, Sesamöl, Sojasauce und Sesam vermengen.",
      "Im Kühlschrank aufbewahren.",
    ],
    freezeMethod: "Kein Einfrieren — fertig angemacht im Kühlschrank, luftdicht verschlossen.",
    freezerLife: "bis zu 3 Tage im Kühlschrank",
    reheat: "Kalt servieren oder kurz bei Zimmertemperatur ziehen lassen.",
    tags: ["Korea", "Banchan", "Vegetarisch", "Diabetes: sehr kohlenhydratarm"],
  },
  {
    id: "korea-oimuchim-gurke",
    type: "Banchan",
    emoji: "🥒",
    title: "Oi-Muchim — Scharf-süßer Gurken-Banchan (오이무침)",
    desc: "Knackige, salzentwässerte Gurke in einer scharf-süß-sauren Gochugaru-Marinade — schneller, sehr beliebter Banchan.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Salatgurke 2 Stück",
      "Salz 1 TL",
      "Gochugaru 1 EL",
      "Knoblauch 1 Zehe",
      "Reisessig mild 1 EL",
      "Zucker 1 TL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Gurke in dünne Scheiben schneiden, mit Salz vermengen, 10 Min. ziehen lassen.",
      "Austretende Flüssigkeit gründlich ausdrücken.",
      "Mit Gochugaru, Knoblauch, Essig, Zucker und Sesamöl vermengen.",
      "Im Kühlschrank aufbewahren, am besten frisch bis zum nächsten Tag genießen.",
    ],
    freezeMethod: "Kein Einfrieren — im Kühlschrank, luftdicht verschlossen.",
    freezerLife: "bis zu 2 Tage im Kühlschrank (bleibt am knackigsten)",
    reheat: "Kalt servieren als Banchan-Beilage.",
    tags: ["Korea", "Banchan", "Vegetarisch", "Low Sugar ✓"],
  },
];
