// src/plans/manifest.ts
// AUTO-GENERATED by scripts/gen-plan-manifest.mjs — do not hand-edit.
// Regenerate after adding/removing a week file: node scripts/gen-plan-manifest.mjs

export type PlanManifestEntry = {
  id: string;
  title?: string;
  startDate: string;
  lang?: string;
  sidebar?: string;
  focus?: string;
  path: string;
};

export const PLAN_MANIFEST: PlanManifestEntry[] = [
  {
    "title": "Woche 1",
    "startDate": "2025-09-29",
    "id": "woche-1-2025-09-29-de",
    "lang": "de",
    "sidebar": "Woche 1 (2025-09-29)",
    "path": "./plans/2025/Woche-1-2025-09-29.de.jsx"
  },
  {
    "title": "第1周",
    "startDate": "2025-09-29",
    "id": "woche-1-2025-09-29-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第1周 (2025-09-29)",
    "path": "./plans/2025/Woche-1-2025-09-29.zh.jsx"
  },
  {
    "title": "第2周",
    "startDate": "2025-10-06",
    "id": "woche-2-2025-10-06-zh",
    "lang": "zh",
    "sidebar": "第2周 (2025-10-06)",
    "path": "./plans/2025/Woche-2-2025-10-06.zh.jsx"
  },
  {
    "title": "Woche 3",
    "startDate": "2025-10-13",
    "id": "woche-3-2025-10-13",
    "lang": "de",
    "sidebar": "Woche 3 (2025-10-13)",
    "path": "./plans/2025/Woche-3-2025-10-13.de.jsx"
  },
  {
    "title": "第3周",
    "startDate": "2025-10-13",
    "id": "woche-3-2025-10-13-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第3周 (2025-10-13)",
    "path": "./plans/2025/Woche-3-2025-10-13.zh.jsx"
  },
  {
    "title": "Woche 4",
    "startDate": "2025-10-20",
    "id": "woche-4-2025-10-20",
    "lang": "de",
    "sidebar": "[DE] Woche 4 (2025-10-20)",
    "path": "./plans/2025/Woche-4-2025-10-20.de.jsx"
  },
  {
    "title": "第4周",
    "startDate": "2025-10-20",
    "id": "woche-4-2025-10-20-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第4周 (2025-10-20)",
    "path": "./plans/2025/Woche-4-2025-10-20.zh.jsx"
  },
  {
    "title": "Woche 5",
    "startDate": "2025-10-27",
    "id": "woche-5-2025-10-27",
    "lang": "de",
    "sidebar": "[DE] Woche 5 (2025-10-27)",
    "path": "./plans/2025/Woche-5-2025-10-27.de.jsx"
  },
  {
    "title": "第5周",
    "startDate": "2025-10-27",
    "id": "woche-5-2025-10-27-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第5周 (2025-10-27)",
    "path": "./plans/2025/Woche-5-2025-10-27.zh.jsx"
  },
  {
    "title": "Woche 6",
    "startDate": "2025-11-03",
    "id": "woche-6-2025-11-03-de",
    "lang": "de",
    "sidebar": "[DE] Woche 6 (2025-11-03)",
    "path": "./plans/2025/Woche-6-2025-11-03.de.jsx"
  },
  {
    "title": "第6周",
    "startDate": "2025-11-03",
    "id": "woche-6-2025-11-03-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第6周 (2025-11-03)",
    "path": "./plans/2025/Woche-6-2025-11-03.zh.jsx"
  },
  {
    "title": "Woche 7",
    "startDate": "2025-11-10",
    "id": "woche-7-2025-11-10-de",
    "lang": "de",
    "sidebar": "[DE] Woche 7 (2025-11-10)",
    "path": "./plans/2025/Woche-7-2025-11-10.de.jsx"
  },
  {
    "title": "第7周",
    "startDate": "2025-11-10",
    "id": "zhou-7-2025-11-10-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第7周 (2025-11-10)",
    "path": "./plans/2025/Woche-7-2025-11-10.zh.jsx"
  },
  {
    "title": "Woche 8",
    "startDate": "2025-11-17",
    "id": "woche-8-2025-11-17-de",
    "lang": "de",
    "sidebar": "[DE] Woche 8 (2025-11-17)",
    "path": "./plans/2025/Woche-8-2025-11-17.de.jsx"
  },
  {
    "title": "第8周",
    "startDate": "2025-11-17",
    "id": "woche-8-2025-11-17-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第8周 (2025-11-17)",
    "path": "./plans/2025/Woche-8-2025-11-17.zh.jsx"
  },
  {
    "title": "Woche 1",
    "startDate": "2025-12-29",
    "id": "woche-1-2025-12-29",
    "lang": "de",
    "sidebar": "Woche 1 (2025-12-29)",
    "focus": "Japanisch mild · Reisbrei & Congee · Schwangerschaftssicher",
    "path": "./plans/2026/Woche-1-2025-12-29.de.jsx"
  },
  {
    "title": "第1周",
    "startDate": "2025-12-29",
    "id": "woche-1-2025-12-29",
    "lang": "zh",
    "sidebar": "第1周（2025-12-29）",
    "focus": "日式温和粥品 · 清蒸鳕鱼 · 孕期安全",
    "path": "./plans/2026/Woche-1-2026-12-29.zh.jsx"
  },
  {
    "title": "Woche 2",
    "startDate": "2026-01-05",
    "id": "woche-2-2026-01-05",
    "lang": "de",
    "sidebar": "Woche 2 (2026-01-05)",
    "focus": "Asiatische Hausmannskost (CN/JP/KR) · Mild & Schwangerschaftsgeeignet · 1x Reiskocher/Tag",
    "path": "./plans/2026/Woche-2-2026-01-05.de.jsx"
  },
  {
    "title": "第2周",
    "startDate": "2026-01-05",
    "id": "woche-2-2026-01-05",
    "lang": "zh",
    "sidebar": "第2周 (2026-01-05)",
    "focus": "韩式鸡肉粥 & 海南鸡饭 · 电饭煲家常 · 孕期安全",
    "path": "./plans/2026/Woche-2-2026-01-05.zh.jsx"
  },
  {
    "title": "Woche 3",
    "startDate": "2026-01-12",
    "id": "woche-3-2026-01-12",
    "lang": "de",
    "sidebar": "Woche 3 (2026-01-12)",
    "focus": "JP/CN · mild & schwangerschaftssicher · viel Fisch/Meeresfrüchte · 1× Reiskocher/Tag",
    "path": "./plans/2026/Woche-3-2026-01-12.de.jsx"
  },
  {
    "title": "第3周",
    "startDate": "2026-01-12",
    "id": "woche-3-2026-01-12",
    "lang": "zh",
    "sidebar": "第3周 (2026-01-12)",
    "focus": "三文鱼 & 海鲜家常 · 电饭煲料理 · 孕期安全",
    "path": "./plans/2026/Woche-3-2026-01-12.zh.jsx"
  },
  {
    "title": "Woche 4",
    "startDate": "2026-01-19",
    "id": "woche-4-2026-01-19",
    "lang": "de",
    "sidebar": "Woche 4 (2026-01-19)",
    "focus": "JP/CN/KR · mild & schwangerschaftssicher · abwechslungsreich · 1× Reiskocher/Tag",
    "path": "./plans/2026/Woche-4-2026-01-19.de.jsx"
  },
  {
    "title": "第4周",
    "startDate": "2026-01-19",
    "id": "woche-4-2026-01-19",
    "lang": "zh",
    "sidebar": "第4周 (2026-01-19)",
    "focus": "韩式风味三文鱼 · 电饭煲煲仔饭 · 孕期安全",
    "path": "./plans/2026/Woche-4-2026-01-19.zh.jsx"
  },
  {
    "title": "Woche 5",
    "startDate": "2026-01-26",
    "id": "woche-5-2026-01-26",
    "lang": "de",
    "sidebar": "Woche 5 (2026-01-26)",
    "focus": "JP/CN/KR · Balanced · Schwangerschaftssicher · 1× Reiskocher/Tag",
    "path": "./plans/2026/Woche-5-2026-01-26.de.jsx"
  },
  {
    "title": "第5周",
    "startDate": "2026-01-26",
    "id": "woche-5-2026-01-26",
    "lang": "zh",
    "sidebar": "第5周 (2026-01-26)",
    "focus": "台式蛋饼 & 天津饭 · 亚洲早餐特辑 · 孕期安全",
    "path": "./plans/2026/Woche-5-2026-01-26.zh.jsx"
  },
  {
    "title": "Woche 6",
    "startDate": "2026-02-02",
    "id": "woche-6-2026-02-02",
    "lang": "de",
    "sidebar": "Woche 6 (2026-02-02)",
    "focus": "Virale Trends (CN/JP/KR) + SWE/IT · Balanced · Schwangerschaftssicher · 1× Reiskocher/Tag",
    "path": "./plans/2026/Woche-6-2026-02-02.de.jsx"
  },
  {
    "title": "Woche 7",
    "startDate": "2026-02-09",
    "id": "woche-7-2026-02-09",
    "lang": "de",
    "sidebar": "Woche 7 (2026-02-09)",
    "focus": "CN Wok & Schwein · Airfryer-Hacks · SWE/HR/IT · 1× Reiskocher/Tag",
    "path": "./plans/2026/Woche-7-2026-02-09.de.jsx"
  },
  {
    "title": "Woche 8",
    "startDate": "2026-02-16",
    "id": "woche-8-2026-02-16",
    "lang": "de",
    "sidebar": "Woche 8 (2026-02-16)",
    "focus": "Airfryer-Hacks · Virale Trends · Balanced · Schwangerschaftssicher",
    "path": "./plans/2026/Woche-8-2026-02-16.de.jsx"
  },
  {
    "title": "Woche 9",
    "startDate": "2026-02-23",
    "id": "woche-9-2026-02-23",
    "lang": "de",
    "sidebar": "Woche 9 (2026-02-23)",
    "focus": "Airfryer Hacks · Reiskocher-Liebe · Balanced · Schwangerschaftssicher",
    "path": "./plans/2026/Woche-9-2026-02-23.de.jsx"
  },
  {
    "title": "Woche 10",
    "startDate": "2026-03-02",
    "id": "woche-10-2026-03-02",
    "lang": "de",
    "sidebar": "Woche 10 (2026-03-02)",
    "focus": "Airfryer Hacks · Udon-Trends · Reiskocher-Magie · Balanced",
    "path": "./plans/2026/Woche-10-2026-03-02.de.jsx"
  },
  {
    "title": "Woche 11",
    "startDate": "2026-03-09",
    "id": "woche-11-2026-03-09",
    "lang": "de",
    "sidebar": "Woche 11 (2026-03-09)",
    "focus": "Japanisch mild · Reiskocher-Donburi · Balanced",
    "path": "./plans/2026/Woche-11-2026-03-09.de.jsx"
  },
  {
    "title": "Woche 12",
    "startDate": "2026-03-16",
    "id": "woche-12-2026-03-16",
    "lang": "de",
    "sidebar": "Woche 12 (2026-03-16)",
    "focus": "Sushi Bake & Donburi · Reiskocher-Vielfalt · Balanced",
    "path": "./plans/2026/Woche-12-2026-03-16.de.jsx"
  },
  {
    "title": "Woche 13",
    "startDate": "2026-03-23",
    "id": "woche-13-2026-03-23",
    "lang": "de",
    "sidebar": "Woche 13 (2026-03-23)",
    "focus": "Drei-Tassen-Huhn & Claypot · Reiskocher-Vielfalt · Balanced",
    "path": "./plans/2026/Woche-13-2026-03-23.de.jsx"
  },
  {
    "title": "Woche 14",
    "startDate": "2026-03-30",
    "id": "woche-14-2026-03-30",
    "lang": "de",
    "sidebar": "Woche 14 (2026-03-30)",
    "focus": "Teriyaki & Takikomi Gohan · Fusion-Frühstück · Balanced",
    "path": "./plans/2026/Woche-14-2026-03-30.de.jsx"
  },
  {
    "title": "Woche 15",
    "startDate": "2026-04-06",
    "id": "woche-15-2026-04-06",
    "lang": "de",
    "sidebar": "Woche 15 (2026-04-06)",
    "focus": "Gochujang & Tom Yum · Würzige Reisbowls · Balanced",
    "path": "./plans/2026/Woche-15-2026-04-06.de.jsx"
  },
  {
    "title": "Woche 16",
    "startDate": "2026-04-13",
    "id": "woche-16-2026-04-13",
    "lang": "de",
    "sidebar": "Woche 16 (2026-04-13)",
    "focus": "Internationale Food-Trends · Bunte Vielfalt · Balanced",
    "path": "./plans/2026/Woche-16-2026-04-13.de.jsx"
  },
  {
    "title": "Woche 17",
    "startDate": "2026-04-20",
    "id": "woche-17-2026-04-20",
    "lang": "de",
    "sidebar": "Woche 17 (2026-04-20)",
    "focus": "Fusion-Nudeln (JP/KR/IT) · Katsu & Risotto · Balanced",
    "path": "./plans/2026/Woche-17-2026-04-20.de.jsx"
  },
  {
    "title": "Woche 18",
    "startDate": "2026-04-27",
    "id": "woche-18-2026-04-27",
    "lang": "de",
    "sidebar": "Woche 18 (2026-04-27)",
    "focus": "Bulgogi & Takikomi Gohan · Curry-Bowls · Balanced",
    "path": "./plans/2026/Woche-18-2026-04-27.de.jsx"
  },
  {
    "title": "Woche 19",
    "startDate": "2026-05-04",
    "id": "woche-19-2026-05-04",
    "lang": "de",
    "sidebar": "Woche 19 (2026-05-04)",
    "focus": "Thai & Kürbis-Kokos · Herzhafte Reisbowls · Balanced",
    "path": "./plans/2026/Woche-19-2026-05-04.de.jsx"
  },
  {
    "title": "Woche 20",
    "startDate": "2026-05-11",
    "id": "woche-20-2026-05-11",
    "lang": "de",
    "sidebar": "Woche 20 (2026-05-11)",
    "focus": "Lachs, Fisch & Meeresfrüchte · Reiskocher-Vielfalt · Balanced",
    "path": "./plans/2026/Woche-20-2026-05-11.de.jsx"
  },
  {
    "title": "Woche 21",
    "startDate": "2026-05-18",
    "id": "woche-21-2026-05-18",
    "lang": "de",
    "sidebar": "Woche 21 (2026-05-18)",
    "focus": "Goldbrasse, Zha Cai & Co · Airfryer-Hacks · Balanced",
    "path": "./plans/2026/Woche-21-2026-05-18.de.jsx"
  },
  {
    "title": "Woche 22",
    "startDate": "2026-05-25",
    "id": "woche-22-2026-05-25",
    "lang": "de",
    "sidebar": "Woche 22 (2026-05-25)",
    "focus": "Chinesische Wok-Hits · Reiskocher-Magie · Balanced",
    "path": "./plans/2026/Woche-22-2026-05-25.de.jsx"
  },
  {
    "title": "Woche 23",
    "startDate": "2026-06-01",
    "id": "woche-23-2026-06-01",
    "lang": "de",
    "sidebar": "Woche 23 (2026-06-01)",
    "focus": "Japan (ausgefallen & leicht) · Reiskocher · Balanced",
    "path": "./plans/2026/Woche-23-2026-06-01.de.jsx"
  },
  {
    "title": "Woche 24",
    "startDate": "2026-06-08",
    "id": "woche-24-2026-06-08",
    "lang": "de",
    "sidebar": "Woche 24 (2026-06-08)",
    "focus": "Koreanische Küche · Airfryer-Hacks · Balanced",
    "path": "./plans/2026/Woche-24-2026-06-08.de.jsx"
  },
  {
    "title": "Woche 25",
    "startDate": "2026-06-15",
    "id": "woche-25-2026-06-15",
    "lang": "de",
    "sidebar": "Woche 25 (2026-06-15)",
    "focus": "Italien & Asia Fusion · Airfryer-Hacks · Balanced",
    "path": "./plans/2026/Woche-25-2026-06-15.de.jsx"
  },
  {
    "title": "Woche 26",
    "startDate": "2026-06-22",
    "id": "woche-26-2026-06-22",
    "lang": "de",
    "sidebar": "Woche 26 (2026-06-22)",
    "focus": "Thai & Szechuan Würze · Airfryer-Vielfalt · Balanced",
    "path": "./plans/2026/Woche-26-2026-06-22.de.jsx"
  },
  {
    "title": "Woche 27",
    "startDate": "2026-06-29",
    "id": "woche-27-2026-06-29",
    "lang": "de",
    "sidebar": "Woche 27 (2026-06-29)",
    "focus": "Kalte Soba & Congee 🌊 · Sanftes Dämpfen · Balanced",
    "path": "./plans/2026/Woche-27-2026-06-29.de.jsx"
  },
  {
    "title": "Woche 28",
    "startDate": "2026-07-06",
    "id": "woche-28-2026-07-06",
    "lang": "de",
    "sidebar": "Woche 28 (2026-07-06)",
    "focus": "Dim Sum & Dampfgaren 🥟 · Kantonesisch mild · Balanced",
    "path": "./plans/2026/Woche-28-2026-07-06.de.jsx"
  },
  {
    "title": "Woche 29",
    "startDate": "2026-07-13",
    "id": "woche-29-2026-07-13",
    "lang": "de",
    "sidebar": "Woche 29 (2026-07-13)",
    "focus": "Sōmen & Donburi 🎐 · Japanisch mild · Balanced",
    "path": "./plans/2026/Woche-29-2026-07-13.de.jsx"
  },
  {
    "title": "Woche 30",
    "startDate": "2026-07-20",
    "id": "woche-30-2026-07-20",
    "lang": "de",
    "sidebar": "Woche 30 (2026-07-20)",
    "focus": "Banchan & Jjigae 🥢 · Koreanisch ohne Chili · Balanced",
    "path": "./plans/2026/Woche-30-2026-07-20.de.jsx"
  },
  {
    "title": "Woche 31",
    "startDate": "2026-07-27",
    "id": "woche-31-2026-07-27",
    "lang": "de",
    "sidebar": "Woche 31 (2026-07-27)",
    "focus": "China-Woche 🇨🇳 · Virale Trends · Low Sugar · Schwangerschaftsgeeignet",
    "path": "./plans/2026/Woche-31-2026-07-27.de.jsx"
  },
  {
    "title": "Woche 32",
    "startDate": "2026-08-03",
    "id": "woche-32-2026-08-03",
    "lang": "de",
    "sidebar": "Woche 32 (2026-08-03)",
    "focus": "Viel Gemüse, viel Tofu 🥒 · Leichte Sommerküche · Balanced",
    "path": "./plans/2026/Woche-32-2026-08-03.de.jsx"
  },
  {
    "title": "Woche 33",
    "startDate": "2026-08-10",
    "id": "woche-33-2026-08-10",
    "lang": "de",
    "sidebar": "Woche 33 (2026-08-10)",
    "focus": "Knusprig, wenig Öl 🍗 · Airfryer-Woche · Balanced",
    "path": "./plans/2026/Woche-33-2026-08-10.de.jsx"
  },
  {
    "title": "Woche 34",
    "startDate": "2026-08-17",
    "id": "woche-34-2026-08-17",
    "lang": "de",
    "sidebar": "Woche 34 (2026-08-17)",
    "focus": "Ramen, Udon & Co. 🍜 · Milde Brühen · Balanced",
    "path": "./plans/2026/Woche-34-2026-08-17.de.jsx"
  },
  {
    "title": "Woche 35",
    "startDate": "2026-08-24",
    "id": "woche-35-2026-08-24",
    "lang": "de",
    "sidebar": "Woche 35 (2026-08-24)",
    "focus": "Kürbis, Mais & Pilze 🌽 · Erntefrisch mild · Balanced",
    "path": "./plans/2026/Woche-35-2026-08-24.de.jsx"
  },
  {
    "title": "Woche 36",
    "startDate": "2026-08-31",
    "id": "woche-36-2026-08-31",
    "lang": "de",
    "sidebar": "Woche 36 (2026-08-31)",
    "focus": "Wärmende Eintöpfe & Congee 🍂 · Herbstauftakt · Balanced",
    "path": "./plans/2026/Woche-36-2026-08-31.de.jsx"
  },
  {
    "title": "Woche 37",
    "startDate": "2026-09-07",
    "id": "woche-37-2026-09-07",
    "lang": "de",
    "sidebar": "Woche 37 (2026-09-07)",
    "focus": "家常菜 · Chinesische Hausmannskost · Balanced",
    "path": "./plans/2026/Woche-37-2026-09-07.de.jsx"
  },
  {
    "title": "Woche 38",
    "startDate": "2026-09-14",
    "id": "woche-38-2026-09-14",
    "lang": "de",
    "sidebar": "Woche 38 (2026-09-14)",
    "focus": "川菜 mild · Mapo & Gong Bao · Balanced",
    "path": "./plans/2026/Woche-38-2026-09-14.de.jsx"
  },
  {
    "title": "Woche 39",
    "startDate": "2026-09-21",
    "id": "woche-39-2026-09-21",
    "lang": "de",
    "sidebar": "Woche 39 (2026-09-21)",
    "focus": "粵菜 · Dampfgaren & klare Brühen · Balanced",
    "path": "./plans/2026/Woche-39-2026-09-21.de.jsx"
  },
  {
    "title": "Woche 40",
    "startDate": "2026-09-28",
    "id": "woche-40-2026-09-28",
    "lang": "de",
    "sidebar": "Woche 40 (2026-09-28)",
    "focus": "家常湯 🥣 · Klare Brühen & Eintöpfe · Balanced",
    "path": "./plans/2026/Woche-40-2026-09-28.de.jsx"
  },
  {
    "title": "Woche 41",
    "startDate": "2026-10-05",
    "id": "woche-41-2026-10-05",
    "lang": "de",
    "sidebar": "Woche 41 (2026-10-05)",
    "focus": "麵食 🥟 · Nudeln, Jiaozi & Baozi · Balanced",
    "path": "./plans/2026/Woche-41-2026-10-05.de.jsx"
  },
  {
    "title": "Woche 42",
    "startDate": "2026-10-12",
    "id": "woche-42-2026-10-12",
    "lang": "de",
    "sidebar": "Woche 42 (2026-10-12)",
    "focus": "家常炒菜 · Hongshao & süß-sauer · Balanced",
    "path": "./plans/2026/Woche-42-2026-10-12.de.jsx"
  },
  {
    "title": "Woche 43",
    "startDate": "2026-10-19",
    "id": "woche-43-2026-10-19",
    "lang": "de",
    "sidebar": "Woche 43 (2026-10-19)",
    "focus": "中式早點 🥣 · Frühstück den ganzen Tag · Balanced",
    "path": "./plans/2026/Woche-43-2026-10-19.de.jsx"
  },
  {
    "title": "Woche 44",
    "startDate": "2026-10-26",
    "id": "woche-44-2026-10-26",
    "lang": "de",
    "sidebar": "Woche 44 (2026-10-26)",
    "focus": "秋冬滋補 🍂 · Nährende Schmorgerichte · Balanced",
    "path": "./plans/2026/Woche-44-2026-10-26.de.jsx"
  }
];
