// src/plans/manifest.ts
// AUTO-GENERATED by scripts/gen-plan-manifest.mjs — do not hand-edit.
// Regenerate after adding/removing a week file: node scripts/gen-plan-manifest.mjs

export type PlanManifestEntry = {
  id: string;
  title?: string;
  startDate: string;
  lang?: string;
  sidebar?: string;
  path: string;
};

export const PLAN_MANIFEST: PlanManifestEntry[] = [
  {
    "title": "Woche 1",
    "startDate": "2025-09-29",
    "id": "woche-1-2025-09-29-de",
    "lang": "de",
    "sidebar": "Woche 1 (2025-09-29)",
    "path": "./plans/2025/Woche-1-2025-09-29.de.jsx"
  },
  {
    "title": "第1周",
    "startDate": "2025-09-29",
    "id": "woche-1-2025-09-29-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第1周 (2025-09-29)",
    "path": "./plans/2025/Woche-1-2025-09-29.zh.jsx"
  },
  {
    "title": "第2周",
    "startDate": "2025-10-06",
    "id": "woche-2-2025-10-06-zh",
    "lang": "zh",
    "sidebar": "第2周 (2025-10-06)",
    "path": "./plans/2025/Woche-2-2025-10-06.zh.jsx"
  },
  {
    "title": "Woche 3",
    "startDate": "2025-10-13",
    "id": "woche-3-2025-10-13",
    "lang": "de",
    "sidebar": "Woche 3 (2025-10-13)",
    "path": "./plans/2025/Woche-3-2025-10-13.de.jsx"
  },
  {
    "title": "第3周",
    "startDate": "2025-10-13",
    "id": "woche-3-2025-10-13-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第3周 (2025-10-13)",
    "path": "./plans/2025/Woche-3-2025-10-13.zh.jsx"
  },
  {
    "title": "Woche 4",
    "startDate": "2025-10-20",
    "id": "woche-4-2025-10-20",
    "lang": "de",
    "sidebar": "[DE] Woche 4 (2025-10-20)",
    "path": "./plans/2025/Woche-4-2025-10-20.de.jsx"
  },
  {
    "title": "第4周",
    "startDate": "2025-10-20",
    "id": "woche-4-2025-10-20-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第4周 (2025-10-20)",
    "path": "./plans/2025/Woche-4-2025-10-20.zh.jsx"
  },
  {
    "title": "Woche 5",
    "startDate": "2025-10-27",
    "id": "woche-5-2025-10-27",
    "lang": "de",
    "sidebar": "[DE] Woche 5 (2025-10-27)",
    "path": "./plans/2025/Woche-5-2025-10-27.de.jsx"
  },
  {
    "title": "第5周",
    "startDate": "2025-10-27",
    "id": "woche-5-2025-10-27-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第5周 (2025-10-27)",
    "path": "./plans/2025/Woche-5-2025-10-27.zh.jsx"
  },
  {
    "title": "Woche 6",
    "startDate": "2025-11-03",
    "id": "woche-6-2025-11-03-de",
    "lang": "de",
    "sidebar": "[DE] Woche 6 (2025-11-03)",
    "path": "./plans/2025/Woche-6-2025-11-03.de.jsx"
  },
  {
    "title": "第6周",
    "startDate": "2025-11-03",
    "id": "woche-6-2025-11-03-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第6周 (2025-11-03)",
    "path": "./plans/2025/Woche-6-2025-11-03.zh.jsx"
  },
  {
    "title": "Woche 7",
    "startDate": "2025-11-10",
    "id": "woche-7-2025-11-10-de",
    "lang": "de",
    "sidebar": "[DE] Woche 7 (2025-11-10)",
    "path": "./plans/2025/Woche-7-2025-11-10.de.jsx"
  },
  {
    "title": "第7周",
    "startDate": "2025-11-10",
    "id": "zhou-7-2025-11-10-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第7周 (2025-11-10)",
    "path": "./plans/2025/Woche-7-2025-11-10.zh.jsx"
  },
  {
    "title": "Woche 8",
    "startDate": "2025-11-17",
    "id": "woche-8-2025-11-17-de",
    "lang": "de",
    "sidebar": "[DE] Woche 8 (2025-11-17)",
    "path": "./plans/2025/Woche-8-2025-11-17.de.jsx"
  },
  {
    "title": "第8周",
    "startDate": "2025-11-17",
    "id": "woche-8-2025-11-17-zh",
    "lang": "zh",
    "sidebar": "[ZH] 第8周 (2025-11-17)",
    "path": "./plans/2025/Woche-8-2025-11-17.zh.jsx"
  },
  {
    "title": "Woche 1",
    "startDate": "2025-12-29",
    "id": "woche-1-2025-12-29",
    "lang": "de",
    "sidebar": "Woche 1 (2025-12-29)",
    "path": "./plans/2026/Woche-1-2025-12-29.de.jsx"
  },
  {
    "title": "第1周",
    "startDate": "2025-12-29",
    "id": "woche-1-2025-12-29",
    "lang": "zh",
    "sidebar": "第1周（2025-12-29）",
    "path": "./plans/2026/Woche-1-2026-12-29.zh.jsx"
  },
  {
    "title": "Woche 2",
    "startDate": "2026-01-05",
    "id": "woche-2-2026-01-05",
    "lang": "de",
    "sidebar": "Woche 2 (2026-01-05)",
    "path": "./plans/2026/Woche-2-2026-01-05.de.jsx"
  },
  {
    "title": "第2周",
    "startDate": "2026-01-05",
    "id": "woche-2-2026-01-05",
    "lang": "zh",
    "sidebar": "第2周 (2026-01-05)",
    "path": "./plans/2026/Woche-2-2026-01-05.zh.jsx"
  },
  {
    "title": "Woche 3",
    "startDate": "2026-01-12",
    "id": "woche-3-2026-01-12",
    "lang": "de",
    "sidebar": "Woche 3 (2026-01-12)",
    "path": "./plans/2026/Woche-3-2026-01-12.de.jsx"
  },
  {
    "title": "第3周",
    "startDate": "2026-01-12",
    "id": "woche-3-2026-01-12",
    "lang": "zh",
    "sidebar": "第3周 (2026-01-12)",
    "path": "./plans/2026/Woche-3-2026-01-12.zh.jsx"
  },
  {
    "title": "Woche 4",
    "startDate": "2026-01-19",
    "id": "woche-4-2026-01-19",
    "lang": "de",
    "sidebar": "Woche 4 (2026-01-19)",
    "path": "./plans/2026/Woche-4-2026-01-19.de.jsx"
  },
  {
    "title": "第4周",
    "startDate": "2026-01-19",
    "id": "woche-4-2026-01-19",
    "lang": "zh",
    "sidebar": "第4周 (2026-01-19)",
    "path": "./plans/2026/Woche-4-2026-01-19.zh.jsx"
  },
  {
    "title": "Woche 5",
    "startDate": "2026-01-26",
    "id": "woche-5-2026-01-26",
    "lang": "de",
    "sidebar": "Woche 5 (2026-01-26)",
    "path": "./plans/2026/Woche-5-2026-01-26.de.jsx"
  },
  {
    "title": "第5周",
    "startDate": "2026-01-26",
    "id": "woche-5-2026-01-26",
    "lang": "zh",
    "sidebar": "第5周 (2026-01-26)",
    "path": "./plans/2026/Woche-5-2026-01-26.zh.jsx"
  },
  {
    "title": "Woche 6",
    "startDate": "2026-02-02",
    "id": "woche-6-2026-02-02",
    "lang": "de",
    "sidebar": "Woche 6 (2026-02-02)",
    "path": "./plans/2026/Woche-6-2026-02-02.de.jsx"
  },
  {
    "title": "Woche 7",
    "startDate": "2026-02-09",
    "id": "woche-7-2026-02-09",
    "lang": "de",
    "sidebar": "Woche 7 (2026-02-09)",
    "path": "./plans/2026/Woche-7-2026-02-09.de.jsx"
  },
  {
    "title": "Woche 8",
    "startDate": "2026-02-16",
    "id": "woche-8-2026-02-16",
    "lang": "de",
    "sidebar": "Woche 8 (2026-02-16)",
    "path": "./plans/2026/Woche-8-2026-02-16.de.jsx"
  },
  {
    "title": "Woche 9",
    "startDate": "2026-02-23",
    "id": "woche-9-2026-02-23",
    "lang": "de",
    "sidebar": "Woche 9 (2026-02-23)",
    "path": "./plans/2026/Woche-9-2026-02-23.de.jsx"
  },
  {
    "title": "Woche 10",
    "startDate": "2026-03-02",
    "id": "woche-10-2026-03-02",
    "lang": "de",
    "sidebar": "Woche 10 (2026-03-02)",
    "path": "./plans/2026/Woche-10-2026-03-02.de.jsx"
  },
  {
    "title": "Woche 11",
    "startDate": "2026-03-09",
    "id": "woche-11-2026-03-09",
    "lang": "de",
    "sidebar": "Woche 11 (2026-03-09)",
    "path": "./plans/2026/Woche-11-2026-03-09.de.jsx"
  },
  {
    "title": "Woche 12",
    "startDate": "2026-03-16",
    "id": "woche-12-2026-03-16",
    "lang": "de",
    "sidebar": "Woche 12 (2026-03-16)",
    "path": "./plans/2026/Woche-12-2026-03-16.de.jsx"
  },
  {
    "title": "Woche 13",
    "startDate": "2026-03-23",
    "id": "woche-13-2026-03-23",
    "lang": "de",
    "sidebar": "Woche 13 (2026-03-23)",
    "path": "./plans/2026/Woche-13-2026-03-23.de.jsx"
  },
  {
    "title": "Woche 14",
    "startDate": "2026-03-30",
    "id": "woche-14-2026-03-30",
    "lang": "de",
    "sidebar": "Woche 14 (2026-03-30)",
    "path": "./plans/2026/Woche-14-2026-03-30.de.jsx"
  },
  {
    "title": "Woche 15",
    "startDate": "2026-04-06",
    "id": "woche-15-2026-04-06",
    "lang": "de",
    "sidebar": "Woche 15 (2026-04-06)",
    "path": "./plans/2026/Woche-15-2026-04-06.de.jsx"
  },
  {
    "title": "Woche 16",
    "startDate": "2026-04-13",
    "id": "woche-16-2026-04-13",
    "lang": "de",
    "sidebar": "Woche 16 (2026-04-13)",
    "path": "./plans/2026/Woche-16-2026-04-13.de.jsx"
  },
  {
    "title": "Woche 17",
    "startDate": "2026-04-20",
    "id": "woche-17-2026-04-20",
    "lang": "de",
    "sidebar": "Woche 17 (2026-04-20)",
    "path": "./plans/2026/Woche-17-2026-04-20.de.jsx"
  },
  {
    "title": "Woche 18",
    "startDate": "2026-04-27",
    "id": "woche-18-2026-04-27",
    "lang": "de",
    "sidebar": "Woche 18 (2026-04-27)",
    "path": "./plans/2026/Woche-18-2026-04-27.de.jsx"
  },
  {
    "title": "Woche 19",
    "startDate": "2026-05-04",
    "id": "woche-19-2026-05-04",
    "lang": "de",
    "sidebar": "Woche 19 (2026-05-04)",
    "path": "./plans/2026/Woche-19-2026-05-04.de.jsx"
  },
  {
    "title": "Woche 20",
    "startDate": "2026-05-11",
    "id": "woche-20-2026-05-11",
    "lang": "de",
    "sidebar": "Woche 20 (2026-05-11)",
    "path": "./plans/2026/Woche-20-2026-05-11.de.jsx"
  },
  {
    "title": "Woche 21",
    "startDate": "2026-05-18",
    "id": "woche-21-2026-05-18",
    "lang": "de",
    "sidebar": "Woche 21 (2026-05-18)",
    "path": "./plans/2026/Woche-21-2026-05-18.de.jsx"
  },
  {
    "title": "Woche 22",
    "startDate": "2026-05-25",
    "id": "woche-22-2026-05-25",
    "lang": "de",
    "sidebar": "Woche 22 (2026-05-25)",
    "path": "./plans/2026/Woche-22-2026-05-25.de.jsx"
  },
  {
    "title": "Woche 23",
    "startDate": "2026-06-01",
    "id": "woche-23-2026-06-01",
    "lang": "de",
    "sidebar": "Woche 23 (2026-06-01)",
    "path": "./plans/2026/Woche-23-2026-06-01.de.jsx"
  },
  {
    "title": "Woche 24",
    "startDate": "2026-06-08",
    "id": "woche-24-2026-06-08",
    "lang": "de",
    "sidebar": "Woche 24 (2026-06-08)",
    "path": "./plans/2026/Woche-24-2026-06-08.de.jsx"
  },
  {
    "title": "Woche 25",
    "startDate": "2026-06-15",
    "id": "woche-25-2026-06-15",
    "lang": "de",
    "sidebar": "Woche 25 (2026-06-15)",
    "path": "./plans/2026/Woche-25-2026-06-15.de.jsx"
  },
  {
    "title": "Woche 26",
    "startDate": "2026-06-22",
    "id": "woche-26-2026-06-22",
    "lang": "de",
    "sidebar": "Woche 26 (2026-06-22)",
    "path": "./plans/2026/Woche-26-2026-06-22.de.jsx"
  },
  {
    "title": "Woche 27",
    "startDate": "2026-06-29",
    "id": "woche-27-2026-06-29",
    "lang": "de",
    "sidebar": "Woche 27 (2026-06-29)",
    "path": "./plans/2026/Woche-27-2026-06-29.de.jsx"
  },
  {
    "title": "Woche 28",
    "startDate": "2026-07-06",
    "id": "woche-28-2026-07-06",
    "lang": "de",
    "sidebar": "Woche 28 (2026-07-06)",
    "path": "./plans/2026/Woche-28-2026-07-06.de.jsx"
  },
  {
    "title": "Woche 29",
    "startDate": "2026-07-13",
    "id": "woche-29-2026-07-13",
    "lang": "de",
    "sidebar": "Woche 29 (2026-07-13)",
    "path": "./plans/2026/Woche-29-2026-07-13.de.jsx"
  },
  {
    "title": "Woche 30",
    "startDate": "2026-07-20",
    "id": "woche-30-2026-07-20",
    "lang": "de",
    "sidebar": "Woche 30 (2026-07-20)",
    "path": "./plans/2026/Woche-30-2026-07-20.de.jsx"
  },
  {
    "title": "Woche 31",
    "startDate": "2026-07-27",
    "id": "woche-31-2026-07-27",
    "lang": "de",
    "sidebar": "Woche 31 (2026-07-27)",
    "path": "./plans/2026/Woche-31-2026-07-27.de.jsx"
  },
  {
    "title": "Woche 32",
    "startDate": "2026-08-03",
    "id": "woche-32-2026-08-03",
    "lang": "de",
    "sidebar": "Woche 32 (2026-08-03)",
    "path": "./plans/2026/Woche-32-2026-08-03.de.jsx"
  },
  {
    "title": "Woche 33",
    "startDate": "2026-08-10",
    "id": "woche-33-2026-08-10",
    "lang": "de",
    "sidebar": "Woche 33 (2026-08-10)",
    "path": "./plans/2026/Woche-33-2026-08-10.de.jsx"
  },
  {
    "title": "Woche 34",
    "startDate": "2026-08-17",
    "id": "woche-34-2026-08-17",
    "lang": "de",
    "sidebar": "Woche 34 (2026-08-17)",
    "path": "./plans/2026/Woche-34-2026-08-17.de.jsx"
  },
  {
    "title": "Woche 35",
    "startDate": "2026-08-24",
    "id": "woche-35-2026-08-24",
    "lang": "de",
    "sidebar": "Woche 35 (2026-08-24)",
    "path": "./plans/2026/Woche-35-2026-08-24.de.jsx"
  },
  {
    "title": "Woche 36",
    "startDate": "2026-08-31",
    "id": "woche-36-2026-08-31",
    "lang": "de",
    "sidebar": "Woche 36 (2026-08-31)",
    "path": "./plans/2026/Woche-36-2026-08-31.de.jsx"
  }
];
