// src/plans/techniques.ts
// "Kochtechniken" — Referenz-Bereich (kein Rezept-Format): erklärt wiederkehrende Handgriffe der
// chinesischen/japanischen/koreanischen Küche (Marinieren, Zart machen, Blanchieren, ...), die in
// vielen Rezepten der App vorkommen, aber nirgends erklärt werden.

export type Technique = {
  id: string;
  /** Kapitel-Gruppierung, z.B. "Marinieren & Zart machen", "Vorgaren & Blanchieren". */
  category: string;
  emoji: string;
  title: string;
  desc: string;
  method: string[];
  tips: string[];
  usedIn: string;
  tags: string[];
};

export const TECHNIQUES: Technique[] = [
  {
    id: "china-shang-jiang-velveting",
    category: "Marinieren & Zart machen",
    emoji: "🥢",
    title: "Shang Jiang — Velveting (上漿)",
    desc: "Die chinesische Restaurant-Technik für seidig-zartes Fleisch in Wok-Gerichten: dünn geschnittenes Fleisch wird in einer Eiweiß-Stärke-Marinade beschichtet und vor dem eigentlichen Braten kurz in warmem Öl oder Wasser vorgegart.",
    method: [
      "Fleisch (Hähnchen, Rind oder Garnelen) in dünne Scheiben oder Streifen schneiden.",
      "Mit 1 Eiweiß, 1–2 EL Speisestärke, 1 EL Shaoxing-Wein und 1 TL Wasser vermengen, 15–20 Min. im Kühlschrank ziehen lassen.",
      "In moderat warmem Öl (ca. 120–140 °C) oder leicht köchelndem Wasser 20–30 Sek. vorgaren, bis die Oberfläche gerade opak ist — nicht durchgaren.",
      "Abtropfen lassen, dann erst im heißen Wok mit der eigentlichen Sauce kurz fertig braten.",
    ],
    tips: [
      "Bei zähen Fleischstücken (z. B. günstigeres Rind) eine Prise Natron zur Marinade geben — macht zusätzlich zart (siehe auch die separate Natron-Technik).",
      "Das Vorgaren nur kurz halten — Ziel ist eine schützende Außenschicht, das Fleisch gart im Wok fertig.",
      "Funktioniert auch im Wasserbad statt in Öl, wenn weniger Fett gewünscht ist.",
    ],
    usedIn: "Klassische Wok-Gerichte wie Kung-Pao-Hähnchen, Rind mit Brokkoli, süß-saure Garnelen.",
    tags: ["China", "Zart machen", "Wok"],
  },
  {
    id: "china-natron-zartmachen",
    category: "Marinieren & Zart machen",
    emoji: "🧂",
    title: "Natron-Zartmachen (嫩肉)",
    desc: "Eine kleine Menge Natron (Backpulver-Basis, nicht Backpulver selbst) hebt den pH-Wert der Fleischoberfläche an und macht dünn geschnittenes Fleisch für Wok-Gerichte deutlich zarter — die Standard-Restaurant-Technik hinter besonders zartem Rind oder Hähnchen.",
    method: [
      "Ca. 1/4–1/2 TL Natron auf 250 g dünn geschnittenes Fleisch geben.",
      "Mit den Händen 2–3 Min. gründlich einmassieren, bis das Fleisch leicht klebrig wirkt.",
      "15–20 Min. im Kühlschrank ruhen lassen (nicht länger, sonst wird die Textur seifig).",
      "Vor dem Weiterverarbeiten gründlich unter kaltem Wasser abspülen und trockentupfen, dann normal marinieren/velveten.",
    ],
    tips: [
      "Nicht überdosieren — zu viel Natron hinterlässt einen seifigen Nachgeschmack, der auch durch Abspülen nicht mehr weggeht.",
      "Lässt sich gut mit Shang-Jiang-Velveting kombinieren: erst Natron, abspülen, dann die Eiweiß-Stärke-Marinade.",
      "Besonders wirksam bei günstigeren, faserigeren Fleischstücken.",
    ],
    usedIn: "Günstigere Rindfleisch-Cuts in Wok-Gerichten, manchmal auch bei Hähnchenbrust.",
    tags: ["China", "Zart machen", "Wok"],
  },
  {
    id: "china-pai-smash-technik",
    category: "Marinieren & Zart machen",
    emoji: "🔨",
    title: "Pai — Plattklopfen (拍)",
    desc: "Mit der Breitseite eines Messers oder Wok-Wenders werden Knoblauch, Ingwer oder Gemüse wie Gurke grob zerschlagen statt geschnitten — die aufgerissene Oberfläche nimmt Marinaden und Saucen viel schneller und gleichmäßiger auf.",
    method: [
      "Zutat (z. B. Knoblauchzehe oder Salatgurke) auf ein Schneidebrett legen.",
      "Mit der breiten Seite eines Kochmessers oder der flachen Hand kräftig, aber kontrolliert draufschlagen, bis sie aufreißt.",
      "Grob in unregelmäßige Stücke weiterzerteilen — die unregelmäßigen Bruchkanten sind gewollt.",
      "Direkt mit Marinade/Dressing vermengen — zieht durch die aufgerissene Struktur deutlich schneller ein.",
    ],
    tips: [
      "Bei Gurken vor dem Plattklopfen die Kerne bei Bedarf entfernen, sonst wird der Salat wässrig.",
      "Nicht zu fein zerkleinern — die unregelmäßige Textur ist Teil des gewünschten Ergebnisses (siehe Smashed-Gurken-Salat).",
      "Bei Knoblauch/Ingwer lässt sich so auch die Schale leichter entfernen.",
    ],
    usedIn: "Smashed-Gurken-Salat (拍黃瓜), Knoblauch-/Ingwer-Basen für Saucen und Marinaden.",
    tags: ["China", "Vorbereitung", "Kalte Küche"],
  },
  {
    id: "japan-shio-koji-marinade",
    category: "Marinieren & Zart machen",
    emoji: "🍶",
    title: "Shio-Koji-Marinade (塩麹漬け)",
    desc: "Fermentierter Reis-Koji mit Salz enthält aktive Enzyme (Protease, Amylase), die Fleisch und Fisch von innen heraus zart machen und gleichzeitig einen milden, umami-reichen Süße-Geschmack entwickeln — ganz ohne Zucker.",
    method: [
      "Fleisch oder Fisch dünn mit Shio Koji (fertig im Asia-Laden erhältlich oder aus Koji-Reis + Salz + Wasser selbst angesetzt) bestreichen.",
      "In einem verschlossenen Beutel 30 Min. bis 24 Std. im Kühlschrank ziehen lassen — je länger, desto intensiver und zarter.",
      "Vor dem Braten überschüssige Koji-Paste abwischen (nicht abspülen, das nimmt den Geschmack wieder mit).",
      "Bei mittlerer Hitze braten/grillen — Koji enthält natürlichen Zucker und verbrennt bei zu hoher Hitze schnell.",
    ],
    tips: [
      "Für Fisch reichen meist 30–60 Min., für zähere Fleischstücke ruhig über Nacht.",
      "Restliche Marinade nicht weiterverwenden (war in Kontakt mit rohem Fleisch/Fisch).",
      "Funktioniert auch bei Tofu für eine vegetarische Variante mit mehr Umami.",
    ],
    usedIn: "Shio-Koji-Lachs im Ofen, generell als Alternative zu Sojasauce-Marinaden mit weniger Salz.",
    tags: ["Japan", "Zart machen", "Fermentiert"],
  },
  {
    id: "korea-yangnyeom-marinade",
    category: "Marinieren & Zart machen",
    emoji: "🍐",
    title: "Yangnyeom-Marinade (양념)",
    desc: "Die koreanische Basis-Marinadentechnik für Bulgogi & Co.: eine dickflüssige Würzpaste aus Sojasauce, Knoblauch, Sesamöl und geriebener Birne oder Kiwi — die Fruchtenzyme machen das Fleisch zusätzlich zart.",
    method: [
      "Birne (oder Kiwi) fein reiben oder pürieren — die enthaltenen Enzyme (u. a. Bromelain-ähnlich) brechen Muskelfasern auf.",
      "Mit Sojasauce, Knoblauch, Ingwer, Sesamöl, etwas Zucker und Frühlingszwiebel zu einer dicken Paste verrühren.",
      "Dünn geschnittenes Fleisch großzügig mit der Paste vermengen, mindestens 30 Min., besser 2–24 Std. im Kühlschrank ziehen lassen.",
      "Direkt aus der Marinade scharf anbraten oder grillen — die Zuckeranteile karamellisieren gut bei hoher Hitze.",
    ],
    tips: [
      "Kiwi ist enzymatisch stärker als Birne — bei empfindlicheren Fleischstücken vorsichtig dosieren, sonst wird die Textur matschig statt zart.",
      "Für Freezer-Bags: Fleisch direkt roh in der Marinade einfrieren, dann im Kühlschrank auftauen und braten.",
      "Funktioniert genauso gut mit magerem Hähnchen wie mit Rind oder Schwein.",
    ],
    usedIn: "Bulgogi, Dak-Bulgogi, Dwaeji-Bulgogi und die meisten koreanischen Grill-Marinaden dieser App.",
    tags: ["Korea", "Zart machen", "Grill/Wok"],
  },
  {
    id: "china-chao-shui-blanchieren",
    category: "Vorgaren & Blanchieren",
    emoji: "♨️",
    title: "Chao Shui — Blanchieren (焯水)",
    desc: "Kurzes Vorkochen von Fleisch, Knochen oder Gemüse in Wasser, um Blut, Schaum und unerwünschte Aromen zu entfernen, bevor das eigentliche Gericht weitergegart wird — die Basis für klare Brühen und sauber schmeckende Schmorgerichte.",
    method: [
      "Für Fleisch/Knochen: mit KALTEM Wasser (plus Ingwer/Frühlingszwiebel/etwas Wein) aufsetzen, langsam zum Kochen bringen — so tritt Blut gleichmäßig aus statt an der Oberfläche zu versiegeln.",
      "Sobald grauer Schaum aufsteigt, 1–2 Min. weiterköcheln, dann Fleisch herausnehmen und unter fließendem Wasser abspülen.",
      "Für Gemüse: in bereits KOCHENDES Wasser geben (umgekehrtes Prinzip) — kurz blanchieren, dann sofort in Eiswasser abschrecken, um Farbe und Biss zu erhalten.",
      "Blanchierwasser bei Fleisch/Knochen wegschütten, nicht als Brühen-Basis weiterverwenden.",
    ],
    tips: [
      "Kalt starten bei Fleisch, heiß starten bei Gemüse — die Eselsbrücke, die sich die meisten Regeln merkt.",
      "Besonders wichtig vor Schmorgerichten wie Hong Shao Rou oder vor dem Ansetzen klarer Brühen.",
      "Holzohrpilze und ähnliche getrocknete Pilze sollten aus Sicherheitsgründen immer blanchiert werden, nie roh gegessen.",
    ],
    usedIn: "Rinderknochenbrühe, Hong Shao Rou, Löwenkopf-Fleischbällchen, Holzohrpilz-Salat.",
    tags: ["China", "Vorgaren", "Brühe"],
  },
  {
    id: "japan-shimofuri-blutabspuelen",
    category: "Vorgaren & Blanchieren",
    emoji: "🧊",
    title: "Shimofuri (霜降り)",
    desc: "Fleisch, Fisch oder Innereien werden nur wenige Sekunden in kochendes Wasser getaucht und sofort in Eiswasser abgeschreckt — die Oberfläche gerinnt, Blut und Geruchsstoffe treten aus, das Innere bleibt roh.",
    method: [
      "Wasser zum Kochen bringen, parallel eine Schüssel Eiswasser bereitstellen.",
      "Fleisch/Fisch für nur 5–15 Sek. ins kochende Wasser geben, bis die Oberfläche sichtbar grau-weiß wird.",
      "Sofort mit einer Schaumkelle herausnehmen und direkt ins Eiswasser geben, um den Garvorgang zu stoppen.",
      "Trockentupfen, dann erst danach weiterverarbeiten (z. B. in den Nabe-Topf geben oder aufschneiden).",
    ],
    tips: [
      "Zeit ist entscheidend — bei zu langem Blanchieren gart das Fleisch durch statt nur an der Oberfläche zu gerinnen.",
      "Das Eiswasser-Bad ist kein optionaler Schritt: ohne sofortiges Abschrecken gart der Kern nach.",
      "Klassisch vor allem bei Rindfleisch, Hühnchen und manchen Innereien für Nabe (Hot Pot) verwendet.",
    ],
    usedIn: "Vorbereitung für Nabe-Hot-Pot, generell zum Entfernen von Blut/Fischgeruch vor dem Weiterverarbeiten.",
    tags: ["Japan", "Vorgaren", "Hot Pot"],
  },
  {
    id: "korea-dechigi-blanchieren",
    category: "Vorgaren & Blanchieren",
    emoji: "🥬",
    title: "Dechigi — Gemüse blanchieren (데치기)",
    desc: "Blattgemüse wie Spinat wird kurz in kochendem Salzwasser blanchiert und danach in kaltem Wasser abgeschreckt — die Standard-Vorbereitung für viele koreanische Namul-/Banchan-Beilagen.",
    method: [
      "Wasser mit einer Prise Salz zum Kochen bringen.",
      "Gemüse (z. B. Spinat, Sojasprossen) für 30–60 Sek. blanchieren, bis es gerade weich, aber noch farbintensiv ist.",
      "Sofort in kaltem Wasser abschrecken, um Farbe und Nährstoffe zu erhalten.",
      "Gründlich ausdrücken, bevor es mit Sesamöl, Knoblauch und Sojasauce zu Namul angemacht wird.",
    ],
    tips: [
      "Sojasprossen brauchen etwas länger (2–3 Min.) und sollten dabei nicht umgerührt werden, sonst wird der Geruch bitter.",
      "Blanchiertes Gemüse gut ausdrücken — überschüssiges Wasser verwässert das spätere Dressing.",
      "Lässt sich gut vorbereiten und portionsweise im Kühlschrank für spätere Banchan-Zubereitung lagern.",
    ],
    usedIn: "Sigeumchi-Namul (Spinat-Beilage), Sukjunamul (Sojasprossen-Beilage) und andere Banchan.",
    tags: ["Korea", "Vorgaren", "Banchan"],
  },
  {
    id: "china-gua-hu-mehlmantel",
    category: "Frittieren & Kruste",
    emoji: "🍤",
    title: "Gua Hu — Trockener Stärkemantel (掛糊)",
    desc: "Anders als beim nassen Velveting (Shang Jiang) wird die Zutat hier kurz vor dem Frittieren trocken in Stärke oder Mehl gewendet — die einfachste Panade für eine knusprige Kruste, ganz ohne Ei-Eiweiß-Marinade.",
    method: [
      "Fleisch, Fisch oder Gemüse trockentupfen — Feuchtigkeit lässt die Stärke klumpen statt gleichmäßig haften.",
      "Direkt vor dem Frittieren dünn und gleichmäßig in Speisestärke oder Mehl wenden, überschüssiges abklopfen.",
      "Sofort ins heiße Öl geben — je länger die trockene Panade wartet, desto eher zieht sie Feuchtigkeit und wird klebrig.",
      "Bei mittelhoher Hitze goldbraun frittieren, bis die Kruste fest und knusprig ist.",
    ],
    tips: [
      "Für eine dickere, blasige Kruste Stärke und Wasser zu einem dünnen Teig verrühren statt trocken zu panieren — beides fällt unter Gua Hu, nur mit oder ohne Flüssigkeit.",
      "Maisstärke ergibt eine leichtere, glasigere Kruste als Weizenmehl.",
      "Nicht mit Shang-Jiang-Velveting verwechseln: Gua Hu ist die letzte Panade vor dem Frittieren, Velveting eine vorherige Garzart-Marinade — beide lassen sich sogar kombinieren.",
    ],
    usedIn: "Süß-saures Schweinefleisch, frittierte Garnelen, viele Straßenimbiss-Snacks.",
    tags: ["China", "Frittieren", "Panade"],
  },
  {
    id: "china-doppelt-frittieren",
    category: "Frittieren & Kruste",
    emoji: "🔥",
    title: "Doppelt frittieren (復炸)",
    desc: "Zweimal frittieren statt einmal: der erste, kühlere Durchgang gart das Innere und drückt Feuchtigkeit an die Oberfläche, der zweite, heißere Durchgang verwandelt diese Feuchtigkeit in eine extra-knusprige, nicht fettige Kruste.",
    method: [
      "Erster Durchgang bei ca. 150–160 °C, bis das Fleisch gerade gar ist, aber noch blass — Ziel ist Garen, nicht Bräunen.",
      "Herausnehmen, 5–10 Min. bei Zimmertemperatur ruhen lassen (auf einem Gitter, nicht auf Küchenpapier — sonst wird die Unterseite feucht).",
      "Öl auf 190–200 °C erhitzen, dann ein zweites Mal für 1–2 Min. frittieren, bis tief goldbraun und hörbar knusprig.",
      "Sofort auf einem Gitter abtropfen lassen, nicht stapeln — sonst weicht die Kruste durch eingeschlossenen Dampf wieder auf.",
    ],
    tips: [
      "Die Ruhepause zwischen den beiden Durchgängen ist der eigentliche Trick — in dieser Zeit wandert Restfeuchtigkeit von innen an die Oberfläche und kann beim zweiten Frittieren verdampfen.",
      "Bei dünn paniertem Hähnchen (koreanischer Stil) ergibt diese Technik eine besonders dünne, glasig-knusprige Kruste bei saftigem Kern.",
      "Funktioniert nur mit ausreichend Ölmenge/-temperatur-Stabilität — kleine Portionen nacheinander frittieren, sonst sinkt die Temperatur zu stark.",
    ],
    usedIn: "Koreanisches Fried Chicken (양념치킨-Basis), Xiaosurou (kross frittiertes Schweinefleisch), viele Wok-Restaurant-Frittiergerichte.",
    tags: ["China/Korea", "Frittieren", "Kruste"],
  },
  {
    id: "japan-tempura-teig",
    category: "Frittieren & Kruste",
    emoji: "❄️",
    title: "Tempura-Teig — eiskalt & kaum gerührt (天ぷら衣)",
    desc: "Der leichte, blasige Tempura-Teig entsteht nicht durch eine besondere Zutat, sondern durch zwei Regeln: eiskaltes Wasser und so wenig Rühren wie möglich — beides verhindert, dass sich Gluten im Mehl entwickelt und der Teig schwer/zäh wird.",
    method: [
      "Sehr kaltes Wasser (am besten mit Eiswürfeln) mit Mehl (idealerweise glutenarmes Mehl) und optional 1 verquirltem Ei nur GROB vermengen.",
      "Klümpchen im Teig bewusst stehen lassen — glattrühren entwickelt Gluten und macht die Kruste zäh statt knusprig.",
      "Zutaten (Gemüse, Garnelen) trockentupfen, dünn durch den Teig ziehen, überschüssigen Teig abtropfen lassen.",
      "Bei ca. 170–180 °C frittieren, bis die Kruste hell-golden und fest ist — Tempura soll bewusst blasser bleiben als westliches Frittiertes.",
    ],
    tips: [
      "Teig immer erst kurz vor dem Frittieren anrühren, nie auf Vorrat — er verliert seine Leichtigkeit, sobald er steht und Gluten nachbildet.",
      "Eiswürfel direkt mit in die Teigschüssel geben hält die Temperatur während des gesamten Frittiervorgangs niedrig.",
      "Sprudelwasser statt stillem Wasser macht den Teig durch die Kohlensäure zusätzlich leichter.",
    ],
    usedIn: "Gemüse- und Garnelen-Tempura, generell als leichtere Alternative zu Panko-Panaden.",
    tags: ["Japan", "Frittieren", "Panade"],
  },
  {
    id: "japan-katsu-panko",
    category: "Frittieren & Kruste",
    emoji: "🍞",
    title: "Katsu-Panade — Mehl, Ei, Panko (パン粉)",
    desc: "Die dreistufige japanische Panier-Technik für eine extra-knusprige, luftige Kruste: grobe Panko-Flocken (statt feiner Semmelbrösel) sorgen für deutlich mehr Oberfläche und Crunch als klassisches Paniermehl.",
    method: [
      "Fleisch/Fisch dünn und gleichmäßig in Mehl wenden, überschüssiges abklopfen — die trockene Grundschicht sorgt dafür, dass das Ei danach gleichmäßig haftet.",
      "Durch verquirltes Ei ziehen, vollständig benetzen lassen.",
      "In Panko-Flocken drücken (nicht nur wenden) — die groben Flocken sollen sich fest mit der Eischicht verbinden.",
      "Bei ca. 170–180 °C frittieren, bis die Panko-Kruste tief golden ist.",
    ],
    tips: [
      "Panko ist gröber und trockener als westliches Paniermehl (aus krustenlosem Toast hergestellt) — das schafft mehr Luftraum in der Kruste und dadurch mehr Crunch bei weniger Fettaufnahme.",
      "Panierte Stücke vor dem Frittieren kurz ruhen lassen (5 Min.) — die Panade haftet dann besser und fällt beim Frittieren nicht ab.",
      "Funktioniert genauso mit dem Airfryer statt Frittieröl, braucht dann aber etwas Sprühöl für die Bräunung.",
    ],
    usedIn: "Tonkatsu, Ebi Fry (panierte Garnelen), Chicken Katsu.",
    tags: ["Japan", "Frittieren", "Panade"],
  },
  {
    id: "korea-doppelt-frittiertes-huehnchen",
    category: "Frittieren & Kruste",
    emoji: "🍗",
    title: "Koreanisches Fried Chicken — dünne Panade, doppelt frittiert",
    desc: "Der koreanische Stil setzt bewusst auf eine sehr dünne Stärke-Panade statt einer dicken Mehlkruste — kombiniert mit der Doppel-Frittier-Technik entsteht eine glasig-knusprige Schale, die auch nach dem Bestreichen mit Sauce nicht durchweicht.",
    method: [
      "Hähnchenteile nur dünn in Speisestärke (nicht Mehl) wenden — die Schicht soll fast durchsichtig wirken, nicht dick und mehlig.",
      "Erster Frittiergang bei ca. 160 °C, bis gerade gar.",
      "5–10 Min. ruhen lassen, dann zweiter Frittiergang bei ca. 190 °C für 1–2 Min. bis tief knusprig.",
      "Erst danach mit der Sauce (Yangnyeom) vermengen — direktes Sauce-Tossing der heißen, knusprigen Kruste erhält den Crunch länger als vorheriges Mischen.",
    ],
    tips: [
      "Je dünner die Panade, desto knuspriger und desto weniger 'mehlig' schmeckt das Ergebnis — Widerstand gegen die Versuchung, dick zu panieren.",
      "Die Sauce erst kurz vor dem Servieren zugeben, sonst erweicht sie die dünne Kruste innerhalb weniger Minuten.",
      "Gut mit der separaten Yangnyeom-Marinade-Technik kombinierbar, wenn das Fleisch vor dem Panieren zusätzlich mariniert werden soll.",
    ],
    usedIn: "Yangnyeom-Chikin, Korean Fried Chicken generell.",
    tags: ["Korea", "Frittieren", "Kruste"],
  },
  {
    id: "china-ge-shui-zheng-fisch",
    category: "Dämpfen & Sanftgaren",
    emoji: "🐟",
    title: "Ge Shui Zheng — Dämpfen über Wasser (隔水蒸)",
    desc: "Die kantonesische Standard-Methode für ganzen Fisch: über (nicht in) kochendem Wasser gegart, bleibt das Fleisch extrem zart und saftig — die eigentliche Würze kommt erst danach durch heißes Öl, das über Ingwer und Frühlingszwiebel gegossen wird.",
    method: [
      "Fisch auf einen hitzebeständigen Teller legen, mit Ingwerscheiben und etwas Frühlingszwiebel im Bauchraum und außen belegen.",
      "Über bereits kräftig kochendem Wasser im Dampfeinsatz garen — Deckel geschlossen halten, bis der Fisch am dicksten Punkt gerade durch ist (ca. 8–10 Min. für einen mittelgroßen Fisch).",
      "Austretende Flüssigkeit vom Teller abgießen, mit frischer Frühlingszwiebel und Ingwerstreifen belegen.",
      "Sojasauce über den Fisch geben, dann sehr heißes Öl (kurz vor Rauchpunkt) darübergießen — das Zischen 'gart' die Aromaten und verteilt ihr Aroma sofort im ganzen Gericht.",
    ],
    tips: [
      "Nicht zu lange dämpfen — Fisch gart schnell nach, lieber 1 Minute zu früh vom Dampf nehmen und mit der Resthitze fertig ziehen lassen.",
      "Das heiße Öl am Ende ist kein optionaler Deko-Schritt, sondern der Hauptgeschmacksträger des ganzen Gerichts.",
      "Funktioniert am besten mit sehr frischem, magerem Weißfisch — fetter Fisch wird bei dieser milden Garmethode schnell fad.",
    ],
    usedIn: "Kantonesisch gedämpfter Fisch (清蒸魚), generell für ganze Fische oder Fischfilets.",
    tags: ["China", "Dämpfen", "Fisch"],
  },
  {
    id: "japan-sakamushi-sake-daempfen",
    category: "Dämpfen & Sanftgaren",
    emoji: "🍶",
    title: "Sakamushi — Dämpfen mit Sake (酒蒸し)",
    desc: "Fisch, Muscheln oder Hähnchen werden mit reichlich Sake statt nur Wasser gedämpft — der Alkohol löst und mildert Fischgeruch, hinterlässt aber selbst nur eine leichte, aromatische Restflüssigkeit als Basis für eine Sauce.",
    method: [
      "Hauptzutat (z. B. Muscheln, weißer Fisch, Hähnchenbrust) mit reichlich Sake (mind. 2–3 EL pro Portion) und etwas Ingwer in einen Topf oder eine Pfanne mit Deckel geben.",
      "Bei mittlerer Hitze zugedeckt dämpfen, bis gar — bei Muscheln, bis sich die Schalen öffnen, bei Fisch/Hähnchen einige Minuten je nach Dicke.",
      "Die zurückbleibende, mit Sake und Kochsäften angereicherte Flüssigkeit als leichte Sauce über die Zutat geben oder für eine Sauce reduzieren.",
      "Mit Frühlingszwiebel oder Yuzu-Schale abschließen.",
    ],
    tips: [
      "Der Alkohol verkocht größtenteils, das Aroma und die geruchsmildernde Wirkung bleiben — für Kinder/Schwangerschaft trotzdem lange genug köcheln lassen, bis kein Alkoholgeruch mehr wahrnehmbar ist.",
      "Funktioniert auch mit trockenem Weißwein als Ersatz, wenn kein Sake zur Hand ist, verändert aber den Geschmackscharakter leicht.",
      "Besonders gut für Zutaten geeignet, die schnell trocken werden — die Dampfmethode hält sie saftig.",
    ],
    usedIn: "Asari no Sakamushi (gedämpfte Venusmuscheln), gedämpftes Hähnchen mit Frühlingszwiebel-Sauce.",
    tags: ["Japan", "Dämpfen", "Meeresfrüchte"],
  },
  {
    id: "korea-jjim-schmordaempfen",
    category: "Dämpfen & Sanftgaren",
    emoji: "🍲",
    title: "Jjim — Schmoren/Dämpfen in Sauce (찜)",
    desc: "Jjim bezeichnet keine einzelne Technik, sondern eine Familie langsamer Garmethoden, bei denen mariniertes Fleisch, Fisch oder Gemüse in wenig, stark gewürzter Flüssigkeit gart, bis diese fast vollständig eingedickt ist.",
    method: [
      "Hauptzutat vorher würzen/marinieren (z. B. mit Sojasauce, Knoblauch, Ingwer, Zucker) — Jjim baut auf bereits aromatisiertem Ausgangsmaterial auf, nicht auf einer separaten Sauce, die erst am Ende zugegeben wird.",
      "Mit wenig Flüssigkeit (Marinade + etwas Wasser/Brühe) aufsetzen — genug zum Garen, aber nicht so viel wie bei einer Suppe.",
      "Bei niedriger bis mittlerer Hitze zugedeckt langsam garen/köcheln, bis die Hauptzutat zart ist und die Flüssigkeit auf eine dicke, klebrige Sauce reduziert ist.",
      "Gegen Ende oft ungedeckt fertiggaren, damit die Sauce am Boden nicht anbrennt, sondern gleichmäßig eindickt.",
    ],
    tips: [
      "Je nach Zutat reicht die Spanne von kurzem Dämpfen (Fisch, Meeresfrüchte, ca. 15–20 Min.) bis zu langem Schmoren (Rippchen, 1–2 Std.) — Jjim ist eine Methoden-Familie, keine feste Zeitangabe.",
      "Die Sauce sollte am Ende so eingedickt sein, dass sie am Fleisch klebt, nicht mehr wie eine flüssige Brühe wirkt.",
      "Ein Klassiker für Meal-Prep: Jjim-Gerichte schmecken aufgewärmt oft noch intensiver, weil die Sauce weiter einzieht.",
    ],
    usedIn: "Galbijjim (geschmorte Kurzrippen), Agujjim (geschmorter Seeteufel), Gyeranjjim (gedämpftes Ei).",
    tags: ["Korea", "Dämpfen", "Schmoren"],
  },
  {
    id: "china-shaguo-sanftes-schmoren",
    category: "Dämpfen & Sanftgaren",
    emoji: "🍯",
    title: "Shaguo — Sanftes Schmoren im Tontopf (砂鍋)",
    desc: "Der chinesische Tontopf speichert und verteilt Hitze deutlich sanfter und gleichmäßiger als Metalltöpfe — ideal für lange, langsame Garzeiten, bei denen Fleisch zart wird, ohne am Boden anzusetzen.",
    method: [
      "Tontopf vor der ersten Nutzung einmal mit Reiswasser oder Congee einkochen (füllt feine Poren, verhindert Rissbildung bei künftigem Gebrauch).",
      "Zutaten bei niedriger bis mittlerer Hitze im Topf ansetzen — nie einen kalten Tontopf auf volle Hitze stellen, das Material verträgt keine Temperatursprünge.",
      "Zugedeckt sehr langsam köcheln lassen (deutlich niedrigere Hitze als bei einem Metalltopf nötig wäre) — der Ton hält die Wärme und gart gleichmäßig von allen Seiten.",
      "Direkt im Topf servieren — er hält die Hitze noch lange auf dem Tisch warm.",
    ],
    tips: [
      "Nie einen heißen Tontopf auf eine kalte oder nasse Oberfläche stellen — der Temperaturschock kann ihn zersprengen.",
      "Auch ein normaler schwerer Schmortopf mit Deckel funktioniert nach demselben Prinzip (niedrige, gleichmäßige Hitze), wenn kein Tontopf zur Hand ist.",
      "Besonders geeignet für Congee, Eintöpfe und alles, was über Stunden köcheln soll, ohne anzubrennen.",
    ],
    usedIn: "Congee, Schmoreintöpfe, alles, was traditionell stundenlang auf kleiner Flamme zieht.",
    tags: ["China", "Dämpfen", "Schmoren"],
  },
  {
    id: "china-re-guo-liang-you",
    category: "Wok-Technik & Hitzeführung",
    emoji: "🌡️",
    title: "Re Guo Liang You — Heißer Wok, kühles Öl (熱鍋涼油)",
    desc: "Der leere Wok wird zuerst bis kurz vor den Rauchpunkt erhitzt, erst DANACH kommt das (vergleichsweise kühlere) Öl hinein — dieses Zeitfenster ist es, das verhindert, dass Fleisch und Gemüse am Wok festkleben.",
    method: [
      "Leeren, trockenen Wok auf höchster Stufe erhitzen, bis er zu rauchen beginnt oder ein Wassertropfen sofort zischend verdampft.",
      "Erst jetzt das Öl hineingeben und den Wok kurz schwenken, damit es die Fläche gleichmäßig benetzt.",
      "Zutaten unmittelbar danach zugeben — das Öl ist zwar heiß, aber noch spürbar kühler als der vorgeheizte Wok selbst.",
      "Die dabei entstehende dünne Öl-Dampf-Schicht zwischen Metall und Zutat ist der eigentliche Grund, warum nichts ansetzt.",
    ],
    tips: [
      "Funktioniert nur mit einem wirklich sehr heißen, meist ungebeschichteten Wok (Carbonstahl/Gusseisen) — bei beschichteten Pfannen ist das Prinzip weniger relevant.",
      "Öl NICHT gleich mit dem kalten Wok zusammen erhitzen — das ist der häufigste Fehler und führt genau zum Ankleben, das die Technik verhindern soll.",
      "Nach dem Ölzugeben nur wenige Sekunden warten, bevor die ersten Zutaten reinkommen, sonst kühlt der Wok bereits wieder ab.",
    ],
    usedIn: "Grundprinzip für praktisch jedes Wok-Gericht in dieser App.",
    tags: ["China", "Wok", "Hitzeführung"],
  },
  {
    id: "china-wok-hei-hitze",
    category: "Wok-Technik & Hitzeführung",
    emoji: "💨",
    title: "Wok Hei — der 'Atem des Woks' (鑊氣)",
    desc: "Das rauchig-karamellige Aroma, das gutes Wok-Essen von zu Hause unterscheidet, entsteht durch eine Kombination aus extremer Hitze, Maillard-Reaktion und leicht anbrennendem Öldampf — nicht durch eine Zutat, sondern durch Hitze und Timing.",
    method: [
      "Wok so heiß wie möglich vorheizen (professionelle Brenner erreichen das leichter als Haushaltsherde, aber auch dort so heiß wie sicher machbar).",
      "Immer nur kleine Portionen auf einmal zubereiten — zu viel Fülle auf einmal kühlt den Wok ab und die Zutaten dünsten statt zu braten.",
      "Zutaten ständig in Bewegung halten (schwenken/wenden), damit sie kurz direkten Flammenkontakt an den Wok-Rändern bekommen, ohne anzubrennen.",
      "Sauce erst ganz am Ende und nur kurz zugeben — zu früh zugegeben verhindert sie die für Wok Hei nötige trockene Hitze.",
    ],
    tips: [
      "Kleine Chargen sind wichtiger als ein besonders starker Brenner — Restaurant-Woks sind vor allem deshalb im Vorteil, weil sie für kleine Portionen ausgelegt sind.",
      "Ein zu voller Wok ist der Hauptgrund, warum Wok-Gerichte zu Hause oft eher gedünstet als gebraten schmecken.",
      "Wok Hei lässt sich nicht nachträglich durch Raucharoma-Zutaten ersetzen — es ist ein tatsächlicher Garprozess, kein Geschmacksstoff.",
    ],
    usedIn: "Alle klassischen Wok-Pfannengerichte, besonders Nudel- und Reispfannen wie Char Kway Teow oder Chow Fun.",
    tags: ["China", "Wok", "Hitzeführung"],
  },
  {
    id: "china-wok-reihenfolge-zutaten",
    category: "Wok-Technik & Hitzeführung",
    emoji: "🥕",
    title: "Zutaten-Reihenfolge im Wok",
    desc: "Ein Wok-Gericht gelingt selten, wenn alles gleichzeitig hineinkommt — die richtige Reihenfolge (Aromaten → Protein → hartes Gemüse → weiches Gemüse → Sauce) sorgt dafür, dass jede Zutat genau ihre eigene Garzeit bekommt.",
    method: [
      "Zuerst Aromaten (Knoblauch, Ingwer, Frühlingszwiebel-Weiß) kurz im heißen Öl anschwitzen, bis duftend — nicht bräunen lassen, sonst wird es bitter.",
      "Protein (bereits mariniert/velvetet) zugeben, kurz scharf anbraten, bei Bedarf herausnehmen und beiseitestellen, wenn es sonst zu lange mitgart.",
      "Hartes Gemüse (Karotte, Brokkoli-Strunk) zuerst zugeben, weiches Gemüse (Blattgemüse, Frühlingszwiebel-Grün) erst kurz vor Schluss — sonst ist das eine matschig, während das andere noch roh ist.",
      "Protein wieder zugeben, Sauce zum Schluss angießen, kurz aufkochen lassen und mit Stärke binden, alles nur so lange wenden, bis die Sauce glänzt und bindet.",
    ],
    tips: [
      "Alle Zutaten VOR dem Erhitzen des Woks bereits geschnitten und griffbereit haben (Mise en Place) — bei der Geschwindigkeit eines Wok-Gerichts bleibt keine Zeit zum Zwischendurch-Schneiden.",
      "Protein bei Bedarf zwischenzeitlich herausnehmen und erst am Ende wieder zugeben, statt es die ganze Garzeit im Wok zu lassen — verhindert Übergaren.",
      "Sauce vorher fertig anrühren (inkl. Stärke-Wasser-Mix), damit sie beim Zugeben sofort bindet statt lange köcheln zu müssen.",
    ],
    usedIn: "Grundprinzip für praktisch jedes gemischte Wok-Gericht (Fleisch + mehrere Gemüsesorten) in dieser App.",
    tags: ["China", "Wok", "Timing"],
  },
  {
    id: "china-gegen-die-faser-schneiden",
    category: "Schneidetechnik",
    emoji: "🔪",
    title: "Gegen die Faser schneiden",
    desc: "Fleisch quer statt entlang der sichtbaren Muskelfaser-Linien zu schneiden verkürzt die einzelnen Fasern — das Ergebnis ist spürbar zarter im Biss, unabhängig davon, wie das Fleisch danach gegart wird.",
    method: [
      "Fleischstück auf ein Schneidebrett legen und die Faserrichtung genau ansehen — feine parallele Linien, die über die Oberfläche laufen.",
      "Das Messer im rechten Winkel zu diesen Fasern ansetzen, nicht parallel dazu.",
      "In dünne Scheiben schneiden (Dicke je nach Rezept, meist 3–5 mm für Wok-Gerichte) — jede Scheibe durchtrennt die Fasern komplett.",
      "Bei Zweifel über die Faserrichtung: an einer Ecke probeschneiden, die Schnittfläche zeigt sofort, ob quer oder entlang geschnitten wurde.",
    ],
    tips: [
      "Bei Rindfleisch besonders wichtig — die Fasern sind gröber und der Unterschied zwischen richtig und falsch geschnitten ist deutlich zu schmecken.",
      "Bei Flanksteak/Bavette ändert sich die Faserrichtung oft in der Mitte des Stücks — beim Schneiden aufmerksam bleiben.",
      "Lässt sich sehr gut mit dem Anfrieren-Trick kombinieren, um überhaupt erst sehr dünn schneiden zu können.",
    ],
    usedIn: "Bulgogi, Wok-Rindfleischgerichte, generell jedes dünn geschnittene Fleisch für kurze, heiße Garmethoden.",
    tags: ["China/Korea", "Schneiden", "Vorbereitung"],
  },
  {
    id: "china-anfrieren-vor-duennem-schneiden",
    category: "Schneidetechnik",
    emoji: "🧊",
    title: "Anfrieren vor dem dünnen Schneiden",
    desc: "Fleisch 20–30 Minuten ins Gefrierfach zu legen, bevor es geschnitten wird, macht es fest genug, um hauchdünne, gleichmäßige Scheiben zu schneiden — von Hand kaum erreichbar, wenn das Fleisch noch weich ist.",
    method: [
      "Fleischstück (am besten schon grob in eine handliche Form gebracht) für 20–30 Min. flach ins Gefrierfach legen — Ziel ist fest, aber nicht durchgefroren.",
      "Mit einem scharfen Messer in sehr dünne Scheiben schneiden, solange das Fleisch noch kalt-fest ist.",
      "Falls das Fleisch zwischendurch wieder zu weich wird, kurz zurück ins Gefrierfach legen.",
      "Vor dem Weiterverarbeiten (Marinieren, Kochen) vollständig auftauen lassen bzw. direkt weiterverarbeiten, wenn das Rezept das erlaubt.",
    ],
    tips: [
      "Funktioniert besonders gut bei Stücken, die ohnehin für den Freezer bestimmt sind — direkt nach dem Schneiden marinieren und einfrieren spart einen Auftau-Zyklus.",
      "Nicht zu lange frieren — komplett durchgefrorenes Fleisch lässt sich schlechter gleichmäßig schneiden als nur angefrorenes.",
      "Ein sehr scharfes Messer ist bei dieser Technik wichtiger als bei den meisten anderen Schneidearbeiten.",
    ],
    usedIn: "Bulgogi-Marinade-Bag, generell jedes Rezept mit hauchdünn geschnittenem rohem Fleisch.",
    tags: ["China/Korea", "Schneiden", "Vorbereitung"],
  },
  {
    id: "china-gundao-kuai-rollschnitt",
    category: "Schneidetechnik",
    emoji: "🥕",
    title: "Gun Dao Kuai — Rollschnitt (滾刀塊)",
    desc: "Längliches Gemüse wie Karotte, Aubergine oder Zucchini wird beim Schneiden nach jedem Schnitt eine Vierteldrehung gedreht — die entstehenden unregelmäßigen, mehrflächigen Stücke haben deutlich mehr Oberfläche als gleichmäßige Scheiben und garen dadurch schneller und gleichmäßiger durch.",
    method: [
      "Gemüse längs auf das Schneidebrett legen.",
      "Diagonal anschneiden (Messer im spitzen Winkel zum Gemüse).",
      "Gemüse um eine Vierteldrehung (90°) rollen.",
      "Erneut im selben diagonalen Winkel schneiden — Rollen und Schneiden so lange wiederholen, bis das ganze Stück in unregelmäßigen, mehrflächigen Stücken vorliegt.",
    ],
    tips: [
      "Die unregelmäßige Form ist gewollt — sie sorgt für mehr Angriffsfläche für Sauce und Hitze als gleichmäßige runde Scheiben.",
      "Besonders sinnvoll bei Schmorgerichten, wo die Garzeit zwischen Gemüse und Fleisch angeglichen werden soll.",
      "Alle Stücke möglichst ähnlich groß halten, sonst garen sie trotz der Technik ungleichmäßig.",
    ],
    usedIn: "Schmorgerichte mit Karotte/Kartoffel/Aubergine wie Nikujaga oder Hongshao-Gerichte.",
    tags: ["China", "Schneiden", "Vorbereitung"],
  },
  {
    id: "china-salzprozent-fermentation",
    category: "Fermentieren-Grundlagen",
    emoji: "🧪",
    title: "Die 2-Prozent-Regel bei Salzlaken",
    desc: "Salz ist bei der Gemüsefermentation kein reiner Geschmacksstoff, sondern der Sicherheitsmechanismus: In der richtigen Konzentration bremst es unerwünschte Fäulnisbakterien, lässt aber die gewünschten Milchsäurebakterien ungehindert arbeiten.",
    method: [
      "Als Faustregel 2 % Salz zum Gewicht von Gemüse plus Wasser berechnen (z. B. 20 g Salz auf 1 kg Gemüse+Wasser zusammen) — der Ausgangspunkt für die meisten Gemüsesorten.",
      "Bei wasserreicherem, weichem Gemüse (Gurke, Pilze) eher 3 % ansetzen — mehr Wasseraustritt verdünnt die effektive Salzkonzentration sonst zu stark.",
      "Salz vollständig in Wasser auflösen, BEVOR das Gemüse hinzukommt — ungleichmäßig verteiltes Salz führt zu ungleichmäßiger Fermentation.",
      "Bei Zimmertemperatur fermentieren lassen, bis die gewünschte Säure erreicht ist, danach zur Verlangsamung in den Kühlschrank stellen.",
    ],
    tips: [
      "Deutlich unter 2 % Salz steigt das Risiko, dass sich unerwünschte Keime statt der Milchsäurebakterien durchsetzen — bei Unsicherheit lieber etwas mehr statt weniger Salz verwenden.",
      "Zu viel Salz (deutlich über 5 %) bremst dagegen auch die gewünschten Milchsäurebakterien und verlangsamt die Fermentation unnötig.",
      "Gemüse muss während der Fermentation vollständig von Lake bedeckt sein — an der Luft liegende Stücke schimmeln, statt zu fermentieren.",
    ],
    usedIn: "Grundprinzip hinter Sichuan-Paocai und jeder anderen milchsauer fermentierten Gemüse-Lake.",
    tags: ["Übergreifend", "Fermentieren", "Sicherheit"],
  },
  {
    id: "japan-koji-enzym-prinzip",
    category: "Fermentieren-Grundlagen",
    emoji: "🍚",
    title: "Koji — das Enzym-Werkzeug der ostasiatischen Küche",
    desc: "Koji (in Japan meist Aspergillus oryzae auf gedämpftem Reis oder Soja kultiviert) liefert vor allem Enzyme: Amylase spaltet Stärke zu Zucker, Protease spaltet Eiweiß zu Aminosäuren (= Umami) — dieselbe Grundlage hinter Miso, Sojasauce, Sake, Mirin und Shio Koji.",
    method: [
      "Koji entsteht durch das gezielte Animpfen von gedämpftem Reis oder Soja mit Koji-Sporen unter kontrollierter Feuchtigkeit und Wärme über 1–2 Tage.",
      "Fertiger Koji wird je nach Anwendung direkt weiterverarbeitet (z. B. mit Salz und Wasser zu Shio Koji) oder als Starter für eine längere Fermentation eingesetzt (z. B. mit Sojabohnen zu Miso).",
      "Die Enzyme arbeiten am effektivsten in einem warmen, aber nicht heißen Bereich — bei zu hoher Hitze werden sie zerstört, bei Kühlschranktemperatur wirken sie nur noch sehr langsam.",
      "Je länger und wärmer die Reifung, desto intensiver werden Süße (aus dem Stärkeabbau) und Umami (aus dem Eiweißabbau).",
    ],
    tips: [
      "Deshalb wird Shio Koji für Marinaden im Kühlschrank angesetzt (langsame, kontrollierte Wirkung über Stunden) statt bei Zimmertemperatur (zu unkontrolliert/unsicher für rohes Fleisch).",
      "Gekaufter Koji hält sich eingefroren monatelang, im Kühlschrank nur einige Wochen — für längere Lagerung einfrieren.",
      "Dasselbe Enzym-Prinzip erklärt auch, warum Miso und Sojasauce mit der Reifezeit immer intensiver im Geschmack werden.",
    ],
    usedIn: "Shio-Koji-Marinade, generell die Basis hinter Miso, Sojasauce, Sake und Mirin.",
    tags: ["Japan", "Fermentieren", "Umami"],
  },
  {
    id: "korea-jang-meju-prinzip",
    category: "Fermentieren-Grundlagen",
    emoji: "🫘",
    title: "Meju & die Jang-Familie — das koreanische Grundprinzip",
    desc: "Doenjang, Ganjang (Sojasauce) und Gochujang gehen alle auf denselben Grundschritt zurück: getrocknete, fermentierte Sojabohnenblöcke (Meju) werden in starker Salzlake eingelegt, wobei sich die Mischung nach einigen Wochen von selbst in eine feste (Doenjang) und eine flüssige (Ganjang) Phase trennt.",
    method: [
      "Sojabohnen kochen, zu Blöcken formen (Meju) und über mehrere Wochen an der Luft und durch natürlich vorkommende Mikroorganismen fermentieren/trocknen lassen.",
      "Fertige Meju-Blöcke in eine starke Salzlake (traditionell ca. 12–20 % Salzgehalt) einlegen, mehrere Wochen bis Monate ziehen lassen.",
      "Nach der Reifung die Mischung trennen: die feste Masse ergibt (nach Weiterverarbeitung) Doenjang, die abgeseihte Flüssigkeit ergibt Ganjang.",
      "Für Gochujang wird statt reinem Meju eine Mischung mit Chiliflocken, Klebreismehl und Malz angesetzt — ein verwandtes, aber eigenständiges Verfahren.",
    ],
    tips: [
      "Die hohe Salzkonzentration (12–20 %) ist bei diesem langen, monatelangen Fermentationsprozess bewusst deutlich höher als bei den schnellen Gemüse-Fermenten (2–3 %) — sie muss über Wochen vor unerwünschten Keimen schützen, nicht nur über Tage.",
      "Dieser gesamte Prozess ist traditionell ein Monate- bis Jahre-Projekt — für den Hausgebrauch werden fertige Doenjang/Ganjang/Gochujang-Pasten gekauft, nicht selbst angesetzt.",
      "Das Grundprinzip (Salz + Zeit + kontrollierte Mikroorganismen) erklärt, warum ältere, länger gereifte Jang-Pasten intensiver und komplexer schmecken als junge.",
    ],
    usedIn: "Erklärt, warum Doenjang, Ganjang und Gochujang aus derselben Familie stammen und unterschiedlich schmecken.",
    tags: ["Korea", "Fermentieren", "Umami"],
  },
];
