// src/plans/prep/preppen.ts
// "Preppen" — Vorrats-/Gefrier-Rezepte, unabhängig von einer bestimmten Wochenplan-Woche.
// Einmal kochen/vorbereiten, mehrmals essen. Quellen: gängige IG/TikTok/YouTube-Freezer-Meal-Prep-
// Tricks (Flach-Einfrieren, Rohreis-Trick, Marinade-Freezer-Bags), auf die China/Japan/Korea-Küche
// und die Projekt-Leitplanken (Diabetes, Schwangerschaft) angepasst.

export type PrepCategory = "gericht" | "basis";

export type PrepRecipe = {
  id: string;
  category: PrepCategory;
  /** Bei category "gericht": Art des Gerichts (Suppe, Schmorgericht, ...). Bei "basis": Art der Basis (Sauce, Brühe, ...). */
  type: string;
  emoji: string;
  title: string;
  desc: string;
  batchSize: string;
  ingredients: string[];
  steps: string[];
  freezeMethod: string;
  freezerLife: string;
  reheat: string;
  tags: string[];
};

export const PREP_RECIPES: PrepRecipe[] = [
  {
    id: "japan-curry-flatpack",
    category: "gericht",
    type: "Schmorgericht/One-Pot",
    emoji: "🍛",
    title: "Japanisches Curry – Flach-Freezer-Pack (日本カレー)",
    desc: "Fertige Curry-Basis, flach eingefroren — im Topf direkt mit Wasser aufbrechen und aufkochen.",
    batchSize: "Ergibt 4 Portionen (2× für 2 Personen)",
    ingredients: [
      "Hähnchenbrust oder mageres Rind 400 g",
      "Karotte 200 g",
      "Zwiebel 150 g",
      "Japanische Curry-Roux (natriumarm, mild) 100 g",
      "Wasser/Brühe 800 ml",
      "Ingwer 10 g",
    ],
    steps: [
      "Fleisch anbraten, Zwiebel und Karotte mitdünsten (Kartoffeln NICHT mitkochen — die werden beim Einfrieren matschig).",
      "Mit Wasser ablöschen, Roux einrühren, 15 Min. köcheln bis sämig.",
      "Vollständig abkühlen lassen, dann in einen Gefrierbeutel füllen.",
      "Beutel flach ausstreichen (Luft raus), liegend einfrieren — spart Platz und taut schneller auf.",
    ],
    freezeMethod: "Flach im Gefrierbeutel, liegend eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Flachpaket direkt mit etwas Wasser/Brühe in den Topf geben, aufbrechen, aufkochen, 8–10 Min. köcheln — kein Auftauen nötig. Frische Kartoffel erst jetzt mitgaren, bis Reis dazu servieren.",
    tags: ["Japan", "One-Pot", "Diabetes: Portion beachten"],
  },
  {
    id: "bulgogi-marinade-bag",
    category: "gericht",
    type: "Marinade/Wok",
    emoji: "🥩",
    title: "Koreanisches Bulgogi – Marinade-Freezer-Bag (불고기)",
    desc: "Rohes, dünn geschnittenes Rind direkt in der Marinade einfrieren — auftauen, in den Wok, fertig.",
    batchSize: "Ergibt 2 Portionen",
    ingredients: [
      "Rindfleisch (mager, für Kurzbraten) 300 g",
      "Sojasauce natriumarm 3 EL",
      "Birne oder Apfel, gerieben 50 g",
      "Knoblauch 1 Zehe",
      "Sesamöl 1 TL",
      "Frühlingszwiebel 2 Stück",
    ],
    steps: [
      "Rind 20–30 Min. anfrieren, dann in sehr dünne Scheiben schneiden — geht dadurch viel leichter.",
      "Alle Marinade-Zutaten in einen Gefrierbeutel geben, Rind dazu, durchmassieren.",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: über Nacht im Kühlschrank auftauen, dann kurz und heiß im Wok anbraten.",
    ],
    freezeMethod: "Flach im Gefrierbeutel, roh in der Marinade.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Im Kühlschrank auftauen (12–24 Std.), dann 5–10 Min. im Wok scharf anbraten — nicht aus gefrorenem Zustand direkt braten, sonst wird das Fleisch zäh.",
    tags: ["Korea", "Low Sugar: Zucker weglassen/reduzieren", "Diabetes: mageres Fleisch"],
  },
  {
    id: "congee-rohreis-trick",
    category: "gericht",
    type: "Suppe/Congee",
    emoji: "🍚",
    title: "Congee-Rohreis-Trick — in 20 Minuten statt 1 Stunde (粥)",
    desc: "Rohen (ungekochten) Reis einfrieren — die Körner platzen beim Frost leicht auf und zerfallen dadurch beim Kochen viel schneller zu cremigem Congee.",
    batchSize: "Ergibt Basis für 4 Portionen",
    ingredients: [
      "Reis (roh) 200 g",
      "Wasser oder Hühnerbrühe natriumarm 1,5 l",
      "Ingwer 10 g",
    ],
    steps: [
      "Rohen Reis abmessen und portionsweise in kleine Gefrierbeutel füllen.",
      "Flach liegend mindestens 4 Std. (am besten über Nacht) einfrieren.",
      "Zum Kochen: gefrorenen Reis direkt mit kalter Brühe aufsetzen — kein Auftauen nötig.",
      "20 Min. köcheln, gelegentlich umrühren, bis cremig; erst am Ende Ei/Fleisch/Gemüse nach Wahl zugeben.",
    ],
    freezeMethod: "Roher, ungekochter Reis, portioniert im Beutel.",
    freezerLife: "mehrere Monate (wie normaler Trockenreis + Frost)",
    reheat: "Kein Auftauen — gefrorene Reiskörner direkt in die kalte Brühe geben und aufkochen, ca. 20 Min. köcheln statt der sonst üblichen 45–60 Min.",
    tags: ["China", "Frühstück", "Schwangerschaft: Zutaten vollständig durchgaren"],
  },
  {
    id: "dashi-miso-wuerfel",
    category: "basis",
    type: "Brühe/Instant-Suppe",
    emoji: "🧊",
    title: "Dashi-/Miso-Brühwürfel für Instant-Suppe (だし・味噌キューブ)",
    desc: "Konzentrierte Brühe/Miso-Paste in Eiswürfelform einfrieren — 1–2 Würfel plus heißes Wasser ergeben in Minuten eine Suppe.",
    batchSize: "Ergibt ca. 12 Würfel",
    ingredients: [
      "Dashi-Grundbrühe (Kombu/Katsuobushi) 500 ml, stark reduziert",
      "Miso-Paste 100 g",
      "Frühlingszwiebel, fein gehackt, optional 2 EL",
    ],
    steps: [
      "Dashi auf etwa die Hälfte einkochen, damit sie konzentriert genug ist.",
      "Mit Miso-Paste glattrühren (nicht mehr kochen, sonst verliert Miso Aroma).",
      "In eine Eiswürfelform füllen, komplett durchfrieren lassen.",
      "Würfel aus der Form lösen, in einen Gefrierbeutel umfüllen.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "1–2 Würfel mit 250 ml kochendem Wasser aufgießen, umrühren — fertig ist die Basis-Miso-Suppe. Nach Wunsch Tofu/Wakame/Frühlingszwiebel frisch dazugeben.",
    tags: ["Japan", "Instant", "Jod (Wakame) sparsam dosieren"],
  },
  {
    id: "karaage-airfryer-frozen",
    category: "gericht",
    type: "Frittiert/Airfryer",
    emoji: "🍗",
    title: "Karaage roh mariniert einfrieren — direkt aus dem Froster in die Heißluftfritteuse (唐揚げ)",
    desc: "Mariniertes, paniertes Hähnchen einzeln vorfrieren — kein Auftauen, direkt in den Airfryer.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hähnchenschenkel ohne Haut, gewürfelt 500 g",
      "Sojasauce natriumarm 2 EL",
      "Ingwer 10 g",
      "Knoblauch 1 Zehe",
      "Ei 1 Stück",
      "Maisstärke 4 EL",
    ],
    steps: [
      "Hähnchen mit Sojasauce, Ingwer und Knoblauch mindestens 30 Min. (besser über Nacht) marinieren.",
      "Kurz vor dem Einfrieren in Ei wenden, dann in Maisstärke panieren.",
      "Panierte Stücke einzeln, ohne Berührung, auf einem Blech vorfrieren.",
      "Sobald fest, in einen Gefrierbeutel umfüllen."
    ],
    freezeMethod: "Einzeln paniert vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt gefroren bei 190°C ca. 6 Min. in die Heißluftfritteuse, bis knusprig und durchgegart (Kerntemperatur prüfen). Nicht in der Mikrowelle aufwärmen — wird gummiartig.",
    tags: ["Japan", "Airfryer", "Schwangerschaft: Ei/Hähnchen vollständig durchgegart"],
  },
  {
    id: "char-siu-marinade-batch",
    category: "gericht",
    type: "Marinade/Ofen",
    emoji: "🍖",
    title: "Char Siu — Chinesisches BBQ-Schwein im Voraus mariniert (叉燒)",
    desc: "Schweinefilet in der Marinade eingefroren — auftauen, im Ofen rösten, in Scheiben portionieren und für die Woche verwenden.",
    batchSize: "Ergibt ca. 6 Portionen (dünn aufgeschnitten)",
    ingredients: [
      "Schweinefilet 600 g",
      "Sojasauce natriumarm 3 EL",
      "Hoisin-Sauce 2 EL",
      "Fünf-Gewürze-Pulver 1 TL",
      "Knoblauch 2 Zehen",
      "Honig oder Agavendicksaft, wenig 1 TL (statt der sonst üblichen mehreren EL Zucker)",
    ],
    steps: [
      "Alle Marinade-Zutaten verrühren, Filet darin wenden.",
      "In einem Gefrierbeutel mit der Marinade flach einfrieren.",
      "Zum Kochen: über Nacht im Kühlschrank auftauen, dann bei 200°C im Ofen rösten — eine Schale Wasser mit in den Ofen stellen, das hält das Fleisch saftig.",
      "Nach dem Durchgaren (Kerntemperatur prüfen) in dünne Scheiben schneiden, portionsweise zu Reis oder Nudeln servieren."
    ],
    freezeMethod: "Roh in der Marinade, flach im Gefrierbeutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Im Kühlschrank auftauen (12–24 Std.), dann vollständig im Ofen durchgaren — nicht aus gefrorenem Zustand rösten, sonst gart es außen an, bevor die Mitte durch ist.",
    tags: ["China", "Low Sugar: Süße stark reduziert", "Diabetes: Portion mager & dünn geschnitten"],
  },
  {
    id: "hambagu-bulgogi-patties",
    category: "gericht",
    type: "Pattys/Braten",
    emoji: "🍔",
    title: "Hambagu/Bulgogi-Pattys roh geformt einfrieren (ハンバーグ)",
    desc: "Japanisch-koreanisch inspirierte Hackfleisch-Pattys, roh geformt eingefroren — auftauen, anbraten, mit einer schnellen Sauce servieren.",
    batchSize: "Ergibt 6 Pattys",
    ingredients: [
      "Rinderhack (mager) oder Hähnchenhack 500 g",
      "Zwiebel, fein gehackt 100 g",
      "Sojasauce natriumarm 2 EL",
      "Ei 1 Stück",
      "Panko 30 g",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Alle Zutaten gut verkneten, zu 6 Pattys formen.",
      "Zwischen Backpapier-Lagen stapeln, damit sie sich nicht verbinden.",
      "Flach im Gefrierbeutel einfrieren.",
      "Zum Kochen: im Kühlschrank auftauen, in der Pfanne durchbraten; separat eine schnelle Sauce aus Sojasauce, wenig Honig und Knoblauch köcheln."
    ],
    freezeMethod: "Roh geformt, mit Backpapier zwischen den Pattys, flach im Beutel.",
    freezerLife: "bis zu 2 Wochen (rohes Hack — nicht so lang haltbar wie fertig Gegartes)",
    reheat: "Im Kühlschrank auftauen, dann vollständig durchbraten (kein Rosa mehr in der Mitte). Nicht direkt aus gefrorenem Zustand braten, sonst bleibt die Mitte roh.",
    tags: ["Japan/Korea", "Schwangerschaft: vollständig durchbraten", "Diabetes: mageres Hack"],
  },
  {
    id: "ingwer-knoblauch-fruehlingszwiebel-paste",
    category: "basis",
    type: "Aromaten-Basis",
    emoji: "🧄",
    title: "Ingwer-Knoblauch-Frühlingszwiebel-Paste — die Basis für fast alles (薑蒜蔥醬)",
    desc: "Der meistverwendbare Preppen-Baustein überhaupt: ein Eiswürfel davon startet jeden Wok, jede Suppe, jede Marinade.",
    batchSize: "Ergibt ca. 16 Eiswürfel",
    ingredients: [
      "Ingwer, geschält 100 g",
      "Knoblauch, geschält 100 g",
      "Frühlingszwiebel (nur weißer Teil) 50 g",
      "Neutrales Öl 2 EL",
    ],
    steps: [
      "Alle Zutaten im Blitzhacker/Mixer zu einer groben Paste zerkleinern.",
      "In eine Eiswürfelform füllen, glattstreichen.",
      "Vollständig durchfrieren lassen (mind. 6 Std.).",
      "Würfel lösen, in einen Gefrierbeutel umfüllen.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "1 Würfel direkt gefroren in den heißen Wok/Topf geben — schmilzt in Sekunden. Basis für: jedes Stir-Fry, jede Suppe (Congee, Brühe, Hühnersuppe), jede Marinade (Bulgogi, Char Siu, Teriyaki) in diesem Ordner.",
    tags: ["China/Japan/Korea", "Universal-Basis", "Kein Zucker/Salz enthalten"],
  },
  {
    id: "all-purpose-stirfry-sauce",
    category: "basis",
    type: "Sauce",
    emoji: "🥡",
    title: "All-Purpose-Stir-Fry-Sauce, wenig Zucker (萬用炒菜醬)",
    desc: "Eine Grundsauce für praktisch jedes Wok-Gericht — nur Protein und Gemüse dazugeben, fertig ist der Alltags-Stir-Fry.",
    batchSize: "Ergibt ca. 12 Portionen (Eiswürfel à 2 EL)",
    ingredients: [
      "Sojasauce natriumarm 120 ml",
      "Hühnerbrühe natriumarm 150 ml",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Sesamöl 1 EL",
      "Reisessig mild 1 EL",
      "Maisstärke 1 EL",
      "Zucker 1 TL (statt der sonst üblichen 2–3 EL)",
    ],
    steps: [
      "Alle Zutaten kalt glattrühren, bis die Stärke sich löst.",
      "In eine Eiswürfelform füllen.",
      "Vollständig durchfrieren lassen.",
      "Würfel lösen, in einen Gefrierbeutel umfüllen.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 2 Monate",
    reheat: "2–3 Würfel direkt gefroren zu angebratenem Protein & Gemüse in den Wok geben, kurz aufkochen bis sie andicken — Basis für Hühnchen-, Tofu- oder Garnelen-Stir-Fry mit beliebigem Gemüse.",
    tags: ["China", "Universal-Basis", "Low Sugar ✓", "Diabetes: Zuckeranteil stark reduziert"],
  },
  {
    id: "huehnerbruehe-basis",
    category: "basis",
    type: "Brühe",
    emoji: "🍲",
    title: "Klare Hühnerbrühe-Basis — Grundlage für Suppen, Congee & Saucen",
    desc: "Eine neutrale, natriumarme Grundbrühe, die als Basis für fast jede Suppe, das Congee oder als Ablösch-Flüssigkeit für Saucen dient.",
    batchSize: "Ergibt ca. 2 Liter (8× 250 ml-Portionen)",
    ingredients: [
      "Hühnerkarkassen oder Hähnchenflügel 1 kg",
      "Ingwer 20 g",
      "Frühlingszwiebel 2 Stück",
      "Wasser 3 l",
    ],
    steps: [
      "Karkassen kurz blanchieren, abspülen (klarere Brühe).",
      "Mit Ingwer, Frühlingszwiebel und Wasser 2–3 Std. sehr sanft köcheln (nicht sprudelnd kochen).",
      "Abseihen, vollständig abkühlen lassen.",
      "In 250-ml-Portionen (Gefrierbeutel oder Muffinform) abfüllen und einfrieren.",
    ],
    freezeMethod: "Portioniert in Gefrierbeuteln oder Muffinform, dann in Beutel umgefüllt.",
    freezerLife: "bis zu 6 Monate",
    reheat: "Portion direkt gefroren in den Topf geben, langsam erhitzen. Basis für: Congee, Nudelsuppen, Miso-/Dashi-Suppe strecken, Ablöschen bei Schmorgerichten.",
    tags: ["China/Japan/Korea", "Universal-Basis", "Natriumarm"],
  },
  {
    id: "teriyaki-sauce-basis",
    category: "basis",
    type: "Sauce/Glasur",
    emoji: "🍯",
    title: "Teriyaki-Glasur-Basis, wenig Zucker (照り焼きのたれ)",
    desc: "Süß-herzhafte Glasur zum Bepinseln/Glasieren von Hähnchen, Lachs oder Tofu — separat von der herzhaften Stir-Fry-Sauce.",
    batchSize: "Ergibt ca. 8 Portionen (Eiswürfel à 1 EL)",
    ingredients: [
      "Sojasauce natriumarm 100 ml",
      "Mirin 60 ml",
      "Ingwer-Knoblauch-Paste (siehe oben) 1 EL",
      "Zucker 2 EL (statt der sonst üblichen 4–5 EL)",
      "Wasser 60 ml",
    ],
    steps: [
      "Alle Zutaten in einem Topf verrühren.",
      "Bei mittlerer Hitze 5–6 Min. einkochen, bis leicht sirupartig.",
      "Vollständig abkühlen lassen.",
      "In eine Eiswürfelform füllen, einfrieren, dann umfüllen.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "1–2 Würfel bei den letzten Minuten zu bereits fast durchgegartem Hähnchen/Lachs/Tofu in die Pfanne geben, glasig einreduzieren lassen. Basis für: Teriyaki-Hähnchen, -Lachs, -Tofu, als Glasur für den Reiskocher-Claypot-Reis.",
    tags: ["Japan", "Universal-Basis", "Low Sugar ✓ (Zucker reduziert)"],
  },
  {
    id: "austernsauce-universal-glasur",
    category: "basis",
    type: "Sauce/Glasur",
    emoji: "🦪",
    title: "Austernsauce-Universal-Glasur, wenig Zucker (蠔油萬用醬)",
    desc: "Die zweite Standard-Dunkelsauce neben Sojasauce — dickflüssig, umami-süßlich. Basis für Stir-Frys, Glasuren und Gemüse-Klassiker wie Rind mit Brokkoli.",
    batchSize: "Ergibt ca. 10 Portionen (Eiswürfel à 1 EL)",
    ingredients: [
      "Austernsauce 100 ml",
      "Sojasauce natriumarm 40 ml",
      "Ingwer-Knoblauch-Paste (siehe oben) 1 EL",
      "Hühnerbrühe natriumarm 60 ml",
      "Maisstärke 1 TL",
      "Zucker 1 TL (statt der sonst üblichen 1–2 EL)",
    ],
    steps: [
      "Alle Zutaten kalt glattrühren, bis die Stärke sich löst.",
      "In eine Eiswürfelform füllen.",
      "Vollständig durchfrieren lassen.",
      "Würfel lösen, in einen Gefrierbeutel umfüllen.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "2–3 Würfel direkt gefroren zu fast fertig gegartem Gemüse/Protein geben, kurz aufkochen bis glänzend-sämig. Basis für: Rind mit Brokkoli, Gemüse-Stir-Fry, als Glasur für Claypot-Reis oder Hähnchen.",
    tags: ["China", "Universal-Basis", "Low Sugar ✓ (Zucker reduziert)"],
  },
  {
    id: "hongshaorou-freezer",
    category: "gericht",
    type: "Schmorgericht",
    emoji: "🥓",
    title: "Hong Shao Rou — Rotgeschmorter Schweinebauch, wenig Zucker (紅燒肉)",
    desc: "Der meistgenannte Cook-ahead-Klassiker in jeder China-Kochcommunity — schmeckt aufgewärmt sogar besser, weil die Sauce durchzieht.",
    batchSize: "Ergibt 6 Portionen",
    ingredients: [
      "Schweinebauch 600 g",
      "Dunkle Sojasauce 3 EL",
      "Sojasauce natriumarm 2 EL",
      "Ingwer 15 g",
      "Sternanis 2 Stück",
      "Zucker 1 EL (statt der sonst üblichen 3–4 EL Karamell-Zucker)",
    ],
    steps: [
      "Schweinebauch in Würfel schneiden, kurz blanchieren, abspülen.",
      "In wenig Öl anbraten, bis leicht gebräunt.",
      "Mit beiden Sojasaucen, Ingwer, Sternanis und Wasser bedeckt 45–60 Min. sanft schmoren, bis butterzart.",
      "Vollständig abkühlen lassen, portionsweise mit der Sauce in Gefrierbeutel/Dosen füllen.",
    ],
    freezeMethod: "Fertig gegart, portioniert mit der Sauce in Dosen/Beuteln.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Portion direkt gefroren in einen Topf geben, bei niedriger Hitze mit einem Schuss Wasser langsam auftauen und erwärmen, bis wieder heiß und die Sauce sich löst.",
    tags: ["China", "Diabetes: kleine Portion, mager anteilig", "Low Sugar ✓ (Zucker reduziert)"],
  },
  {
    id: "zhajiangmian-sauce-basis",
    category: "basis",
    type: "Sauce (Nudeln)",
    emoji: "🍜",
    title: "Zhajiangmian-Nudelsauce-Basis (炸醬)",
    desc: "Die Hackfleisch-Bohnenpasten-Sauce für Zhajiangmian — friert hervorragend ein, einfach über frisch gekochte Nudeln geben.",
    batchSize: "Ergibt 6 Portionen",
    ingredients: [
      "Schweine- oder Hähnchenhack (mager) 400 g",
      "Süße Bohnenpaste (Tianmianjiang) 3 EL",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Hühnerbrühe natriumarm 200 ml",
      "Frühlingszwiebel 2 Stück",
    ],
    steps: [
      "Hack krümelig anbraten.",
      "Bohnenpaste und Ingwer-Knoblauch-Paste einrühren, kurz mitrösten.",
      "Mit Brühe ablöschen, 15 Min. sanft köcheln, bis sämig.",
      "Vollständig abkühlen lassen, portionsweise einfrieren.",
    ],
    freezeMethod: "Fertig gegart, portioniert in Dosen/Beuteln.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Portion direkt gefroren im Topf langsam erhitzen, bei Bedarf mit wenig Wasser verdünnen. Über frisch gekochte Weizen- oder Vollkornnudeln geben, mit rohem Gurken-/Karottenstreifen servieren.",
    tags: ["China", "Universal-Basis (Nudelsauce)", "Diabetes: Nudelmenge beachten"],
  },
  {
    id: "loewenkopf-fleischbaellchen",
    category: "gericht",
    type: "Suppe/Fleischbällchen",
    emoji: "🍡",
    title: "Löwenkopf-Fleischbällchen in Brühe (獅子頭)",
    desc: "Große, saftige Fleischbällchen, die in ihrer eigenen Brühe eingefroren werden — dadurch bleiben sie beim Auftauen besonders saftig.",
    batchSize: "Ergibt ca. 8 große Bällchen",
    ingredients: [
      "Schweinehack (mager) 500 g",
      "Wasserkastanien, fein gehackt 80 g",
      "Ei 1 Stück",
      "Ingwer-Knoblauch-Paste (siehe oben) 1 EL",
      "Hühnerbrühe natriumarm 800 ml",
      "Chinakohl 200 g",
    ],
    steps: [
      "Hack, Wasserkastanien, Ei und Paste gut verkneten, zu großen Bällchen formen.",
      "In der Brühe 30 Min. sanft ziehen lassen, bis vollständig durchgegart.",
      "Chinakohl in den letzten 5 Min. mitgaren.",
      "Vollständig abkühlen lassen, Bällchen mitsamt Brühe portionsweise einfrieren.",
    ],
    freezeMethod: "Fertig gegart, mitsamt der Brühe portioniert in Dosen.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Portion direkt gefroren im Topf langsam erhitzen, bis Bällchen und Brühe wieder durchgehend heiß sind.",
    tags: ["China", "Schwangerschaft: Ei/Hack vollständig durchgegart", "Diabetes: proteinreich"],
  },
  {
    id: "schwarze-bohnen-knoblauch-sauce",
    category: "basis",
    type: "Sauce",
    emoji: "🫘",
    title: "Schwarze-Bohnen-Knoblauch-Sauce (豆豉蒜蓉醬)",
    desc: "Fermentierte schwarze Bohnen mit Knoblauch — Klassiker zum Dämpfen von Fisch, für Tofu oder als Stir-Fry-Booster.",
    batchSize: "Ergibt ca. 8 Portionen (Eiswürfel à 1 EL)",
    ingredients: [
      "Fermentierte schwarze Bohnen (Douchi), grob gehackt 3 EL",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Sojasauce natriumarm 2 EL",
      "Neutrales Öl 2 EL",
      "Wasser 2 EL",
    ],
    steps: [
      "Bohnen kurz abspülen, um überschüssiges Salz zu reduzieren.",
      "Mit den restlichen Zutaten zu einer groben Paste verrühren.",
      "In eine Eiswürfelform füllen.",
      "Vollständig durchfrieren lassen, dann umfüllen.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "1–2 Würfel direkt gefroren zu Dampf-Fisch (z. B. Kabeljau), Tofu oder Gemüse-Stir-Fry geben — schmilzt beim Garen ein. Sehr salzhaltig, daher sparsam dosieren.",
    tags: ["China", "Universal-Basis", "Salzgehalt beachten (Douchi ist salzig)"],
  },
  {
    id: "fruehlingszwiebeloel-basis",
    category: "basis",
    type: "Öl/Aroma",
    emoji: "🧅",
    title: "Frühlingszwiebelöl — Cong You (蔥油)",
    desc: "Langsam in Öl gezogene Frühlingszwiebeln — das vielseitigste Fertig-Aroma für Nudeln, Reis, Dumplingsauce oder als Topping.",
    batchSize: "Ergibt ca. 200 ml",
    ingredients: [
      "Frühlingszwiebel, reichlich 150 g",
      "Neutrales Öl 200 ml",
      "Ingwer, 2–3 Scheiben",
    ],
    steps: [
      "Frühlingszwiebel und Ingwer bei niedrigster Hitze im Öl 20–25 Min. langsam ziehen lassen, bis goldbraun und das Öl aromatisiert ist.",
      "Feststoffe abseihen (optional aufheben zum Mitessen).",
      "Öl vollständig abkühlen lassen.",
      "In kleine Portionsgläschen oder eine Eiswürfelform füllen und einfrieren.",
    ],
    freezeMethod: "Abgekühlt in Portionsgläschen oder Eiswürfelform.",
    freezerLife: "bis zu 6 Monate (Öl friert nicht komplett fest, bleibt leicht entnehmbar)",
    reheat: "Direkt aus dem Froster über heiße Nudeln, Reis oder gedämpftes Gemüse geben — kein Erhitzen nötig, das Öl taut durch die Wärme des Gerichts von selbst auf.",
    tags: ["China", "Universal-Basis", "Kein Erhitzen nötig"],
  },
  {
    id: "xo-style-sauce-mild",
    category: "basis",
    type: "Sauce",
    emoji: "🌶️",
    title: "XO-Style Trockengarnelen-Sauce, mild (無辣XO風味醬)",
    desc: "Umami-Bombe aus getrockneten Garnelen und Knoblauch, angelehnt an die berühmte XO-Sauce — hier standardmäßig ohne Schärfe, Chili optional separat.",
    batchSize: "Ergibt ca. 10 Portionen (Eiswürfel à 1 EL)",
    ingredients: [
      "Getrocknete Garnelen, eingeweicht & gehackt 30 g",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Schalotte, fein gehackt 50 g",
      "Neutrales Öl 4 EL",
      "Sojasauce natriumarm 1 EL",
    ],
    steps: [
      "Getrocknete Garnelen 20 Min. in warmem Wasser einweichen, fein hacken.",
      "Schalotte und Paste im Öl bei niedriger Hitze langsam goldbraun anschwitzen.",
      "Garnelen zugeben, 5–6 Min. mitrösten, bis aromatisch. Mit Sojasauce abschmecken.",
      "Vollständig abkühlen lassen, in eine Eiswürfelform füllen und einfrieren.",
    ],
    freezeMethod: "In Eiswürfelform vorgefroren, dann lose im Beutel.",
    freezerLife: "bis zu 3 Monate",
    reheat: "1 Würfel direkt gefroren zu Gemüse, Tofu, Reis oder Nudeln geben — schmilzt beim Anbraten ein. Für Schärfe optional etwas Chiliöl separat dazugeben.",
    tags: ["China", "Universal-Basis", "Getrocknete Garnelen vollständig gegart verwenden"],
  },
  // ---- Slow-Cooker-Freezer-Bags: alles roh in den Beutel, gefroren/aufgetaut direkt in den
  // Crockpot — keine Vorbereitung am Kochtag. Prinzip nach thefamilyfreezer.com/asian-crockpot-freezer-meals.
  {
    id: "suess-sauer-schwein-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🍍",
    title: "Süß-Saures Schweinefleisch — Crockpot-Freezer-Bag (咕嚕肉)",
    desc: "Alle Zutaten roh im Beutel eingefroren — direkt in den Slow Cooker, kein Anbraten nötig.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Schweinefilet, gewürfelt 500 g",
      "Ananasstücke (ungezuckert) 200 g",
      "Paprika, gewürfelt 150 g",
      "Sojasauce natriumarm 3 EL",
      "Reisessig mild 2 EL",
      "Zucker 1 EL (statt der sonst üblichen 3–4 EL)",
      "Maisstärke 1 EL",
    ],
    steps: [
      "Alle Zutaten roh in einen großen Gefrierbeutel geben.",
      "Gut durchmischen, Luft herausdrücken.",
      "Flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 4 Std. auf High oder 6–7 Std. auf Low garen.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel, flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut). Vor dem Servieren gut durchgaren prüfen.",
    tags: ["China", "Slow-Cooker", "Low Sugar ✓ (Zucker reduziert)", "Diabetes: Ananas maßvoll (fruchtzuckerhaltig)"],
  },
  {
    id: "japan-rind-teriyaki-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🐄",
    title: "Japanisches Rind-Teriyaki — Crockpot-Freezer-Bag (牛肉の照り焼き)",
    desc: "Rohes Rindfleisch direkt in der Teriyaki-Marinade eingefroren — Slow Cooker übernimmt den Rest.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Rindfleisch (mager, Schmorstück) 500 g",
      "Sojasauce natriumarm 4 EL",
      "Mirin 3 EL",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Zucker 1 EL (statt der sonst üblichen 3 EL)",
      "Frühlingszwiebel 2 Stück",
    ],
    steps: [
      "Alle Zutaten roh im Gefrierbeutel vermengen.",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 6–7 Std. auf Low garen, bis zart.",
      "Vor dem Servieren Fleisch zerzupfen/schneiden, Sauce leicht einkochen lassen.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel, flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut). Kerntemperatur/Durchgaren prüfen.",
    tags: ["Japan", "Slow-Cooker", "Low Sugar ✓ (Zucker reduziert)"],
  },
  {
    id: "korean-bbq-chicken-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🍗",
    title: "Koreanisches BBQ-Hähnchen — Crockpot-Freezer-Bag (코리안 바베큐 치킨)",
    desc: "Hähnchenschenkel direkt in der Gochujang-freien BBQ-Marinade eingefroren.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hähnchenschenkel ohne Haut 600 g",
      "Sojasauce natriumarm 3 EL",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Reisessig mild 1 EL",
      "Zucker 1 EL (statt der sonst üblichen 3 EL)",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Alle Zutaten roh im Gefrierbeutel vermengen.",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 5–6 Std. auf Low garen.",
      "Vor dem Servieren mit Sesam bestreuen, Sauce leicht einkochen lassen.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel, flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut). Hähnchen muss vollständig durchgegart sein.",
    tags: ["Korea", "Slow-Cooker", "Low Sugar ✓ (Zucker reduziert)", "Schwangerschaft: vollständig durchgegart"],
  },
  {
    id: "singapur-chicken-rice-stew-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🍲",
    title: "Singapurischer Hühnchen-Reis-Eintopf — Crockpot-Freezer-Bag (海南鸡饭风味炖菜)",
    desc: "An Hainan-Chicken-Rice angelehnter Eintopf, roh im Beutel eingefroren.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hähnchenschenkel ohne Haut 500 g",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Frühlingszwiebel 3 Stück",
      "Hühnerbrühe natriumarm 400 ml",
      "Sojasauce natriumarm 2 EL",
      "Sesamöl 1 TL",
    ],
    steps: [
      "Alle Zutaten roh im Gefrierbeutel vermengen.",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 5–6 Std. auf Low garen.",
      "Hähnchen zerzupfen, mit separat gekochtem Reis servieren.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel, flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut). Hähnchen muss vollständig durchgegart sein.",
    tags: ["Singapur/China", "Slow-Cooker", "Diabetes: Reisportion separat dosieren"],
  },
  {
    id: "thai-gruenes-curry-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🍛",
    title: "Thai Grünes Curry-Hähnchen, mild — Crockpot-Freezer-Bag (เขียวหวานไก่)",
    desc: "Milde Version ohne Chili-Schärfe — Currypaste-Basis roh mit Hähnchen und Kokosmilch eingefroren.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hähnchenbrust, gewürfelt 500 g",
      "Grüne Thai-Currypaste, mild/chilifrei 3 EL",
      "Kokosmilch, light 400 ml",
      "Aubergine, gewürfelt 150 g",
      "Fischsauce 1 EL",
      "Frühlingszwiebel 2 Stück",
    ],
    steps: [
      "Alle Zutaten roh im Gefrierbeutel vermengen.",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 4–5 Std. auf Low garen.",
      "Vor dem Servieren abschmecken, mit Reis servieren. Für Schärfe optional Chiliöl separat dazugeben.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel, flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut). Hähnchen muss vollständig durchgegart sein.",
    tags: ["Thailand", "Slow-Cooker", "Sekundär-Küche (max. 1×/Woche einplanen)"],
  },
  {
    id: "indisches-butter-chicken-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🍛",
    title: "Indisches Butter Chicken — Crockpot-Freezer-Bag (मक्खन चिकन)",
    desc: "Tomaten-Butter-Sauce mit Hähnchen, roh im Beutel eingefroren — mild, ohne Chili-Schärfe.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Hähnchenbrust, gewürfelt 500 g",
      "Passierte Tomaten 300 ml",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Joghurt natur 100 g",
      "Garam Masala, mild 1 TL",
      "Butter 2 EL (separat erst beim Kochen dazugeben)",
    ],
    steps: [
      "Hähnchen, Tomaten, Paste, Joghurt und Gewürze roh im Gefrierbeutel vermengen (Butter separat aufbewahren).",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 5–6 Std. auf Low garen.",
      "Butter erst in den letzten 15 Min. einrühren, mit Reis servieren.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel (Butter separat), flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut). Hähnchen muss vollständig durchgegart sein.",
    tags: ["Indien", "Slow-Cooker", "Sekundär-Küche (max. 1×/Woche einplanen)"],
  },
  {
    id: "libanesischer-linsen-chili-crockpot",
    category: "gericht",
    type: "Slow-Cooker",
    emoji: "🍠",
    title: "Libanesischer Süßkartoffel-Linsen-Chili — Crockpot-Freezer-Bag (vegetarisch)",
    desc: "Vegetarischer Eintopf, roh im Beutel eingefroren — ballaststoffreich, gut für Diabetes-Zielwerte.",
    batchSize: "Ergibt 4 Portionen",
    ingredients: [
      "Süßkartoffel, gewürfelt 300 g",
      "Rote Linsen (roh) 150 g",
      "Passierte Tomaten 300 ml",
      "Ingwer-Knoblauch-Paste (siehe oben) 2 EL",
      "Kreuzkümmel 1 TL",
      "Gemüsebrühe natriumarm 400 ml",
    ],
    steps: [
      "Alle Zutaten roh im Gefrierbeutel vermengen.",
      "Luft herausdrücken, flach liegend einfrieren.",
      "Zum Kochen: gefroren oder aufgetaut in den Slow Cooker geben, 5–6 Std. auf Low garen, bis Linsen weich sind.",
      "Vor dem Servieren abschmecken, bei Bedarf etwas Wasser nachgießen.",
    ],
    freezeMethod: "Alles roh zusammen im Beutel, flach eingefroren.",
    freezerLife: "bis zu 3 Monate",
    reheat: "Direkt aus dem Froster in den Slow Cooker (Garzeit +1 Std. gegenüber aufgetaut).",
    tags: ["Libanon", "Slow-Cooker", "Vegetarisch", "Diabetes: ballaststoffreich, KH beachten (Linsen + Süßkartoffel)"],
  },
];
